// src/generators/CypherExporter.ts
// Export Cypher queries from view definitions
// v8.0.0

import type {
  ExtendedViewDefinition,
  GeneratedCypher,
  CypherExporterOptions,
  CypherExample,
} from './types.js';

const DEFAULT_OPTIONS: CypherExporterOptions = {
  includeParams: true,
  includeComments: true,
  format: 'single',
};

/**
 * Export Cypher queries from view definitions.
 *
 * @example
 * ```typescript
 * // Extract queries
 * const result = CypherExporter.extract(view);
 *
 * // Generate combined Cypher file
 * const cypherFile = CypherExporter.toCypherFile(view);
 * ```
 */
export class CypherExporter {
  /**
   * Extract all Cypher queries from a view definition.
   */
  static extract(view: ExtendedViewDefinition): GeneratedCypher {
    const queries: CypherExample[] = view.docs?.examples ?? [];

    return {
      viewId: view.id,
      queries,
      combined: this.combineQueries(view.id, queries),
    };
  }

  /**
   * Generate a combined Cypher file from view.
   */
  static toCypherFile(
    view: ExtendedViewDefinition,
    options: CypherExporterOptions = {}
  ): string {
    const opts = { ...DEFAULT_OPTIONS, ...options };
    const lines: string[] = [];

    // Header
    lines.push(`// View: ${view.id}`);
    lines.push(`// ${view.docs?.title ?? view.name}`);
    lines.push(`// Generated by NovaNet Unified View System`);
    lines.push('');

    const queries = view.docs?.examples ?? [];

    for (const example of queries) {
      if (opts.includeComments) {
        lines.push(`// ${'='.repeat(70)}`);
        lines.push(`// Query: ${example.name}`);
        if (example.description) {
          lines.push(`// ${example.description}`);
        }
        lines.push(`// ${'='.repeat(70)}`);
      }

      // Parameter setup (Neo4j Browser format)
      if (opts.includeParams && example.params) {
        for (const [key, value] of Object.entries(example.params)) {
          lines.push(`:param ${key} => ${JSON.stringify(value)};`);
        }
        lines.push('');
      }

      // The query itself
      lines.push(example.query.trim());
      lines.push('');
    }

    return lines.join('\n');
  }

  /**
   * Generate Neo4j Browser compatible format.
   * Can be used with :play command or imported directly.
   */
  static toNeoBrowserFormat(view: ExtendedViewDefinition): string {
    const lines: string[] = [];

    lines.push(`// NovaNet View: ${view.id}`);
    lines.push(`// ${view.docs?.description ?? view.description}`);
    lines.push('');

    const queries = view.docs?.examples ?? [];

    for (let i = 0; i < queries.length; i++) {
      const example = queries[i];

      lines.push(`// [${i + 1}/${queries.length}] ${example.name}`);

      if (example.params) {
        for (const [key, value] of Object.entries(example.params)) {
          lines.push(`:param ${key} => ${JSON.stringify(value)};`);
        }
      }

      lines.push(example.query.trim());

      if (i < queries.length - 1) {
        lines.push('');
        lines.push('// ---');
        lines.push('');
      }
    }

    return lines.join('\n');
  }

  /**
   * Extract queries from multiple views.
   */
  static extractAll(views: ExtendedViewDefinition[]): GeneratedCypher[] {
    return views.map(view => this.extract(view));
  }

  /**
   * Combine queries into a single string.
   */
  private static combineQueries(viewId: string, queries: CypherExample[]): string {
    if (queries.length === 0) {
      return `// View: ${viewId}\n// No queries defined`;
    }

    const lines: string[] = [];
    lines.push(`// View: ${viewId}`);
    lines.push('');

    for (const query of queries) {
      lines.push(`// ${query.name}`);
      lines.push(query.query.trim());
      lines.push('');
    }

    return lines.join('\n');
  }
}
