// packages/core/src/graph/hierarchy.ts
// REALM_HIERARCHY — v9 realm → layer tree with node type mappings
// AUTO-GENERATED by novanet v9.0.0 — DO NOT EDIT
// Run: novanet schema generate

import type { Realm } from '../types/nodes.js';
import type { Layer, RealmDefinition, LayerMeta } from './types.js';
import { getNodeTypesByLayer } from './layers.js';

// =============================================================================
// REALM_HIERARCHY - Complete realm hierarchy definition
// =============================================================================

/**
 * Complete realm hierarchy definition.
 * This is the single source of truth for the ontology structure.
 *
 * 3 Realms (9 layers):
 * - Global: Shared across ALL projects. (2 layers)
 * - Project: Business-specific nodes for a single project. (5 layers)
 * - Shared: Cross-project resources that can be linked to multiple projects. (2 layers)
 */
export const REALM_HIERARCHY: Record<Realm, RealmDefinition> = {
  // ═══════════════════════════════════════════════════════════════════════════
  // GLOBAL (2 layers)
  // ═══════════════════════════════════════════════════════════════════════════
  global: {
    realm: 'global',
    label: 'GLOBAL',
    icon: '🌍',
    description: 'Shared across ALL projects.',
    layers: {
      config: {
        label: 'Configuration',
        description: 'Core configuration nodes.',
        icon: '⚙️',
        nodeTypes: getNodeTypesByLayer('config'),
      },
      knowledge: {
        label: 'Locale Knowledge',
        description: 'Deep locale-specific knowledge for native content generation.',
        icon: '📚',
        nodeTypes: getNodeTypesByLayer('knowledge'),
      },
    } as Record<Layer, LayerMeta>,
  },
  // ═══════════════════════════════════════════════════════════════════════════
  // PROJECT (5 layers)
  // ═══════════════════════════════════════════════════════════════════════════
  project: {
    realm: 'project',
    label: 'PROJECT',
    icon: '📦',
    description: 'Business-specific nodes for a single project.',
    layers: {
      foundation: {
        label: 'Foundation',
        description: 'Core project identity.',
        icon: '🏛️',
        nodeTypes: getNodeTypesByLayer('foundation'),
      },
      structure: {
        label: 'Structure',
        description: 'Information architecture.',
        icon: '🏗️',
        nodeTypes: getNodeTypesByLayer('structure'),
      },
      semantic: {
        label: 'Semantic Layer',
        description: 'Meaning and concepts.',
        icon: '💡',
        nodeTypes: getNodeTypesByLayer('semantic'),
      },
      instruction: {
        label: 'Instructions',
        description: 'Generation directives.',
        icon: '📝',
        nodeTypes: getNodeTypesByLayer('instruction'),
      },
      output: {
        label: 'Generated Output',
        description: 'LLM-generated content.',
        icon: '✨',
        nodeTypes: getNodeTypesByLayer('output'),
      },
    } as Record<Layer, LayerMeta>,
  },
  // ═══════════════════════════════════════════════════════════════════════════
  // SHARED (2 layers)
  // ═══════════════════════════════════════════════════════════════════════════
  shared: {
    realm: 'shared',
    label: 'SHARED',
    icon: '🎯',
    description: 'Cross-project resources that can be linked to multiple projects.',
    layers: {
      seo: {
        label: 'SEO Intelligence',
        description: 'Search engine optimization data.',
        icon: '🔍',
        nodeTypes: getNodeTypesByLayer('seo'),
      },
      geo: {
        label: 'GEO Intelligence',
        description: 'Geographic/local SEO data.',
        icon: '📍',
        nodeTypes: getNodeTypesByLayer('geo'),
      },
    } as Record<Layer, LayerMeta>,
  },
};

// =============================================================================
// HELPER FUNCTIONS
// =============================================================================

/**
 * Get realm definition by realm key
 * @param realm - The realm to look up
 * @returns The realm definition
 */
export function getRealmDefinition(realm: Realm): RealmDefinition {
  return REALM_HIERARCHY[realm];
}

/**
 * Get layer metadata within a realm
 * @param realm - The realm to look up
 * @param layer - The layer to look up
 * @returns The layer metadata, or undefined if not found
 */
export function getLayerMeta(
  realm: Realm,
  layer: Layer
): LayerMeta | undefined {
  return REALM_HIERARCHY[realm]?.layers[layer];
}

/**
 * Get all layers for a realm
 * @param realm - The realm to look up
 * @returns Array of layer keys
 */
export function getLayersForRealm(realm: Realm): Layer[] {
  return Object.keys(REALM_HIERARCHY[realm].layers) as Layer[];
}