// packages/core/src/graph/layers.ts
// NODE_LAYERS mapping all 44 node types to their layers
// AUTO-GENERATED by novanet v9.0.0 — DO NOT EDIT
// Run: novanet schema generate

import type { NodeType } from '../types/nodes.js';
import type { Layer } from './types.js';

// =============================================================================
// NODE_LAYERS - Maps each NodeType to its layer
// =============================================================================

/**
 * Maps each NodeType to its layer within its realm.
 * AUTO-GENERATED from models/node-kinds/ folder structure.
 *
 * Layers by realm:
 * - Global: config, knowledge
 * - Project: foundation, instruction, output, semantic, structure
 * - Shared: geo, seo
 */
export const NODE_LAYERS: Record<NodeType, Layer> = {
  // ═══════════════════════════════════════════════════════════════════════════
  // GLOBAL REALM (15 nodes)
  // ═══════════════════════════════════════════════════════════════════════════

  // config (1 node) - matches models/node-kinds/global/config/
  Locale: 'config',

  // knowledge (14 nodes) - matches models/node-kinds/global/knowledge/
  Constraint: 'knowledge',
  Expression: 'knowledge',
  LocaleCulture: 'knowledge',
  LocaleCultureReferences: 'knowledge',
  LocaleIdentity: 'knowledge',
  LocaleLexicon: 'knowledge',
  LocaleMarket: 'knowledge',
  LocaleRulesAdaptation: 'knowledge',
  LocaleRulesFormatting: 'knowledge',
  LocaleRulesSlug: 'knowledge',
  LocaleVoice: 'knowledge',
  Metaphor: 'knowledge',
  Pattern: 'knowledge',
  Reference: 'knowledge',

  // ═══════════════════════════════════════════════════════════════════════════
  // PROJECT REALM (21 nodes)
  // ═══════════════════════════════════════════════════════════════════════════

  // foundation (3 nodes) - matches models/node-kinds/project/foundation/
  BrandIdentity: 'foundation',
  Project: 'foundation',
  ProjectL10n: 'foundation',

  // instruction (6 nodes) - matches models/node-kinds/project/instruction/
  BlockPrompt: 'instruction',
  BlockRules: 'instruction',
  BlockType: 'instruction',
  PagePrompt: 'instruction',
  PageType: 'instruction',
  PromptArtifact: 'instruction',

  // output (5 nodes) - matches models/node-kinds/project/output/
  BlockL10n: 'output',
  EvaluationSignal: 'output',
  GenerationJob: 'output',
  OutputArtifact: 'output',
  PageL10n: 'output',

  // semantic (4 nodes) - matches models/node-kinds/project/semantic/
  Concept: 'semantic',
  ConceptL10n: 'semantic',
  SearchIntent: 'semantic',
  TopicCluster: 'semantic',

  // structure (3 nodes) - matches models/node-kinds/project/structure/
  Block: 'structure',
  ContentSlot: 'structure',
  Page: 'structure',

  // ═══════════════════════════════════════════════════════════════════════════
  // SHARED REALM (8 nodes)
  // ═══════════════════════════════════════════════════════════════════════════

  // geo (5 nodes) - matches models/node-kinds/shared/geo/
  GEOMiningRun: 'geo',
  GEOSeedL10n: 'geo',
  GEOSeedMetrics: 'geo',
  Thing: 'geo',
  ThingL10n: 'geo',

  // seo (3 nodes) - matches models/node-kinds/shared/seo/
  SEOKeywordL10n: 'seo',
  SEOKeywordMetrics: 'seo',
  SEOMiningRun: 'seo',

};

// =============================================================================
// HELPER FUNCTIONS
// =============================================================================

/**
 * Get the layer for a node type
 * @param nodeType - The node type to look up
 * @returns The layer for the node type
 */
export function getLayer(nodeType: NodeType): Layer {
  return NODE_LAYERS[nodeType];
}

/**
 * Get all node types in a layer
 * @param layer - The layer to look up
 * @returns Array of node types belonging to the layer
 */
export function getNodeTypesByLayer(layer: Layer): NodeType[] {
  return (Object.entries(NODE_LAYERS) as [NodeType, Layer][])
    .filter(([, l]) => l === layer)
    .map(([nodeType]) => nodeType);
}