// packages/core/src/graph/visual-encoding.ts
// Visual encoding rules from visual-encoding.yaml
// AUTO-GENERATED by novanet v9.5.0 — DO NOT EDIT
// Run: cargo run -- schema generate

// =============================================================================
// CHANNEL MAPPING — Which visual channel encodes which facet
// =============================================================================

/**
 * Visual channel mapping for nodes.
 *
 * - fill_color: layer — Uses taxonomy colors
 * - border_style: trait — Uses trait borders
 * - border_color: realm — Uses realm colors
 * - icon: kind — Uses kind icons
 * - spatial_grouping: realm — Layout clustering
 */
export const NODE_CHANNEL_MAPPING = {
  fillColor: 'layer',
  borderStyle: 'trait',
  borderColor: 'realm',
  icon: 'kind',
  spatialGrouping: 'realm',
} as const;

/**
 * Visual channel mapping for arcs.
 *
 * - stroke_color: family — Uses family colors
 * - stroke_style: scope — solid (intra) vs dashed (cross)
 * - arrow_head: cardinality — Based on relationship cardinality
 * - label_position: auto — center or offset
 */
export const ARC_CHANNEL_MAPPING = {
  strokeColor: 'family',
  strokeStyle: 'scope',
  arrowHead: 'cardinality',
  labelPosition: 'auto',
} as const;

// =============================================================================
// NODE STATES (5)
// =============================================================================

export type NodeStateKey = 'default' | 'filtered' | 'focused' | 'hover' | 'selected';

export interface NodeStateStyle {
  opacity: number;
  scale: number;
  shadow: string | null;
  ring: string | null;
}

export const NODE_STATES: Record<NodeStateKey, NodeStateStyle> = {
  default: {
    opacity: 1.0,
    scale: 1.0,
    shadow: 'none',
    ring: null,
  },
  filtered: {
    opacity: 0.30000001192092896,
    scale: 1.0,
    shadow: 'none',
    ring: null,
  },
  focused: {
    opacity: 1.0,
    scale: 1.0499999523162842,
    shadow: '0 0 12px {color}40',
    ring: '2px solid {color}',
  },
  hover: {
    opacity: 1.0,
    scale: 1.0199999809265137,
    shadow: '0 2px 8px rgba(0,0,0,0.2)',
    ring: null,
  },
  selected: {
    opacity: 1.0,
    scale: 1.0,
    shadow: null,
    ring: '2px solid white',
  },
};

// =============================================================================
// ARC STATES (4)
// =============================================================================

export type ArcStateKey = 'default' | 'filtered' | 'highlighted' | 'hover';

export interface ArcStateStyle {
  opacity: number;
  strokeWidth: number;
  animated: boolean;
  labelVisible: boolean;
}

export const ARC_STATES: Record<ArcStateKey, ArcStateStyle> = {
  default: {
    opacity: 0.6000000238418579,
    strokeWidth: 1.5,
    animated: false,
    labelVisible: false,
  },
  filtered: {
    opacity: 0.15000000596046448,
    strokeWidth: 1.0,
    animated: false,
    labelVisible: false,
  },
  highlighted: {
    opacity: 1.0,
    strokeWidth: 2.5,
    animated: true,
    labelVisible: false,
  },
  hover: {
    opacity: 1.0,
    strokeWidth: 2.0,
    animated: false,
    labelVisible: true,
  },
};

// =============================================================================
// TRAIT BORDERS (5) — Studio CSS + TUI Unicode
// =============================================================================

export type TraitKey = 'derived' | 'invariant' | 'job' | 'knowledge' | 'localized';

export interface TraitBorderStyle {
  cssStyle: string;
  cssWidth: string;
  cssDashArray: string | null;
  cssCornerRadius: string | null;
  unicodeChar: string;
  unicodeStyle: string;
  description: string;
}

export const TRAIT_BORDERS: Record<TraitKey, TraitBorderStyle> = {
  derived: {
    cssStyle: 'double',
    cssWidth: '3px',
    cssDashArray: null,
    cssCornerRadius: null,
    unicodeChar: '═',
    unicodeStyle: 'double',
    description: 'Computed from other nodes',
  },
  invariant: {
    cssStyle: 'solid',
    cssWidth: '2px',
    cssDashArray: null,
    cssCornerRadius: null,
    unicodeChar: '─',
    unicodeStyle: 'light',
    description: 'Stable, doesn't change between locales',
  },
  job: {
    cssStyle: 'solid',
    cssWidth: '1px',
    cssDashArray: null,
    cssCornerRadius: '8px',
    unicodeChar: '─',
    unicodeStyle: 'thin',
    description: 'Processing task / generation job',
  },
  knowledge: {
    cssStyle: 'dotted',
    cssWidth: '2px',
    cssDashArray: '2 2',
    cssCornerRadius: null,
    unicodeChar: '┈',
    unicodeStyle: 'dotted',
    description: 'Locale knowledge reference data',
  },
  localized: {
    cssStyle: 'dashed',
    cssWidth: '2px',
    cssDashArray: '6 3',
    cssCornerRadius: null,
    unicodeChar: '┄',
    unicodeStyle: 'dashed',
    description: 'Generated natively per locale',
  },
};

// =============================================================================
// SCOPE STROKES (2) — Intra vs Cross realm arcs
// =============================================================================

export type ScopeKey = 'cross_realm' | 'intra_realm';

export interface ScopeStrokeStyle {
  strokeStyle: string;
  opacity: number;
  description: string;
}

export const SCOPE_STROKES: Record<ScopeKey, ScopeStrokeStyle> = {
  cross_realm: {
    strokeStyle: 'dashed',
    opacity: 0.699999988079071,
    description: 'Arc crossing realm boundaries',
  },
  intra_realm: {
    strokeStyle: 'solid',
    opacity: 1.0,
    description: 'Arc within same realm',
  },
};

// =============================================================================
// CARDINALITY ARROWS (4)
// =============================================================================

export type CardinalityKey = 'many_to_many' | 'one_to_many' | 'one_to_one' | 'zero_to_one';

export interface CardinalityArrowStyle {
  arrowHead: string;
  arrowEnd: string;
  description: string;
}

export const CARDINALITY_ARROWS: Record<CardinalityKey, CardinalityArrowStyle> = {
  many_to_many: {
    arrowHead: 'diamond',
    arrowEnd: 'arrow-double',
    description: 'Multiple sources to multiple targets',
  },
  one_to_many: {
    arrowHead: 'none',
    arrowEnd: 'arrow-double',
    description: 'Single source to multiple targets',
  },
  one_to_one: {
    arrowHead: 'none',
    arrowEnd: 'arrow',
    description: 'Required single target',
  },
  zero_to_one: {
    arrowHead: 'circle',
    arrowEnd: 'arrow',
    description: 'Optional single target',
  },
};

// =============================================================================
// KIND ICONS (44) — Lucide icon names
// =============================================================================

export const KIND_ICONS: Record<string, string> = {
  Block: 'square',
  BlockL10n: 'check-square',
  BlockPrompt: 'terminal',
  BlockRules: 'shield-check',
  BlockType: 'component',
  BrandIdentity: 'palette',
  Concept: 'lightbulb',
  ConceptL10n: 'globe',
  Constraint: 'alert-triangle',
  ContentSlot: 'inbox',
  EvaluationSignal: 'activity',
  Expression: 'message-circle',
  GEOMiningRun: 'cpu',
  GEOSeedL10n: 'map-pin',
  GEOSeedMetrics: 'trending-up',
  GenerationJob: 'play-circle',
  Locale: 'globe',
  LocaleCulture: 'heart',
  LocaleCultureReferences: 'bookmark',
  LocaleIdentity: 'fingerprint',
  LocaleLexicon: 'book-open',
  LocaleMarket: 'trending-up',
  LocaleRulesAdaptation: 'sliders',
  LocaleRulesFormatting: 'type',
  LocaleRulesSlug: 'link',
  LocaleVoice: 'mic',
  Metaphor: 'lamp',
  OutputArtifact: 'package',
  Page: 'file-text',
  PageL10n: 'file-check',
  PagePrompt: 'message-square',
  PageType: 'layout',
  Pattern: 'puzzle',
  Project: 'folder',
  ProjectL10n: 'languages',
  PromptArtifact: 'file-code',
  Reference: 'external-link',
  SEOKeywordL10n: 'search',
  SEOKeywordMetrics: 'bar-chart-2',
  SEOMiningRun: 'pickaxe',
  SearchIntent: 'compass',
  Thing: 'box',
  ThingL10n: 'box',
  TopicCluster: 'network',
};

/**
 * Get Lucide icon name for a Kind.
 */
export function getKindIcon(kind: string): string {
  return KIND_ICONS[kind] ?? 'circle';
}

// =============================================================================
// ANIMATIONS (5) — Studio only
// =============================================================================

export type AnimationKey = 'arc_highlight' | 'expand_node' | 'filter_change' | 'focus_transition' | 'layout_change';

export interface AnimationPreset {
  durationMs: number;
  easing: string;
  staggerMs: number;
}

export const ANIMATIONS: Record<AnimationKey, AnimationPreset> = {
  arc_highlight: {
    durationMs: 200,
    easing: 'ease-out',
    staggerMs: 0,
  },
  expand_node: {
    durationMs: 200,
    easing: 'ease-out',
    staggerMs: 0,
  },
  filter_change: {
    durationMs: 150,
    easing: 'ease-in-out',
    staggerMs: 20,
  },
  focus_transition: {
    durationMs: 300,
    easing: 'ease-out',
    staggerMs: 0,
  },
  layout_change: {
    durationMs: 500,
    easing: 'ease-in-out',
    staggerMs: 0,
  },
};

// =============================================================================
// ACCESSIBILITY
// =============================================================================

export const ACCESSIBILITY = {
  minContrastRatio: 4.5,
  usePatterns: true,
  useIcons: true,
  useBorders: true,
  focusRingWidth: '2px',
  focusRingColor: 'white',
  focusRingOffset: '2px',
} as const;

// =============================================================================
// HELPER FUNCTIONS
// =============================================================================

/**
 * Get node state style by key.
 */
export function getNodeState(key: NodeStateKey): NodeStateStyle {
  return NODE_STATES[key];
}

/**
 * Get arc state style by key.
 */
export function getArcState(key: ArcStateKey): ArcStateStyle {
  return ARC_STATES[key];
}

/**
 * Get trait border style by trait key.
 */
export function getTraitBorder(trait: TraitKey): TraitBorderStyle {
  return TRAIT_BORDERS[trait];
}

/**
 * Get scope stroke style by scope key.
 */
export function getScopeStroke(scope: ScopeKey): ScopeStrokeStyle {
  return SCOPE_STROKES[scope];
}

/**
 * Get animation preset by key.
 */
export function getAnimation(key: AnimationKey): AnimationPreset {
  return ANIMATIONS[key];
}