// apps/studio/src/design/colors/index.ts
// Re-exports from auto-generated colors file
//
// Source of truth: packages/core/models/organizing-principles.yaml
// Generated by: cargo run -- schema generate

export {
  // Types
  type ColorTokens,
  type RealmKey,
  type LayerKey,
  type ArcFamilyKey,
  // Realm colors
  REALM_COLORS,
  REALM_DISPLAY_NAMES,
  getRealmColor,
  // Layer colors
  LAYER_COLORS,
  LAYER_DISPLAY_NAMES,
  getLayerColor,
  // Arc family colors
  ARC_FAMILY_COLORS,
  ARC_FAMILY_DISPLAY_NAMES,
  getArcFamilyColor,
  // Utility
  getFacetHex,
} from './generated';

// v0.17.3 (ADR-036): Trait colors defined locally in palette.ts, not auto-generated
export {
  type TraitKey,
  TRAIT_COLORS,
  TRAIT_DISPLAY_NAMES,
  getTraitColor,
} from './palette';
