//! Views Tab — Schema views explorer for Nexus mode.
//!
//! Shows available views from `doc generate --list` organized by category.
//! Teaches users about:
//! - View categories (overview, generation, knowledge, project, mining, contextual)
//! - Query-First architecture concept
//! - How views are generated from YAML definitions

use ratatui::Frame;
use ratatui::layout::{Constraint, Direction, Layout, Rect};
use ratatui::style::{Color, Modifier, Style};
use ratatui::text::{Line, Span};
use ratatui::widgets::{Block, Borders, Paragraph, Wrap};

use crate::tui::app::App;

// =============================================================================
// VIEW DATA
// =============================================================================

/// A view entry with metadata for display.
#[derive(Debug, Clone)]
pub struct ViewEntry {
    /// View ID (e.g., "block-generation").
    pub id: &'static str,
    /// Display name.
    pub name: &'static str,
    /// Short description.
    pub description: &'static str,
    /// Category for grouping.
    pub category: ViewCategory,
    /// Root node type.
    pub root_type: &'static str,
    /// Educational notes about the view.
    pub notes: &'static [&'static str],
}

/// View categories matching the registry.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum ViewCategory {
    Overview,
    Generation,
    Knowledge,
    Project,
    Mining,
    Contextual,
}

impl ViewCategory {
    /// Get all categories in display order.
    pub fn all() -> &'static [ViewCategory] {
        &[
            ViewCategory::Overview,
            ViewCategory::Generation,
            ViewCategory::Knowledge,
            ViewCategory::Project,
            ViewCategory::Mining,
            ViewCategory::Contextual,
        ]
    }

    /// Get display name for category.
    pub fn label(&self) -> &'static str {
        match self {
            ViewCategory::Overview => "Overview",
            ViewCategory::Generation => "Generation",
            ViewCategory::Knowledge => "Knowledge",
            ViewCategory::Project => "Project",
            ViewCategory::Mining => "Mining",
            ViewCategory::Contextual => "Contextual",
        }
    }

    /// Get description for category.
    pub fn description(&self) -> &'static str {
        match self {
            ViewCategory::Overview => "Layer views showing complete graph or realm subsets",
            ViewCategory::Generation => "Context views for orchestrator and sub-agents",
            ViewCategory::Knowledge => "Locale and entity knowledge views",
            ViewCategory::Project => "Project structure and configuration views",
            ViewCategory::Mining => "SEO/GEO pipeline views",
            ViewCategory::Contextual => "Node-specific views shown in sidebar",
        }
    }

    /// Get icon for category.
    pub fn icon(&self) -> &'static str {
        match self {
            ViewCategory::Overview => "\u{25a3}",   // ▣
            ViewCategory::Generation => "\u{26a1}", // ⚡
            ViewCategory::Knowledge => "\u{25ca}",  // ◊
            ViewCategory::Project => "\u{25a0}",    // ■
            ViewCategory::Mining => "\u{2692}",     // ⚒
            ViewCategory::Contextual => "\u{2630}", // ☰
        }
    }

    /// Get color for category.
    pub fn color(&self) -> Color {
        match self {
            ViewCategory::Overview => Color::Cyan,
            ViewCategory::Generation => Color::Yellow,
            ViewCategory::Knowledge => Color::Rgb(139, 92, 246), // Purple
            ViewCategory::Project => Color::Rgb(34, 197, 94),    // Green
            ViewCategory::Mining => Color::Rgb(249, 115, 22),    // Orange
            ViewCategory::Contextual => Color::Rgb(100, 116, 139), // Slate
        }
    }
}

/// All available views (static data, matches _registry.yaml).
pub const VIEWS: &[ViewEntry] = &[
    // Overview views
    ViewEntry {
        id: "complete-graph",
        name: "Complete Graph",
        description: "Full NovaNet graph with all 60 nodes and relations",
        category: ViewCategory::Overview,
        root_type: "Project",
        notes: &[
            "Entry point for understanding the full schema",
            "Generated by `novanet schema generate`, not `doc generate`",
            "Shows all realms, layers, and arc families",
        ],
    },
    ViewEntry {
        id: "shared-layer",
        name: "Shared Layer",
        description: "Locale configuration and knowledge (39 nodes)",
        category: ViewCategory::Overview,
        root_type: "Locale",
        notes: &[
            "Universal knowledge shared across organizations",
            "READ-ONLY in production (curated reference data)",
            "Includes config, locale, geography, knowledge layers",
        ],
    },
    ViewEntry {
        id: "seo-keywords",
        name: "SEO Keywords",
        description: "SEO keywords and metrics (shared realm)",
        category: ViewCategory::Overview,
        root_type: "SEOKeyword",
        notes: &[
            "Market intelligence data",
            "Moved to shared realm in v11.5 (universal across orgs)",
            "Links SEOKeyword -> SEOKeywordMetrics",
        ],
    },
    ViewEntry {
        id: "project-layer",
        name: "Project Layer",
        description: "Per-project nodes from foundation to output (14 nodes)",
        category: ViewCategory::Overview,
        root_type: "Project",
        notes: &[
            "Organization-specific content",
            "Foundation -> Structure -> Semantic -> Output flow",
            "Includes Pages, Blocks, Entities, and generated content",
        ],
    },
    // Generation views
    ViewEntry {
        id: "page-generation-context",
        name: "Page Generation Context",
        description: "Full context for orchestrator to generate a page",
        category: ViewCategory::Generation,
        root_type: "Page",
        notes: &[
            "Used by the generation orchestrator",
            "Collects Page -> Blocks -> Entities -> Knowledge",
            "Includes PagePrompt and PageType for instructions",
        ],
    },
    ViewEntry {
        id: "block-generation",
        name: "Block Generation",
        description: "Full context for sub-agent to generate a block",
        category: ViewCategory::Generation,
        root_type: "Block",
        notes: &[
            "Sub-agent receives this context slice",
            "Block -> BlockPrompt -> used Terms/Expressions",
            "Entities linked via USES_ENTITY arc",
        ],
    },
    ViewEntry {
        id: "block-semantic-network",
        name: "Block Semantic Network",
        description: "Block with concepts and spreading activation",
        category: ViewCategory::Generation,
        root_type: "Block",
        notes: &[
            "Semantic activation spreading from Block",
            "Entity relationships form a network",
            "Used for context enrichment",
        ],
    },
    // Knowledge views
    ViewEntry {
        id: "locale-full-knowledge",
        name: "Locale Full Knowledge",
        description: "Complete locale knowledge (Identity, Voice, Culture, Market, Lexicon)",
        category: ViewCategory::Knowledge,
        root_type: "Locale",
        notes: &[
            "All knowledge atoms for a locale",
            "Terms, Expressions, Patterns, CultureRefs, Taboos",
            "Loaded selectively based on generation context",
        ],
    },
    ViewEntry {
        id: "entity-ecosystem",
        name: "Entity Ecosystem",
        description: "Entity with content, SEO keywords, semantic links",
        category: ViewCategory::Knowledge,
        root_type: "Entity",
        notes: &[
            "Shows Entity -> EntityContent per locale",
            "Includes SEO keyword associations",
            "RELATES_TO semantic links to other entities",
        ],
    },
    // Project views
    ViewEntry {
        id: "project-context",
        name: "Project Context",
        description: "Project with supported locales and page inventory",
        category: ViewCategory::Project,
        root_type: "Project",
        notes: &[
            "Project -> SUPPORTS_LOCALE -> Locale",
            "Project -> HAS_PAGE -> Page inventory",
            "Entry point for understanding project scope",
        ],
    },
    ViewEntry {
        id: "project-overview",
        name: "Project Overview",
        description: "Project dashboard with pages, brand identity, and concepts",
        category: ViewCategory::Project,
        root_type: "Project",
        notes: &[
            "Dashboard view for project management",
            "Includes BrandIdentity configuration",
            "Shows page count and entity usage",
        ],
    },
    // Mining views
    ViewEntry {
        id: "seo-pipeline",
        name: "SEO Pipeline",
        description: "SEO keyword mining and optimization workflow",
        category: ViewCategory::Mining,
        root_type: "SEOKeyword",
        notes: &[
            "SEOKeyword -> SEOKeywordMetrics (aggregated)",
            "SEOCluster for topic grouping",
            "Feeds into page optimization",
        ],
    },
    // Contextual views (subset)
    ViewEntry {
        id: "composition",
        name: "Composition",
        description: "Page/Block composition hierarchy",
        category: ViewCategory::Contextual,
        root_type: "Page",
        notes: &[
            "Shown in sidebar when Page or Block selected",
            "Page -> HAS_BLOCK -> Block hierarchy",
            "Useful for understanding page structure",
        ],
    },
    ViewEntry {
        id: "knowledge",
        name: "Knowledge",
        description: "Locale knowledge atoms (Terms, Expressions, Patterns)",
        category: ViewCategory::Contextual,
        root_type: "Locale",
        notes: &[
            "Shown when Locale selected",
            "TermSet, ExpressionSet, PatternSet containers",
            "Atoms are loaded selectively for generation",
        ],
    },
    ViewEntry {
        id: "generation-pipeline",
        name: "Generation Pipeline",
        description: "Generation pipeline and outputs",
        category: ViewCategory::Contextual,
        root_type: "Page",
        notes: &[
            "Shown for Page, Block, or Generated nodes",
            "Page -> PageGenerated output relationship",
            "Tracks generation metadata (timestamps, versions)",
        ],
    },
];

/// Query-First architecture explanation.
pub const QUERY_FIRST_CONCEPT: &[&str] = &[
    "QUERY-FIRST ARCHITECTURE",
    "",
    "Views define traversal patterns from a root node type.",
    "Instead of loading the entire graph, views specify:",
    "",
    "  1. ROOT: Starting node type (e.g., Block)",
    "  2. INCLUDE: Relations to follow (e.g., HAS_PROMPT)",
    "  3. DIRECTION: outgoing, incoming, or both",
    "  4. DEPTH: Max hops for runtime queries",
    "",
    "This enables:",
    "  - Selective context loading for LLM prompts",
    "  - Efficient Cypher query generation",
    "  - Mermaid diagram generation for docs",
    "",
    "Views are defined in YAML:",
    "  packages/core/models/views/<view-id>.yaml",
    "",
    "Generate docs with:",
    "  cargo run -- doc generate --view=<view-id>",
];

// =============================================================================
// STATE
// =============================================================================

/// State for the Views tab.
#[derive(Debug, Clone, Default)]
pub struct ViewsState {
    /// Currently selected category index.
    pub category_cursor: usize,
    /// Currently selected view within category.
    pub view_cursor: usize,
    /// Whether showing Query-First concept panel.
    pub show_concept: bool,
}

impl ViewsState {
    /// Create new ViewsState.
    pub fn new() -> Self {
        Self::default()
    }

    /// Reset cursors.
    pub fn reset(&mut self) {
        self.category_cursor = 0;
        self.view_cursor = 0;
        self.show_concept = false;
    }

    /// Navigate up in views list.
    pub fn navigate_up(&mut self) {
        if self.view_cursor > 0 {
            self.view_cursor -= 1;
        } else if self.category_cursor > 0 {
            // Move to previous category
            self.category_cursor -= 1;
            let views = self.views_in_category();
            self.view_cursor = views.len().saturating_sub(1);
        }
    }

    /// Navigate down in views list.
    pub fn navigate_down(&mut self) {
        let views = self.views_in_category();
        if self.view_cursor + 1 < views.len() {
            self.view_cursor += 1;
        } else if self.category_cursor + 1 < ViewCategory::all().len() {
            // Move to next category
            self.category_cursor += 1;
            self.view_cursor = 0;
        }
    }

    /// Jump to next category.
    pub fn next_category(&mut self) {
        if self.category_cursor + 1 < ViewCategory::all().len() {
            self.category_cursor += 1;
            self.view_cursor = 0;
        }
    }

    /// Jump to previous category.
    pub fn prev_category(&mut self) {
        if self.category_cursor > 0 {
            self.category_cursor -= 1;
            self.view_cursor = 0;
        }
    }

    /// Toggle Query-First concept panel.
    pub fn toggle_concept(&mut self) {
        self.show_concept = !self.show_concept;
    }

    /// Get current category.
    pub fn current_category(&self) -> ViewCategory {
        ViewCategory::all()
            .get(self.category_cursor)
            .copied()
            .unwrap_or(ViewCategory::Overview)
    }

    /// Get views in current category.
    pub fn views_in_category(&self) -> Vec<&'static ViewEntry> {
        let cat = self.current_category();
        VIEWS.iter().filter(|v| v.category == cat).collect()
    }

    /// Get currently selected view.
    pub fn current_view(&self) -> Option<&'static ViewEntry> {
        self.views_in_category().get(self.view_cursor).copied()
    }

    /// Get text for yanking.
    pub fn get_yank_text(&self) -> Option<String> {
        self.current_view().map(|v| v.id.to_string())
    }
}

// =============================================================================
// RENDERING
// =============================================================================

/// Render the Views tab.
pub fn render_views_tab(f: &mut Frame, app: &App, area: Rect) {
    let views_state = &app.nexus.views;

    if views_state.show_concept {
        // Show Query-First concept panel
        render_concept_panel(f, area);
    } else {
        // Normal view: categories + views + detail
        let chunks = Layout::default()
            .direction(Direction::Horizontal)
            .constraints([Constraint::Percentage(40), Constraint::Percentage(60)])
            .split(area);

        render_views_list(f, app, chunks[0]);
        render_view_detail(f, app, chunks[1]);
    }
}

/// Render the views list organized by category.
fn render_views_list(f: &mut Frame, app: &App, area: Rect) {
    let views_state = &app.nexus.views;

    let block = Block::default()
        .title(Span::styled(
            " SCHEMA VIEWS ",
            Style::default()
                .fg(Color::Cyan)
                .add_modifier(Modifier::BOLD),
        ))
        .borders(Borders::ALL)
        .border_style(Style::default().fg(Color::Rgb(60, 60, 70)));

    let inner = block.inner(area);
    f.render_widget(block, area);

    let mut lines: Vec<Line> = Vec::new();

    // Header
    lines.push(Line::from(vec![
        Span::styled(
            "Query-First Architecture ",
            Style::default().fg(Color::Rgb(180, 180, 180)),
        ),
        Span::styled(
            "[?:concept]",
            Style::default().fg(Color::DarkGray),
        ),
    ]));
    lines.push(Line::from(Span::styled(
        "\u{2500}".repeat(inner.width.saturating_sub(2) as usize),
        Style::default().fg(Color::Rgb(60, 60, 70)),
    )));
    lines.push(Line::from(""));

    // Categories and views
    for (cat_idx, cat) in ViewCategory::all().iter().enumerate() {
        let is_selected_cat = cat_idx == views_state.category_cursor;
        let cat_color = cat.color();

        // Category header
        let cat_style = if is_selected_cat {
            Style::default()
                .fg(cat_color)
                .add_modifier(Modifier::BOLD)
        } else {
            Style::default().fg(cat_color)
        };

        let cat_views: Vec<_> = VIEWS.iter().filter(|v| v.category == *cat).collect();

        lines.push(Line::from(vec![
            Span::styled(format!("{} ", cat.icon()), cat_style),
            Span::styled(cat.label(), cat_style),
            Span::styled(
                format!(" ({})", cat_views.len()),
                Style::default().fg(Color::DarkGray),
            ),
        ]));

        // Views in category (only show if selected or nearby)
        if is_selected_cat {
            for (view_idx, view) in cat_views.iter().enumerate() {
                let is_selected = is_selected_cat && view_idx == views_state.view_cursor;

                let prefix = if is_selected { "  \u{25b8} " } else { "    " }; // ▸

                let style = if is_selected {
                    Style::default()
                        .fg(Color::White)
                        .bg(Color::Rgb(30, 50, 70))
                        .add_modifier(Modifier::BOLD)
                } else {
                    Style::default().fg(Color::Rgb(180, 180, 180))
                };

                lines.push(Line::from(vec![
                    Span::styled(prefix, style),
                    Span::styled(view.name, style),
                ]));
            }
        }

        lines.push(Line::from(""));
    }

    // Navigation hints
    lines.push(Line::from(Span::styled(
        "[j/k:nav] [h/l:category] [?:concept]",
        Style::default().fg(Color::DarkGray),
    )));

    let paragraph = Paragraph::new(lines).wrap(Wrap { trim: false });
    f.render_widget(paragraph, inner);
}

/// Render the detail panel for selected view.
fn render_view_detail(f: &mut Frame, app: &App, area: Rect) {
    let views_state = &app.nexus.views;

    let block = Block::default()
        .title(Span::styled(
            " VIEW DETAIL ",
            Style::default()
                .fg(Color::Cyan)
                .add_modifier(Modifier::BOLD),
        ))
        .borders(Borders::ALL)
        .border_style(Style::default().fg(Color::Rgb(60, 60, 70)));

    let inner = block.inner(area);
    f.render_widget(block, area);

    let Some(view) = views_state.current_view() else {
        let empty = Paragraph::new("Select a view to see details");
        f.render_widget(empty, inner);
        return;
    };

    let cat_color = view.category.color();

    let mut lines: Vec<Line> = Vec::new();

    // View name
    lines.push(Line::from(Span::styled(
        view.name,
        Style::default()
            .fg(Color::White)
            .add_modifier(Modifier::BOLD),
    )));

    // Separator
    lines.push(Line::from(Span::styled(
        "\u{2550}".repeat(inner.width.saturating_sub(2) as usize),
        Style::default().fg(cat_color),
    )));
    lines.push(Line::from(""));

    // Metadata
    lines.push(Line::from(vec![
        Span::styled("ID:       ", Style::default().fg(Color::DarkGray)),
        Span::styled(view.id, Style::default().fg(Color::Cyan)),
    ]));
    lines.push(Line::from(vec![
        Span::styled("Category: ", Style::default().fg(Color::DarkGray)),
        Span::styled(
            format!("{} {}", view.category.icon(), view.category.label()),
            Style::default().fg(cat_color),
        ),
    ]));
    lines.push(Line::from(vec![
        Span::styled("Root:     ", Style::default().fg(Color::DarkGray)),
        Span::styled(view.root_type, Style::default().fg(Color::Yellow)),
    ]));
    lines.push(Line::from(""));

    // Description
    lines.push(Line::from(Span::styled(
        "Description:",
        Style::default()
            .fg(Color::Yellow)
            .add_modifier(Modifier::BOLD),
    )));
    lines.push(Line::from(Span::styled(
        view.description,
        Style::default().fg(Color::Rgb(180, 180, 180)),
    )));
    lines.push(Line::from(""));

    // Notes section
    if !view.notes.is_empty() {
        lines.push(Line::from(Span::styled(
            "\u{250c}\u{2500} NOTES \u{2500}\u{2500}\u{2500}\u{2500}\u{2500}\u{2500}\u{2500}\u{2500}\u{2500}\u{2500}\u{2500}\u{2500}\u{2500}\u{2510}",
            Style::default().fg(Color::Rgb(100, 100, 120)),
        )));

        for note in view.notes {
            lines.push(Line::from(vec![
                Span::styled(
                    "\u{2502} \u{2022} ",
                    Style::default().fg(Color::Rgb(100, 100, 120)),
                ),
                Span::styled(*note, Style::default().fg(Color::Rgb(160, 160, 170))),
            ]));
        }

        lines.push(Line::from(Span::styled(
            "\u{2514}\u{2500}\u{2500}\u{2500}\u{2500}\u{2500}\u{2500}\u{2500}\u{2500}\u{2500}\u{2500}\u{2500}\u{2500}\u{2500}\u{2500}\u{2500}\u{2500}\u{2500}\u{2500}\u{2500}\u{2500}\u{2500}\u{2518}",
            Style::default().fg(Color::Rgb(100, 100, 120)),
        )));
        lines.push(Line::from(""));
    }

    // Usage example
    lines.push(Line::from(Span::styled(
        "Generate docs:",
        Style::default()
            .fg(Color::Green)
            .add_modifier(Modifier::BOLD),
    )));
    lines.push(Line::from(Span::styled(
        format!("  cargo run -- doc generate --view={}", view.id),
        Style::default().fg(Color::Rgb(150, 200, 150)),
    )));
    lines.push(Line::from(""));

    // YAML path
    lines.push(Line::from(Span::styled(
        "YAML definition:",
        Style::default()
            .fg(Color::Cyan)
            .add_modifier(Modifier::BOLD),
    )));
    lines.push(Line::from(Span::styled(
        format!("  packages/core/models/views/{}.yaml", view.id),
        Style::default().fg(Color::Rgb(150, 180, 220)),
    )));

    let paragraph = Paragraph::new(lines).wrap(Wrap { trim: false });
    f.render_widget(paragraph, inner);
}

/// Render the Query-First concept panel.
fn render_concept_panel(f: &mut Frame, area: Rect) {
    let block = Block::default()
        .title(Span::styled(
            " QUERY-FIRST ARCHITECTURE ",
            Style::default()
                .fg(Color::Yellow)
                .add_modifier(Modifier::BOLD),
        ))
        .borders(Borders::ALL)
        .border_style(Style::default().fg(Color::Cyan));

    let inner = block.inner(area);
    f.render_widget(block, area);

    let mut lines: Vec<Line> = Vec::new();

    for (i, line) in QUERY_FIRST_CONCEPT.iter().enumerate() {
        let style = if i == 0 {
            Style::default()
                .fg(Color::Cyan)
                .add_modifier(Modifier::BOLD)
        } else if line.starts_with("  ") && line.contains(':') {
            // Numbered items
            Style::default().fg(Color::Yellow)
        } else if line.starts_with("  -") || line.starts_with("  cargo") || line.starts_with("  packages") {
            Style::default().fg(Color::Rgb(150, 200, 150))
        } else {
            Style::default().fg(Color::Rgb(180, 180, 180))
        };

        lines.push(Line::from(Span::styled(*line, style)));
    }

    lines.push(Line::from(""));
    lines.push(Line::from(Span::styled(
        "[? or Esc: back to views]",
        Style::default().fg(Color::DarkGray),
    )));

    let paragraph = Paragraph::new(lines).wrap(Wrap { trim: false });
    f.render_widget(paragraph, inner);
}

// =============================================================================
// TESTS
// =============================================================================

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_views_state_default() {
        let state = ViewsState::new();
        assert_eq!(state.category_cursor, 0);
        assert_eq!(state.view_cursor, 0);
        assert!(!state.show_concept);
    }

    #[test]
    fn test_view_categories_count() {
        assert_eq!(ViewCategory::all().len(), 6);
    }

    #[test]
    fn test_views_count() {
        // Should have at least 15 views defined
        assert!(VIEWS.len() >= 15, "Expected at least 15 views, got {}", VIEWS.len());
    }

    #[test]
    fn test_views_have_valid_categories() {
        for view in VIEWS {
            // Just check category is one of the enum variants
            let _ = view.category.label();
            let _ = view.category.icon();
            let _ = view.category.color();
        }
    }

    #[test]
    fn test_navigate_down() {
        let mut state = ViewsState::new();
        assert_eq!(state.view_cursor, 0);

        state.navigate_down();
        assert_eq!(state.view_cursor, 1);
    }

    #[test]
    fn test_navigate_up() {
        let mut state = ViewsState::new();
        state.view_cursor = 2;

        state.navigate_up();
        assert_eq!(state.view_cursor, 1);
    }

    #[test]
    fn test_navigate_up_at_zero_goes_to_prev_category() {
        let mut state = ViewsState::new();
        state.category_cursor = 1;
        state.view_cursor = 0;

        state.navigate_up();
        assert_eq!(state.category_cursor, 0);
        // Should be at last view of previous category
    }

    #[test]
    fn test_next_category() {
        let mut state = ViewsState::new();
        state.view_cursor = 2;

        state.next_category();
        assert_eq!(state.category_cursor, 1);
        assert_eq!(state.view_cursor, 0); // Reset on category change
    }

    #[test]
    fn test_prev_category() {
        let mut state = ViewsState::new();
        state.category_cursor = 2;

        state.prev_category();
        assert_eq!(state.category_cursor, 1);
    }

    #[test]
    fn test_prev_category_at_zero() {
        let mut state = ViewsState::new();
        assert_eq!(state.category_cursor, 0);

        state.prev_category();
        assert_eq!(state.category_cursor, 0); // Should stay at 0
    }

    #[test]
    fn test_toggle_concept() {
        let mut state = ViewsState::new();
        assert!(!state.show_concept);

        state.toggle_concept();
        assert!(state.show_concept);

        state.toggle_concept();
        assert!(!state.show_concept);
    }

    #[test]
    fn test_views_in_category() {
        let state = ViewsState::new();
        let views = state.views_in_category();

        // First category (Overview) should have views
        assert!(!views.is_empty());
        for view in views {
            assert_eq!(view.category, ViewCategory::Overview);
        }
    }

    #[test]
    fn test_current_view() {
        let state = ViewsState::new();
        let view = state.current_view();

        assert!(view.is_some());
        assert_eq!(view.unwrap().category, ViewCategory::Overview);
    }

    #[test]
    fn test_get_yank_text() {
        let state = ViewsState::new();
        let text = state.get_yank_text();

        assert!(text.is_some());
        assert!(!text.unwrap().is_empty());
    }

    #[test]
    fn test_reset() {
        let mut state = ViewsState::new();
        state.category_cursor = 3;
        state.view_cursor = 2;
        state.show_concept = true;

        state.reset();

        assert_eq!(state.category_cursor, 0);
        assert_eq!(state.view_cursor, 0);
        assert!(!state.show_concept);
    }

    #[test]
    fn test_category_labels() {
        assert_eq!(ViewCategory::Overview.label(), "Overview");
        assert_eq!(ViewCategory::Generation.label(), "Generation");
        assert_eq!(ViewCategory::Knowledge.label(), "Knowledge");
        assert_eq!(ViewCategory::Project.label(), "Project");
        assert_eq!(ViewCategory::Mining.label(), "Mining");
        assert_eq!(ViewCategory::Contextual.label(), "Contextual");
    }

    #[test]
    fn test_category_descriptions() {
        for cat in ViewCategory::all() {
            assert!(!cat.description().is_empty());
        }
    }

    #[test]
    fn test_query_first_concept_not_empty() {
        assert!(!QUERY_FIRST_CONCEPT.is_empty());
        assert!(QUERY_FIRST_CONCEPT.len() >= 10);
    }
}
