// src/filters/ViewLoader.ts
// v10.4.0: Uses generated view definitions (no runtime YAML parsing)

import type { ViewDefinition, ViewRegistry, ViewRegistryEntry, IncludeRule } from './types.js';
import { NovaNetFilter } from './NovaNetFilter.js';
import {
  VIEWS,
  VIEW_REGISTRY,
  getView as getGeneratedView,
  type ViewDefinition as GeneratedViewDefinition,
  type IncludeRule as GeneratedIncludeRule,
} from './views.generated.js';

// ─────────────────────────────────────────────────────────────────────────────
// Type conversion (generated → types.ts)
// ─────────────────────────────────────────────────────────────────────────────

function convertIncludeRule(rule: GeneratedIncludeRule): IncludeRule {
  return {
    relation: rule.relation,
    direction: rule.direction,
    depth: rule.depth,
    targetTypes: rule.targetTypes as IncludeRule['targetTypes'],
    include: rule.include?.map(convertIncludeRule),
  };
}

function convertViewDefinition(view: GeneratedViewDefinition): ViewDefinition {
  return {
    id: view.id,
    name: view.name,
    description: view.description,
    version: view.version ?? '9.9.0',
    root: {
      type: view.root.type as ViewDefinition['root']['type'],
      key: view.root.key,
    },
    include: view.include.map(convertIncludeRule),
    filters: view.filters ? {
      locale: view.filters.locale,
      maxDepth: view.filters.maxDepth,
    } : undefined,
  };
}

// ─────────────────────────────────────────────────────────────────────────────
// ViewLoader
// ─────────────────────────────────────────────────────────────────────────────

/**
 * ViewLoader - Loads view definitions from generated TypeScript constants.
 *
 * v10.4.0: No longer reads YAML at runtime. Views are generated by Rust
 * from YAML sources at build time (`novanet schema generate`).
 *
 * Usage:
 * ```typescript
 * const view = ViewLoader.loadView('page-generation-context');
 * const filter = ViewLoader.toFilter(view, { key: 'page-pricing', locale: 'fr-FR' });
 * const { query, params } = CypherGenerator.generate(filter);
 * ```
 */
export class ViewLoader {
  /**
   * Loads a single view definition by ID.
   *
   * @param viewId - The view identifier
   * @param _viewsDir - Deprecated: no longer used (kept for API compatibility)
   * @returns The parsed ViewDefinition
   * @throws Error if view does not exist
   */
  static async loadView(viewId: string, _viewsDir?: string): Promise<ViewDefinition> {
    // Use generated constant - no file I/O needed
    const generated = getGeneratedView(viewId);
    return convertViewDefinition(generated);
  }

  /**
   * Loads a single view definition synchronously.
   *
   * @param viewId - The view identifier
   * @returns The parsed ViewDefinition
   * @throws Error if view does not exist
   */
  static loadViewSync(viewId: string): ViewDefinition {
    const generated = getGeneratedView(viewId);
    return convertViewDefinition(generated);
  }

  /**
   * Loads the view registry.
   *
   * @param _viewsDir - Deprecated: no longer used (kept for API compatibility)
   * @returns The view registry
   */
  static async loadRegistry(_viewsDir?: string): Promise<ViewRegistry> {
    return {
      version: '9.9.0',
      description: 'NovaNet Core View Definitions (generated)',
      views: VIEW_REGISTRY.map(entry => ({
        id: entry.id,
        file: `${entry.id}.yaml`, // For compatibility
        description: entry.description,
        category: entry.category as ViewRegistryEntry['category'],
        modes: entry.modes as ViewRegistryEntry['modes'],
      })),
    };
  }

  /**
   * Loads the view registry synchronously.
   *
   * @returns The view registry
   */
  static loadRegistrySync(): ViewRegistry {
    return {
      version: '9.9.0',
      description: 'NovaNet Core View Definitions (generated)',
      views: VIEW_REGISTRY.map(entry => ({
        id: entry.id,
        file: `${entry.id}.yaml`,
        description: entry.description,
        category: entry.category as ViewRegistryEntry['category'],
        modes: entry.modes as ViewRegistryEntry['modes'],
      })),
    };
  }

  /**
   * Get all available view IDs.
   */
  static getViewIds(): string[] {
    return Object.keys(VIEWS);
  }

  /**
   * Check if a view exists.
   */
  static hasView(viewId: string): boolean {
    return viewId in VIEWS;
  }

  /**
   * Converts a ViewDefinition to a NovaNetFilter instance.
   *
   * @param view - The ViewDefinition to convert
   * @param params - Optional parameters (key for root node, locale for filtering)
   * @returns A configured NovaNetFilter instance
   */
  static toFilter(
    view: ViewDefinition,
    params: { key?: string; locale?: string } = {}
  ): NovaNetFilter {
    const filter = NovaNetFilter.create();

    // Set root node
    const rootKey = params.key || view.root.key || '';
    switch (view.root.type) {
      case 'Page':
        filter.fromPage(rootKey);
        break;
      case 'Block':
        filter.fromBlock(rootKey);
        break;
      case 'Entity':
        filter.fromEntity(rootKey);
        break;
      case 'Locale':
        filter.fromLocale(rootKey);
        break;
      case 'Project':
        filter.fromProject(rootKey);
        break;
      default:
        throw new Error(`Unsupported root type: ${view.root.type}`);
    }

    // Apply include rules
    for (const include of view.include) {
      this.applyInclude(filter, include);
    }

    // Apply filters
    if (view.filters) {
      // Handle locale - support $locale placeholder
      if (view.filters.locale === '$locale' && params.locale) {
        filter.forLocale(params.locale);
      } else if (view.filters.locale && view.filters.locale !== '$locale') {
        filter.forLocale(view.filters.locale);
      }

      // Handle maxDepth
      if (view.filters.maxDepth !== undefined) {
        filter.maxDepth(view.filters.maxDepth);
      }
    }

    return filter;
  }

  /**
   * Applies a single include rule to a NovaNetFilter.
   */
  private static applyInclude(filter: NovaNetFilter, include: IncludeRule): void {
    const activeOnly = include.filters?.active === true;

    switch (include.relation) {
      case 'HAS_BLOCK':
        filter.includeBlocks({ depth: include.depth });
        break;

      case 'USES_ENTITY':
        filter.includeEntities({
          depth: include.depth,
          spreading: (include.depth || 1) > 1
        });
        break;

      case 'HAS_PROMPT':
        filter.includePrompts({ activeOnly });
        break;

      case 'HAS_RULES':
        filter.includeRules({ activeOnly });
        break;

      case 'HAS_OUTPUT':
        filter.includeOutputs();
        break;

      case 'HAS_L10N':
        filter.includeL10n();
        break;

      case 'HAS_IDENTITY':
      case 'HAS_VOICE':
      case 'HAS_CULTURE':
      case 'HAS_MARKET':
      case 'HAS_LEXICON': {
        const criteria = filter.getCriteria();
        const hasKnowledge = criteria.includes.some(i =>
          ['HAS_IDENTITY', 'HAS_VOICE', 'HAS_CULTURE', 'HAS_MARKET', 'HAS_LEXICON'].includes(i.relation)
        );
        if (!hasKnowledge) {
          filter.includeKnowledge();
        }
        break;
      }

      case 'EXPRESSES':
        filter.includeSEO();
        break;

      case 'OF_TYPE':
        filter.includeBlockType();
        break;

      case 'SEMANTIC_LINK':
        filter.includeSemanticLinks({ depth: include.depth });
        break;

      case 'HAS_PAGE':
        filter.includePages();
        break;

      case 'HAS_BRAND_IDENTITY':
        filter.includeBrandIdentity();
        break;

      case 'FOR_LOCALE':
        filter.includeForLocale();
        break;

      case 'SUPPORTS_LOCALE':
        filter.includeSupportedLocales();
        break;

      case 'DEFAULT_LOCALE':
        filter.includeDefaultLocale();
        break;

      case 'FALLBACK_TO':
        filter.includeFallbackLocale();
        break;

      case 'HAS_METRICS':
        filter.includeMetrics();
        break;

      case 'LINKS_TO':
        filter.includePageLinks();
        break;

      case 'SUBTOPIC_OF':
        filter.includeSubtopics();
        break;

      case 'HAS_RULES_ADAPTATION':
      case 'HAS_RULES_FORMATTING':
      case 'HAS_RULES_SLUG':
        filter.includeLocaleRules();
        break;

      case 'HAS_EXPRESSION':
        filter.includeExpressions();
        break;

      case 'HAS_REFERENCE':
        filter.includeCultureReferences();
        break;

      case 'HAS_METAPHOR':
        filter.includeMetaphors();
        break;

      case 'HAS_PATTERN':
        filter.includePatterns();
        break;

      case 'HAS_CONSTRAINT':
        filter.includeConstraints();
        break;

      default:
        throw new Error(`Unknown relation in view include: ${include.relation}. Update ViewLoader.applyInclude() to handle this relation.`);
    }
  }
}
