import type { Shortcut } from '@/lib/keyboard';

/**
 * All keyboard shortcuts
 */
export const SHORTCUTS: Shortcut[] = [
  // Navigation
  {
    id: 'fit-view',
    keys: 'f',
    label: 'Fit View',
    description: 'Fit graph to viewport',
    category: 'navigation',
    icon: 'Maximize2',
    when: ['input-not-focused'],
    action: 'novanet:fit-view',
  },
  {
    id: 'zoom-in',
    keys: '=',
    label: 'Zoom In',
    category: 'navigation',
    icon: 'ZoomIn',
    when: ['input-not-focused'],
    action: 'novanet:zoom-in',
  },
  {
    id: 'zoom-out',
    keys: '-',
    label: 'Zoom Out',
    category: 'navigation',
    icon: 'ZoomOut',
    when: ['input-not-focused'],
    action: 'novanet:zoom-out',
  },
  {
    id: 'center-selected',
    keys: 'c',
    label: 'Center Selected',
    description: 'Center on selected node',
    category: 'navigation',
    icon: 'Crosshair',
    when: ['input-not-focused', 'has-selection'],
    action: 'novanet:center-selected',
  },

  // View
  {
    id: 'toggle-2d-3d',
    keys: 'v',
    label: 'Toggle 2D/3D',
    description: 'Switch between 2D and 3D view',
    category: 'view',
    icon: 'Box',
    when: ['input-not-focused'],
    action: 'novanet:toggle-view',
  },
  {
    id: 'focus-mode',
    keys: 'g',
    label: 'Focus Mode',
    description: 'Hide all panels (Zen mode)',
    category: 'view',
    icon: 'Minimize2',
    when: ['input-not-focused'],
    action: 'novanet:toggle-focus',
  },
  {
    id: 'toggle-sidebar',
    keys: '[',
    label: 'Toggle Sidebar',
    description: 'Show/hide filter sidebar',
    category: 'view',
    icon: 'PanelLeft',
    when: ['input-not-focused'],
    action: 'novanet:toggle-sidebar',
  },
  {
    id: 'toggle-panel',
    keys: ']',
    label: 'Toggle Panel',
    description: 'Show/hide detail panel',
    category: 'view',
    icon: 'PanelRight',
    when: ['input-not-focused'],
    action: 'novanet:toggle-panel',
  },
  {
    id: 'toggle-minimap',
    keys: 'm',
    label: 'Toggle MiniMap',
    category: 'view',
    icon: 'Map',
    when: ['input-not-focused'],
    action: 'novanet:toggle-minimap',
  },
  {
    id: 'toggle-edge-labels',
    keys: 'l',
    label: 'Toggle Edge Labels',
    description: 'Show/hide relationship names on edges',
    category: 'view',
    icon: 'Tag',
    when: ['input-not-focused'],
    action: 'novanet:toggle-edge-labels',
  },

  // Filter / Search
  {
    id: 'cycle-locale',
    keys: 'shift+l',
    label: 'Cycle Locale',
    description: 'Cycle through available locales',
    category: 'filter',
    icon: 'Globe',
    when: ['input-not-focused'],
    action: 'novanet:cycle-locale',
  },
  {
    id: 'command-palette',
    keys: 'mod+k',
    label: 'Command Palette',
    description: 'Open command palette',
    category: 'filter',
    icon: 'Search',
    action: 'novanet:command-palette',
  },
  {
    id: 'search',
    keys: '/',
    label: 'Search',
    description: 'Focus search input',
    category: 'filter',
    icon: 'Search',
    when: ['input-not-focused'],
    action: 'novanet:search',
  },
  {
    id: 'ai-chat',
    keys: 'mod+j',
    label: 'AI Chat',
    description: 'Open AI search chat',
    category: 'filter',
    icon: 'Sparkles',
    action: 'novanet:ai-chat',
  },

  // Presets (1-9, 0)
  {
    id: 'preset-1',
    keys: '1',
    label: 'Project Overview',
    category: 'preset',
    icon: 'LayoutDashboard',
    when: ['input-not-focused'],
    action: 'novanet:preset:overview',
  },
  {
    id: 'preset-2',
    keys: '2',
    label: 'Full Graph',
    category: 'preset',
    icon: 'Globe',
    when: ['input-not-focused'],
    action: 'novanet:preset:full',
  },
  {
    id: 'preset-3',
    keys: '3',
    label: 'Core + Concepts',
    category: 'preset',
    icon: 'Layers',
    when: ['input-not-focused'],
    action: 'novanet:preset:core-concepts',
  },
  {
    id: 'preset-4',
    keys: '4',
    label: 'All Locales',
    category: 'preset',
    icon: 'Map',
    when: ['input-not-focused'],
    action: 'novanet:preset:all-locales',
  },
  {
    id: 'preset-5',
    keys: '5',
    label: 'Concepts',
    category: 'preset',
    icon: 'Lightbulb',
    when: ['input-not-focused'],
    action: 'novanet:preset:concepts',
  },
  {
    id: 'preset-6',
    keys: '6',
    label: 'Current Locale',
    category: 'preset',
    icon: 'Target',
    when: ['input-not-focused'],
    action: 'novanet:preset:current-locale',
  },
  {
    id: 'preset-7',
    keys: '7',
    label: 'Locale + Expressions',
    category: 'preset',
    icon: 'MessageSquare',
    when: ['input-not-focused'],
    action: 'novanet:preset:locale-expressions',
  },
  {
    id: 'preset-0',
    keys: '0',
    label: 'Clear Filters',
    category: 'preset',
    icon: 'X',
    when: ['input-not-focused'],
    action: 'novanet:preset:clear',
  },

  // Node Navigation (Neo4j Browser style)
  {
    id: 'cycle-next-connected',
    keys: 'tab',
    label: 'Next Connected Node',
    description: 'Cycle to next connected node',
    category: 'navigation',
    icon: 'ArrowRight',
    when: ['input-not-focused', 'has-selection'],
    action: 'novanet:cycle-next',
  },
  {
    id: 'cycle-prev-connected',
    keys: 'shift+tab',
    label: 'Previous Connected Node',
    description: 'Cycle to previous connected node',
    category: 'navigation',
    icon: 'ArrowLeft',
    when: ['input-not-focused', 'has-selection'],
    action: 'novanet:cycle-prev',
  },
  {
    id: 'expand-node',
    keys: 'enter',
    label: 'Expand Node',
    description: 'Expand selected node neighbors',
    category: 'navigation',
    icon: 'Maximize2',
    when: ['input-not-focused', 'has-selection'],
    action: 'novanet:expand-node',
  },
  {
    id: 'hide-node',
    keys: 'delete',
    label: 'Hide Node',
    description: 'Hide selected node from view',
    category: 'navigation',
    icon: 'EyeOff',
    when: ['input-not-focused', 'has-selection'],
    action: 'novanet:hide-node',
  },

  // Layout (Shift + key)
  {
    id: 'layout-horizontal',
    keys: 'shift+h',
    label: 'Horizontal Layout',
    description: 'Arrange nodes horizontally (LR)',
    category: 'layout',
    icon: 'ArrowRight',
    when: ['input-not-focused'],
    action: 'novanet:layout:horizontal',
  },
  {
    id: 'layout-vertical',
    keys: 'shift+v',
    label: 'Vertical Layout',
    description: 'Arrange nodes vertically (TB)',
    category: 'layout',
    icon: 'ArrowDown',
    when: ['input-not-focused'],
    action: 'novanet:layout:vertical',
  },
  {
    id: 'layout-dagre',
    keys: 'shift+d',
    label: 'Dagre Layout',
    description: 'Hierarchical directed layout',
    category: 'layout',
    icon: 'GitBranch',
    when: ['input-not-focused'],
    action: 'novanet:layout:dagre',
  },
  {
    id: 'layout-radial',
    keys: 'shift+r',
    label: 'Radial Layout',
    description: 'Circular arrangement around center',
    category: 'layout',
    icon: 'Circle',
    when: ['input-not-focused'],
    action: 'novanet:layout:radial',
  },
  {
    id: 'layout-force',
    keys: 'shift+f',
    label: 'Force Layout',
    description: 'Force-directed simulation',
    category: 'layout',
    icon: 'Zap',
    when: ['input-not-focused'],
    action: 'novanet:layout:force',
  },

  // Help
  {
    id: 'show-help',
    keys: '?',
    label: 'Keyboard Shortcuts',
    description: 'Show keyboard shortcuts help',
    category: 'action',
    icon: 'HelpCircle',
    when: ['input-not-focused'],
    action: 'novanet:show-help',
  },

  // Actions
  {
    id: 'copy-properties',
    keys: 'mod+c',
    label: 'Copy Properties',
    description: 'Copy selected node properties',
    category: 'action',
    icon: 'Copy',
    when: ['has-selection'],
    action: 'novanet:copy-properties',
  },
  {
    id: 'copy-cypher',
    keys: 'mod+shift+c',
    label: 'Copy Cypher',
    description: 'Copy Cypher query for selected',
    category: 'action',
    icon: 'Code',
    when: ['has-selection'],
    action: 'novanet:copy-cypher',
  },
  {
    id: 'refresh',
    keys: 'mod+r',
    label: 'Refresh',
    description: 'Reload graph data',
    category: 'action',
    icon: 'RefreshCw',
    action: 'novanet:refresh',
  },
  {
    id: 'escape',
    keys: 'escape',
    label: 'Deselect / Close',
    description: 'Clear selection or close dialogs',
    category: 'action',
    icon: 'X',
    action: 'novanet:escape',
  },
];
