// Organizing Principles Seed v9.0.0
// AUTO-GENERATED by novanet — do not edit manually
// Run: novanet schema generate
//
// Creates: 3 Realms, 9 Layers, 5 Traits, 5 EdgeFamilies
// All meta-nodes have :Meta double-label
// Uses MERGE for idempotent execution

// ═══════════════════════════════════════════════════════════════════════════════
// REALMS (3)
// ═══════════════════════════════════════════════════════════════════════════════

MERGE (r_global:Meta:Realm {key: 'global'})
ON CREATE SET
  r_global.display_name = 'Global',
  r_global.emoji = '🌍',
  r_global.color = '#2aa198',
  r_global.llm_context = 'Shared across ALL projects. Locale-specific knowledge that applies universally: cultural norms, linguistic patterns, voice guidelines, idiomatic expressions. These nodes are READ-ONLY at project level. Changes here affect all projects using that locale.',
  r_global.created_at = datetime()
ON MATCH SET
  r_global.display_name = 'Global',
  r_global.emoji = '🌍',
  r_global.color = '#2aa198',
  r_global.llm_context = 'Shared across ALL projects. Locale-specific knowledge that applies universally: cultural norms, linguistic patterns, voice guidelines, idiomatic expressions. These nodes are READ-ONLY at project level. Changes here affect all projects using that locale.',
  r_global.updated_at = datetime();

MERGE (r_project:Meta:Realm {key: 'project'})
ON CREATE SET
  r_project.display_name = 'Project',
  r_project.emoji = '📦',
  r_project.color = '#6c71c4',
  r_project.llm_context = 'Business-specific nodes for a single project. Contains brand identity, page structure, semantic concepts, generation prompts, and localized outputs. These nodes define WHAT content to generate and HOW to structure it for this specific product/service.',
  r_project.created_at = datetime()
ON MATCH SET
  r_project.display_name = 'Project',
  r_project.emoji = '📦',
  r_project.color = '#6c71c4',
  r_project.llm_context = 'Business-specific nodes for a single project. Contains brand identity, page structure, semantic concepts, generation prompts, and localized outputs. These nodes define WHAT content to generate and HOW to structure it for this specific product/service.',
  r_project.updated_at = datetime();

MERGE (r_shared:Meta:Realm {key: 'shared'})
ON CREATE SET
  r_shared.display_name = 'Shared',
  r_shared.emoji = '🎯',
  r_shared.color = '#cb4b16',
  r_shared.llm_context = 'Cross-project resources that can be linked to multiple projects. SEO keywords and GEO seeds with their metrics. These enable competitive intelligence sharing across the portfolio.',
  r_shared.created_at = datetime()
ON MATCH SET
  r_shared.display_name = 'Shared',
  r_shared.emoji = '🎯',
  r_shared.color = '#cb4b16',
  r_shared.llm_context = 'Cross-project resources that can be linked to multiple projects. SEO keywords and GEO seeds with their metrics. These enable competitive intelligence sharing across the portfolio.',
  r_shared.updated_at = datetime();

// ═══════════════════════════════════════════════════════════════════════════════
// LAYERS (9)
// ═══════════════════════════════════════════════════════════════════════════════

// Global layers
MERGE (l_config:Meta:Layer {key: 'config'})
ON CREATE SET
  l_config.display_name = 'Configuration',
  l_config.emoji = '⚙️',
  l_config.color = '#64748b',
  l_config.llm_context = 'Core configuration nodes. Locale definitions with their properties (language code, region, writing direction). Entry point for all locale-specific knowledge traversal.',
  l_config.created_at = datetime()
ON MATCH SET
  l_config.display_name = 'Configuration',
  l_config.emoji = '⚙️',
  l_config.color = '#64748b',
  l_config.llm_context = 'Core configuration nodes. Locale definitions with their properties (language code, region, writing direction). Entry point for all locale-specific knowledge traversal.',
  l_config.updated_at = datetime();

MATCH (r:Realm {key: 'global'}), (l:Layer {key: 'config'})
MERGE (r)-[:HAS_LAYER]->(l);
MERGE (l_knowledge:Meta:Layer {key: 'knowledge'})
ON CREATE SET
  l_knowledge.display_name = 'Locale Knowledge',
  l_knowledge.emoji = '📚',
  l_knowledge.color = '#8b5cf6',
  l_knowledge.llm_context = 'Deep locale-specific knowledge for native content generation. Cultural norms, linguistic patterns, voice guidelines, idiomatic expressions, formatting conventions. This is what makes generated content feel NATIVE rather than translated.',
  l_knowledge.created_at = datetime()
ON MATCH SET
  l_knowledge.display_name = 'Locale Knowledge',
  l_knowledge.emoji = '📚',
  l_knowledge.color = '#8b5cf6',
  l_knowledge.llm_context = 'Deep locale-specific knowledge for native content generation. Cultural norms, linguistic patterns, voice guidelines, idiomatic expressions, formatting conventions. This is what makes generated content feel NATIVE rather than translated.',
  l_knowledge.updated_at = datetime();

MATCH (r:Realm {key: 'global'}), (l:Layer {key: 'knowledge'})
MERGE (r)-[:HAS_LAYER]->(l);

// Project layers
MERGE (l_foundation:Meta:Layer {key: 'foundation'})
ON CREATE SET
  l_foundation.display_name = 'Foundation',
  l_foundation.emoji = '🏛️',
  l_foundation.color = '#3b82f6',
  l_foundation.llm_context = 'Core project identity. Brand voice, visual identity, value proposition. These nodes anchor ALL content generation for the project - every generated block must align with foundation.',
  l_foundation.created_at = datetime()
ON MATCH SET
  l_foundation.display_name = 'Foundation',
  l_foundation.emoji = '🏛️',
  l_foundation.color = '#3b82f6',
  l_foundation.llm_context = 'Core project identity. Brand voice, visual identity, value proposition. These nodes anchor ALL content generation for the project - every generated block must align with foundation.',
  l_foundation.updated_at = datetime();

MATCH (r:Realm {key: 'project'}), (l:Layer {key: 'foundation'})
MERGE (r)-[:HAS_LAYER]->(l);
MERGE (l_structure:Meta:Layer {key: 'structure'})
ON CREATE SET
  l_structure.display_name = 'Structure',
  l_structure.emoji = '🏗️',
  l_structure.color = '#06b6d4',
  l_structure.llm_context = 'Information architecture. Pages, blocks, and their types. Defines the SKELETON of the website - what pages exist, what blocks compose each page, and the rules for each block type.',
  l_structure.created_at = datetime()
ON MATCH SET
  l_structure.display_name = 'Structure',
  l_structure.emoji = '🏗️',
  l_structure.color = '#06b6d4',
  l_structure.llm_context = 'Information architecture. Pages, blocks, and their types. Defines the SKELETON of the website - what pages exist, what blocks compose each page, and the rules for each block type.',
  l_structure.updated_at = datetime();

MATCH (r:Realm {key: 'project'}), (l:Layer {key: 'structure'})
MERGE (r)-[:HAS_LAYER]->(l);
MERGE (l_semantic:Meta:Layer {key: 'semantic'})
ON CREATE SET
  l_semantic.display_name = 'Semantic Layer',
  l_semantic.emoji = '💡',
  l_semantic.color = '#f97316',
  l_semantic.llm_context = 'Meaning and concepts. Invariant ideas (Concept) that get localized per locale (ConceptL10n). The WHAT of content - pricing tiers, features, benefits, use cases. Concepts link via SEMANTIC_LINK for spreading activation during generation.',
  l_semantic.created_at = datetime()
ON MATCH SET
  l_semantic.display_name = 'Semantic Layer',
  l_semantic.emoji = '💡',
  l_semantic.color = '#f97316',
  l_semantic.llm_context = 'Meaning and concepts. Invariant ideas (Concept) that get localized per locale (ConceptL10n). The WHAT of content - pricing tiers, features, benefits, use cases. Concepts link via SEMANTIC_LINK for spreading activation during generation.',
  l_semantic.updated_at = datetime();

MATCH (r:Realm {key: 'project'}), (l:Layer {key: 'semantic'})
MERGE (r)-[:HAS_LAYER]->(l);
MERGE (l_instruction:Meta:Layer {key: 'instruction'})
ON CREATE SET
  l_instruction.display_name = 'Instructions',
  l_instruction.emoji = '📝',
  l_instruction.color = '#eab308',
  l_instruction.llm_context = 'Generation directives. Prompts and rules that guide the LLM during content generation. PagePrompt for page-level guidance, BlockPrompt for block-specific instructions, BlockRules for constraints.',
  l_instruction.created_at = datetime()
ON MATCH SET
  l_instruction.display_name = 'Instructions',
  l_instruction.emoji = '📝',
  l_instruction.color = '#eab308',
  l_instruction.llm_context = 'Generation directives. Prompts and rules that guide the LLM during content generation. PagePrompt for page-level guidance, BlockPrompt for block-specific instructions, BlockRules for constraints.',
  l_instruction.updated_at = datetime();

MATCH (r:Realm {key: 'project'}), (l:Layer {key: 'instruction'})
MERGE (r)-[:HAS_LAYER]->(l);
MERGE (l_output:Meta:Layer {key: 'output'})
ON CREATE SET
  l_output.display_name = 'Generated Output',
  l_output.emoji = '✨',
  l_output.color = '#22c55e',
  l_output.llm_context = 'LLM-generated content. The final localized pages and blocks ready for rendering. These are the RESULTS of the generation pipeline - created by combining foundation, structure, semantic, and instruction nodes with locale knowledge.',
  l_output.created_at = datetime()
ON MATCH SET
  l_output.display_name = 'Generated Output',
  l_output.emoji = '✨',
  l_output.color = '#22c55e',
  l_output.llm_context = 'LLM-generated content. The final localized pages and blocks ready for rendering. These are the RESULTS of the generation pipeline - created by combining foundation, structure, semantic, and instruction nodes with locale knowledge.',
  l_output.updated_at = datetime();

MATCH (r:Realm {key: 'project'}), (l:Layer {key: 'output'})
MERGE (r)-[:HAS_LAYER]->(l);

// Shared layers
MERGE (l_seo:Meta:Layer {key: 'seo'})
ON CREATE SET
  l_seo.display_name = 'SEO Intelligence',
  l_seo.emoji = '🔍',
  l_seo.color = '#ec4899',
  l_seo.llm_context = 'Search engine optimization data. Keywords with their localized forms, search volume metrics, and mining run history. Used to inject relevant keywords into generated content for organic search visibility.',
  l_seo.created_at = datetime()
ON MATCH SET
  l_seo.display_name = 'SEO Intelligence',
  l_seo.emoji = '🔍',
  l_seo.color = '#ec4899',
  l_seo.llm_context = 'Search engine optimization data. Keywords with their localized forms, search volume metrics, and mining run history. Used to inject relevant keywords into generated content for organic search visibility.',
  l_seo.updated_at = datetime();

MATCH (r:Realm {key: 'shared'}), (l:Layer {key: 'seo'})
MERGE (r)-[:HAS_LAYER]->(l);
MERGE (l_geo:Meta:Layer {key: 'geo'})
ON CREATE SET
  l_geo.display_name = 'GEO Intelligence',
  l_geo.emoji = '📍',
  l_geo.color = '#ef4444',
  l_geo.llm_context = 'Geographic/local SEO data. Location-based seeds with their localized forms, metrics, and mining history. Used for local business visibility and location-specific content generation.',
  l_geo.created_at = datetime()
ON MATCH SET
  l_geo.display_name = 'GEO Intelligence',
  l_geo.emoji = '📍',
  l_geo.color = '#ef4444',
  l_geo.llm_context = 'Geographic/local SEO data. Location-based seeds with their localized forms, metrics, and mining history. Used for local business visibility and location-specific content generation.',
  l_geo.updated_at = datetime();

MATCH (r:Realm {key: 'shared'}), (l:Layer {key: 'geo'})
MERGE (r)-[:HAS_LAYER]->(l);

// ═══════════════════════════════════════════════════════════════════════════════
// TRAITS (5)
// ═══════════════════════════════════════════════════════════════════════════════

MERGE (t_invariant:Meta:Trait {key: 'invariant'})
ON CREATE SET
  t_invariant.display_name = 'Invariant',
  t_invariant.color = '#3b82f6',
  t_invariant.llm_context = 'Nodes that do not change between locales. Structural definitions, configuration, and invariant business logic. Always the same regardless of target locale.',
  t_invariant.created_at = datetime()
ON MATCH SET
  t_invariant.display_name = 'Invariant',
  t_invariant.color = '#3b82f6',
  t_invariant.llm_context = 'Nodes that do not change between locales. Structural definitions, configuration, and invariant business logic. Always the same regardless of target locale.',
  t_invariant.updated_at = datetime();

MERGE (t_localized:Meta:Trait {key: 'localized'})
ON CREATE SET
  t_localized.display_name = 'Localized',
  t_localized.color = '#22c55e',
  t_localized.llm_context = 'Content generated natively per locale. NOT translated — each locale version is generated independently from the invariant Concept using locale-specific knowledge.',
  t_localized.created_at = datetime()
ON MATCH SET
  t_localized.display_name = 'Localized',
  t_localized.color = '#22c55e',
  t_localized.llm_context = 'Content generated natively per locale. NOT translated — each locale version is generated independently from the invariant Concept using locale-specific knowledge.',
  t_localized.updated_at = datetime();

MERGE (t_knowledge:Meta:Trait {key: 'knowledge'})
ON CREATE SET
  t_knowledge.display_name = 'Knowledge',
  t_knowledge.color = '#8b5cf6',
  t_knowledge.llm_context = 'Cultural and linguistic expertise per locale. Deep knowledge about how a locale communicates: voice, culture, formatting rules, lexicon, expressions. The foundation for native content generation.',
  t_knowledge.created_at = datetime()
ON MATCH SET
  t_knowledge.display_name = 'Knowledge',
  t_knowledge.color = '#8b5cf6',
  t_knowledge.llm_context = 'Cultural and linguistic expertise per locale. Deep knowledge about how a locale communicates: voice, culture, formatting rules, lexicon, expressions. The foundation for native content generation.',
  t_knowledge.updated_at = datetime();

MERGE (t_derived:Meta:Trait {key: 'derived'})
ON CREATE SET
  t_derived.display_name = 'Derived',
  t_derived.color = '#9ca3af',
  t_derived.llm_context = 'Computed or aggregated data. Time-series metrics, analytics snapshots, and other values derived from external sources or calculations.',
  t_derived.created_at = datetime()
ON MATCH SET
  t_derived.display_name = 'Derived',
  t_derived.color = '#9ca3af',
  t_derived.llm_context = 'Computed or aggregated data. Time-series metrics, analytics snapshots, and other values derived from external sources or calculations.',
  t_derived.updated_at = datetime();

MERGE (t_job:Meta:Trait {key: 'job'})
ON CREATE SET
  t_job.display_name = 'Job',
  t_job.color = '#6b7280',
  t_job.llm_context = 'Background processing tasks. Mining runs, batch operations, and other asynchronous jobs that produce or update data nodes.',
  t_job.created_at = datetime()
ON MATCH SET
  t_job.display_name = 'Job',
  t_job.color = '#6b7280',
  t_job.llm_context = 'Background processing tasks. Mining runs, batch operations, and other asynchronous jobs that produce or update data nodes.',
  t_job.updated_at = datetime();

// ═══════════════════════════════════════════════════════════════════════════════
// EDGE FAMILIES (5)
// ═══════════════════════════════════════════════════════════════════════════════

MERGE (ef_ownership:Meta:EdgeFamily {key: 'ownership'})
ON CREATE SET
  ef_ownership.display_name = 'Ownership',
  ef_ownership.color = '#3b82f6',
  ef_ownership.arrow_style = '-->',
  ef_ownership.llm_context = 'Parent-child structural relationships. A node "owns" or "contains" another. Always follow in traversal (structural backbone).',
  ef_ownership.created_at = datetime()
ON MATCH SET
  ef_ownership.display_name = 'Ownership',
  ef_ownership.color = '#3b82f6',
  ef_ownership.arrow_style = '-->',
  ef_ownership.llm_context = 'Parent-child structural relationships. A node "owns" or "contains" another. Always follow in traversal (structural backbone).',
  ef_ownership.updated_at = datetime();

MERGE (ef_localization:Meta:EdgeFamily {key: 'localization'})
ON CREATE SET
  ef_localization.display_name = 'Localization',
  ef_localization.color = '#22c55e',
  ef_localization.arrow_style = '.->',
  ef_localization.llm_context = 'Links between invariant nodes and their locale-specific content. Includes locale knowledge edges (Locale → LocaleVoice, etc.) and content localization edges (Concept → ConceptL10n, etc.).',
  ef_localization.created_at = datetime()
ON MATCH SET
  ef_localization.display_name = 'Localization',
  ef_localization.color = '#22c55e',
  ef_localization.arrow_style = '.->',
  ef_localization.llm_context = 'Links between invariant nodes and their locale-specific content. Includes locale knowledge edges (Locale → LocaleVoice, etc.) and content localization edges (Concept → ConceptL10n, etc.).',
  ef_localization.updated_at = datetime();

MERGE (ef_semantic:Meta:EdgeFamily {key: 'semantic'})
ON CREATE SET
  ef_semantic.display_name = 'Semantic',
  ef_semantic.color = '#f97316',
  ef_semantic.arrow_style = '.->',
  ef_semantic.llm_context = 'Meaning and concept connections. Spreading activation traversal with temperature-based filtering. Links concepts to each other and to the pages/blocks that use them.',
  ef_semantic.created_at = datetime()
ON MATCH SET
  ef_semantic.display_name = 'Semantic',
  ef_semantic.color = '#f97316',
  ef_semantic.arrow_style = '.->',
  ef_semantic.llm_context = 'Meaning and concept connections. Spreading activation traversal with temperature-based filtering. Links concepts to each other and to the pages/blocks that use them.',
  ef_semantic.updated_at = datetime();

MERGE (ef_generation:Meta:EdgeFamily {key: 'generation'})
ON CREATE SET
  ef_generation.display_name = 'Generation',
  ef_generation.color = '#8b5cf6',
  ef_generation.arrow_style = '==>',
  ef_generation.llm_context = 'LLM generation pipeline flow. Provenance tracking from prompts to outputs, version history, and assembly relationships.',
  ef_generation.created_at = datetime()
ON MATCH SET
  ef_generation.display_name = 'Generation',
  ef_generation.color = '#8b5cf6',
  ef_generation.arrow_style = '==>',
  ef_generation.llm_context = 'LLM generation pipeline flow. Provenance tracking from prompts to outputs, version history, and assembly relationships.',
  ef_generation.updated_at = datetime();

MERGE (ef_mining:Meta:EdgeFamily {key: 'mining'})
ON CREATE SET
  ef_mining.display_name = 'Mining',
  ef_mining.color = '#ec4899',
  ef_mining.arrow_style = '--o',
  ef_mining.llm_context = 'SEO/GEO data extraction and targeting. Links mining runs to their targets and concepts to their SEO/GEO keyword targets.',
  ef_mining.created_at = datetime()
ON MATCH SET
  ef_mining.display_name = 'Mining',
  ef_mining.color = '#ec4899',
  ef_mining.arrow_style = '--o',
  ef_mining.llm_context = 'SEO/GEO data extraction and targeting. Links mining runs to their targets and concepts to their SEO/GEO keyword targets.',
  ef_mining.updated_at = datetime();

