// =============================================================================
// GEOGRAPHIC TAXONOMY SEED - NovaNet v10.8
// =============================================================================
// Creates taxonomy nodes for geographic, linguistic, cultural, economic,
// and population classification.
//
// Sources:
// - UN M49: https://unstats.un.org/unsd/methodology/m49/
// - ISO 639-5: SIL International language families
// - World Bank: FY26 income classifications
// - Broek & Webb: Cultural realms classification
//
// AUTO-GENERATED by novanet v10.8.0
// =============================================================================

// -----------------------------------------------------------------------------
// CONTINENTS (UN M49 - 6 macro-regions)
// -----------------------------------------------------------------------------

MERGE (c:Continent {
  key: 'africa',
  name: 'Africa',
  m49_code: '002',
  wikidata_id: 'Q15',
  llm_context: 'USE: for African countries and markets. TRIGGERS: africa, african, subsaharan. CULTURAL_NOTES: Extremely diverse - 54 countries, 2000+ languages. Never generalize. Split by: Northern Africa (Arab/Berber), Sub-Saharan (diverse). ECONOMIC: Mix of LMIC/LIC, rapid mobile adoption, young population. AVOID: Treating as monolithic; colonial stereotypes; poverty focus.'
});

MERGE (c:Continent {
  key: 'americas',
  name: 'Americas',
  m49_code: '019',
  wikidata_id: 'Q828',
  llm_context: 'USE: for North, Central, South America + Caribbean. TRIGGERS: americas, american, western hemisphere. CULTURAL_NOTES: Split Occidental (NA, Southern Cone) vs Latin American. Indigenous influence varies: high (Guatemala, Peru) vs low (Argentina, USA). ECONOMIC: Full range HIC (US/CA) to LIC (Haiti). LANGUAGE: English north, Spanish/Portuguese south. AVOID: American = USA only.'
});

MERGE (c:Continent {
  key: 'asia',
  name: 'Asia',
  m49_code: '142',
  wikidata_id: 'Q48',
  llm_context: 'USE: for Asian countries and markets. TRIGGERS: asia, asian, east, southeast, middle east. CULTURAL_NOTES: 4 major cultural realms: East Asian, South Asian, Southeast Asian, Islamic (Middle East/Central Asia). High-context communication common. ECONOMIC: Full range from HIC (Japan, Singapore) to LIC (Afghanistan). SCRIPTS: CJK, Arabic, Devanagari, Thai. RTL: Arabic regions.'
});

MERGE (c:Continent {
  key: 'europe',
  name: 'Europe',
  m49_code: '150',
  wikidata_id: 'Q46',
  llm_context: 'USE: for European countries and markets. TRIGGERS: europe, european, eu. CULTURAL_NOTES: Predominantly Occidental. Split: Western (low-context), Eastern (medium-context), Mediterranean (relationship-focused), Nordic (egalitarian). ECONOMIC: Mostly HIC/UMIC. EU integration in west, post-Soviet east. SCRIPTS: Latin west, Cyrillic east. AVOID: EU = Europe.'
});

MERGE (c:Continent {
  key: 'oceania',
  name: 'Oceania',
  m49_code: '009',
  wikidata_id: 'Q538',
  llm_context: 'USE: for Pacific region markets. TRIGGERS: oceania, pacific, australasia. CULTURAL_NOTES: Australia/NZ = Occidental (British-influenced). Pacific Islands = Melanesian, Polynesian, Micronesian cultures with strong community focus. ECONOMIC: AU/NZ = HIC. Pacific Islands = LMIC/LIC. LANGUAGE: English dominant in AU/NZ. 1000+ indigenous languages in Melanesia.'
});

MERGE (c:Continent {
  key: 'antarctica',
  name: 'Antarctica',
  m49_code: '010',
  wikidata_id: 'Q51',
  llm_context: 'USE: for scientific/research contexts only. TRIGGERS: antarctica, antarctic, polar. NOTES: No permanent population. Research stations only. No commercial markets. Skip for localization.'
});

// -----------------------------------------------------------------------------
// GEO REGIONS (UN M49 - 22 intermediate regions)
// -----------------------------------------------------------------------------

// Africa regions
MERGE (r:GeoRegion {
  key: 'northern-africa',
  name: 'Northern Africa',
  m49_code: '015',
  parent_continent: 'africa',
  wikidata_id: 'Q27381',
  cultural_notes: 'CULTURE: Islamic-Arab realm, NOT Meso-African despite geography. Arabic + French + Berber. Mediterranean influence. HIGH-CONTEXT communication.',
  dominant_languages: ['ar', 'fr', 'ber']
});

MERGE (r:GeoRegion {
  key: 'western-africa',
  name: 'Western Africa',
  m49_code: '011',
  parent_continent: 'africa',
  wikidata_id: 'Q4412',
  cultural_notes: 'CULTURE: Meso-African with Islamic influence in north. Niger-Congo languages dominant. Strong oral traditions. Community-focused. French/English colonial legacy.',
  dominant_languages: ['fr', 'en', 'ha', 'yo', 'ig']
});

MERGE (r:GeoRegion {
  key: 'middle-africa',
  name: 'Middle Africa',
  m49_code: '017',
  parent_continent: 'africa',
  wikidata_id: 'Q27433',
  cultural_notes: 'CULTURE: Meso-African. Bantu languages dominant. French/Portuguese colonial legacy. DRC is largest country. Rich biodiversity context.',
  dominant_languages: ['fr', 'pt', 'sw', 'ln']
});

MERGE (r:GeoRegion {
  key: 'eastern-africa',
  name: 'Eastern Africa',
  m49_code: '014',
  parent_continent: 'africa',
  wikidata_id: 'Q27407',
  cultural_notes: 'CULTURE: Mix of Meso-African, Islamic (coast), and unique (Ethiopia). Swahili lingua franca. English dominant in east. Diverse: Nilotic, Cushitic, Bantu peoples.',
  dominant_languages: ['sw', 'en', 'am', 'om', 'so']
});

MERGE (r:GeoRegion {
  key: 'southern-africa',
  name: 'Southern Africa',
  m49_code: '018',
  parent_continent: 'africa',
  wikidata_id: 'Q27394',
  cultural_notes: 'CULTURE: Mix of Bantu, Khoisan, and European settler cultures. South Africa most developed. English/Afrikaans/Portuguese. Mining economies.',
  dominant_languages: ['en', 'af', 'zu', 'xh', 'pt']
});

// Americas regions
MERGE (r:GeoRegion {
  key: 'northern-america',
  name: 'Northern America',
  m49_code: '021',
  parent_continent: 'americas',
  wikidata_id: 'Q2017699',
  cultural_notes: 'CULTURE: Occidental. US and Canada. Low-context, direct communication. English dominant. French in Quebec. Indigenous populations. Consumer culture.',
  dominant_languages: ['en', 'fr', 'es']
});

MERGE (r:GeoRegion {
  key: 'central-america',
  name: 'Central America',
  m49_code: '013',
  parent_continent: 'americas',
  wikidata_id: 'Q27611',
  cultural_notes: 'CULTURE: Latin American with strong Mesoamerican indigenous influence. Spanish dominant. Catholic heritage. Guatemala/Belize exceptions. Family-centered.',
  dominant_languages: ['es', 'en']
});

MERGE (r:GeoRegion {
  key: 'caribbean',
  name: 'Caribbean',
  m49_code: '029',
  parent_continent: 'americas',
  wikidata_id: 'Q664609',
  cultural_notes: 'CULTURE: Syncretic - African, European, Indigenous mix. Spanish/English/French/Dutch colonial legacy. Island diversity. Tourism economies. Relaxed communication style.',
  dominant_languages: ['es', 'en', 'fr', 'ht', 'nl']
});

MERGE (r:GeoRegion {
  key: 'south-america',
  name: 'South America',
  m49_code: '005',
  parent_continent: 'americas',
  wikidata_id: 'Q18',
  cultural_notes: 'CULTURE: Latin American. Portuguese (Brazil) vs Spanish (rest). Indigenous influence varies. WARM communication, relationship-focused. Catholic heritage. Growing middle class.',
  dominant_languages: ['pt', 'es', 'qu', 'gn']
});

// Asia regions
MERGE (r:GeoRegion {
  key: 'western-asia',
  name: 'Western Asia',
  m49_code: '145',
  parent_continent: 'asia',
  wikidata_id: 'Q27293',
  cultural_notes: 'CULTURE: Islamic realm (Arab + Persian + Turkish). HIGH-CONTEXT. Formal/hierarchical. RTL scripts. Israel exception (Occidental/Judaic). Oil economies.',
  dominant_languages: ['ar', 'fa', 'tr', 'he', 'ku']
});

MERGE (r:GeoRegion {
  key: 'central-asia',
  name: 'Central Asia',
  m49_code: '143',
  parent_continent: 'asia',
  wikidata_id: 'Q27275',
  cultural_notes: 'CULTURE: Islamic with Soviet legacy. Turkic languages dominant. Russian widely spoken. Nomadic heritage. Post-Soviet transition economies.',
  dominant_languages: ['ru', 'kk', 'uz', 'tg', 'ky']
});

MERGE (r:GeoRegion {
  key: 'southern-asia',
  name: 'Southern Asia',
  m49_code: '034',
  parent_continent: 'asia',
  wikidata_id: 'Q771405',
  cultural_notes: 'CULTURE: Indic realm (Hindu-Buddhist) + Islamic (Pakistan, Bangladesh). HIGH-CONTEXT. Hierarchical. Diverse scripts. Collectivist. IT/services growth.',
  dominant_languages: ['hi', 'bn', 'ur', 'ta', 'te', 'mr']
});

MERGE (r:GeoRegion {
  key: 'eastern-asia',
  name: 'Eastern Asia',
  m49_code: '030',
  parent_continent: 'asia',
  wikidata_id: 'Q27231',
  cultural_notes: 'CULTURE: East Asian (Confucian-Buddhist). HIGH-CONTEXT. Indirect, face-saving. CJK scripts. Group harmony. Tech-forward. Japan, Korea, China, Taiwan.',
  dominant_languages: ['zh', 'ja', 'ko']
});

MERGE (r:GeoRegion {
  key: 'south-eastern-asia',
  name: 'South-Eastern Asia',
  m49_code: '035',
  parent_continent: 'asia',
  wikidata_id: 'Q11708',
  cultural_notes: 'CULTURE: Southeast Asian (Buddhist/Hindu/Islamic mix). Diverse. Indirect communication. Thailand, Vietnam, Indonesia, Philippines, Malaysia, Singapore. Mobile-first.',
  dominant_languages: ['id', 'ms', 'th', 'vi', 'tl', 'my']
});

// Europe regions
MERGE (r:GeoRegion {
  key: 'northern-europe',
  name: 'Northern Europe',
  m49_code: '154',
  parent_continent: 'europe',
  wikidata_id: 'Q27479',
  cultural_notes: 'CULTURE: Occidental Nordic. LOW-CONTEXT, direct, egalitarian. High trust societies. English widely spoken. Sustainability focus. Premium markets.',
  dominant_languages: ['en', 'sv', 'no', 'da', 'fi', 'is']
});

MERGE (r:GeoRegion {
  key: 'western-europe',
  name: 'Western Europe',
  m49_code: '155',
  parent_continent: 'europe',
  wikidata_id: 'Q27496',
  cultural_notes: 'CULTURE: Occidental core. Germanic + Romance. LOW-CONTEXT. Quality-focused consumers. EU core. Strong environmentalism. Direct communication.',
  dominant_languages: ['de', 'fr', 'nl', 'en']
});

MERGE (r:GeoRegion {
  key: 'eastern-europe',
  name: 'Eastern Europe',
  m49_code: '151',
  parent_continent: 'europe',
  wikidata_id: 'Q27468',
  cultural_notes: 'CULTURE: Occidental with Orthodox/Soviet legacy. Slavic languages. Cyrillic in east. MEDIUM-CONTEXT. Post-transition economies. EU members and non-members.',
  dominant_languages: ['ru', 'pl', 'uk', 'ro', 'cs', 'hu']
});

MERGE (r:GeoRegion {
  key: 'southern-europe',
  name: 'Southern Europe',
  m49_code: '039',
  parent_continent: 'europe',
  wikidata_id: 'Q27449',
  cultural_notes: 'CULTURE: Mediterranean. Romance languages. MEDIUM-CONTEXT, relationship-focused. Catholic heritage. Family values. Tourism economies. Warm communication style.',
  dominant_languages: ['es', 'it', 'pt', 'el', 'sr', 'hr']
});

// Oceania regions
MERGE (r:GeoRegion {
  key: 'australia-new-zealand',
  name: 'Australia and New Zealand',
  m49_code: '053',
  parent_continent: 'oceania',
  wikidata_id: 'Q45256',
  cultural_notes: 'CULTURE: Occidental (British heritage). English dominant. LOW-CONTEXT, direct. Multicultural (Asian immigration). Indigenous cultures. HIC markets.',
  dominant_languages: ['en', 'mi']
});

MERGE (r:GeoRegion {
  key: 'melanesia',
  name: 'Melanesia',
  m49_code: '054',
  parent_continent: 'oceania',
  wikidata_id: 'Q37394',
  cultural_notes: 'CULTURE: Pacific Islander. Extreme linguistic diversity (1000+ languages in PNG). Community-focused. Oral traditions. Mixed colonial legacy.',
  dominant_languages: ['en', 'fr', 'tpi', 'bi']
});

MERGE (r:GeoRegion {
  key: 'micronesia',
  name: 'Micronesia',
  m49_code: '057',
  parent_continent: 'oceania',
  wikidata_id: 'Q3359409',
  cultural_notes: 'CULTURE: Pacific Islander. Small island nations. US influence in some areas. Tourism-dependent. Community-focused.',
  dominant_languages: ['en', 'ch']
});

MERGE (r:GeoRegion {
  key: 'polynesia',
  name: 'Polynesia',
  m49_code: '061',
  parent_continent: 'oceania',
  wikidata_id: 'Q35942',
  cultural_notes: 'CULTURE: Pacific Islander. Shared Austronesian heritage. Hawaii, Samoa, Tonga, French Polynesia. Strong cultural identity. Tourism important.',
  dominant_languages: ['en', 'fr', 'sm', 'to', 'haw']
});

// -----------------------------------------------------------------------------
// GEO SUB-REGIONS (UN M49 intermediate + cultural groupings)
// -----------------------------------------------------------------------------
// Optional finer level below GeoRegion for localization granularity.
// Mix of official UN M49 codes and commonly used cultural/economic groupings.

// --- Europe ---

MERGE (sr:GeoSubRegion {
  key: 'channel-islands',
  name: 'Channel Islands',
  m49_code: '830',
  parent_region: 'northern-europe',
  wikidata_id: 'Q42314',
  llm_context: 'USE: for Jersey, Guernsey markets. TRIGGERS: channel islands, jersey, guernsey. CULTURE: British Crown Dependencies, NOT part of UK. Unique tax status. English dominant, Norman French heritage. HIGH income. AVOID: Treating as UK.'
});

MERGE (sr:GeoSubRegion {
  key: 'nordic-countries',
  name: 'Nordic Countries',
  
  parent_region: 'northern-europe',
  wikidata_id: 'Q52062',
  llm_context: 'USE: for Denmark, Finland, Iceland, Norway, Sweden. TRIGGERS: nordic, scandinavian, norden. CULTURE: High trust, egalitarian, design-focused, sustainability-conscious. HIGH income. English proficiency excellent. AVOID: Conflating with Baltic states.'
});

MERGE (sr:GeoSubRegion {
  key: 'baltic-states',
  name: 'Baltic States',
  
  parent_region: 'northern-europe',
  wikidata_id: 'Q107426',
  llm_context: 'USE: for Estonia, Latvia, Lithuania. TRIGGERS: baltic, baltics. CULTURE: Post-Soviet, EU members, distinct from Nordic. Tech-savvy (Estonia especially). Russian minority influence. AVOID: Conflating with Nordic or Eastern Europe.'
});

MERGE (sr:GeoSubRegion {
  key: 'british-isles',
  name: 'British Isles',
  
  parent_region: 'northern-europe',
  wikidata_id: 'Q38272',
  llm_context: 'USE: for UK + Ireland grouping. TRIGGERS: british isles. CULTURE: English-speaking, shared history but distinct identities. UK = Brexit, Ireland = EU. SENSITIVE: Term controversial in Ireland. AVOID: Using for Ireland alone.'
});

MERGE (sr:GeoSubRegion {
  key: 'benelux',
  name: 'Benelux',
  
  parent_region: 'western-europe',
  wikidata_id: 'Q12047',
  llm_context: 'USE: for Belgium, Netherlands, Luxembourg. TRIGGERS: benelux, low countries. CULTURE: Multilingual (Dutch, French, German), EU hub, high international business. LANGUAGE: NL has Dutch only, BE has Dutch+French+German, LU has French+German+Luxembourgish.'
});

MERGE (sr:GeoSubRegion {
  key: 'dach',
  name: 'DACH',
  
  parent_region: 'western-europe',
  wikidata_id: 'Q1079962',
  llm_context: 'USE: for Germany, Austria, Switzerland German-speaking markets. TRIGGERS: dach, german-speaking. CULTURE: German language unifies but distinct varieties (Hochdeutsch, Österreichisch, Schweizerdeutsch). High precision, quality focus. AVOID: Assuming identical German.'
});

MERGE (sr:GeoSubRegion {
  key: 'iberian-peninsula',
  name: 'Iberian Peninsula',
  
  parent_region: 'southern-europe',
  wikidata_id: 'Q12837',
  llm_context: 'USE: for Spain, Portugal, Andorra, Gibraltar. TRIGGERS: iberian, iberia. CULTURE: Romance languages (Spanish, Portuguese, Catalan, Basque). Mediterranean lifestyle. Regional identities strong (Catalonia, Basque Country). AVOID: Assuming Spanish = Castilian only.'
});

// --- Africa ---

MERGE (sr:GeoSubRegion {
  key: 'great-lakes-africa',
  name: 'Great Lakes Region',
  
  parent_region: 'eastern-africa',
  wikidata_id: 'Q186533',
  llm_context: 'USE: for Burundi, DRC, Kenya, Rwanda, Tanzania, Uganda. TRIGGERS: great lakes, african great lakes. CULTURE: Bantu languages dominant, Swahili lingua franca. Complex history (genocide, conflict). Rapid tech adoption (mobile money). SENSITIVE: Ethnic tensions.'
});

MERGE (sr:GeoSubRegion {
  key: 'horn-of-africa',
  name: 'Horn of Africa',
  
  parent_region: 'eastern-africa',
  wikidata_id: 'Q40530',
  llm_context: 'USE: for Djibouti, Eritrea, Ethiopia, Somalia. TRIGGERS: horn of africa. CULTURE: Cushitic + Semitic languages. Ethiopia unique (Amharic script, Orthodox Christianity, never colonized). Somalia = Islamic. SENSITIVE: Conflict zones, famine history.'
});

MERGE (sr:GeoSubRegion {
  key: 'maghreb',
  name: 'Maghreb',
  
  parent_region: 'northern-africa',
  wikidata_id: 'Q7835',
  llm_context: 'USE: for Algeria, Libya, Mauritania, Morocco, Tunisia. TRIGGERS: maghreb, north africa arab. CULTURE: Arab-Berber, Islamic, French colonial legacy. Arabic + French bilingual. Darija (Maghrebi Arabic) distinct from Middle Eastern Arabic. AVOID: Conflating with Middle East.'
});

// --- Asia ---

MERGE (sr:GeoSubRegion {
  key: 'mainland-southeast-asia',
  name: 'Mainland Southeast Asia',
  
  parent_region: 'south-eastern-asia',
  wikidata_id: 'Q11708',
  llm_context: 'USE: for Cambodia, Laos, Myanmar, Thailand, Vietnam. TRIGGERS: indochina, mainland southeast asia. CULTURE: Buddhist (Theravada) dominant except Vietnam (Mahayana + ancestor worship). Tonal languages. Rice culture. French colonial legacy (VN, LA, KH). SENSITIVE: Myanmar conflict.'
});

MERGE (sr:GeoSubRegion {
  key: 'maritime-southeast-asia',
  name: 'Maritime Southeast Asia',
  
  parent_region: 'south-eastern-asia',
  wikidata_id: 'Q3922305',
  llm_context: 'USE: for Indonesia, Malaysia, Philippines, Singapore, Brunei, Timor-Leste. TRIGGERS: maritime southeast asia, malay world. CULTURE: Austronesian heritage. Islam dominant (ID, MY, BN) except Philippines (Catholic) and Singapore (diverse). Malay lingua franca in MY/ID/BN.'
});

MERGE (sr:GeoSubRegion {
  key: 'levant',
  name: 'Levant',
  
  parent_region: 'western-asia',
  wikidata_id: 'Q81483',
  llm_context: 'USE: for Jordan, Lebanon, Palestine, Syria, Israel. TRIGGERS: levant, sham, eastern mediterranean. CULTURE: Levantine Arabic distinct. Christian minorities significant (Lebanon). HIGH complexity: Israeli-Palestinian conflict, Syrian crisis. SENSITIVE: Political terminology critical.'
});

MERGE (sr:GeoSubRegion {
  key: 'gulf-states',
  name: 'Gulf Cooperation Council',
  
  parent_region: 'western-asia',
  wikidata_id: 'Q217172',
  llm_context: 'USE: for Bahrain, Kuwait, Oman, Qatar, Saudi Arabia, UAE. TRIGGERS: gcc, gulf states, khaleeji. CULTURE: Gulf Arabic, Islamic (Sunni majority, Shia in Bahrain). Oil wealth, expat workforce majority. Luxury + traditional values. AVOID: Assuming homogeneous.'
});

MERGE (sr:GeoSubRegion {
  key: 'indian-subcontinent',
  name: 'Indian Subcontinent',
  
  parent_region: 'southern-asia',
  wikidata_id: 'Q60140',
  llm_context: 'USE: for India, Pakistan, Bangladesh, Sri Lanka, Nepal, Bhutan, Maldives. TRIGGERS: south asia, indian subcontinent. CULTURE: Indo-Aryan + Dravidian languages. Hindu/Muslim/Buddhist. Cricket-loving. Huge linguistic diversity (22 official languages in India alone).'
});

// --- Americas ---

MERGE (sr:GeoSubRegion {
  key: 'central-american-isthmus',
  name: 'Central American Isthmus',
  
  parent_region: 'central-america',
  wikidata_id: 'Q27611',
  llm_context: 'USE: for Guatemala, Belize, El Salvador, Honduras, Nicaragua, Costa Rica, Panama. TRIGGERS: central america, isthmus. CULTURE: Spanish dominant (except Belize = English). Strong indigenous heritage (Guatemala). Catholic. Panama = more cosmopolitan.'
});

MERGE (sr:GeoSubRegion {
  key: 'southern-cone',
  name: 'Southern Cone',
  
  parent_region: 'south-america',
  wikidata_id: 'Q110628',
  llm_context: 'USE: for Argentina, Chile, Uruguay, (sometimes Paraguay, S. Brazil). TRIGGERS: southern cone, cono sur. CULTURE: European immigrant influence (Italian, German). Rioplatense Spanish (voseo). Mate culture. More secular than rest of LatAm. Higher income.'
});

MERGE (sr:GeoSubRegion {
  key: 'andean-region',
  name: 'Andean Region',
  
  parent_region: 'south-america',
  wikidata_id: 'Q188590',
  llm_context: 'USE: for Bolivia, Colombia, Ecuador, Peru, Venezuela. TRIGGERS: andean, andes. CULTURE: Strong indigenous heritage (Quechua, Aymara). Spanish + indigenous languages. Altitude influences lifestyle. SENSITIVE: Venezuela political situation.'
});

// --- Oceania ---

MERGE (sr:GeoSubRegion {
  key: 'pacific-islands-forum',
  name: 'Pacific Islands Forum',
  
  parent_region: 'polynesia',
  wikidata_id: 'Q153541',
  llm_context: 'USE: for Pacific island nations excluding AU/NZ. TRIGGERS: pacific islands, south pacific. CULTURE: Polynesian, Melanesian, Micronesian. Community-focused. Climate change = existential threat. Small populations. Tourism + fishing economies.'
});

// -----------------------------------------------------------------------------
// INCOME GROUPS (World Bank FY26)
// -----------------------------------------------------------------------------

MERGE (i:IncomeGroup {
  key: 'lic',
  name: 'Low Income',
  gni_threshold_max: 1135,
  fiscal_year: 'FY26',
  wikidata_id: 'Q107482814',
  llm_context: 'USE: for markets with GNI ≤$1,135/capita. TRIGGERS: low income, developing, emerging. CONTENT_STYLE: Value-focused, practical benefits, mobile-first. AVOID: Luxury positioning, complex features.',
  content_style: 'value-focused, practical, mobile-first',
  market_characteristics: 'Price-sensitive, mobile-first, informal economy, youth demographic'
});

MERGE (i:IncomeGroup {
  key: 'lmic',
  name: 'Lower-Middle Income',
  gni_threshold_min: 1136,
  gni_threshold_max: 4495,
  fiscal_year: 'FY26',
  wikidata_id: 'Q107482815',
  llm_context: 'USE: for markets with GNI $1,136-$4,495/capita. TRIGGERS: lower-middle income, emerging. CONTENT_STYLE: Aspirational but accessible, growth messaging. AVOID: Premium-only positioning.',
  content_style: 'aspirational, accessible, growth-focused',
  market_characteristics: 'Growing middle class, mobile commerce, value-conscious aspirational'
});

MERGE (i:IncomeGroup {
  key: 'umic',
  name: 'Upper-Middle Income',
  gni_threshold_min: 4496,
  gni_threshold_max: 13935,
  fiscal_year: 'FY26',
  wikidata_id: 'Q107482816',
  llm_context: 'USE: for markets with GNI $4,496-$13,935/capita. TRIGGERS: upper-middle income, emerging market. CONTENT_STYLE: Quality + value balance, brand awareness growing. Mix of premium and accessible.',
  content_style: 'quality-value balance, brand-aware',
  market_characteristics: 'Established middle class, brand-conscious, e-commerce growth'
});

MERGE (i:IncomeGroup {
  key: 'hic',
  name: 'High Income',
  gni_threshold_min: 13936,
  fiscal_year: 'FY26',
  wikidata_id: 'Q107482817',
  llm_context: 'USE: for markets with GNI >$13,935/capita. TRIGGERS: high income, developed, advanced economy. CONTENT_STYLE: Quality, innovation, sustainability. Premium positioning acceptable.',
  content_style: 'quality-focused, innovation, sustainability',
  market_characteristics: 'Mature market, quality over price, sustainability-conscious, omnichannel'
});

// -----------------------------------------------------------------------------
// ECONOMIC REGIONS (World Bank)
// -----------------------------------------------------------------------------

MERGE (er:EconomicRegion {
  key: 'eap',
  name: 'East Asia & Pacific',
  abbreviation: 'EAP',
  wikidata_id: 'Q4119134',
  llm_context: 'USE: for China, Japan, Korea, SE Asia, Pacific islands markets. TRIGGERS: east asia, pacific rim, asia-pacific. CONTENT: Diverse from high-tech (Japan, Korea) to emerging (Vietnam, Indonesia). Mobile-first. E-commerce advanced.',
  country_examples: ['China', 'Japan', 'South Korea', 'Indonesia', 'Vietnam', 'Thailand', 'Philippines', 'Australia'],
  economic_characteristics: 'Manufacturing hub, tech-forward, mobile commerce, diverse income levels'
});

MERGE (er:EconomicRegion {
  key: 'eca',
  name: 'Europe & Central Asia',
  abbreviation: 'ECA',
  wikidata_id: 'Q4119132',
  llm_context: 'USE: for Eastern Europe, Russia, Turkey, Central Asia markets. TRIGGERS: eastern europe, central asia, eurasia. CONTENT: Post-Soviet transition economies to EU members. Cyrillic/Latin scripts. Orthodox Christian + Islamic influences.',
  country_examples: ['Russia', 'Turkey', 'Poland', 'Ukraine', 'Romania', 'Kazakhstan', 'Uzbekistan'],
  economic_characteristics: 'Transition economies, EU integration path, energy exports, manufacturing'
});

MERGE (er:EconomicRegion {
  key: 'lac',
  name: 'Latin America & Caribbean',
  abbreviation: 'LAC',
  wikidata_id: 'Q4119135',
  llm_context: 'USE: for Central/South America, Caribbean markets. TRIGGERS: latin america, latam, caribbean. CONTENT: Spanish/Portuguese dominant. Catholic cultural base. High inequality. Urban concentration. Social media heavy.',
  country_examples: ['Brazil', 'Mexico', 'Argentina', 'Colombia', 'Chile', 'Peru', 'Dominican Republic'],
  economic_characteristics: 'Commodity exports, inequality, urban concentration, social commerce growth'
});

MERGE (er:EconomicRegion {
  key: 'mena',
  name: 'Middle East & North Africa',
  abbreviation: 'MENA',
  wikidata_id: 'Q4119136',
  llm_context: 'USE: for Arab world, Iran, Israel, Turkey markets. TRIGGERS: middle east, north africa, mena, arab world. CONTENT: Arabic dominant. Islamic cultural context. RTL scripts. Oil economies + diversification. High mobile penetration.',
  country_examples: ['Saudi Arabia', 'UAE', 'Egypt', 'Morocco', 'Iran', 'Israel', 'Qatar'],
  economic_characteristics: 'Oil-dependent to diversifying, high mobile adoption, luxury segments, Islamic finance'
});

MERGE (er:EconomicRegion {
  key: 'na',
  name: 'North America',
  abbreviation: 'NA',
  wikidata_id: 'Q4119137',
  llm_context: 'USE: for USA, Canada markets. TRIGGERS: north america, usa, canada. CONTENT: English dominant (French in Quebec). Mature e-commerce. Innovation-driven. Multicultural. Sustainability-conscious. High expectations.',
  country_examples: ['United States', 'Canada'],
  economic_characteristics: 'Mature market, innovation hub, high purchasing power, sustainability focus'
});

MERGE (er:EconomicRegion {
  key: 'sa',
  name: 'South Asia',
  abbreviation: 'SA',
  wikidata_id: 'Q4119138',
  llm_context: 'USE: for India, Pakistan, Bangladesh, Sri Lanka markets. TRIGGERS: south asia, subcontinent, indian subcontinent. CONTENT: Hindi/English + regional languages. Hindu/Muslim/Buddhist. Mobile-first. Value-conscious. Festivals important.',
  country_examples: ['India', 'Pakistan', 'Bangladesh', 'Sri Lanka', 'Nepal'],
  economic_characteristics: 'Mobile-first, value-conscious, young demographics, festival-driven commerce'
});

MERGE (er:EconomicRegion {
  key: 'ssa',
  name: 'Sub-Saharan Africa',
  abbreviation: 'SSA',
  wikidata_id: 'Q4119133',
  llm_context: 'USE: for Africa south of Sahara markets. TRIGGERS: sub-saharan africa, africa, ssa. CONTENT: Multilingual (colonial + indigenous). Mobile money dominant. Young population. Informal economy large. Community-oriented.',
  country_examples: ['Nigeria', 'South Africa', 'Kenya', 'Ethiopia', 'Ghana', 'Tanzania'],
  economic_characteristics: 'Mobile money leaders, young demographics, informal economy, leapfrog tech adoption'
});

// -----------------------------------------------------------------------------
// LENDING CATEGORIES (World Bank)
// -----------------------------------------------------------------------------

MERGE (lc:LendingCategory {
  key: 'ida',
  name: 'IDA',
  full_name: 'International Development Association',
  wikidata_id: 'Q827525',
  llm_context: 'USE: for poorest countries (GNI ≤ $1,315/capita). TRIGGERS: ida, least developed, poorest countries. CONTENT: Basic needs focus. NGO/aid sector presence. Infrastructure gaps. Affordability critical. Local language important.',
  target_countries: 'Poorest countries with GNI per capita below $1,315',
  content_implications: 'Affordability-first, basic needs, development messaging, NGO partnerships'
});

MERGE (lc:LendingCategory {
  key: 'blend',
  name: 'Blend',
  full_name: 'Blend (IDA + IBRD eligible)',
  wikidata_id: 'Q827525',
  llm_context: 'USE: for transition countries (IDA-eligible but IBRD creditworthy). TRIGGERS: blend, transitional. CONTENT: Emerging from poverty. Growing middle class. Mix of basic and aspirational. Infrastructure improving.',
  target_countries: 'IDA-eligible but IBRD creditworthy (e.g., Pakistan, Nigeria, India historically)',
  content_implications: 'Aspirational + accessible mix, emerging middle class, infrastructure growth'
});

MERGE (lc:LendingCategory {
  key: 'ibrd',
  name: 'IBRD',
  full_name: 'International Bank for Reconstruction and Development',
  wikidata_id: 'Q189746',
  llm_context: 'USE: for middle-income countries (creditworthy). TRIGGERS: ibrd, middle-income, creditworthy. CONTENT: Standard commercial approach. Brand-conscious. Quality expectations. Sustainability messaging resonates.',
  target_countries: 'Middle-income countries with IBRD creditworthiness',
  content_implications: 'Standard commercial content, quality expectations, brand positioning'
});

// -----------------------------------------------------------------------------
// LANGUAGE FAMILIES (ISO 639-5)
// -----------------------------------------------------------------------------

MERGE (f:LanguageFamily {
  key: 'ine',
  name: 'Indo-European',
  iso_639_5: 'ine',
  speaker_estimate: '3.2 billion',
  wikidata_id: 'Q19860',
  primary_cultural_realm: 'occidental',
  writing_systems: ['Latin', 'Cyrillic', 'Greek', 'Armenian', 'Devanagari', 'Arabic'],
  llm_context: 'USE: for European, South Asian, Iranian languages. INCLUDES: English, Spanish, French, German, Russian, Hindi, Portuguese, Bengali, Urdu, Persian. LARGEST family by speakers (46% of world).'
});

MERGE (f:LanguageFamily {
  key: 'sit',
  name: 'Sino-Tibetan',
  iso_639_5: 'sit',
  speaker_estimate: '1.4 billion',
  wikidata_id: 'Q45961',
  primary_cultural_realm: 'east-asian',
  writing_systems: ['Chinese', 'Tibetan', 'Burmese'],
  llm_context: 'USE: for Chinese, Tibetan, Burmese languages. INCLUDES: Mandarin, Cantonese, Wu, Min, Hakka, Tibetan, Burmese. TONAL languages. CJK scripts.'
});

MERGE (f:LanguageFamily {
  key: 'nic',
  name: 'Niger-Congo',
  iso_639_5: 'nic',
  speaker_estimate: '700 million',
  wikidata_id: 'Q33838',
  primary_cultural_realm: 'meso-african',
  writing_systems: ['Latin'],
  llm_context: 'USE: for Sub-Saharan African languages. INCLUDES: Swahili, Yoruba, Igbo, Zulu, Shona, Fula. LARGEST African family. Bantu branch dominant in east/south.'
});

MERGE (f:LanguageFamily {
  key: 'afa',
  name: 'Afroasiatic',
  iso_639_5: 'afa',
  speaker_estimate: '500 million',
  wikidata_id: 'Q25268',
  primary_cultural_realm: 'islamic',
  writing_systems: ['Arabic', 'Hebrew', 'Latin', 'Ethiopic'],
  llm_context: 'USE: for Arabic, Hebrew, Amharic, Hausa, Somali. INCLUDES: Semitic (Arabic, Hebrew), Berber, Cushitic, Chadic. RTL for Arabic/Hebrew. Islamic cultural context for most.'
});

MERGE (f:LanguageFamily {
  key: 'map',
  name: 'Austronesian',
  iso_639_5: 'map',
  speaker_estimate: '400 million',
  wikidata_id: 'Q49228',
  primary_cultural_realm: 'southeast-asian',
  writing_systems: ['Latin', 'Javanese', 'Balinese'],
  llm_context: 'USE: for Indonesian, Malay, Filipino, Maori, Hawaiian. SPANS: Maritime SEA to Pacific to Madagascar. Latin script dominant today.'
});

MERGE (f:LanguageFamily {
  key: 'dra',
  name: 'Dravidian',
  iso_639_5: 'dra',
  speaker_estimate: '250 million',
  wikidata_id: 'Q33311',
  primary_cultural_realm: 'indic',
  writing_systems: ['Tamil', 'Telugu', 'Kannada', 'Malayalam'],
  llm_context: 'USE: for South Indian languages. INCLUDES: Tamil, Telugu, Kannada, Malayalam. DISTINCT from Indo-Aryan Hindi belt. Unique scripts. Strong regional identity.'
});

MERGE (f:LanguageFamily {
  key: 'trk',
  name: 'Turkic',
  iso_639_5: 'trk',
  speaker_estimate: '200 million',
  wikidata_id: 'Q34090',
  primary_cultural_realm: 'islamic',
  writing_systems: ['Latin', 'Cyrillic', 'Arabic'],
  llm_context: 'USE: for Turkish, Azerbaijani, Uzbek, Kazakh. CULTURAL: Islamic despite linguistic isolation. Ottoman heritage. Latin in Turkey, Cyrillic in Central Asia.'
});

MERGE (f:LanguageFamily {
  key: 'jpx',
  name: 'Japonic',
  iso_639_5: 'jpx',
  speaker_estimate: '130 million',
  wikidata_id: 'Q33702',
  primary_cultural_realm: 'east-asian',
  writing_systems: ['Japanese (Kanji, Hiragana, Katakana)'],
  llm_context: 'USE: for Japanese. ISOLATE family. Unique writing system (3 scripts). HIGH-CONTEXT culture. Honorifics essential. Polite forms required in business.'
});

MERGE (f:LanguageFamily {
  key: 'aav',
  name: 'Austroasiatic',
  iso_639_5: 'aav',
  speaker_estimate: '117 million',
  wikidata_id: 'Q33199',
  primary_cultural_realm: 'southeast-asian',
  writing_systems: ['Latin', 'Khmer'],
  llm_context: 'USE: for Vietnamese, Khmer. NOTE: Vietnamese culturally Sinosphere despite Austroasiatic linguistic family. Khmer with unique script. Tonal (Vietnamese).'
});

MERGE (f:LanguageFamily {
  key: 'tai',
  name: 'Tai-Kadai',
  iso_639_5: 'tai',
  speaker_estimate: '100 million',
  wikidata_id: 'Q33311',
  primary_cultural_realm: 'southeast-asian',
  writing_systems: ['Thai', 'Lao', 'Latin'],
  llm_context: 'USE: for Thai, Lao. CULTURE: Theravada Buddhist. Unique scripts derived from Khmer. Tonal languages. Respectful forms important.'
});

MERGE (f:LanguageFamily {
  key: 'kor',
  name: 'Koreanic',
  iso_639_5: 'kor',
  speaker_estimate: '80 million',
  wikidata_id: 'Q33552',
  primary_cultural_realm: 'east-asian',
  writing_systems: ['Hangul'],
  llm_context: 'USE: for Korean. ISOLATE family. Hangul script (scientific design). HIGH-CONTEXT. Honorifics essential. Confucian heritage. K-culture global influence.'
});

MERGE (f:LanguageFamily {
  key: 'ura',
  name: 'Uralic',
  iso_639_5: 'ura',
  speaker_estimate: '25 million',
  wikidata_id: 'Q47779',
  primary_cultural_realm: 'occidental',
  writing_systems: ['Latin', 'Cyrillic'],
  llm_context: 'USE: for Finnish, Hungarian, Estonian. CULTURAL: Occidental despite linguistic isolation. EU members. Nordic (Finnish) vs Central European (Hungarian) cultures.'
});

// -----------------------------------------------------------------------------
// LANGUAGE BRANCHES (ISO 639-5 subgroups)
// -----------------------------------------------------------------------------

// Indo-European branches
MERGE (b:LanguageBranch { key: 'gem', name: 'Germanic', iso_639_5: 'gem', parent_family: 'ine', includes: ['en', 'de', 'nl', 'sv', 'no', 'da', 'is', 'af'], llm_context: 'English, German, Dutch, Scandinavian. Latin script. Occidental culture.' });
MERGE (b:LanguageBranch { key: 'roa', name: 'Romance', iso_639_5: 'roa', parent_family: 'ine', includes: ['es', 'pt', 'fr', 'it', 'ro', 'ca'], llm_context: 'Spanish, Portuguese, French, Italian, Romanian. Latin script. Mediterranean + Latin American cultures.' });
MERGE (b:LanguageBranch { key: 'sla', name: 'Slavic', iso_639_5: 'sla', parent_family: 'ine', includes: ['ru', 'pl', 'uk', 'cs', 'sr', 'hr', 'bg', 'sk'], llm_context: 'Russian, Polish, Ukrainian, Czech, Serbian. Cyrillic (east) or Latin (west). Orthodox/Catholic split.' });
MERGE (b:LanguageBranch { key: 'inc', name: 'Indo-Aryan', iso_639_5: 'inc', parent_family: 'ine', includes: ['hi', 'bn', 'ur', 'pa', 'gu', 'mr', 'ne'], llm_context: 'Hindi, Bengali, Urdu, Punjabi. Devanagari/Arabic scripts. Indic + Islamic cultures.' });
MERGE (b:LanguageBranch { key: 'ira', name: 'Iranian', iso_639_5: 'ira', parent_family: 'ine', includes: ['fa', 'ps', 'ku', 'tg'], llm_context: 'Persian, Pashto, Kurdish, Tajik. Arabic script (mostly). Islamic cultural context.' });
MERGE (b:LanguageBranch { key: 'cel', name: 'Celtic', iso_639_5: 'cel', parent_family: 'ine', includes: ['ga', 'cy', 'gd', 'br'], llm_context: 'Irish, Welsh, Scottish Gaelic, Breton. Latin script. Strong cultural revival movements.' });
MERGE (b:LanguageBranch { key: 'grk', name: 'Hellenic', iso_639_5: 'grk', parent_family: 'ine', includes: ['el'], llm_context: 'Greek. Unique script. Mediterranean culture. Orthodox heritage.' });
MERGE (b:LanguageBranch { key: 'bal', name: 'Baltic', iso_639_5: 'bat', parent_family: 'ine', includes: ['lt', 'lv'], llm_context: 'Lithuanian, Latvian. Latin script. EU members. Mix of Nordic and Slavic influences.' });

// Sino-Tibetan branches
MERGE (b:LanguageBranch { key: 'zhx', name: 'Chinese', iso_639_5: 'zhx', parent_family: 'sit', includes: ['zh', 'yue', 'nan', 'wuu'], llm_context: 'Mandarin, Cantonese, Min, Wu. CJK characters. Tonal. Sinosphere culture.' });
MERGE (b:LanguageBranch { key: 'tbq', name: 'Tibeto-Burman', iso_639_5: 'tbq', parent_family: 'sit', includes: ['bo', 'my', 'dz'], llm_context: 'Tibetan, Burmese, Dzongkha. Buddhist cultures. Unique scripts.' });

// Afroasiatic branches
MERGE (b:LanguageBranch { key: 'sem', name: 'Semitic', iso_639_5: 'sem', parent_family: 'afa', includes: ['ar', 'he', 'am', 'ti', 'mt'], llm_context: 'Arabic, Hebrew, Amharic, Maltese. RTL (Arabic, Hebrew). Arabic = Islamic, Hebrew = Judaic, Maltese = Mediterranean.' });
MERGE (b:LanguageBranch { key: 'ber', name: 'Berber', iso_639_5: 'ber', parent_family: 'afa', includes: ['ber', 'tzm', 'kab'], llm_context: 'Berber languages of North Africa. Tifinagh/Latin scripts. Indigenous to Maghreb.' });

// Niger-Congo branches
MERGE (b:LanguageBranch { key: 'bnt', name: 'Bantu', iso_639_5: 'bnt', parent_family: 'nic', includes: ['sw', 'zu', 'xh', 'rw', 'rn', 'sn', 'lg'], llm_context: 'Swahili, Zulu, Xhosa, Rwandan. Latin script. East/Southern Africa. Swahili = lingua franca.' });
MERGE (b:LanguageBranch { key: 'alv', name: 'Atlantic-Congo', iso_639_5: 'alv', parent_family: 'nic', includes: ['yo', 'ig', 'ha', 'wo', 'ff'], llm_context: 'Yoruba, Igbo, Wolof, Fula. Latin script. West Africa. English/French colonial legacy.' });

// Turkic branches
MERGE (b:LanguageBranch { key: 'ogz', name: 'Oghuz', iso_639_5: 'ogz', parent_family: 'trk', includes: ['tr', 'az', 'tk'], llm_context: 'Turkish, Azerbaijani, Turkmen. Latin script (Turkey, Azerbaijan). Islamic culture.' });
MERGE (b:LanguageBranch { key: 'kip', name: 'Kipchak', iso_639_5: 'kip', parent_family: 'trk', includes: ['kk', 'ky', 'tt'], llm_context: 'Kazakh, Kyrgyz, Tatar. Cyrillic script. Central Asian. Post-Soviet context.' });

// Austronesian branches
MERGE (b:LanguageBranch { key: 'poz', name: 'Malayo-Polynesian', iso_639_5: 'poz', parent_family: 'map', includes: ['id', 'ms', 'tl', 'jv', 'mi', 'haw', 'sm', 'to'], llm_context: 'Indonesian, Malay, Filipino, Javanese, Maori, Hawaiian, Samoan. Latin script. SEA + Pacific.' });

// Austroasiatic branches
MERGE (b:LanguageBranch { key: 'mkh', name: 'Mon-Khmer', iso_639_5: 'mkh', parent_family: 'aav', includes: ['vi', 'km'], llm_context: 'Vietnamese, Khmer. Tonal (Vi). Unique Khmer script. Vietnamese = Sinosphere culture despite language family.' });

// Dravidian branches
MERGE (b:LanguageBranch { key: 'sdv', name: 'South Dravidian', iso_639_5: 'sdv', parent_family: 'dra', includes: ['ta', 'te', 'kn', 'ml'], llm_context: 'Tamil, Telugu, Kannada, Malayalam. Unique scripts each. South India. Strong regional identity.' });

// Uralic branches
MERGE (b:LanguageBranch { key: 'fiu', name: 'Finno-Ugric', iso_639_5: 'fiu', parent_family: 'ura', includes: ['fi', 'hu', 'et'], llm_context: 'Finnish, Hungarian, Estonian. Latin script. EU members. Nordic (Fi, Et) vs Central European (Hu).' });

// -----------------------------------------------------------------------------
// CULTURAL REALMS (Broek & Webb)
// -----------------------------------------------------------------------------

MERGE (cr:CulturalRealm {
  key: 'occidental',
  name: 'Occidental',
  wikidata_id: 'Q1410',
  core_values: 'individualism, rationalism, secularism, democracy, human rights',
  communication_style: 'low-context, direct, explicit, time-conscious',
  power_distance: 'low to medium',
  content_taboos: 'religious extremism, explicit nationalism, discrimination',
  llm_context: 'USE: for Western Europe, Americas, Australia/NZ. TRIGGERS: western, occidental, european-influenced. VALUES: Individual rights, direct communication, time efficiency. STYLE: Low-context, explicit, data-driven. AVOID: Vague claims, excessive formality.'
});

MERGE (cr:CulturalRealm {
  key: 'islamic',
  name: 'Islamic',
  wikidata_id: 'Q98032199',
  core_values: 'faith, community, family, hospitality, modesty',
  communication_style: 'high-context, relationship-focused, indirect at times',
  power_distance: 'medium to high',
  content_taboos: 'alcohol, pork, immodest imagery, religious disrespect, LGBTQ+',
  llm_context: 'USE: for Middle East, North Africa, Central Asia, parts of South/Southeast Asia. TRIGGERS: islamic, muslim, arab, middle-eastern. VALUES: Faith, family, hospitality. STYLE: Respectful, relationship-first. AVOID: Alcohol, pork, immodest images, religious imagery.'
});

MERGE (cr:CulturalRealm {
  key: 'indic',
  name: 'Indic',
  wikidata_id: 'Q176770',
  core_values: 'dharma, family hierarchy, spiritual diversity, education',
  communication_style: 'high-context, hierarchical, indirect',
  power_distance: 'high',
  content_taboos: 'beef (Hindu), religious disrespect, caste insensitivity',
  llm_context: 'USE: for India, Nepal, Sri Lanka, parts of Southeast Asia. TRIGGERS: indian, hindu, south-asian. VALUES: Family, education, spirituality. STYLE: Respectful of hierarchy, indirect. AVOID: Beef references (Hindu), religious insensitivity.'
});

MERGE (cr:CulturalRealm {
  key: 'east-asian',
  name: 'East Asian',
  wikidata_id: 'Q27231',
  core_values: 'harmony, hierarchy, education, face, collective good',
  communication_style: 'high-context, indirect, face-saving, formal',
  power_distance: 'high',
  content_taboos: 'loss of face, direct criticism, number 4 (death association)',
  llm_context: 'USE: for China, Japan, Korea, Taiwan, Vietnam. TRIGGERS: east-asian, confucian, cjk. VALUES: Harmony, face, education, hierarchy. STYLE: Indirect, respectful, group-oriented. AVOID: Direct criticism, number 4, causing embarrassment.'
});

MERGE (cr:CulturalRealm {
  key: 'southeast-asian',
  name: 'Southeast Asian',
  wikidata_id: 'Q11708',
  core_values: 'harmony, flexibility, family, religious tolerance',
  communication_style: 'high-context, indirect, smile-based, non-confrontational',
  power_distance: 'medium to high',
  content_taboos: 'disrespect to royalty (Thailand), head-touching, feet pointing',
  llm_context: 'USE: for Thailand, Indonesia, Philippines, Malaysia, Myanmar. TRIGGERS: southeast-asian, asean. VALUES: Harmony, flexibility, smiles. STYLE: Non-confrontational, polite. AVOID: Confrontation, disrespect to elders/royalty.'
});

MERGE (cr:CulturalRealm {
  key: 'meso-african',
  name: 'Meso-African',
  wikidata_id: 'Q27407',
  core_values: 'community, oral tradition, extended family, respect for elders',
  communication_style: 'high-context, community-focused, storytelling',
  power_distance: 'varies by culture',
  content_taboos: 'disrespect to elders, ignoring community values',
  llm_context: 'USE: for Sub-Saharan Africa. TRIGGERS: african, subsaharan. VALUES: Ubuntu (community), oral tradition, elders. STYLE: Community-focused, relationship-building. AVOID: Individualistic framing, poverty stereotypes.'
});

// -----------------------------------------------------------------------------
// CULTURAL SUB-REALMS
// -----------------------------------------------------------------------------

// Occidental sub-realms
MERGE (csr:CulturalSubRealm { key: 'anglo-american', name: 'Anglo-American', parent_realm: 'occidental', regions: ['northern-america', 'australia-new-zealand'], llm_context: 'US, UK, Canada, Australia, NZ. English. Very low-context. Direct. Informal. Consumer culture.' });
MERGE (csr:CulturalSubRealm { key: 'west-european', name: 'Western European', parent_realm: 'occidental', regions: ['western-europe'], llm_context: 'Germany, France, Netherlands, Belgium. Mix of Germanic and Romance. Quality-focused. Environmental awareness.' });
MERGE (csr:CulturalSubRealm { key: 'nordic', name: 'Nordic', parent_realm: 'occidental', regions: ['northern-europe'], llm_context: 'Scandinavia, Finland, Iceland. Egalitarian. Design-conscious. Sustainability. Premium markets.' });
MERGE (csr:CulturalSubRealm { key: 'mediterranean', name: 'Mediterranean', parent_realm: 'occidental', regions: ['southern-europe'], llm_context: 'Spain, Italy, Portugal, Greece. Relationship-focused. Warm communication. Family values.' });
MERGE (csr:CulturalSubRealm { key: 'eastern-european', name: 'Eastern European', parent_realm: 'occidental', regions: ['eastern-europe'], llm_context: 'Poland, Czech, Hungary, Romania, Balkans. Post-transition. Mix of Catholic and Orthodox.' });
MERGE (csr:CulturalSubRealm { key: 'latin-american', name: 'Latin American', parent_realm: 'occidental', regions: ['central-america', 'south-america', 'caribbean'], llm_context: 'Spanish/Portuguese Americas. Warm, relationship-focused. Family-centered. Growing middle class.' });
MERGE (csr:CulturalSubRealm { key: 'slavic-orthodox', name: 'Slavic Orthodox', parent_realm: 'occidental', regions: ['eastern-europe'], llm_context: 'Russia, Ukraine, Belarus, Serbia, Bulgaria. Orthodox heritage. Cyrillic. Collectivist tradition.' });

// Islamic sub-realms
MERGE (csr:CulturalSubRealm { key: 'islamic-arab', name: 'Islamic Arab', parent_realm: 'islamic', regions: ['western-asia', 'northern-africa'], llm_context: 'Arab world. Arabic language. Gulf + Levant + Maghreb variations. RTL. Conservative in Gulf, moderate in Levant.' });
MERGE (csr:CulturalSubRealm { key: 'islamic-persian', name: 'Islamic Persian', parent_realm: 'islamic', regions: ['western-asia', 'central-asia'], llm_context: 'Iran, Afghanistan, Tajikistan. Persian heritage. Poetry tradition. Distinct from Arab culture.' });
MERGE (csr:CulturalSubRealm { key: 'islamic-turkic', name: 'Islamic Turkic', parent_realm: 'islamic', regions: ['western-asia', 'central-asia'], llm_context: 'Turkey, Azerbaijan, Central Asia. Turkic languages. Turkey more secular. Ottoman heritage.' });
MERGE (csr:CulturalSubRealm { key: 'south-asian-islamic', name: 'South Asian Islamic', parent_realm: 'islamic', regions: ['southern-asia'], llm_context: 'Pakistan, Bangladesh, Indian Muslims. Indo-Islamic culture. Urdu/Bengali. South Asian context.' });
MERGE (csr:CulturalSubRealm { key: 'maritime-islamic', name: 'Maritime Islamic', parent_realm: 'islamic', regions: ['south-eastern-asia'], llm_context: 'Malaysia, Indonesia, Brunei. Malay culture. Moderate Islam. Halal important but less conservative.' });

// Indic sub-realms
MERGE (csr:CulturalSubRealm { key: 'north-indian', name: 'North Indian', parent_realm: 'indic', regions: ['southern-asia'], llm_context: 'Hindi belt. Devanagari script. Hindu majority. Bollywood influence. Cricket culture.' });
MERGE (csr:CulturalSubRealm { key: 'south-indian', name: 'South Indian', parent_realm: 'indic', regions: ['southern-asia'], llm_context: 'Dravidian states. Tamil, Telugu, Kannada, Malayalam. Strong regional identity. IT hubs.' });
MERGE (csr:CulturalSubRealm { key: 'himalayan-buddhist', name: 'Himalayan Buddhist', parent_realm: 'indic', regions: ['southern-asia'], llm_context: 'Nepal, Bhutan, Tibetan diaspora. Buddhist. Mountain cultures. Traditional values.' });

// East Asian sub-realms
MERGE (csr:CulturalSubRealm { key: 'sinosphere', name: 'Sinosphere', parent_realm: 'east-asian', regions: ['eastern-asia'], llm_context: 'China, Taiwan, Singapore Chinese. Mandarin. CJK characters. Confucian. Face culture.' });
MERGE (csr:CulturalSubRealm { key: 'japanese', name: 'Japanese', parent_realm: 'east-asian', regions: ['eastern-asia'], llm_context: 'Japan. Unique. Extreme politeness. Attention to detail. Pop culture global influence.' });
MERGE (csr:CulturalSubRealm { key: 'korean', name: 'Korean', parent_realm: 'east-asian', regions: ['eastern-asia'], llm_context: 'Korea. Hangul. Confucian + dynamic. K-wave global influence. Tech-forward.' });
MERGE (csr:CulturalSubRealm { key: 'vietnamese-sinosphere', name: 'Vietnamese Sinosphere', parent_realm: 'east-asian', regions: ['south-eastern-asia'], llm_context: 'Vietnam. Sinosphere culture despite Austroasiatic language. Confucian values. Latin script.' });

// Southeast Asian sub-realms
MERGE (csr:CulturalSubRealm { key: 'theravada-buddhist', name: 'Theravada Buddhist', parent_realm: 'southeast-asian', regions: ['south-eastern-asia'], llm_context: 'Thailand, Myanmar, Cambodia, Laos. Buddhist. Monarchy respect (Thailand). Non-confrontational.' });
MERGE (csr:CulturalSubRealm { key: 'philippine-syncretic', name: 'Philippine Syncretic', parent_realm: 'southeast-asian', regions: ['south-eastern-asia'], llm_context: 'Philippines. Catholic + Malay + American mix. English widely spoken. Unique in region.' });

// Meso-African sub-realms
MERGE (csr:CulturalSubRealm { key: 'west-african', name: 'West African', parent_realm: 'meso-african', regions: ['western-africa'], llm_context: 'Nigeria, Ghana, Senegal. Diverse. English/French. Strong oral traditions. Music influence.' });
MERGE (csr:CulturalSubRealm { key: 'east-african', name: 'East African', parent_realm: 'meso-african', regions: ['eastern-africa'], llm_context: 'Kenya, Tanzania, Uganda. Swahili. English. Safari tourism. Mix of cultures.' });
MERGE (csr:CulturalSubRealm { key: 'southern-african', name: 'Southern African', parent_realm: 'meso-african', regions: ['southern-africa'], llm_context: 'South Africa, Zimbabwe, Botswana. Most developed in region. English/Afrikaans. Mining heritage.' });

// -----------------------------------------------------------------------------
// POPULATION CLUSTERS (for AI image generation diversity)
// -----------------------------------------------------------------------------

MERGE (pc:PopulationCluster {
  key: 'west-eurasian',
  name: 'West Eurasian',
  regions: ['Europe', 'Middle East', 'North Africa', 'South Asia'],
  visual_traits: 'Light to olive skin tones, varied eye colors (blue, green, brown, hazel), straight to wavy hair textures, narrow to medium nose bridge',
  llm_context: 'USE: for European, Middle Eastern, North African, South Asian phenotypes. DIVERSE: Nordic to Mediterranean to South Asian range.'
});

MERGE (pc:PopulationCluster {
  key: 'east-asian',
  name: 'East Asian',
  regions: ['East Asia', 'Central Asia', 'Arctic'],
  visual_traits: 'Warm ivory to golden skin tones, straight black hair, dark brown eyes, epicanthic fold, high flat cheekbones',
  llm_context: 'USE: for East Asian, Central Asian phenotypes. INCLUDES: Han Chinese, Japanese, Korean, Mongolian appearances.'
});

MERGE (pc:PopulationCluster {
  key: 'southeast-asian',
  name: 'Southeast Asian',
  regions: ['Southeast Asia', 'Pacific Islands'],
  visual_traits: 'Warm golden to brown skin tones, straight to wavy black hair, dark brown eyes, varied nose shapes, fuller lips possible',
  llm_context: 'USE: for Southeast Asian, Filipino, Indonesian, Thai, Vietnamese phenotypes. DIVERSE within region.'
});

MERGE (pc:PopulationCluster {
  key: 'south-asian',
  name: 'South Asian',
  regions: ['South Asia'],
  visual_traits: 'Warm brown skin ranging light to dark, straight to wavy black hair, dark brown eyes, defined nose bridge',
  llm_context: 'USE: for Indian, Pakistani, Bangladeshi, Sri Lankan phenotypes. DIVERSE: North to South India range.'
});

MERGE (pc:PopulationCluster {
  key: 'sub-saharan',
  name: 'Sub-Saharan African',
  regions: ['Sub-Saharan Africa'],
  visual_traits: 'Rich dark brown to deep black skin tones, tightly coiled to kinky hair textures, dark brown eyes, broad nose, full lips',
  llm_context: 'USE: for African phenotypes. MOST DIVERSE genetically. West, East, Southern variations.'
});

MERGE (pc:PopulationCluster {
  key: 'native-american',
  name: 'Native American',
  regions: ['North America', 'Central America', 'South America'],
  visual_traits: 'Warm bronze to copper skin tones, straight jet-black hair, dark brown eyes, high prominent cheekbones, varied nose shapes',
  llm_context: 'USE: for Indigenous Americas phenotypes. DIVERSE: Inuit to Mesoamerican to Andean variations.'
});

MERGE (pc:PopulationCluster {
  key: 'oceanian',
  name: 'Oceanian',
  regions: ['Australia', 'Melanesia', 'Polynesia', 'Micronesia'],
  visual_traits: 'Deep brown to dark skin, wavy to curly dark hair, dark brown eyes, broad nose, varied builds',
  llm_context: 'USE: for Pacific Islander, Aboriginal Australian phenotypes. Melanesian, Polynesian, Micronesian variations.'
});

// -----------------------------------------------------------------------------
// POPULATION SUB-CLUSTERS (more specific for image generation)
// -----------------------------------------------------------------------------

// West Eurasian sub-clusters
MERGE (psc:PopulationSubCluster { key: 'nordic', name: 'Nordic', parent_cluster: 'west-eurasian', visual_traits: 'Fair porcelain skin, light blonde to strawberry blonde hair, blue or grey eyes, tall stature, angular features', regions: ['Scandinavia', 'Iceland', 'Baltic'] });
MERGE (psc:PopulationSubCluster { key: 'mediterranean', name: 'Mediterranean', parent_cluster: 'west-eurasian', visual_traits: 'Warm olive skin, dark brown to black wavy hair, brown or hazel eyes, expressive dark eyebrows', regions: ['Southern Europe', 'Mediterranean'] });
MERGE (psc:PopulationSubCluster { key: 'slavic', name: 'Slavic', parent_cluster: 'west-eurasian', visual_traits: 'Fair to light skin, light brown to dark blonde hair, blue green or grey eyes, high cheekbones', regions: ['Eastern Europe', 'Russia'] });
MERGE (psc:PopulationSubCluster { key: 'celtic', name: 'Celtic', parent_cluster: 'west-eurasian', visual_traits: 'Very fair freckled skin, red to auburn hair, green or blue eyes, soft rounded features', regions: ['Ireland', 'Scotland', 'Wales'] });
MERGE (psc:PopulationSubCluster { key: 'middle-eastern', name: 'Middle Eastern', parent_cluster: 'west-eurasian', visual_traits: 'Warm tan to olive skin, dark brown to black wavy hair, dark brown eyes, thick dark eyebrows, prominent nose', regions: ['Middle East', 'Levant'] });
MERGE (psc:PopulationSubCluster { key: 'north-african', name: 'North African', parent_cluster: 'west-eurasian', visual_traits: 'Light olive to tan skin, dark wavy to curly hair, dark brown eyes, defined cheekbones', regions: ['Maghreb', 'Egypt'] });

// East Asian sub-clusters
MERGE (psc:PopulationSubCluster { key: 'han-chinese', name: 'Han Chinese', parent_cluster: 'east-asian', visual_traits: 'Warm ivory to light golden skin, straight fine black hair, almond-shaped dark brown eyes with epicanthic fold, round face', regions: ['China', 'Taiwan', 'Singapore'] });
MERGE (psc:PopulationSubCluster { key: 'japanese', name: 'Japanese', parent_cluster: 'east-asian', visual_traits: 'Fair ivory skin, straight fine black hair, narrow almond eyes, delicate features, small nose', regions: ['Japan'] });
MERGE (psc:PopulationSubCluster { key: 'korean', name: 'Korean', parent_cluster: 'east-asian', visual_traits: 'Fair to light golden skin, straight silky black hair, monolid or subtle double eyelid, V-shaped jaw', regions: ['Korea'] });
MERGE (psc:PopulationSubCluster { key: 'central-asian', name: 'Central Asian', parent_cluster: 'east-asian', visual_traits: 'Tan to golden skin, straight dark hair, almond eyes with varied epicanthic fold, high cheekbones, mixed features', regions: ['Kazakhstan', 'Mongolia', 'Tibet'] });

// Southeast Asian sub-clusters
MERGE (psc:PopulationSubCluster { key: 'mainland-sea', name: 'Mainland Southeast Asian', parent_cluster: 'southeast-asian', visual_traits: 'Warm golden to light brown skin, straight black hair, dark brown eyes, medium nose, medium build', regions: ['Thailand', 'Vietnam', 'Cambodia', 'Myanmar'] });
MERGE (psc:PopulationSubCluster { key: 'maritime-sea', name: 'Maritime Southeast Asian', parent_cluster: 'southeast-asian', visual_traits: 'Warm brown skin, straight to wavy black hair, dark brown eyes, broader nose, varied builds', regions: ['Indonesia', 'Malaysia', 'Philippines'] });

// South Asian sub-clusters
MERGE (psc:PopulationSubCluster { key: 'north-indian', name: 'North Indian', parent_cluster: 'south-asian', visual_traits: 'Light to medium brown skin, straight to wavy black hair, dark brown eyes, prominent nose, varied features', regions: ['North India', 'Pakistan'] });
MERGE (psc:PopulationSubCluster { key: 'south-indian', name: 'South Indian', parent_cluster: 'south-asian', visual_traits: 'Medium to dark brown skin, wavy to curly black hair, dark brown eyes, broader nose, strong features', regions: ['South India', 'Sri Lanka'] });

// Sub-Saharan sub-clusters
MERGE (psc:PopulationSubCluster { key: 'west-african', name: 'West African', parent_cluster: 'sub-saharan', visual_traits: 'Deep rich dark skin, tightly coiled black hair, dark brown eyes, broad nose, full sculpted lips', regions: ['Nigeria', 'Ghana', 'Senegal'] });
MERGE (psc:PopulationSubCluster { key: 'east-african', name: 'East African', parent_cluster: 'sub-saharan', visual_traits: 'Rich dark brown skin, tightly curled black hair, dark almond eyes, narrow refined nose, high cheekbones, elongated features', regions: ['Ethiopia', 'Kenya', 'Somalia'] });
MERGE (psc:PopulationSubCluster { key: 'southern-african-bantu', name: 'Southern African Bantu', parent_cluster: 'sub-saharan', visual_traits: 'Dark brown to black skin, coiled black hair, dark brown eyes, broad nose, full lips, rounded features', regions: ['South Africa', 'Zimbabwe'] });

// Native American sub-clusters
MERGE (psc:PopulationSubCluster { key: 'north-american-indigenous', name: 'North American Indigenous', parent_cluster: 'native-american', visual_traits: 'Warm bronze to reddish-brown skin, straight coarse black hair, dark brown eyes, high prominent cheekbones, aquiline nose', regions: ['United States', 'Canada'] });
MERGE (psc:PopulationSubCluster { key: 'mesoamerican', name: 'Mesoamerican', parent_cluster: 'native-american', visual_traits: 'Warm brown to bronze skin, straight thick black hair, dark brown eyes, high cheekbones, prominent nose, rounded face', regions: ['Mexico', 'Guatemala'] });
MERGE (psc:PopulationSubCluster { key: 'andean', name: 'Andean', parent_cluster: 'native-american', visual_traits: 'Copper to bronze skin, straight jet-black hair, dark brown eyes, high cheekbones, aquiline nose, compact build', regions: ['Peru', 'Bolivia', 'Ecuador'] });

// Oceanian sub-clusters
MERGE (psc:PopulationSubCluster { key: 'aboriginal-australian', name: 'Aboriginal Australian', parent_cluster: 'oceanian', visual_traits: 'Deep dark brown skin, wavy to curly dark hair, dark brown deep-set eyes, broad nose, pronounced brow ridge', regions: ['Australia'] });
MERGE (psc:PopulationSubCluster { key: 'melanesian', name: 'Melanesian', parent_cluster: 'oceanian', visual_traits: 'Very dark skin, naturally blonde to dark curly hair, dark brown eyes, broad nose, full lips, strong features', regions: ['Papua New Guinea', 'Fiji', 'Solomon Islands'] });
MERGE (psc:PopulationSubCluster { key: 'polynesian', name: 'Polynesian', parent_cluster: 'oceanian', visual_traits: 'Warm brown to tan skin, wavy dark hair, dark brown eyes, broad nose, full lips, strong muscular build', regions: ['Hawaii', 'Samoa', 'Tonga', 'New Zealand'] });

// -----------------------------------------------------------------------------
// CREATE HIERARCHY RELATIONSHIPS
// -----------------------------------------------------------------------------

// Continent -> GeoRegion
MATCH (c:Continent {key: 'africa'}), (r:GeoRegion) WHERE r.parent_continent = 'africa' MERGE (r)-[:IN_CONTINENT]->(c);
MATCH (c:Continent {key: 'americas'}), (r:GeoRegion) WHERE r.parent_continent = 'americas' MERGE (r)-[:IN_CONTINENT]->(c);
MATCH (c:Continent {key: 'asia'}), (r:GeoRegion) WHERE r.parent_continent = 'asia' MERGE (r)-[:IN_CONTINENT]->(c);
MATCH (c:Continent {key: 'europe'}), (r:GeoRegion) WHERE r.parent_continent = 'europe' MERGE (r)-[:IN_CONTINENT]->(c);
MATCH (c:Continent {key: 'oceania'}), (r:GeoRegion) WHERE r.parent_continent = 'oceania' MERGE (r)-[:IN_CONTINENT]->(c);

// GeoSubRegion -> GeoRegion
MATCH (sr:GeoSubRegion), (r:GeoRegion) WHERE sr.parent_region = r.key MERGE (sr)-[:IN_REGION]->(r);

// LanguageFamily -> LanguageBranch
MATCH (f:LanguageFamily), (b:LanguageBranch) WHERE b.parent_family = f.key MERGE (b)-[:BRANCH_OF]->(f);

// CulturalRealm -> CulturalSubRealm
MATCH (cr:CulturalRealm), (csr:CulturalSubRealm) WHERE csr.parent_realm = cr.key MERGE (csr)-[:PART_OF_REALM]->(cr);

// PopulationCluster -> PopulationSubCluster
MATCH (pc:PopulationCluster), (psc:PopulationSubCluster) WHERE psc.parent_cluster = pc.key MERGE (psc)-[:CLUSTER_OF]->(pc);

// -----------------------------------------------------------------------------
// CONNECT TO CLASS SCHEMA-NODES (OF_CLASS relationships)
// -----------------------------------------------------------------------------

MATCH (n:Continent), (c:Schema:Class {label: 'Continent'}) MERGE (n)-[:OF_CLASS]->(c);
MATCH (n:GeoRegion), (c:Schema:Class {label: 'GeoRegion'}) MERGE (n)-[:OF_CLASS]->(c);
MATCH (n:GeoSubRegion), (c:Schema:Class {label: 'GeoSubRegion'}) MERGE (n)-[:OF_CLASS]->(c);
MATCH (n:IncomeGroup), (c:Schema:Class {label: 'IncomeGroup'}) MERGE (n)-[:OF_CLASS]->(c);
MATCH (n:LanguageFamily), (c:Schema:Class {label: 'LanguageFamily'}) MERGE (n)-[:OF_CLASS]->(c);
MATCH (n:LanguageBranch), (c:Schema:Class {label: 'LanguageBranch'}) MERGE (n)-[:OF_CLASS]->(c);
MATCH (n:CulturalRealm), (c:Schema:Class {label: 'CulturalRealm'}) MERGE (n)-[:OF_CLASS]->(c);
MATCH (n:CulturalSubRealm), (c:Schema:Class {label: 'CulturalSubRealm'}) MERGE (n)-[:OF_CLASS]->(c);
MATCH (n:PopulationCluster), (c:Schema:Class {label: 'PopulationCluster'}) MERGE (n)-[:OF_CLASS]->(c);
MATCH (n:PopulationSubCluster), (c:Schema:Class {label: 'PopulationSubCluster'}) MERGE (n)-[:OF_CLASS]->(c);
