// =============================================================================
// Seed: BlockType head-seo-meta
// NovaNet v0.13.1
// =============================================================================
// Creates the head-seo-meta BlockType instance.
// This BlockType MUST be the first block (order=0) of every page.
// Contains: slug, meta_title, meta_description
//
// CRITICAL: The slug is COPIED from SEOKeyword.slug_form, NOT generated.
// SEOKeyword.slug_form already has correct diacritics per locale rules.
// =============================================================================

// Create the BlockType instance for head-seo-meta
MERGE (bt:BlockType {key: 'head-seo-meta'})
ON CREATE SET
  bt.display_name = 'SEO Metadata',
  bt.description = 'SEO metadata block - MUST be first block (order=0) of every page. Contains URL slug, meta title, meta description.',
  bt.category = 'header',
  bt.structure = 'schemas/head-seo-meta.json',
  bt.created_at = datetime(),
  bt.updated_at = datetime(),
  // JSON Schema for validation
  bt.schema = '{
    "type": "object",
    "properties": {
      "slug": {
        "type": "string",
        "pattern": "^[\\\\p{Ll}\\\\p{N}\\\\-]+$",
        "description": "URL-safe localized slug (UTF-8 allowed). COPIED from SEOKeyword.slug_form."
      },
      "meta_title": {
        "type": "string",
        "maxLength": 60,
        "description": "Page title for search engines (<title> tag)"
      },
      "meta_description": {
        "type": "string",
        "maxLength": 160,
        "description": "Page description for search engines (<meta name=\"description\">)"
      }
    },
    "required": ["slug", "meta_title", "meta_description"]
  }',
  bt.llm_context = 'USE: when generating SEO metadata for a page.
TRIGGERS: slug, URL, meta title, meta description, SEO, head.
NOT: for page content (use other block types), for keywords (use TARGETS).
RELATES: BlockNative (output), Slugification (rules via SLUGIFIED_BY), SEOKeyword (source via DERIVED_SLUG_FROM).

CRITICAL: The slug is COPIED from SEOKeyword.slug_form, NOT generated by LLM.
SEOKeyword.slug_form already contains correct diacritics per locale rules.
Example: es-MX with latin_preserve → slug = "código-qr" (NOT "codigo-qr")'
ON MATCH SET
  bt.updated_at = datetime()
RETURN 'Created BlockType: head-seo-meta' AS status, bt.key AS key;
