// =============================================================================
// 49-blocknative-head-seo-meta.cypher — BlockNative:head-seo-meta nodes
// v0.13.1 - ADR-030 (Slug Ownership), ADR-032 (URL Slugification)
// =============================================================================
//
// MUST RUN BEFORE 50-page-native.cypher (which creates ASSEMBLES arcs)
//
// This file creates:
//   1. BlockNative:head-seo-meta nodes (the first block of every page)
//   2. SLUGIFIED_BY arcs (BlockNative -> Slugification) for validation
//   3. DERIVED_SLUG_FROM arcs (BlockNative -> SEOKeyword) for provenance
//   4. FOR_LOCALE arcs (BlockNative -> Locale)
//   5. OF_TYPE arcs (BlockNative -> BlockType)
//
// Two complementary arcs for slug management:
//   - DERIVED_SLUG_FROM = PROVENANCE (BlockNative -> SEOKeyword)
//   - SLUGIFIED_BY = VALIDATION (BlockNative -> Slugification)
//
// CRITICAL: The slug is COPIED from SEOKeyword.slug_form, NOT generated by LLM.
// SEOKeyword.slug_form already contains correct diacritics per locale rules.
// =============================================================================

// =============================================================================
// PART 1: Create head-seo-meta BlockNative nodes for qr-code page
// These are the first block (order=0) of every page, containing slug + meta
// =============================================================================

// en-US: qr-code page
MERGE (bn:BlockNative {key: 'block:qr-code:head-seo-meta:1@en-US'})
ON CREATE SET
  bn.block_key = 'qr-code:head-seo-meta:1',
  bn.locale_key = 'en-US',
  bn.display_name = 'QR Code Generator SEO Meta (en-US)',
  bn.description = 'SEO metadata for qr-code page - en-US',
  bn.block_type = 'head-seo-meta',
  bn.content = '{"slug": "qr-code-generator", "meta_title": "QR Code Generator - Create Custom QR Codes Free", "meta_description": "Generate custom QR codes instantly. Free QR code generator for URLs, WiFi, contacts, and more."}',
  bn.status = 'published',
  bn.created_at = datetime(),
  bn.updated_at = datetime()
ON MATCH SET
  bn.updated_at = datetime();

// fr-FR: qr-code page
MERGE (bn:BlockNative {key: 'block:qr-code:head-seo-meta:1@fr-FR'})
ON CREATE SET
  bn.block_key = 'qr-code:head-seo-meta:1',
  bn.locale_key = 'fr-FR',
  bn.display_name = 'Générateur QR Code SEO Meta (fr-FR)',
  bn.description = 'SEO metadata for qr-code page - fr-FR',
  bn.block_type = 'head-seo-meta',
  bn.content = '{"slug": "générateur-qr-code", "meta_title": "Générateur QR Code - Créez vos QR Codes Gratuit", "meta_description": "Générez des QR codes personnalisés instantanément. Créateur de QR code gratuit pour URL, WiFi, contacts et plus."}',
  bn.status = 'published',
  bn.created_at = datetime(),
  bn.updated_at = datetime()
ON MATCH SET
  bn.updated_at = datetime();

// es-MX: qr-code page (CRITICAL: latin_preserve with diacritics)
MERGE (bn:BlockNative {key: 'block:qr-code:head-seo-meta:1@es-MX'})
ON CREATE SET
  bn.block_key = 'qr-code:head-seo-meta:1',
  bn.locale_key = 'es-MX',
  bn.display_name = 'Código QR SEO Meta (es-MX)',
  bn.description = 'SEO metadata for qr-code page - es-MX',
  bn.block_type = 'head-seo-meta',
  // CRITICAL: "código-qr" with accent, NOT "codigo-qr"
  // The slug is COPIED from SEOKeyword.slug_form which has correct diacritics
  bn.content = '{"slug": "código-qr", "meta_title": "Generador de Código QR - Crea Códigos QR Gratis", "meta_description": "Genera códigos QR personalizados al instante. Generador de código QR gratuito para URLs, WiFi, contactos y más."}',
  bn.status = 'published',
  bn.created_at = datetime(),
  bn.updated_at = datetime()
ON MATCH SET
  bn.updated_at = datetime();

// ja-JP: qr-code page (native_script with Japanese characters)
MERGE (bn:BlockNative {key: 'block:qr-code:head-seo-meta:1@ja-JP'})
ON CREATE SET
  bn.block_key = 'qr-code:head-seo-meta:1',
  bn.locale_key = 'ja-JP',
  bn.display_name = 'QRコード作成 SEO Meta (ja-JP)',
  bn.description = 'SEO metadata for qr-code page - ja-JP',
  bn.block_type = 'head-seo-meta',
  bn.content = '{"slug": "qrコード作成", "meta_title": "QRコード作成 - 無料でカスタムQRコードを生成", "meta_description": "カスタムQRコードを瞬時に生成。URL、WiFi、連絡先など用の無料QRコードジェネレーター。"}',
  bn.status = 'published',
  bn.created_at = datetime(),
  bn.updated_at = datetime()
ON MATCH SET
  bn.updated_at = datetime();

// de-DE: qr-code page (latin_transform: ü→ue, etc.)
MERGE (bn:BlockNative {key: 'block:qr-code:head-seo-meta:1@de-DE'})
ON CREATE SET
  bn.block_key = 'qr-code:head-seo-meta:1',
  bn.locale_key = 'de-DE',
  bn.display_name = 'QR-Code Generator SEO Meta (de-DE)',
  bn.description = 'SEO metadata for qr-code page - de-DE',
  bn.block_type = 'head-seo-meta',
  // German uses latin_transform: ü→ue, ö→oe, ä→ae, ß→ss
  bn.content = '{"slug": "qr-code-generator", "meta_title": "QR-Code Generator - Kostenlos QR-Codes erstellen", "meta_description": "Erstellen Sie individuelle QR-Codes sofort. Kostenloser QR-Code-Generator für URLs, WLAN, Kontakte und mehr."}',
  bn.status = 'published',
  bn.created_at = datetime(),
  bn.updated_at = datetime()
ON MATCH SET
  bn.updated_at = datetime();

// =============================================================================
// PART 2: Link BlockNative to Locale via FOR_LOCALE
// =============================================================================

MATCH (bn:BlockNative {key: 'block:qr-code:head-seo-meta:1@en-US'})
MATCH (l:Locale {key: 'en-US'})
MERGE (bn)-[:FOR_LOCALE]->(l);

MATCH (bn:BlockNative {key: 'block:qr-code:head-seo-meta:1@fr-FR'})
MATCH (l:Locale {key: 'fr-FR'})
MERGE (bn)-[:FOR_LOCALE]->(l);

MATCH (bn:BlockNative {key: 'block:qr-code:head-seo-meta:1@es-MX'})
MATCH (l:Locale {key: 'es-MX'})
MERGE (bn)-[:FOR_LOCALE]->(l);

MATCH (bn:BlockNative {key: 'block:qr-code:head-seo-meta:1@ja-JP'})
MATCH (l:Locale {key: 'ja-JP'})
MERGE (bn)-[:FOR_LOCALE]->(l);

MATCH (bn:BlockNative {key: 'block:qr-code:head-seo-meta:1@de-DE'})
MATCH (l:Locale {key: 'de-DE'})
MERGE (bn)-[:FOR_LOCALE]->(l);

// =============================================================================
// PART 3: Create SLUGIFIED_BY arcs (BlockNative -> Slugification)
// =============================================================================

// en-US: validated with latin_strip (removes diacritics)
MATCH (bn:BlockNative {key: 'block:qr-code:head-seo-meta:1@en-US'})
MATCH (s:Slugification {key: 'en-US'})
MERGE (bn)-[r:SLUGIFIED_BY]->(s)
ON CREATE SET
  r.validated = true,
  r.applied_rule = 'latin_strip',
  r.validation_timestamp = datetime(),
  r.validation_errors = '[]'
ON MATCH SET
  r.validation_timestamp = datetime();

// fr-FR: validated with latin_preserve (keeps diacritics like é, è, ê)
MATCH (bn:BlockNative {key: 'block:qr-code:head-seo-meta:1@fr-FR'})
MATCH (s:Slugification {key: 'fr-FR'})
MERGE (bn)-[r:SLUGIFIED_BY]->(s)
ON CREATE SET
  r.validated = true,
  r.applied_rule = 'latin_preserve',
  r.validation_timestamp = datetime(),
  r.validation_errors = '[]'
ON MATCH SET
  r.validation_timestamp = datetime();

// es-MX: validated with latin_preserve (MUST preserve ó in código)
// CRITICAL VALIDATION: "código-qr" is VALID, "codigo-qr" would be INVALID
MATCH (bn:BlockNative {key: 'block:qr-code:head-seo-meta:1@es-MX'})
MATCH (s:Slugification {key: 'es-MX'})
MERGE (bn)-[r:SLUGIFIED_BY]->(s)
ON CREATE SET
  r.validated = true,
  r.applied_rule = 'latin_preserve',
  r.validation_timestamp = datetime(),
  r.validation_errors = '[]'
ON MATCH SET
  r.validation_timestamp = datetime();

// ja-JP: validated with native_script (preserves Japanese characters)
MATCH (bn:BlockNative {key: 'block:qr-code:head-seo-meta:1@ja-JP'})
MATCH (s:Slugification {key: 'ja-JP'})
MERGE (bn)-[r:SLUGIFIED_BY]->(s)
ON CREATE SET
  r.validated = true,
  r.applied_rule = 'native_script',
  r.validation_timestamp = datetime(),
  r.validation_errors = '[]'
ON MATCH SET
  r.validation_timestamp = datetime();

// de-DE: validated with latin_transform (transforms umlauts: ü→ue)
MATCH (bn:BlockNative {key: 'block:qr-code:head-seo-meta:1@de-DE'})
MATCH (s:Slugification {key: 'de-DE'})
MERGE (bn)-[r:SLUGIFIED_BY]->(s)
ON CREATE SET
  r.validated = true,
  r.applied_rule = 'latin_transform',
  r.validation_timestamp = datetime(),
  r.validation_errors = '[]'
ON MATCH SET
  r.validation_timestamp = datetime();

// =============================================================================
// PART 4: Create DERIVED_SLUG_FROM arcs (BlockNative -> SEOKeyword)
// PROVENANCE: Where did the slug come from?
// All locales derive from the same SEO concept (seo-qr-code-generator)
// The locale-specific slug form is computed using Slugification rules
// =============================================================================

// en-US: slug derived from SEOKeyword
MATCH (bn:BlockNative {key: 'block:qr-code:head-seo-meta:1@en-US'})
MATCH (kw:SEOKeyword {key: 'seo-qr-code-generator'})
MERGE (bn)-[r:DERIVED_SLUG_FROM]->(kw)
ON CREATE SET
  r.extracted_terms = ['qr', 'code', 'generator'],
  r.excluded_terms = [],
  r.derivation_score = 1.0,
  r.derivation_timestamp = datetime()
ON MATCH SET
  r.derivation_timestamp = datetime();

// fr-FR: slug derived from same SEOKeyword (locale slug computed via Slugification)
MATCH (bn:BlockNative {key: 'block:qr-code:head-seo-meta:1@fr-FR'})
MATCH (kw:SEOKeyword {key: 'seo-qr-code-generator'})
MERGE (bn)-[r:DERIVED_SLUG_FROM]->(kw)
ON CREATE SET
  r.extracted_terms = ['générateur', 'qr', 'code'],
  r.excluded_terms = [],
  r.derivation_score = 1.0,
  r.derivation_timestamp = datetime()
ON MATCH SET
  r.derivation_timestamp = datetime();

// es-MX: slug derived from same SEOKeyword (CRITICAL: accent on código)
MATCH (bn:BlockNative {key: 'block:qr-code:head-seo-meta:1@es-MX'})
MATCH (kw:SEOKeyword {key: 'seo-qr-code-generator'})
MERGE (bn)-[r:DERIVED_SLUG_FROM]->(kw)
ON CREATE SET
  r.extracted_terms = ['código', 'qr'],
  r.excluded_terms = [],
  r.derivation_score = 1.0,
  r.derivation_timestamp = datetime()
ON MATCH SET
  r.derivation_timestamp = datetime();

// ja-JP: slug derived from same SEOKeyword (native script)
MATCH (bn:BlockNative {key: 'block:qr-code:head-seo-meta:1@ja-JP'})
MATCH (kw:SEOKeyword {key: 'seo-qr-code-generator'})
MERGE (bn)-[r:DERIVED_SLUG_FROM]->(kw)
ON CREATE SET
  r.extracted_terms = ['qr', 'コード', '作成'],
  r.excluded_terms = [],
  r.derivation_score = 1.0,
  r.derivation_timestamp = datetime()
ON MATCH SET
  r.derivation_timestamp = datetime();

// de-DE: slug derived from same SEOKeyword (umlauts transformed)
MATCH (bn:BlockNative {key: 'block:qr-code:head-seo-meta:1@de-DE'})
MATCH (kw:SEOKeyword {key: 'seo-qr-code-generator'})
MERGE (bn)-[r:DERIVED_SLUG_FROM]->(kw)
ON CREATE SET
  r.extracted_terms = ['qr', 'code', 'generator'],
  r.excluded_terms = [],
  r.derivation_score = 1.0,
  r.derivation_timestamp = datetime()
ON MATCH SET
  r.derivation_timestamp = datetime();

// =============================================================================
// PART 5: Link head-seo-meta BlockNative to BlockType
// =============================================================================

MATCH (bn:BlockNative)
WHERE bn.block_type = 'head-seo-meta'
MATCH (bt:BlockType {key: 'head-seo-meta'})
MERGE (bn)-[:OF_TYPE]->(bt);

// =============================================================================
// Log creation
// =============================================================================

RETURN 'Created head-seo-meta BlockNative nodes with SLUGIFIED_BY, DERIVED_SLUG_FROM, and FOR_LOCALE arcs' AS status;
