// =============================================================================
// 49-blocknative-head-seo-meta.cypher — BlockNative:head-seo-meta nodes
// v0.13.1 - ADR-030 (Slug Ownership), ADR-032 (URL Slugification)
// =============================================================================
//
// MUST RUN BEFORE 50-page-native.cypher (which creates ASSEMBLES arcs)
//
// This file creates:
//   1. BlockNative:head-seo-meta nodes (the first block of every page)
//   2. SLUGIFIED_BY arcs (BlockNative -> Slugification) for validation
//   3. DERIVED_SLUG_FROM arcs (BlockNative -> SEOKeyword) for provenance
//   4. FOR_LOCALE arcs (BlockNative -> Locale)
//   5. OF_TYPE arcs (BlockNative -> BlockType)
//
// Two complementary arcs for slug management:
//   - DERIVED_SLUG_FROM = PROVENANCE (BlockNative -> SEOKeyword)
//   - SLUGIFIED_BY = VALIDATION (BlockNative -> Slugification)
//
// CRITICAL: The slug is COPIED from SEOKeyword.slug_form, NOT generated by LLM.
// SEOKeyword.slug_form already contains correct diacritics per locale rules.
//
// SLUGS — Validated with Ahrefs data (2026-02-17):
//   en-US: qr-code-generator    → 699K SV, KD93, Transactional ✓
//   fr-FR: créer-un-qr-code     → 14K SV, KD31 (was: générateur-qr-code 7.4K/KD38)
//   es-MX: crear-código-qr      → 11K SV, KD44 (was: generador-de-qr 26K but "generador" = tous les concurrents)
//                                  Strategy: différenciation sur "crear" + signal "código" dans tout le cluster
//                                  "generador de qr" = 26K/KD46 mais marché saturé
//                                  "crear codigo qr" = 11K/KD44 + aucun concurrent positionné dessus
//                                  latin_preserve rule: "código" garde l'accent (ó)
//   ja-JP: qrコード作成           → 274K SV, KD35 ✓
//   de-DE: qr-code-erstellen    → 95K SV, KD52, Transactional ✓
//
// FUTURE SPANISH LOCALES — Strategy: vary "crear" intent per region
//   es-ES (Spain):  crear-código-qr     OR  generar-código-qr (Spain says "generar" more)
//   es-AR (Argentina): crear-código-qr  (Argentina = same "crear" usage as MX)
//   es-CO (Colombia):  crear-código-qr  (same)
//   es-CL (Chile):     crear-código-qr  (same)
//   Note: all Spanish locales use latin_preserve (keep diacritics: código, gratis, etc.)
// =============================================================================

// =============================================================================
// PART 1: Create head-seo-meta BlockNative nodes for qr-code page
// These are the first block (order=0) of every page, containing slug + meta
// =============================================================================

// en-US: qr-code page
// Keyword: "qr code generator" — 699K SV, KD93, Transactional (Ahrefs 2026-02-17)
MERGE (bn:BlockNative {key: 'block:qr-code:head-seo-meta:1@en-US'})
ON CREATE SET
  bn.block_key = 'qr-code:head-seo-meta:1',
  bn.locale_key = 'en-US',
  bn.display_name = 'QR Code Generator SEO Meta (en-US)',
  bn.content = 'SEO metadata for qr-code page - en-US',
  bn.block_type = 'head-seo-meta',
  bn.content = '{"slug": "qr-code-generator", "meta_title": "QR Code Generator - Create Custom QR Codes Free", "meta_description": "Generate custom QR codes instantly. Free QR code generator for URLs, WiFi, contacts, and more."}',
  bn.status = 'published',
  bn.created_at = datetime(),
  bn.updated_at = datetime()
ON MATCH SET
  bn.content = '{"slug": "qr-code-generator", "meta_title": "QR Code Generator - Create Custom QR Codes Free", "meta_description": "Generate custom QR codes instantly. Free QR code generator for URLs, WiFi, contacts, and more."}',
  bn.updated_at = datetime();

// fr-FR: qr-code page
// Keyword: "créer un qr code" — 14K SV, KD31 (Ahrefs 2026-02-17)
// latin_preserve rule: keep accent on "créer"
MERGE (bn:BlockNative {key: 'block:qr-code:head-seo-meta:1@fr-FR'})
ON CREATE SET
  bn.block_key = 'qr-code:head-seo-meta:1',
  bn.locale_key = 'fr-FR',
  bn.display_name = 'Créer un QR Code SEO Meta (fr-FR)',
  bn.content = 'SEO metadata for qr-code page - fr-FR',
  bn.block_type = 'head-seo-meta',
  bn.content = '{"slug": "créer-un-qr-code", "meta_title": "Créer un QR Code - Générateur Gratuit en Ligne", "meta_description": "Créez un QR code personnalisé en quelques secondes. Générateur de QR code gratuit pour URL, WiFi, contacts et plus."}',
  bn.status = 'published',
  bn.created_at = datetime(),
  bn.updated_at = datetime()
ON MATCH SET
  bn.content = '{"slug": "créer-un-qr-code", "meta_title": "Créer un QR Code - Générateur Gratuit en Ligne", "meta_description": "Créez un QR code personnalisé en quelques secondes. Générateur de QR code gratuit pour URL, WiFi, contacts et plus."}',
  bn.updated_at = datetime();

// es-MX: qr-code page
// Keyword: "crear codigo qr" — 11K SV, KD44 (Ahrefs 2026-02-17)
// Strategy: "generador" = saturé (tous les concurrents). "crear" = différenciation + signal "código" dans tout le cluster
// "crear codigo qr" = 11K/KD44 vs "generador de codigo qr" = 7.4K/KD54 (meilleur volume ET KD)
// latin_preserve rule: "código" garde l'accent (ó) → crear-código-qr
// NOTE: meta_title/H1 mentionneront "generador" aussi pour capturer les deux intents
MERGE (bn:BlockNative {key: 'block:qr-code:head-seo-meta:1@es-MX'})
ON CREATE SET
  bn.block_key = 'qr-code:head-seo-meta:1',
  bn.locale_key = 'es-MX',
  bn.display_name = 'Crear Código QR SEO Meta (es-MX)',
  bn.content = 'SEO metadata for qr-code page - es-MX',
  bn.block_type = 'head-seo-meta',
  bn.content = '{"slug": "crear-código-qr", "meta_title": "Crear Código QR Gratis - Sin Registro", "meta_description": "Crea tu código QR personalizado en segundos. Gratis para URLs, WiFi, WhatsApp, contactos y más."}',
  bn.status = 'published',
  bn.created_at = datetime(),
  bn.updated_at = datetime()
ON MATCH SET
  bn.content = '{"slug": "crear-código-qr", "meta_title": "Crear Código QR Gratis - Sin Registro", "meta_description": "Crea tu código QR personalizado en segundos. Gratis para URLs, WiFi, WhatsApp, contactos y más."}',
  bn.updated_at = datetime();

// ja-JP: qr-code page
// Keyword: "qrコード作成" — 274K SV, KD35 (Ahrefs 2026-02-17)
// native_script rule: Japanese characters allowed in slug (atomic opportunity)
MERGE (bn:BlockNative {key: 'block:qr-code:head-seo-meta:1@ja-JP'})
ON CREATE SET
  bn.block_key = 'qr-code:head-seo-meta:1',
  bn.locale_key = 'ja-JP',
  bn.display_name = 'QRコード作成 SEO Meta (ja-JP)',
  bn.content = 'SEO metadata for qr-code page - ja-JP',
  bn.block_type = 'head-seo-meta',
  bn.content = '{"slug": "qrコード作成", "meta_title": "QRコード作成 - 無料でカスタムQRコードを生成", "meta_description": "カスタムQRコードを瞬時に生成。URL、WiFi、連絡先など用の無料QRコードジェネレーター。"}',
  bn.status = 'published',
  bn.created_at = datetime(),
  bn.updated_at = datetime()
ON MATCH SET
  bn.content = '{"slug": "qrコード作成", "meta_title": "QRコード作成 - 無料でカスタムQRコードを生成", "meta_description": "カスタムQRコードを瞬時に生成。URL、WiFi、連絡先など用の無料QRコードジェネレーター。"}',
  bn.updated_at = datetime();

// de-DE: qr-code page
// Keyword: "qr code erstellen" — 95K SV, KD52, Transactional (Ahrefs 2026-02-17)
// latin_transform rule: ü→ue, ö→oe, ä→ae, ß→ss (no umlauts in this slug)
MERGE (bn:BlockNative {key: 'block:qr-code:head-seo-meta:1@de-DE'})
ON CREATE SET
  bn.block_key = 'qr-code:head-seo-meta:1',
  bn.locale_key = 'de-DE',
  bn.display_name = 'QR-Code erstellen SEO Meta (de-DE)',
  bn.content = 'SEO metadata for qr-code page - de-DE',
  bn.block_type = 'head-seo-meta',
  bn.content = '{"slug": "qr-code-erstellen", "meta_title": "QR Code erstellen - Kostenloser QR-Code-Generator", "meta_description": "QR Code kostenlos erstellen in Sekunden. QR-Code-Generator für URLs, WLAN, Kontakte und mehr."}',
  bn.status = 'published',
  bn.created_at = datetime(),
  bn.updated_at = datetime()
ON MATCH SET
  bn.content = '{"slug": "qr-code-erstellen", "meta_title": "QR Code erstellen - Kostenloser QR-Code-Generator", "meta_description": "QR Code kostenlos erstellen in Sekunden. QR-Code-Generator für URLs, WLAN, Kontakte und mehr."}',
  bn.updated_at = datetime();

// =============================================================================
// PART 1.5: Link Block → BlockNative via HAS_NATIVE (ADR-029)
// =============================================================================

MATCH (b:Block {key: 'block:qr-code:head-seo-meta:1'})
MATCH (bn:BlockNative {key: 'block:qr-code:head-seo-meta:1@en-US'})
MERGE (b)-[:HAS_NATIVE {locale: 'en-US'}]->(bn);

MATCH (b:Block {key: 'block:qr-code:head-seo-meta:1'})
MATCH (bn:BlockNative {key: 'block:qr-code:head-seo-meta:1@fr-FR'})
MERGE (b)-[:HAS_NATIVE {locale: 'fr-FR'}]->(bn);

MATCH (b:Block {key: 'block:qr-code:head-seo-meta:1'})
MATCH (bn:BlockNative {key: 'block:qr-code:head-seo-meta:1@es-MX'})
MERGE (b)-[:HAS_NATIVE {locale: 'es-MX'}]->(bn);

MATCH (b:Block {key: 'block:qr-code:head-seo-meta:1'})
MATCH (bn:BlockNative {key: 'block:qr-code:head-seo-meta:1@ja-JP'})
MERGE (b)-[:HAS_NATIVE {locale: 'ja-JP'}]->(bn);

MATCH (b:Block {key: 'block:qr-code:head-seo-meta:1'})
MATCH (bn:BlockNative {key: 'block:qr-code:head-seo-meta:1@de-DE'})
MERGE (b)-[:HAS_NATIVE {locale: 'de-DE'}]->(bn);

// =============================================================================
// PART 2: Link BlockNative to Locale via FOR_LOCALE
// =============================================================================

MATCH (bn:BlockNative {key: 'block:qr-code:head-seo-meta:1@en-US'})
MATCH (l:Locale {key: 'en-US'})
MERGE (bn)-[:FOR_LOCALE]->(l);

MATCH (bn:BlockNative {key: 'block:qr-code:head-seo-meta:1@fr-FR'})
MATCH (l:Locale {key: 'fr-FR'})
MERGE (bn)-[:FOR_LOCALE]->(l);

MATCH (bn:BlockNative {key: 'block:qr-code:head-seo-meta:1@es-MX'})
MATCH (l:Locale {key: 'es-MX'})
MERGE (bn)-[:FOR_LOCALE]->(l);

MATCH (bn:BlockNative {key: 'block:qr-code:head-seo-meta:1@ja-JP'})
MATCH (l:Locale {key: 'ja-JP'})
MERGE (bn)-[:FOR_LOCALE]->(l);

MATCH (bn:BlockNative {key: 'block:qr-code:head-seo-meta:1@de-DE'})
MATCH (l:Locale {key: 'de-DE'})
MERGE (bn)-[:FOR_LOCALE]->(l);

// =============================================================================
// PART 3: Create SLUGIFIED_BY arcs (BlockNative -> Slugification)
// =============================================================================

// en-US: validated with latin_strip (removes diacritics)
MATCH (bn:BlockNative {key: 'block:qr-code:head-seo-meta:1@en-US'})
MATCH (s:Slugification {key: 'en-US'})
MERGE (bn)-[r:SLUGIFIED_BY]->(s)
ON CREATE SET
  r.validated = true,
  r.applied_rule = 'latin_strip',
  r.validation_timestamp = datetime(),
  r.validation_errors = '[]'
ON MATCH SET
  r.validation_timestamp = datetime();

// fr-FR: validated with latin_preserve (keeps diacritics like é in créer)
MATCH (bn:BlockNative {key: 'block:qr-code:head-seo-meta:1@fr-FR'})
MATCH (s:Slugification {key: 'fr-FR'})
MERGE (bn)-[r:SLUGIFIED_BY]->(s)
ON CREATE SET
  r.validated = true,
  r.applied_rule = 'latin_preserve',
  r.validation_timestamp = datetime(),
  r.validation_errors = '[]'
ON MATCH SET
  r.validation_timestamp = datetime();

// es-MX: validated with latin_preserve
// NOTE: "generador-de-qr" (no diacritics needed) — beats "generador-de-código-qr" 29:1 in volume
MATCH (bn:BlockNative {key: 'block:qr-code:head-seo-meta:1@es-MX'})
MATCH (s:Slugification {key: 'es-MX'})
MERGE (bn)-[r:SLUGIFIED_BY]->(s)
ON CREATE SET
  r.validated = true,
  r.applied_rule = 'latin_preserve',
  r.validation_timestamp = datetime(),
  r.validation_errors = '[]'
ON MATCH SET
  r.validation_timestamp = datetime();

// ja-JP: validated with native_script (preserves Japanese characters)
MATCH (bn:BlockNative {key: 'block:qr-code:head-seo-meta:1@ja-JP'})
MATCH (s:Slugification {key: 'ja-JP'})
MERGE (bn)-[r:SLUGIFIED_BY]->(s)
ON CREATE SET
  r.validated = true,
  r.applied_rule = 'native_script',
  r.validation_timestamp = datetime(),
  r.validation_errors = '[]'
ON MATCH SET
  r.validation_timestamp = datetime();

// de-DE: validated with latin_transform (transforms umlauts: ü→ue)
MATCH (bn:BlockNative {key: 'block:qr-code:head-seo-meta:1@de-DE'})
MATCH (s:Slugification {key: 'de-DE'})
MERGE (bn)-[r:SLUGIFIED_BY]->(s)
ON CREATE SET
  r.validated = true,
  r.applied_rule = 'latin_transform',
  r.validation_timestamp = datetime(),
  r.validation_errors = '[]'
ON MATCH SET
  r.validation_timestamp = datetime();

// =============================================================================
// PART 4: Create DERIVED_SLUG_FROM arcs (BlockNative -> EntityNative)
// PROVENANCE: The slug was derived from this entity's content strategy.
// The specific keyword source is marked with is_slug_source: true on TARGETS arc.
// All keyword knowledge stays on EntityNative (ADR-030 Option B).
// =============================================================================

// en-US
MATCH (bn:BlockNative {key: 'block:qr-code:head-seo-meta:1@en-US'})
MATCH (en:EntityNative {key: 'qr-code@en-US'})
MERGE (bn)-[r:DERIVED_SLUG_FROM]->(en)
ON CREATE SET
  r.derivation_score = 1.0,
  r.derivation_timestamp = datetime()
ON MATCH SET
  r.derivation_timestamp = datetime();

// fr-FR: slug source → "créer un qr code" (14K/KD31, low competition)
MATCH (bn:BlockNative {key: 'block:qr-code:head-seo-meta:1@fr-FR'})
MATCH (en:EntityNative {key: 'qr-code@fr-FR'})
MERGE (bn)-[r:DERIVED_SLUG_FROM]->(en)
ON CREATE SET
  r.derivation_score = 1.0,
  r.derivation_rationale = 'KD31 vs KD51 for générateur — low competition differentiator',
  r.derivation_timestamp = datetime()
ON MATCH SET
  r.derivation_timestamp = datetime();

// es-MX: slug source → "crear codigo qr" (11K/KD44, differentiation)
// Note: primary keyword is "código qr" (44K dominant market signal)
// Slug comes from SECONDARY keyword — no competitor positioned on "crear"
MATCH (bn:BlockNative {key: 'block:qr-code:head-seo-meta:1@es-MX'})
MATCH (en:EntityNative {key: 'qr-code@es-MX'})
MERGE (bn)-[r:DERIVED_SLUG_FROM]->(en)
ON CREATE SET
  r.derivation_score = 1.0,
  r.derivation_rationale = 'crear differentiates from all generador competitors (0 positioned)',
  r.no_repetition_applied = false,
  r.derivation_timestamp = datetime()
ON MATCH SET
  r.derivation_timestamp = datetime();

// ja-JP: slug source → "qrコード作成" (274K/KD35, native_script)
MATCH (bn:BlockNative {key: 'block:qr-code:head-seo-meta:1@ja-JP'})
MATCH (en:EntityNative {key: 'qr-code@ja-JP'})
MERGE (bn)-[r:DERIVED_SLUG_FROM]->(en)
ON CREATE SET
  r.derivation_score = 1.0,
  r.derivation_timestamp = datetime()
ON MATCH SET
  r.derivation_timestamp = datetime();

// de-DE: slug source → "qr code erstellen" (95K/KD52, Transactional)
MATCH (bn:BlockNative {key: 'block:qr-code:head-seo-meta:1@de-DE'})
MATCH (en:EntityNative {key: 'qr-code@de-DE'})
MERGE (bn)-[r:DERIVED_SLUG_FROM]->(en)
ON CREATE SET
  r.derivation_score = 1.0,
  r.derivation_timestamp = datetime()
ON MATCH SET
  r.derivation_timestamp = datetime();

// =============================================================================
// PART 5: Link head-seo-meta BlockNative to BlockType
// =============================================================================

MATCH (bn:BlockNative)
WHERE bn.block_type = 'head-seo-meta'
MATCH (bt:BlockType {key: 'head-seo-meta'})
MERGE (bn)-[:OF_TYPE]->(bt);

// =============================================================================
// Log creation
// =============================================================================

RETURN 'Created head-seo-meta BlockNative nodes with SLUGIFIED_BY, DERIVED_SLUG_FROM, and FOR_LOCALE arcs' AS status;
