//! Generate OF_KIND wiring Cypher statements (instance → Kind bridge).
//!
//! For every node type in the schema, generates a MERGE statement that links
//! all existing instances of that type to their Kind meta-node via [:OF_KIND].
//! Replaces the v8 `99-autowire-subcategories.cypher` (IN_SUBCATEGORY → OF_KIND).
//!
//! Output target: `packages/db/seed/99-autowire-kinds.cypher`

use crate::parsers::yaml_node;
use std::collections::BTreeMap;
use std::fmt::Write;
use std::path::Path;

// ─────────────────────────────────────────────────────────────────────────────
// Constants
// ─────────────────────────────────────────────────────────────────────────────

/// Fixed realm order matching the seed file convention (v10.2: 2 realms).
const REALM_ORDER: &[&str] = &["global", "project"];

// ─────────────────────────────────────────────────────────────────────────────
// Generator
// ─────────────────────────────────────────────────────────────────────────────

pub struct AutowireGenerator;

impl super::Generator for AutowireGenerator {
    fn name(&self) -> &'static str {
        "autowire"
    }

    fn generate(&self, root: &Path) -> crate::Result<String> {
        let nodes = yaml_node::load_all_nodes(root)?;
        generate_autowire(&nodes)
    }
}

fn generate_autowire(nodes: &[yaml_node::ParsedNode]) -> crate::Result<String> {
    // Group by realm → layer → sorted node names
    let mut realm_map: BTreeMap<String, BTreeMap<String, Vec<String>>> = BTreeMap::new();

    for node in nodes {
        realm_map
            .entry(node.realm.clone())
            .or_default()
            .entry(node.layer.clone())
            .or_default()
            .push(node.def.name.clone());
    }

    // Sort node names within each layer
    for layers in realm_map.values_mut() {
        for names in layers.values_mut() {
            names.sort();
        }
    }

    let mut out = String::with_capacity(8 * 1024);

    // Header
    writeln!(
        out,
        "// Auto-wire OF_KIND relationships (v9 instance → Kind bridge)"
    )
    .unwrap();
    writeln!(
        out,
        "// ═══════════════════════════════════════════════════════════════════════════════"
    )
    .unwrap();
    writeln!(
        out,
        "// Runs AFTER all other seeds to connect instance nodes to their Kind meta-nodes."
    )
    .unwrap();
    writeln!(
        out,
        "// Idempotent: Uses MERGE to allow repeated execution."
    )
    .unwrap();
    writeln!(out, "//").unwrap();
    writeln!(out, "// AUTO-GENERATED by novanet v9.0.0 — DO NOT EDIT").unwrap();
    writeln!(out, "// Total: {count} node types", count = nodes.len()).unwrap();
    writeln!(
        out,
        "// ═══════════════════════════════════════════════════════════════════════════════"
    )
    .unwrap();
    writeln!(out).unwrap();

    for &realm_key in REALM_ORDER {
        let Some(layers_map) = realm_map.get(realm_key) else {
            return Err(crate::NovaNetError::Validation(format!(
                "realm '{realm_key}' has no nodes — expected nodes under models/node-kinds/{realm_key}/"
            )));
        };

        // Realm header
        writeln!(
            out,
            "// ─────────────────────────────────────────────────────────────────────────────"
        )
        .unwrap();
        writeln!(out, "// {} REALM", realm_key.to_uppercase()).unwrap();
        writeln!(
            out,
            "// ─────────────────────────────────────────────────────────────────────────────"
        )
        .unwrap();
        writeln!(out).unwrap();

        // Sorted layers within realm
        let mut layers: Vec<(&String, &Vec<String>)> = layers_map.iter().collect();
        layers.sort_by_key(|(k, _)| k.as_str());

        for (layer_key, node_names) in layers {
            writeln!(
                out,
                "// {realm} > {layer} ({count} type{s})",
                realm = {
                    let mut c = realm_key.chars();
                    match c.next() {
                        None => String::new(),
                        Some(f) => f.to_uppercase().to_string() + c.as_str(),
                    }
                },
                layer = {
                    let mut c = layer_key.chars();
                    match c.next() {
                        None => String::new(),
                        Some(f) => f.to_uppercase().to_string() + c.as_str(),
                    }
                },
                count = node_names.len(),
                s = if node_names.len() == 1 { "" } else { "s" },
            )
            .unwrap();

            for name in node_names {
                writeln!(out, "MATCH (n:{name})").unwrap();
                writeln!(out, "MATCH (k:Kind {{label: '{name}'}})").unwrap();
                writeln!(out, "MERGE (n)-[:OF_KIND]->(k);").unwrap();
                writeln!(out).unwrap();
            }
        }
    }

    // Verification query
    writeln!(
        out,
        "// ═══════════════════════════════════════════════════════════════════════════════"
    )
    .unwrap();
    writeln!(out, "// VERIFICATION QUERY").unwrap();
    writeln!(
        out,
        "// ═══════════════════════════════════════════════════════════════════════════════"
    )
    .unwrap();
    writeln!(out, "// Run this to verify the wiring was successful:").unwrap();
    writeln!(out, "//").unwrap();
    writeln!(
        out,
        "// MATCH (r:Realm)-[:HAS_LAYER]->(l:Layer)-[:HAS_KIND]->(k:Kind)"
    )
    .unwrap();
    writeln!(out, "// OPTIONAL MATCH (k)<-[rel:OF_KIND]-(n)").unwrap();
    writeln!(
        out,
        "// WITH r.key AS realm, l.key AS layer, k.label AS kind, count(rel) AS instanceCount"
    )
    .unwrap();
    writeln!(out, "// ORDER BY realm, layer, instanceCount DESC").unwrap();
    writeln!(out, "// RETURN realm, layer, kind, instanceCount;").unwrap();

    Ok(out)
}

// ─────────────────────────────────────────────────────────────────────────────
// Tests
// ─────────────────────────────────────────────────────────────────────────────

#[cfg(test)]
mod tests {
    use super::*;
    use crate::generators::Generator;
    use crate::parsers::yaml_node::{LocaleBehavior, NodeDef, ParsedNode};

    fn make_node(name: &str, realm: &str, layer: &str) -> ParsedNode {
        ParsedNode {
            def: NodeDef {
                name: name.to_string(),
                realm: realm.to_string(),
                layer: layer.to_string(),
                node_trait: LocaleBehavior::Invariant,
                knowledge_tier: None,
                icon: None,
                description: "test".to_string(),
                standard_properties: None,
                properties: None,
                relations: None,
                incoming_relations: None,
                neo4j: None,
                example: None,
            },
            realm: realm.to_string(),
            layer: layer.to_string(),
            source_path: std::path::PathBuf::from(format!(
                "models/node-kinds/{realm}/{layer}/{name}.yaml"
            )),
        }
    }

    #[test]
    fn generate_small_autowire() {
        let nodes = vec![
            make_node("Project", "project", "foundation"),
            make_node("Page", "project", "structure"),
            make_node("Block", "project", "structure"),
            make_node("Locale", "global", "config"),
            make_node("SEOKeyword", "global", "seo"), // v10.2: moved to global
        ];

        let cypher = generate_autowire(&nodes).unwrap();

        // Header
        assert!(cypher.contains("Total: 5 node types"));
        assert!(cypher.contains("OF_KIND"));
        assert!(cypher.contains("v9.0.0"));

        // 5 MERGE OF_KIND statements
        let of_kind = cypher
            .lines()
            .filter(|l: &&str| l.contains("MERGE") && l.contains("[:OF_KIND]"))
            .count();
        assert_eq!(of_kind, 5, "expected 5 OF_KIND statements");

        // Spot check patterns
        assert!(cypher.contains("MATCH (n:Project)"));
        assert!(cypher.contains("MATCH (k:Kind {label: 'Project'})"));
        assert!(cypher.contains("MERGE (n)-[:OF_KIND]->(k);"));

        assert!(cypher.contains("MATCH (n:Locale)"));
        assert!(cypher.contains("MATCH (k:Kind {label: 'Locale'})"));

        // Realm order: global, project (v10.2: shared removed)
        let global_pos = cypher.find("GLOBAL REALM").unwrap();
        let project_pos = cypher.find("PROJECT REALM").unwrap();
        assert!(global_pos < project_pos);

        // Layer comments with counts (v10.2: SEO moved to global)
        assert!(cypher.contains("Global > Config (1 type)"));
        assert!(cypher.contains("Project > Foundation (1 type)"));
        assert!(cypher.contains("Project > Structure (2 types)"));
        assert!(cypher.contains("Global > Seo (1 type)"));

        // Nodes sorted within layer
        let block_pos = cypher.find("MATCH (n:Block)").unwrap();
        let page_pos = cypher.find("MATCH (n:Page)").unwrap();
        assert!(block_pos < page_pos, "Block should come before Page");

        // No IN_SUBCATEGORY (v8 term)
        assert!(!cypher.contains("IN_SUBCATEGORY"));
        assert!(!cypher.contains("Subcategory"));

        // Verification query present
        assert!(cypher.contains("VERIFICATION QUERY"));
    }

    #[test]
    fn generate_autowire_missing_realm_fails() {
        let nodes = vec![
            make_node("Project", "project", "foundation"),
            // Missing global (v10.2: shared removed)
        ];

        let result = generate_autowire(&nodes);
        assert!(result.is_err());
        let err = result.unwrap_err().to_string();
        assert!(
            err.contains("global"),
            "error should mention missing realm: {err}"
        );
    }

    #[test]
    fn generate_autowire_integration() {
        let root = std::path::Path::new(env!("CARGO_MANIFEST_DIR"))
            .parent()
            .and_then(|p| p.parent());

        let Some(root) = root else { return };
        if !root.join("pnpm-workspace.yaml").exists() {
            return;
        }

        let generator = AutowireGenerator;
        let cypher = generator
            .generate(root)
            .expect("should generate autowire cypher");

        // v10.1: 43 OF_KIND statements (37 base + 6 atoms)
        let of_kind = cypher
            .lines()
            .filter(|l: &&str| l.contains("MERGE") && l.contains("[:OF_KIND]"))
            .count();
        assert_eq!(
            of_kind, 43,
            "expected 43 OF_KIND statements (37 base + 6 atoms)"
        );

        // All 2 realms present (v10.2: shared removed)
        assert!(cypher.contains("GLOBAL REALM"));
        assert!(cypher.contains("PROJECT REALM"));

        // Spot checks (v10.2: SEO moved to global)
        assert!(cypher.contains("MATCH (n:Style)")); // v10: LocaleVoice → Style
        assert!(cypher.contains("MATCH (k:Kind {label: 'Style'})"));
        assert!(cypher.contains("MATCH (n:SEOMiningRun)"));

        // v10.2: Layer counts match 43 nodes (23 project, 20 global)
        assert!(cypher.contains("Global > Config (1 type)"));
        assert!(cypher.contains("Global > Knowledge (16 types)")); // 10 + 6 atoms

        // v10.2: Header
        assert!(cypher.contains("Total: 43 node types"));

        // Verification query present
        assert!(cypher.contains("VERIFICATION QUERY"));
    }
}
