//! Generate OF_CLASS wiring Cypher statements (instance → Class bridge).
//!
//! v11.8 (ADR-023): Kind → Class, OF_KIND → OF_CLASS
//!
//! For every node type in the schema, generates a MERGE statement that links
//! all existing instances of that type to their Class node via `OF_CLASS`.
//! Replaces the v8 `99-autowire-subcategories.cypher` (IN_SUBCATEGORY → OF_CLASS).
//!
//! Output target: `packages/db/seed/99-autowire-classes.cypher`

use crate::parsers::yaml_node;
use std::collections::BTreeMap;
use std::fmt::Write;
use std::path::Path;

// ─────────────────────────────────────────────────────────────────────────────
// Constants
// ─────────────────────────────────────────────────────────────────────────────

/// Fixed realm order matching the seed file convention (v10.6: 2 realms).
const REALM_ORDER: &[&str] = &["shared", "org"];

// ─────────────────────────────────────────────────────────────────────────────
// Generator
// ─────────────────────────────────────────────────────────────────────────────

pub struct AutowireGenerator;

impl super::Generator for AutowireGenerator {
    fn name(&self) -> &'static str {
        "autowire"
    }

    fn generate(&self, root: &Path) -> crate::Result<String> {
        let nodes = yaml_node::load_all_nodes(root)?;
        generate_autowire(&nodes)
    }
}

fn generate_autowire(nodes: &[yaml_node::ParsedNode]) -> crate::Result<String> {
    // Group by realm → layer → sorted node names
    let mut realm_map: BTreeMap<String, BTreeMap<String, Vec<String>>> = BTreeMap::new();

    for node in nodes {
        realm_map
            .entry(node.realm.clone())
            .or_default()
            .entry(node.layer.clone())
            .or_default()
            .push(node.def.name.clone());
    }

    // Sort node names within each layer
    for layers in realm_map.values_mut() {
        for names in layers.values_mut() {
            names.sort();
        }
    }

    let mut out = String::with_capacity(8 * 1024);

    // Header
    writeln!(
        out,
        "// Auto-wire OF_CLASS relationships (v11.8 instance → Class bridge)"
    )
    .unwrap();
    writeln!(
        out,
        "// ═══════════════════════════════════════════════════════════════════════════════"
    )
    .unwrap();
    writeln!(
        out,
        "// Runs AFTER all other seeds to connect instance nodes to their Class nodes."
    )
    .unwrap();
    writeln!(
        out,
        "// Idempotent: Uses MERGE to allow repeated execution."
    )
    .unwrap();
    writeln!(out, "//").unwrap();
    writeln!(out, "// AUTO-GENERATED by novanet v0.13.0 — DO NOT EDIT").unwrap();
    writeln!(out, "// Total: {count} node types", count = nodes.len()).unwrap();
    writeln!(
        out,
        "// ═══════════════════════════════════════════════════════════════════════════════"
    )
    .unwrap();
    writeln!(out).unwrap();

    for &realm_key in REALM_ORDER {
        let Some(layers_map) = realm_map.get(realm_key) else {
            return Err(crate::NovaNetError::Validation(format!(
                "realm '{realm_key}' has no nodes — expected nodes under models/node-classes/{realm_key}/"
            )));
        };

        // Realm header
        writeln!(
            out,
            "// ─────────────────────────────────────────────────────────────────────────────"
        )
        .unwrap();
        writeln!(out, "// {} REALM", realm_key.to_uppercase()).unwrap();
        writeln!(
            out,
            "// ─────────────────────────────────────────────────────────────────────────────"
        )
        .unwrap();
        writeln!(out).unwrap();

        // Sorted layers within realm
        let mut layers: Vec<(&String, &Vec<String>)> = layers_map.iter().collect();
        layers.sort_by_key(|(k, _)| k.as_str());

        for (layer_key, node_names) in layers {
            writeln!(
                out,
                "// {realm} > {layer} ({count} type{s})",
                realm = {
                    let mut c = realm_key.chars();
                    match c.next() {
                        None => String::new(),
                        Some(f) => f.to_uppercase().to_string() + c.as_str(),
                    }
                },
                layer = {
                    let mut c = layer_key.chars();
                    match c.next() {
                        None => String::new(),
                        Some(f) => f.to_uppercase().to_string() + c.as_str(),
                    }
                },
                count = node_names.len(),
                s = if node_names.len() == 1 { "" } else { "s" },
            )
            .unwrap();

            for name in node_names {
                writeln!(out, "MATCH (n:{name})").unwrap();
                // v11.8: :Class (was :Kind)
                writeln!(out, "MATCH (c:Class {{label: '{name}'}})").unwrap();
                writeln!(out, "MERGE (n)-[:OF_CLASS]->(c);").unwrap();
                writeln!(out).unwrap();
            }
        }
    }

    // Verification query
    writeln!(
        out,
        "// ═══════════════════════════════════════════════════════════════════════════════"
    )
    .unwrap();
    writeln!(out, "// VERIFICATION QUERY").unwrap();
    writeln!(
        out,
        "// ═══════════════════════════════════════════════════════════════════════════════"
    )
    .unwrap();
    writeln!(out, "// Run this to verify the wiring was successful:").unwrap();
    writeln!(out, "//").unwrap();
    // v11.8: :Class, [:HAS_CLASS], [:OF_CLASS] (was :Kind, [:HAS_KIND], [:OF_KIND])
    writeln!(
        out,
        "// MATCH (r:Realm)-[:HAS_LAYER]->(l:Layer)-[:HAS_CLASS]->(c:Class)"
    )
    .unwrap();
    writeln!(out, "// OPTIONAL MATCH (c)<-[rel:OF_CLASS]-(n)").unwrap();
    writeln!(
        out,
        "// WITH r.key AS realm, l.key AS layer, c.label AS class, count(rel) AS instanceCount"
    )
    .unwrap();
    writeln!(out, "// ORDER BY realm, layer, instanceCount DESC").unwrap();
    writeln!(out, "// RETURN realm, layer, class, instanceCount;").unwrap();

    Ok(out)
}

// ─────────────────────────────────────────────────────────────────────────────
// Tests
// ─────────────────────────────────────────────────────────────────────────────

#[cfg(test)]
mod tests {
    use super::*;
    use crate::generators::Generator;
    use crate::generators::test_utils::make_node_simple as make_node;

    /// Clean up any test files left by other tests to avoid pollution.
    fn cleanup_test_files(root: &std::path::Path) {
        use walkdir::WalkDir;

        let node_classes_dir = crate::config::node_classes_dir(root);
        if !node_classes_dir.exists() {
            return;
        }

        for entry in WalkDir::new(node_classes_dir)
            .into_iter()
            .filter_map(|e| e.ok())
            .filter(|e| e.file_type().is_file())
        {
            if let Some(name) = entry.path().file_name().and_then(|n| n.to_str()) {
                if name.starts_with("test-") || name.contains("-test") {
                    let _ = std::fs::remove_file(entry.path());
                }
            }
        }
    }

    #[test]
    fn generate_small_autowire() {
        let nodes = vec![
            make_node("Project", "org", "foundation"),
            make_node("Page", "org", "structure"),
            make_node("Block", "org", "structure"),
            make_node("Locale", "shared", "locale"),
            make_node("Term", "shared", "knowledge"),
            make_node("OrgConfig", "org", "config"), // v11.4: org realm
        ];

        let cypher = generate_autowire(&nodes).unwrap();

        // Header
        assert!(cypher.contains("Total: 6 node types"));
        assert!(cypher.contains("OF_CLASS")); // v11.8: renamed from OF_KIND
        assert!(cypher.contains("v0.13.0"));

        // 6 MERGE OF_CLASS statements (v11.8: renamed from OF_KIND)
        let of_class = cypher
            .lines()
            .filter(|l: &&str| l.contains("MERGE") && l.contains("[:OF_CLASS]"))
            .count();
        assert_eq!(of_class, 6, "expected 6 OF_CLASS statements");

        // Spot check patterns (v11.8: :Class, c variable)
        assert!(cypher.contains("MATCH (n:Project)"));
        assert!(cypher.contains("MATCH (c:Class {label: 'Project'})"));
        assert!(cypher.contains("MERGE (n)-[:OF_CLASS]->(c);"));

        assert!(cypher.contains("MATCH (n:Locale)"));
        assert!(cypher.contains("MATCH (c:Class {label: 'Locale'})"));

        // Realm order: shared, org (v11.4: 2 realms)
        let shared_pos = cypher.find("SHARED REALM").unwrap();
        let org_pos = cypher.find("ORG REALM").unwrap();
        assert!(shared_pos < org_pos);

        // Layer comments with counts (v11.4: no seo/geo layers)
        assert!(cypher.contains("Shared > Locale (1 type)")); // Locale
        assert!(cypher.contains("Shared > Knowledge (1 type)")); // Term
        assert!(cypher.contains("Org > Config (1 type)")); // OrgConfig
        assert!(cypher.contains("Org > Foundation (1 type)"));
        assert!(cypher.contains("Org > Structure (2 types)"));

        // Nodes sorted within layer
        let block_pos = cypher.find("MATCH (n:Block)").unwrap();
        let page_pos = cypher.find("MATCH (n:Page)").unwrap();
        assert!(block_pos < page_pos, "Block should come before Page");

        // No deprecated terms (v8: IN_SUBCATEGORY, v11.7: OF_KIND)
        assert!(!cypher.contains("IN_SUBCATEGORY"));
        assert!(!cypher.contains("Subcategory"));
        assert!(!cypher.contains("OF_KIND")); // v11.8: renamed to OF_CLASS
        assert!(!cypher.contains(":Kind {")); // v11.8: renamed to :Class

        // Verification query present
        assert!(cypher.contains("VERIFICATION QUERY"));
    }

    #[test]
    fn generate_autowire_missing_realm_fails() {
        let nodes = vec![
            make_node("Project", "project", "foundation"),
            // Missing global (v10.2: shared removed)
        ];

        let result = generate_autowire(&nodes);
        assert!(result.is_err());
        let err = result.unwrap_err().to_string();
        assert!(
            err.contains("shared"),
            "error should mention missing realm: {err}"
        );
    }

    #[test]
    fn generate_autowire_integration() {
        let root = std::path::Path::new(env!("CARGO_MANIFEST_DIR"))
            .parent()
            .and_then(|p| p.parent());

        let Some(root) = root else { return };
        if !root.join("pnpm-workspace.yaml").exists() {
            return;
        }

        // Clean up any test files from parallel tests
        cleanup_test_files(root);

        let generator = AutowireGenerator;
        let cypher = generator
            .generate(root)
            .expect("should generate autowire cypher");

        // v0.12.5 + Brand Architecture: 61 OF_CLASS statements
        let of_class = cypher
            .lines()
            .filter(|l: &&str| l.contains("MERGE") && l.contains("[:OF_CLASS]"))
            .count();
        assert_eq!(
            of_class, 61,
            "expected 61 OF_CLASS statements (40 shared + 21 org)"
        );

        // 2 realms present (v11.3: shared + org)
        assert!(cypher.contains("SHARED REALM"));
        assert!(cypher.contains("ORG REALM"));

        // Spot checks (v11.8: :Class instead of :Kind)
        assert!(cypher.contains("MATCH (n:Style)"));
        assert!(cypher.contains("MATCH (c:Class {label: 'Style'})"));

        // v0.12.5: Layer counts (4 shared + 6 org = 10 layers, updated for Country)
        assert!(cypher.contains("Shared > Config (3 types)")); // EntityCategory + Locale + SEOKeywordFormat
        assert!(cypher.contains("Shared > Locale (6 types)")); // Formatting, Style, etc.
        assert!(cypher.contains("Shared > Geography (7 types)")); // Continent, Region, etc. + Country
        assert!(cypher.contains("Shared > Knowledge (24 types)")); // v11.4: +2 containers, -4 obsolete

        // v0.12.5 + Brand Architecture: Header
        assert!(cypher.contains("Total: 61 node types"));

        // Verification query present
        assert!(cypher.contains("VERIFICATION QUERY"));
    }
}
