//! Generate `colors.ts` via MiniJinja template (YAML → TypeScript).
//!
//! Reads `taxonomy.yaml` and produces color tokens for:
//! - Realms (2)
//! - Layers (10)
//! - ArcFamilies (6)
//!
//! v0.17.3 (ADR-036): Traits removed, provenance is per-instance.
//!
//! Output target: `apps/studio/src/design/colors/generated.ts`
//!
//! This is the SINGLE SOURCE OF TRUTH for colors. Both Studio (TypeScript)
//! and TUI (Rust) consume these colors from the same YAML file.

use crate::parsers::organizing::{self, OrganizingDoc};
use minijinja::{Environment, context};
use serde::Serialize;
use std::path::Path;

// ─────────────────────────────────────────────────────────────────────────────
// Template data structures
// ─────────────────────────────────────────────────────────────────────────────

/// Color entry for template rendering.
#[derive(Debug, Serialize)]
struct ColorEntry {
    key: String,
    color: String,
    display_name: String,
}

/// All color data for the template.
/// v0.17.3 (ADR-036): traits removed, provenance is per-instance.
#[derive(Debug, Serialize)]
struct TemplateData {
    version: String,
    realms: Vec<ColorEntry>,
    layers: Vec<ColorEntry>,
    // v0.17.3 (ADR-036): traits removed, provenance is per-instance
    arc_families: Vec<ColorEntry>,
}

// ─────────────────────────────────────────────────────────────────────────────
// MiniJinja template
// ─────────────────────────────────────────────────────────────────────────────

const COLORS_TEMPLATE: &str = r##"// apps/studio/src/design/colors/generated.ts
// Color tokens from taxonomy.yaml (SINGLE SOURCE OF TRUTH)
// AUTO-GENERATED by novanet v{{ version }} — DO NOT EDIT
// Run: cargo run -- schema generate

// =============================================================================
// TYPES
// =============================================================================

export interface ColorTokens {
  /** Raw hex color (e.g., "#2aa198") */
  color: string;
  /** Tailwind bg class at 20% opacity */
  bg: string;
  /** Tailwind text class */
  text: string;
  /** Tailwind border class at 30% opacity */
  border: string;
  /** Tailwind bg class for solid fills */
  bgSolid: string;
}

// =============================================================================
// REALM COLORS ({{ realms | length }})
// =============================================================================

export type RealmKey = {% for r in realms %}'{{ r.key }}'{{ " | " if not loop.last else "" }}{% endfor %};

export const REALM_COLORS: Record<RealmKey, ColorTokens> = {
{%- for r in realms %}
  '{{ r.key }}': {
    color: '{{ r.color }}',
    bg: 'bg-[{{ r.color }}]/20',
    text: 'text-[{{ r.color }}]',
    border: 'border-[{{ r.color }}]/30',
    bgSolid: 'bg-[{{ r.color }}]',
  },
{%- endfor %}
};

export const REALM_DISPLAY_NAMES: Record<RealmKey, string> = {
{%- for r in realms %}
  '{{ r.key }}': '{{ r.display_name }}',
{%- endfor %}
};

// =============================================================================
// LAYER COLORS ({{ layers | length }})
// =============================================================================

export type LayerKey = {% for l in layers %}'{{ l.key }}'{{ " | " if not loop.last else "" }}{% endfor %};

export const LAYER_COLORS: Record<LayerKey, ColorTokens> = {
{%- for l in layers %}
  '{{ l.key }}': {
    color: '{{ l.color }}',
    bg: 'bg-[{{ l.color }}]/20',
    text: 'text-[{{ l.color }}]',
    border: 'border-[{{ l.color }}]/30',
    bgSolid: 'bg-[{{ l.color }}]',
  },
{%- endfor %}
};

export const LAYER_DISPLAY_NAMES: Record<LayerKey, string> = {
{%- for l in layers %}
  '{{ l.key }}': '{{ l.display_name }}',
{%- endfor %}
};

// v0.17.3 (ADR-036): TRAIT COLORS section removed, provenance is per-instance

// =============================================================================
// ARC FAMILY COLORS ({{ arc_families | length }})
// =============================================================================

export type ArcFamilyKey = {% for e in arc_families %}'{{ e.key }}'{{ " | " if not loop.last else "" }}{% endfor %};

export const ARC_FAMILY_COLORS: Record<ArcFamilyKey, ColorTokens> = {
{%- for e in arc_families %}
  '{{ e.key }}': {
    color: '{{ e.color }}',
    bg: 'bg-[{{ e.color }}]/20',
    text: 'text-[{{ e.color }}]',
    border: 'border-[{{ e.color }}]/30',
    bgSolid: 'bg-[{{ e.color }}]',
  },
{%- endfor %}
};

export const ARC_FAMILY_DISPLAY_NAMES: Record<ArcFamilyKey, string> = {
{%- for e in arc_families %}
  '{{ e.key }}': '{{ e.display_name }}',
{%- endfor %}
};

// =============================================================================
// HELPER FUNCTIONS
// =============================================================================

/**
 * Get color tokens for a realm
 */
export function getRealmColor(key: RealmKey): ColorTokens {
  return REALM_COLORS[key];
}

/**
 * Get color tokens for a layer
 */
export function getLayerColor(key: LayerKey): ColorTokens {
  return LAYER_COLORS[key];
}

/**
 * Get color tokens for a trait
 */
export function getTraitColor(key: TraitKey): ColorTokens {
  return TRAIT_COLORS[key];
}

/**
 * Get color tokens for an arc family
 */
export function getArcFamilyColor(key: ArcFamilyKey): ColorTokens {
  return ARC_FAMILY_COLORS[key];
}

/**
 * Get raw hex color for any facet type
 */
export function getFacetHex(
  facetType: 'realm' | 'layer' | 'trait' | 'arcFamily',
  key: string
): string {
  switch (facetType) {
    case 'realm':
      return REALM_COLORS[key as RealmKey]?.color ?? '#ffffff';
    case 'layer':
      return LAYER_COLORS[key as LayerKey]?.color ?? '#ffffff';
    case 'trait':
      return TRAIT_COLORS[key as TraitKey]?.color ?? '#ffffff';
    case 'arcFamily':
      return ARC_FAMILY_COLORS[key as ArcFamilyKey]?.color ?? '#ffffff';
  }
}
"##;

// ─────────────────────────────────────────────────────────────────────────────
// Generator
// ─────────────────────────────────────────────────────────────────────────────

pub struct ColorsGenerator;

impl super::Generator for ColorsGenerator {
    fn name(&self) -> &'static str {
        "colors"
    }

    fn generate(&self, root: &Path) -> crate::Result<String> {
        let doc = organizing::load_organizing(root)?;
        render_colors(&doc)
    }
}

/// Build template data from organizing principles and render.
fn render_colors(doc: &OrganizingDoc) -> crate::Result<String> {
    // Extract realms
    let realms: Vec<ColorEntry> = doc
        .realms
        .iter()
        .map(|r| ColorEntry {
            key: r.key.clone(),
            color: r.color.clone(),
            display_name: r.display_name.clone(),
        })
        .collect();

    // Extract layers (nested under realms), deduplicated by key
    // Multiple realms may have layers with the same key (e.g., 'config' in shared and org)
    // We keep only unique keys (first occurrence wins)
    let mut seen_layers = std::collections::HashSet::new();
    let layers: Vec<ColorEntry> = doc
        .realms
        .iter()
        .flat_map(|r| &r.layers)
        .filter(|l| seen_layers.insert(l.key.clone()))
        .map(|l| ColorEntry {
            key: l.key.clone(),
            color: l.color.clone(),
            display_name: l.display_name.clone(),
        })
        .collect();

    // v0.17.3 (ADR-036): traits extraction removed, provenance is per-instance

    // Extract arc families
    let arc_families: Vec<ColorEntry> = doc
        .arc_families
        .iter()
        .map(|e| ColorEntry {
            key: e.key.clone(),
            color: e.color.clone(),
            display_name: e.display_name.clone(),
        })
        .collect();

    let data = TemplateData {
        version: doc.version.clone(),
        realms,
        layers,
        arc_families,
    };

    // Render MiniJinja template
    let mut env = Environment::new();
    env.add_template("colors.ts", COLORS_TEMPLATE)
        .map_err(|e| crate::NovaNetError::Generator {
            generator: "colors".to_string(),
            detail: format!("template parse error: {e}"),
        })?;

    let tmpl = env
        .get_template("colors.ts")
        .map_err(|e| crate::NovaNetError::Generator {
            generator: "colors".to_string(),
            detail: format!("template not found: {e}"),
        })?;

    let output = tmpl
        .render(context! {
            version => data.version,
            realms => data.realms,
            layers => data.layers,
            // v0.17.3 (ADR-036): traits removed, provenance is per-instance
            arc_families => data.arc_families,
        })
        .map_err(|e| crate::NovaNetError::Generator {
            generator: "colors".to_string(),
            detail: format!("template render error: {e}"),
        })?;

    Ok(output)
}

// ─────────────────────────────────────────────────────────────────────────────
// Hex to RGB helper (for TUI)
// ─────────────────────────────────────────────────────────────────────────────

/// Parse a hex color string to RGB tuple.
/// Supports "#RRGGBB" and "RRGGBB" formats.
pub fn hex_to_rgb(hex: &str) -> Option<(u8, u8, u8)> {
    let hex = hex.trim_start_matches('#');
    if hex.len() != 6 {
        return None;
    }
    let r = u8::from_str_radix(&hex[0..2], 16).ok()?;
    let g = u8::from_str_radix(&hex[2..4], 16).ok()?;
    let b = u8::from_str_radix(&hex[4..6], 16).ok()?;
    Some((r, g, b))
}

// ─────────────────────────────────────────────────────────────────────────────
// Tests
// ─────────────────────────────────────────────────────────────────────────────

#[cfg(test)]
mod tests {
    use super::*;
    use crate::generators::Generator;
    use crate::parsers::organizing::{ArcFamilyDef, LayerDef, OrganizingDoc, RealmDef};
    // v0.17.3 (ADR-036): TraitDef removed, provenance is per-instance
    use serial_test::serial;

    fn make_test_principles() -> OrganizingDoc {
        // v0.17.3 (ADR-036): traits removed, provenance is per-instance
        OrganizingDoc {
            version: "0.17.3".to_string(),
            realms: vec![
                RealmDef {
                    key: "shared".to_string(),
                    display_name: "Shared".to_string(),
                    emoji: "🌍".to_string(),
                    color: "#2aa198".to_string(),
                    llm_context: "test".to_string(),
                    layers: vec![LayerDef {
                        key: "config".to_string(),
                        display_name: "Configuration".to_string(),
                        emoji: "⚙️".to_string(),
                        color: "#64748b".to_string(),
                        llm_context: "test".to_string(),
                    }],
                },
                RealmDef {
                    key: "org".to_string(),
                    display_name: "Organization".to_string(),
                    emoji: "🏢".to_string(),
                    color: "#6c71c4".to_string(),
                    llm_context: "test".to_string(),
                    layers: vec![LayerDef {
                        key: "foundation".to_string(),
                        display_name: "Foundation".to_string(),
                        emoji: "🏛️".to_string(),
                        color: "#3b82f6".to_string(),
                        llm_context: "test".to_string(),
                    }],
                },
            ],
            arc_families: vec![ArcFamilyDef {
                key: "ownership".to_string(),
                display_name: "Ownership".to_string(),
                color: "#3b82f6".to_string(),
                arrow_style: "-->".to_string(),
                llm_context: "test".to_string(),
            }],
        }
    }

    #[test]
    fn render_colors_basic() {
        let principles = make_test_principles();
        let output = render_colors(&principles).unwrap();

        // Header
        assert!(output.contains("AUTO-GENERATED by novanet v0.17.3"));
        assert!(output.contains("SINGLE SOURCE OF TRUTH"));

        // Types (v0.17.3: traits removed, provenance is per-instance)
        assert!(output.contains("export interface ColorTokens"));
        assert!(output.contains("export type RealmKey = 'shared' | 'org'"));
        assert!(output.contains("export type LayerKey = 'config' | 'foundation'"));
        // v0.17.3 (ADR-036): TraitKey removed, provenance is per-instance
        assert!(output.contains("export type ArcFamilyKey = 'ownership'"));
    }

    #[test]
    fn render_colors_realm_entries() {
        let principles = make_test_principles();
        let output = render_colors(&principles).unwrap();

        // Realm colors (quoted keys, v11.2: shared + org)
        assert!(output.contains("'shared': {"));
        assert!(output.contains("color: '#2aa198'"));
        assert!(output.contains("bg: 'bg-[#2aa198]/20'"));
        assert!(output.contains("text: 'text-[#2aa198]'"));
        assert!(output.contains("border: 'border-[#2aa198]/30'"));
        assert!(output.contains("bgSolid: 'bg-[#2aa198]'"));

        // Display names (quoted keys)
        assert!(output.contains("'shared': 'Shared'"));
        assert!(output.contains("'org': 'Organization'"));
    }

    #[test]
    fn render_colors_layer_entries() {
        let principles = make_test_principles();
        let output = render_colors(&principles).unwrap();

        // Layer colors (quoted keys)
        assert!(output.contains("'config': {"));
        assert!(output.contains("color: '#64748b'"));
        assert!(output.contains("'foundation': {"));
        assert!(output.contains("color: '#3b82f6'"));
    }

    #[test]
    fn render_colors_helper_functions() {
        let principles = make_test_principles();
        let output = render_colors(&principles).unwrap();

        assert!(output.contains("export function getRealmColor(key: RealmKey): ColorTokens"));
        assert!(output.contains("export function getLayerColor(key: LayerKey): ColorTokens"));
        // v0.17.3 (ADR-036): getTraitColor removed, provenance is per-instance
        assert!(
            output.contains("export function getArcFamilyColor(key: ArcFamilyKey): ColorTokens")
        );
        assert!(output.contains("export function getFacetHex"));
    }

    #[test]
    fn hex_to_rgb_valid() {
        assert_eq!(hex_to_rgb("#2aa198"), Some((42, 161, 152)));
        assert_eq!(hex_to_rgb("2aa198"), Some((42, 161, 152)));
        assert_eq!(hex_to_rgb("#000000"), Some((0, 0, 0)));
        assert_eq!(hex_to_rgb("#ffffff"), Some((255, 255, 255)));
        assert_eq!(hex_to_rgb("#3b82f6"), Some((59, 130, 246)));
    }

    #[test]
    fn hex_to_rgb_invalid() {
        assert_eq!(hex_to_rgb(""), None);
        assert_eq!(hex_to_rgb("#fff"), None); // Too short
        assert_eq!(hex_to_rgb("#gggggg"), None); // Invalid hex
        assert_eq!(hex_to_rgb("not-a-color"), None);
    }

    #[test]
    #[serial]
    fn generate_colors_integration() {
        let root = std::path::Path::new(env!("CARGO_MANIFEST_DIR"))
            .parent()
            .and_then(|p| p.parent());

        let Some(root) = root else { return };
        if !root.join("pnpm-workspace.yaml").exists() {
            return;
        }

        let generator = ColorsGenerator;
        let output = generator.generate(root).expect("should generate colors.ts");

        // Should have all realms from YAML (v11.2: shared + org)
        assert!(output.contains("'shared'"));
        assert!(output.contains("'org'"));

        // Should have 9 unique layer names (v11.5: 10 total, config in both realms)
        // SHARED: config, locale, geography, knowledge (4)
        // ORG: config, foundation, structure, semantic, instruction, output (6)
        for layer in [
            "config",
            "locale",
            "geography",
            "knowledge",
            "semantic",
            "foundation",
            "structure",
            "instruction",
            "output",
        ] {
            assert!(
                output.contains(&format!("'{layer}'")),
                "missing layer: {layer}"
            );
        }

        // v0.17.3 (ADR-036): traits removed from output, provenance is per-instance

        // Should have all 5 arc families
        for af in [
            "ownership",
            "localization",
            "semantic",
            "generation",
            "mining",
        ] {
            assert!(
                output.contains(&format!("'{af}'")),
                "missing arc family: {af}"
            );
        }

        // Helper functions present
        assert!(output.contains("export function getRealmColor"));
        assert!(output.contains("export function getFacetHex"));
    }
}
