//! Generate EdgeKind meta-nodes + cypher_pattern + FROM/TO_KIND + IN_FAMILY relations.
//!
//! Reads `relations.yaml`, filters out inverse relations, and produces idempotent
//! MERGE statements for EdgeKind nodes plus hierarchy and edge-schema relationships.
//!
//! Output target: `packages/db/seed/02-edge-kinds.cypher`

use super::cypher_utils::{cypher_list_owned, cypher_str};
use crate::parsers::relations::{self, Cardinality, RelationDef, RelationsDocument};
use std::collections::HashMap;
use std::fmt::Write;
use std::path::Path;

// ─────────────────────────────────────────────────────────────────────────────
// Helpers
// ─────────────────────────────────────────────────────────────────────────────

/// Convert SCREAMING_SNAKE_CASE to Title Case.
/// e.g. "HAS_PAGE" -> "Has Page", "SEMANTIC_LINK" -> "Semantic Link"
fn display_name(rel_type: &str) -> String {
    rel_type
        .split('_')
        .map(|word| {
            let mut chars = word.chars();
            match chars.next() {
                None => String::new(),
                Some(first) => first.to_uppercase().to_string() + &chars.as_str().to_lowercase(),
            }
        })
        .collect::<Vec<_>>()
        .join(" ")
}

/// Build a Cypher-ready traversal pattern from source/target labels.
/// e.g. "(Project)-[:HAS_PAGE]->(Page)" or "(Page, Block)-[:HAS_OUTPUT]->(BlockL10n, PageL10n)"
fn cypher_pattern(rel: &RelationDef) -> String {
    let sources = rel.source.labels().join(", ");
    let targets = rel.target.labels().join(", ");
    format!(
        "({sources})-[:{rel_type}]->({targets})",
        rel_type = rel.rel_type
    )
}

/// Map Cardinality enum to snake_case string for Cypher property.
fn cardinality_key(c: Cardinality) -> &'static str {
    match c {
        Cardinality::OneToOne => "one_to_one",
        Cardinality::OneToMany => "one_to_many",
        Cardinality::ManyToOne => "many_to_one",
        Cardinality::ManyToMany => "many_to_many",
    }
}

// ─────────────────────────────────────────────────────────────────────────────
// Generator
// ─────────────────────────────────────────────────────────────────────────────

pub struct EdgeSchemaGenerator;

impl super::Generator for EdgeSchemaGenerator {
    fn name(&self) -> &'static str {
        "edge_schema"
    }

    fn generate(&self, root: &Path) -> crate::Result<String> {
        let doc = relations::load_relations(root)?;
        generate_edge_schema(&doc)
    }
}

fn generate_edge_schema(doc: &RelationsDocument) -> crate::Result<String> {
    // Separate forward (non-inverse) from inverse relations
    let forward: Vec<&RelationDef> = doc.relations.iter().filter(|r| !r.is_inverse()).collect();

    // Build inverse name lookup: forward_type -> inverse_type
    let inverse_names: HashMap<&str, &str> = doc
        .relations
        .iter()
        .filter(|r| r.is_inverse())
        .filter_map(|r| {
            r.inverse_of
                .as_deref()
                .map(|fwd| (fwd, r.rel_type.as_str()))
        })
        .collect();

    let mut out = String::with_capacity(32 * 1024);

    // Header
    writeln!(
        out,
        "// ═══════════════════════════════════════════════════════════════════════════════"
    )
    .unwrap();
    writeln!(out, "// EdgeKind Meta-Nodes — v9.0.0").unwrap();
    writeln!(out, "// AUTO-GENERATED by novanet — DO NOT EDIT").unwrap();
    writeln!(
        out,
        "// {count} EdgeKind nodes + hierarchy + edge schema relations",
        count = forward.len()
    )
    .unwrap();
    writeln!(
        out,
        "// ═══════════════════════════════════════════════════════════════════════════════"
    )
    .unwrap();
    writeln!(out).unwrap();

    // ── Section 1: EdgeKind nodes ─────────────────────────────────────────────
    write_section_header(&mut out, "EdgeKind Nodes", forward.len());
    writeln!(out).unwrap();

    for rel in &forward {
        let key = &rel.rel_type;
        let var = format!("ek_{key}");
        let dn = cypher_str(&display_name(key));
        let llm = cypher_str(&rel.llm_context);
        let card = cardinality_key(rel.cardinality);
        let self_ref = rel.is_self_referential.unwrap_or(false);
        let inv = inverse_names.get(key.as_str());
        let props: Vec<String> = rel.properties.clone().unwrap_or_default();
        let pattern = cypher_str(&cypher_pattern(rel));

        writeln!(out, "MERGE ({var}:Meta:EdgeKind {{key: '{key}'}})").unwrap();
        writeln!(out, "ON CREATE SET").unwrap();
        writeln!(out, "  {var}.display_name = '{dn}',").unwrap();
        writeln!(out, "  {var}.llm_context = '{llm}',").unwrap();
        writeln!(out, "  {var}.cardinality = '{card}',").unwrap();
        writeln!(out, "  {var}.is_self_referential = {self_ref},").unwrap();
        if let Some(inv_name) = inv {
            writeln!(out, "  {var}.inverse_name = '{inv_name}',").unwrap();
        } else {
            writeln!(out, "  {var}.inverse_name = null,").unwrap();
        }
        writeln!(
            out,
            "  {var}.edge_properties = {props},",
            props = cypher_list_owned(&props)
        )
        .unwrap();
        writeln!(out, "  {var}.cypher_pattern = '{pattern}',").unwrap();
        writeln!(out, "  {var}.temperature_threshold = null,").unwrap();
        writeln!(out, "  {var}.created_at = datetime()").unwrap();
        writeln!(out, "ON MATCH SET").unwrap();
        writeln!(out, "  {var}.display_name = '{dn}',").unwrap();
        writeln!(out, "  {var}.llm_context = '{llm}',").unwrap();
        writeln!(out, "  {var}.cardinality = '{card}',").unwrap();
        writeln!(out, "  {var}.is_self_referential = {self_ref},").unwrap();
        if let Some(inv_name) = inv {
            writeln!(out, "  {var}.inverse_name = '{inv_name}',").unwrap();
        } else {
            writeln!(out, "  {var}.inverse_name = null,").unwrap();
        }
        writeln!(
            out,
            "  {var}.edge_properties = {props},",
            props = cypher_list_owned(&props)
        )
        .unwrap();
        writeln!(out, "  {var}.cypher_pattern = '{pattern}',").unwrap();
        writeln!(out, "  {var}.temperature_threshold = null,").unwrap();
        writeln!(out, "  {var}.updated_at = datetime();").unwrap();
        writeln!(out).unwrap();
    }

    // ── Section 2: HAS_EDGE_KIND (EdgeFamily → EdgeKind) ─────────────────────
    write_section_header(
        &mut out,
        "Hierarchy: EdgeFamily -[:HAS_EDGE_KIND]-> EdgeKind",
        forward.len(),
    );
    writeln!(out).unwrap();

    for rel in &forward {
        writeln!(
            out,
            "MATCH (ef:EdgeFamily {{key: '{family}'}}), (ek:EdgeKind {{key: '{key}'}})",
            family = rel.family,
            key = rel.rel_type
        )
        .unwrap();
        writeln!(out, "MERGE (ef)-[:HAS_EDGE_KIND]->(ek);").unwrap();
        writeln!(out).unwrap();
    }

    // ── Section 3: IN_FAMILY (EdgeKind → EdgeFamily) ─────────────────────────
    write_section_header(
        &mut out,
        "Facet: EdgeKind -[:IN_FAMILY]-> EdgeFamily",
        forward.len(),
    );
    writeln!(out).unwrap();

    for rel in &forward {
        writeln!(
            out,
            "MATCH (ek:EdgeKind {{key: '{key}'}}), (ef:EdgeFamily {{key: '{family}'}})",
            key = rel.rel_type,
            family = rel.family
        )
        .unwrap();
        writeln!(out, "MERGE (ek)-[:IN_FAMILY]->(ef);").unwrap();
        writeln!(out).unwrap();
    }

    // ── Section 4: FROM_KIND (EdgeKind → Kind source labels) ─────────────────
    let from_count: usize = forward.iter().map(|r| r.source.len()).sum();
    write_section_header(
        &mut out,
        "Edge Schema: EdgeKind -[:FROM_KIND]-> Kind",
        from_count,
    );
    writeln!(out).unwrap();

    for rel in &forward {
        for source in rel.source.labels() {
            writeln!(
                out,
                "MATCH (ek:EdgeKind {{key: '{key}'}}), (k:Kind {{label: '{source}'}})",
                key = rel.rel_type
            )
            .unwrap();
            writeln!(out, "MERGE (ek)-[:FROM_KIND]->(k);").unwrap();
            writeln!(out).unwrap();
        }
    }

    // ── Section 5: TO_KIND (EdgeKind → Kind target labels) ───────────────────
    let to_count: usize = forward.iter().map(|r| r.target.len()).sum();
    write_section_header(
        &mut out,
        "Edge Schema: EdgeKind -[:TO_KIND]-> Kind",
        to_count,
    );
    writeln!(out).unwrap();

    for rel in &forward {
        for target in rel.target.labels() {
            writeln!(
                out,
                "MATCH (ek:EdgeKind {{key: '{key}'}}), (k:Kind {{label: '{target}'}})",
                key = rel.rel_type
            )
            .unwrap();
            writeln!(out, "MERGE (ek)-[:TO_KIND]->(k);").unwrap();
            writeln!(out).unwrap();
        }
    }

    Ok(out)
}

/// Write a visual section header comment.
fn write_section_header(out: &mut String, title: &str, count: usize) {
    let bar = "// ═══════════════════════════════════════════════════════════════════════════════";
    writeln!(out, "{bar}").unwrap();
    writeln!(out, "// {title} ({count})").unwrap();
    writeln!(out, "{bar}").unwrap();
}

// ─────────────────────────────────────────────────────────────────────────────
// Tests
// ─────────────────────────────────────────────────────────────────────────────

#[cfg(test)]
mod tests {
    use super::*;
    use crate::generators::Generator;
    use crate::parsers::relations::{EdgeFamily, NodeRef};

    fn make_rel(
        rel_type: &str,
        family: EdgeFamily,
        source: NodeRef,
        target: NodeRef,
        cardinality: Cardinality,
    ) -> RelationDef {
        RelationDef {
            rel_type: rel_type.to_string(),
            family,
            source,
            target,
            cardinality,
            llm_context: format!("{rel_type} context."),
            properties: None,
            is_self_referential: None,
            inverse_of: None,
        }
    }

    fn make_inverse(rel_type: &str, family: EdgeFamily, inverse_of: &str) -> RelationDef {
        RelationDef {
            rel_type: rel_type.to_string(),
            family,
            source: NodeRef::Single("B".to_string()),
            target: NodeRef::Single("A".to_string()),
            cardinality: Cardinality::ManyToOne,
            llm_context: "Inverse.".to_string(),
            properties: None,
            is_self_referential: None,
            inverse_of: Some(inverse_of.to_string()),
        }
    }

    #[test]
    fn display_name_simple() {
        assert_eq!(display_name("HAS_PAGE"), "Has Page");
    }

    #[test]
    fn display_name_three_words() {
        assert_eq!(display_name("SEMANTIC_LINK"), "Semantic Link");
    }

    #[test]
    fn display_name_single_word() {
        assert_eq!(display_name("GENERATES"), "Generates");
    }

    #[test]
    fn cypher_pattern_simple() {
        let rel = make_rel(
            "HAS_PAGE",
            EdgeFamily::Ownership,
            NodeRef::Single("Project".to_string()),
            NodeRef::Single("Page".to_string()),
            Cardinality::OneToMany,
        );
        assert_eq!(cypher_pattern(&rel), "(Project)-[:HAS_PAGE]->(Page)");
    }

    #[test]
    fn cypher_pattern_multi_source_target() {
        let rel = make_rel(
            "HAS_OUTPUT",
            EdgeFamily::Localization,
            NodeRef::Multiple(vec!["Page".to_string(), "Block".to_string()]),
            NodeRef::Multiple(vec!["PageL10n".to_string(), "BlockL10n".to_string()]),
            Cardinality::OneToMany,
        );
        assert_eq!(
            cypher_pattern(&rel),
            "(Page, Block)-[:HAS_OUTPUT]->(PageL10n, BlockL10n)"
        );
    }

    #[test]
    fn cardinality_key_values() {
        assert_eq!(cardinality_key(Cardinality::OneToOne), "one_to_one");
        assert_eq!(cardinality_key(Cardinality::OneToMany), "one_to_many");
        assert_eq!(cardinality_key(Cardinality::ManyToOne), "many_to_one");
        assert_eq!(cardinality_key(Cardinality::ManyToMany), "many_to_many");
    }

    #[test]
    fn generate_small_edge_schema() {
        let doc = RelationsDocument {
            relations: vec![
                make_rel(
                    "HAS_PAGE",
                    EdgeFamily::Ownership,
                    NodeRef::Single("Project".to_string()),
                    NodeRef::Single("Page".to_string()),
                    Cardinality::OneToMany,
                ),
                {
                    let mut rel = make_rel(
                        "HAS_BLOCK",
                        EdgeFamily::Ownership,
                        NodeRef::Single("Page".to_string()),
                        NodeRef::Single("Block".to_string()),
                        Cardinality::OneToMany,
                    );
                    rel.properties = Some(vec!["position".to_string()]);
                    rel
                },
                make_inverse("BLOCK_OF", EdgeFamily::Ownership, "HAS_BLOCK"),
            ],
            semantic_link_types: None,
            examples: None,
        };

        let cypher = generate_edge_schema(&doc).unwrap();

        // Header
        assert!(cypher.contains("2 EdgeKind nodes"));

        // EdgeKind MERGE statements (only forward, not inverse)
        let ek_merges = cypher
            .lines()
            .filter(|l: &&str| l.contains("MERGE") && l.contains(":Meta:EdgeKind"))
            .count();
        assert_eq!(ek_merges, 2, "should have 2 EdgeKind merges (no inverse)");

        // No BLOCK_OF EdgeKind node
        assert!(
            !cypher.contains("ek_BLOCK_OF:Meta:EdgeKind"),
            "inverse should not create EdgeKind"
        );

        // Properties
        assert!(cypher.contains("ek_HAS_PAGE.cardinality = 'one_to_many'"));
        assert!(cypher.contains("ek_HAS_PAGE.display_name = 'Has Page'"));
        assert!(cypher.contains("ek_HAS_PAGE.cypher_pattern = '(Project)-[:HAS_PAGE]->(Page)'"));
        assert!(cypher.contains("ek_HAS_PAGE.inverse_name = null"));

        // HAS_BLOCK has inverse_name and properties
        assert!(cypher.contains("ek_HAS_BLOCK.inverse_name = 'BLOCK_OF'"));
        assert!(cypher.contains("ek_HAS_BLOCK.edge_properties = ['position']"));

        // HAS_PAGE has no properties
        assert!(cypher.contains("ek_HAS_PAGE.edge_properties = []"));

        // temperature_threshold always null
        assert!(cypher.contains("ek_HAS_PAGE.temperature_threshold = null"));

        // HAS_EDGE_KIND relationships
        let has_ek = cypher
            .lines()
            .filter(|l: &&str| l.contains("MERGE") && l.contains("[:HAS_EDGE_KIND]"))
            .count();
        assert_eq!(has_ek, 2);

        // IN_FAMILY relationships
        let in_family = cypher
            .lines()
            .filter(|l: &&str| l.contains("MERGE") && l.contains("[:IN_FAMILY]"))
            .count();
        assert_eq!(in_family, 2);

        // FROM_KIND relationships (1 source each = 2 total)
        let from_kind = cypher
            .lines()
            .filter(|l: &&str| l.contains("MERGE") && l.contains("[:FROM_KIND]"))
            .count();
        assert_eq!(from_kind, 2);

        // TO_KIND relationships (1 target each = 2 total)
        let to_kind = cypher
            .lines()
            .filter(|l: &&str| l.contains("MERGE") && l.contains("[:TO_KIND]"))
            .count();
        assert_eq!(to_kind, 2);

        // Spot check FROM_KIND wiring
        assert!(cypher.contains("(ek:EdgeKind {key: 'HAS_PAGE'}), (k:Kind {label: 'Project'})"));
        assert!(cypher.contains("(ek:EdgeKind {key: 'HAS_BLOCK'}), (k:Kind {label: 'Page'})"));

        // Spot check TO_KIND wiring
        assert!(cypher.contains("(ek:EdgeKind {key: 'HAS_PAGE'}), (k:Kind {label: 'Page'})"));
        assert!(cypher.contains("(ek:EdgeKind {key: 'HAS_BLOCK'}), (k:Kind {label: 'Block'})"));

        // Timestamps
        assert!(cypher.contains("created_at = datetime()"));
        assert!(cypher.contains("updated_at = datetime()"));
    }

    #[test]
    fn generate_multi_source_target_from_to() {
        let doc = RelationsDocument {
            relations: vec![make_rel(
                "HAS_OUTPUT",
                EdgeFamily::Localization,
                NodeRef::Multiple(vec!["Page".to_string(), "Block".to_string()]),
                NodeRef::Multiple(vec!["PageL10n".to_string(), "BlockL10n".to_string()]),
                Cardinality::OneToMany,
            )],
            semantic_link_types: None,
            examples: None,
        };

        let cypher = generate_edge_schema(&doc).unwrap();

        // 2 FROM_KIND (Page, Block)
        let from_kind = cypher
            .lines()
            .filter(|l: &&str| l.contains("MERGE") && l.contains("[:FROM_KIND]"))
            .count();
        assert_eq!(from_kind, 2, "should have 2 FROM_KIND for multi-source");

        // 2 TO_KIND (PageL10n, BlockL10n)
        let to_kind = cypher
            .lines()
            .filter(|l: &&str| l.contains("MERGE") && l.contains("[:TO_KIND]"))
            .count();
        assert_eq!(to_kind, 2, "should have 2 TO_KIND for multi-target");

        // cypher_pattern includes all sources and targets
        assert!(cypher.contains("(Page, Block)-[:HAS_OUTPUT]->(PageL10n, BlockL10n)"));
    }

    #[test]
    fn generate_self_referential() {
        let mut rel = make_rel(
            "FALLBACK_TO",
            EdgeFamily::Localization,
            NodeRef::Single("Locale".to_string()),
            NodeRef::Single("Locale".to_string()),
            Cardinality::ManyToOne,
        );
        rel.is_self_referential = Some(true);

        let doc = RelationsDocument {
            relations: vec![rel],
            semantic_link_types: None,
            examples: None,
        };

        let cypher = generate_edge_schema(&doc).unwrap();
        assert!(cypher.contains("ek_FALLBACK_TO.is_self_referential = true"));
    }

    #[test]
    fn generate_edge_schema_integration() {
        let root = std::path::Path::new(env!("CARGO_MANIFEST_DIR"))
            .parent()
            .and_then(|p| p.parent());

        let Some(root) = root else { return };
        if !root.join("pnpm-workspace.yaml").exists() {
            return;
        }

        let generator = EdgeSchemaGenerator;
        let cypher = generator
            .generate(root)
            .expect("should generate edge schema cypher");

        // Count non-inverse relations (75 total - 5 inverse = 70)
        let ek_merges = cypher
            .lines()
            .filter(|l: &&str| l.contains("MERGE") && l.contains(":Meta:EdgeKind"))
            .count();
        assert_eq!(ek_merges, 70, "expected 70 EdgeKind MERGE statements");

        // HAS_EDGE_KIND relationships match EdgeKind count
        let has_ek = cypher
            .lines()
            .filter(|l: &&str| l.contains("MERGE") && l.contains("[:HAS_EDGE_KIND]"))
            .count();
        assert_eq!(has_ek, 70, "expected 70 HAS_EDGE_KIND relationships");

        // IN_FAMILY relationships match EdgeKind count
        let in_family = cypher
            .lines()
            .filter(|l: &&str| l.contains("MERGE") && l.contains("[:IN_FAMILY]"))
            .count();
        assert_eq!(in_family, 70, "expected 70 IN_FAMILY relationships");

        // Family distribution (non-inverse counts)
        // Section 2 MATCH lines have EdgeFamily first: "MATCH (ef:EdgeFamily ..."
        let count_family = |family: &str| {
            cypher
                .lines()
                .filter(|l: &&str| {
                    l.contains("MATCH (ef:EdgeFamily")
                        && l.contains(&format!("EdgeFamily {{key: '{family}'}}"))
                })
                .count()
        };

        let ownership = count_family("ownership");
        let localization = count_family("localization");
        let semantic = count_family("semantic");
        let generation = count_family("generation");
        let mining = count_family("mining");

        assert!(
            ownership + localization + semantic + generation + mining == 70,
            "family counts should sum to 70: o={ownership} l={localization} s={semantic} g={generation} m={mining}"
        );

        // Spot checks — specific EdgeKinds
        assert!(cypher.contains("ek_HAS_PAGE:Meta:EdgeKind {key: 'HAS_PAGE'}"));
        assert!(cypher.contains("ek_HAS_BLOCK:Meta:EdgeKind {key: 'HAS_BLOCK'}"));
        assert!(cypher.contains("ek_FOR_LOCALE:Meta:EdgeKind {key: 'FOR_LOCALE'}"));

        // Spot check — inverse_name populated
        assert!(
            cypher.contains("ek_HAS_BLOCK.inverse_name = 'BLOCK_OF'"),
            "HAS_BLOCK should have inverse_name BLOCK_OF"
        );

        // Spot check — FROM_KIND/TO_KIND for HAS_PAGE
        assert!(cypher.contains("(ek:EdgeKind {key: 'HAS_PAGE'}), (k:Kind {label: 'Project'})"));

        // All cardinality values are valid
        for line in cypher.lines() {
            if line.contains(".cardinality = '") {
                assert!(
                    line.contains("'one_to_one'")
                        || line.contains("'one_to_many'")
                        || line.contains("'many_to_one'")
                        || line.contains("'many_to_many'"),
                    "invalid cardinality: {line}"
                );
            }
        }

        // Header reflects count
        assert!(cypher.contains("70 EdgeKind nodes"));
    }
}
