//! Generate `hierarchy.ts` via MiniJinja template (taxonomy → TypeScript).
//!
//! Reads `taxonomy.yaml` and produces the realm → layer hierarchy tree
//! used by Studio for schema visualization and grouping.
//! Replaces the hand-written `hierarchy.ts` (v8: SCOPE_HIERARCHY → v9: REALM_HIERARCHY).
//!
//! Output target: `packages/core/src/graph/hierarchy.ts`

use crate::parsers::organizing;
use minijinja::{Environment, context};
use serde::Serialize;
use std::path::Path;

// ─────────────────────────────────────────────────────────────────────────────
// Template data structures
// ─────────────────────────────────────────────────────────────────────────────

/// A realm group for the template.
#[derive(Debug, Serialize)]
struct TemplateRealm {
    key: String,
    display_name: String,
    emoji: String,
    description: String,
    layer_count: usize,
    layers: Vec<TemplateLayer>,
}

/// A layer within a realm.
#[derive(Debug, Serialize)]
struct TemplateLayer {
    key: String,
    display_name: String,
    emoji: String,
    description: String,
}

// ─────────────────────────────────────────────────────────────────────────────
// Helpers
// ─────────────────────────────────────────────────────────────────────────────

/// Extract the first sentence from a multiline llm_context field.
/// Collapses whitespace, splits at ". ", and escapes for TS single-quoted strings.
fn first_sentence(text: &str) -> String {
    let collapsed: String = text.split_whitespace().collect::<Vec<_>>().join(" ");
    let sentence = if let Some(idx) = collapsed.find(". ") {
        collapsed[..=idx].to_string()
    } else if collapsed.ends_with('.') {
        collapsed
    } else {
        format!("{collapsed}.")
    };
    sentence.replace('\'', "\\'")
}

// ─────────────────────────────────────────────────────────────────────────────
// MiniJinja template
// ─────────────────────────────────────────────────────────────────────────────

const HIERARCHY_TEMPLATE: &str = r##"// packages/core/src/graph/hierarchy.ts
// REALM_HIERARCHY — v9 realm → layer tree with node type mappings
// AUTO-GENERATED by novanet v{{ version }} — DO NOT EDIT
// Run: novanet schema generate

import type { Realm } from '../types/nodes.js';
import type { Layer, RealmDefinition, LayerMeta } from './types.js';
import { getNodeTypesByRealmAndLayer } from './layers.js';

// =============================================================================
// REALM_HIERARCHY - Complete realm hierarchy definition
// =============================================================================

/**
 * Complete realm hierarchy definition.
 * This is the single source of truth for the ontology structure.
 *
 * {{ realm_count }} Realms ({{ total_layers }} layers):
{%- for realm in realms %}
 * - {{ realm.display_name }}: {{ realm.description }} ({{ realm.layer_count }} layer{{ "s" if realm.layer_count != 1 else "" }})
{%- endfor %}
 */
export const REALM_HIERARCHY: Record<Realm, RealmDefinition> = {
{%- for realm in realms %}
  // ═══════════════════════════════════════════════════════════════════════════
  // {{ realm.key | upper }} ({{ realm.layer_count }} layer{{ "s" if realm.layer_count != 1 else "" }})
  // ═══════════════════════════════════════════════════════════════════════════
  {{ realm.key }}: {
    realm: '{{ realm.key }}',
    label: '{{ realm.key | upper }}',
    icon: '{{ realm.emoji }}',
    description: '{{ realm.description }}',
    layers: {
{%- for layer in realm.layers %}
      '{{ layer.key }}': {
        label: '{{ layer.display_name }}',
        description: '{{ layer.description }}',
        icon: '{{ layer.emoji }}',
        nodeTypes: getNodeTypesByRealmAndLayer('{{ realm.key }}', '{{ layer.key }}'),
      },
{%- endfor %}
    } as Record<Layer, LayerMeta>,
  },
{%- endfor %}
};

// =============================================================================
// HELPER FUNCTIONS
// =============================================================================

/**
 * Get realm definition by realm key
 * @param realm - The realm to look up
 * @returns The realm definition
 */
export function getRealmDefinition(realm: Realm): RealmDefinition {
  return REALM_HIERARCHY[realm];
}

/**
 * Get layer metadata within a realm
 * @param realm - The realm to look up
 * @param layer - The layer to look up
 * @returns The layer metadata, or undefined if not found
 */
export function getLayerMeta(
  realm: Realm,
  layer: Layer
): LayerMeta | undefined {
  return REALM_HIERARCHY[realm]?.layers[layer];
}

/**
 * Get all layers for a realm
 * @param realm - The realm to look up
 * @returns Array of layer keys
 */
export function getLayersForRealm(realm: Realm): Layer[] {
  return Object.keys(REALM_HIERARCHY[realm].layers) as Layer[];
}
"##;

// ─────────────────────────────────────────────────────────────────────────────
// Generator
// ─────────────────────────────────────────────────────────────────────────────

pub struct HierarchyGenerator;

impl super::Generator for HierarchyGenerator {
    fn name(&self) -> &'static str {
        "hierarchy"
    }

    fn generate(&self, root: &Path) -> crate::Result<String> {
        let doc = organizing::load_organizing(root)?;
        render_hierarchy(&doc)
    }
}

fn render_hierarchy(doc: &organizing::OrganizingDoc) -> crate::Result<String> {
    let realms: Vec<TemplateRealm> = doc
        .realms
        .iter()
        .map(|r| TemplateRealm {
            key: r.key.clone(),
            display_name: r.display_name.clone(),
            emoji: r.emoji.clone(),
            description: first_sentence(&r.llm_context),
            layer_count: r.layers.len(),
            layers: r
                .layers
                .iter()
                .map(|l| TemplateLayer {
                    key: l.key.clone(),
                    display_name: l.display_name.clone(),
                    emoji: l.emoji.clone(),
                    description: first_sentence(&l.llm_context),
                })
                .collect(),
        })
        .collect();

    let total_layers: usize = realms.iter().map(|r| r.layer_count).sum();

    let mut env = Environment::new();
    env.add_template("hierarchy.ts", HIERARCHY_TEMPLATE)
        .map_err(|e| crate::NovaNetError::Generator {
            generator: "hierarchy".to_string(),
            detail: format!("template parse error: {e}"),
        })?;

    let tmpl = env
        .get_template("hierarchy.ts")
        .map_err(|e| crate::NovaNetError::Generator {
            generator: "hierarchy".to_string(),
            detail: format!("template not found: {e}"),
        })?;

    let output = tmpl
        .render(context! {
            version => &doc.version,
            realm_count => doc.realms.len(),
            total_layers => total_layers,
            realms => realms,
        })
        .map_err(|e| crate::NovaNetError::Generator {
            generator: "hierarchy".to_string(),
            detail: format!("template render error: {e}"),
        })?;

    Ok(output)
}

// ─────────────────────────────────────────────────────────────────────────────
// Tests
// ─────────────────────────────────────────────────────────────────────────────

#[cfg(test)]
mod tests {
    use super::*;
    use crate::generators::Generator;
    use crate::parsers::organizing::{ArcFamilyDef, LayerDef, OrganizingDoc, RealmDef, TraitDef};

    #[test]
    fn first_sentence_period_space() {
        assert_eq!(first_sentence("Hello world. Goodbye."), "Hello world.");
    }

    #[test]
    fn first_sentence_trailing_period() {
        assert_eq!(first_sentence("Just one sentence."), "Just one sentence.");
    }

    #[test]
    fn first_sentence_no_period() {
        assert_eq!(first_sentence("No period here"), "No period here.");
    }

    #[test]
    fn first_sentence_multiline() {
        assert_eq!(
            first_sentence("First line.\n  Second line.  \n  Third.\n"),
            "First line."
        );
    }

    #[test]
    fn first_sentence_escapes_quotes() {
        assert_eq!(first_sentence("It's a test."), "It\\'s a test.");
    }

    fn make_doc() -> OrganizingDoc {
        OrganizingDoc {
            version: "0.13.0".to_string(),
            realms: vec![
                RealmDef {
                    key: "shared".to_string(),
                    display_name: "Shared".to_string(),
                    emoji: "\u{1F30D}".to_string(),
                    color: "#2aa198".to_string(),
                    llm_context: "Shared across ALL orgs. Universal locale knowledge.".to_string(),
                    layers: vec![LayerDef {
                        key: "config".to_string(),
                        display_name: "Configuration".to_string(),
                        emoji: "\u{2699}\u{FE0F}".to_string(),
                        color: "#64748b".to_string(),
                        llm_context: "Core configuration nodes. Locale definitions.".to_string(),
                    }],
                },
                RealmDef {
                    key: "org".to_string(),
                    display_name: "Org".to_string(),
                    emoji: "\u{1F3E2}".to_string(), // 🏢
                    color: "#6c71c4".to_string(),
                    llm_context: "Organization-specific content. Contains OrgConfig and Projects."
                        .to_string(),
                    layers: vec![
                        LayerDef {
                            key: "foundation".to_string(),
                            display_name: "Foundation".to_string(),
                            emoji: "\u{1F3DB}\u{FE0F}".to_string(),
                            color: "#3b82f6".to_string(),
                            llm_context: "Core project identity.".to_string(),
                        },
                        LayerDef {
                            key: "structure".to_string(),
                            display_name: "Structure".to_string(),
                            emoji: "\u{1F3D7}\u{FE0F}".to_string(),
                            color: "#06b6d4".to_string(),
                            llm_context: "Information architecture. Pages and blocks.".to_string(),
                        },
                    ],
                },
                // v11.2: 2 realms only (shared + org)
            ],
            traits: vec![TraitDef {
                key: "defined".to_string(),
                display_name: "Defined".to_string(),
                color: "#3b82f6".to_string(),
                llm_context: "Invariant nodes.".to_string(),
            }],
            arc_families: vec![ArcFamilyDef {
                key: "ownership".to_string(),
                display_name: "Ownership".to_string(),
                color: "#3b82f6".to_string(),
                arrow_style: "-->".to_string(),
                llm_context: "Ownership edges.".to_string(),
            }],
        }
    }

    #[test]
    fn render_small_hierarchy() {
        let doc = make_doc();
        let output = render_hierarchy(&doc).unwrap();

        // Header
        assert!(output.contains("AUTO-GENERATED by novanet v0.13.0"));
        assert!(output.contains("REALM_HIERARCHY"));

        // Imports
        assert!(output.contains("import type { Realm } from '../types/nodes.js';"));
        assert!(
            output.contains("import type { Layer, RealmDefinition, LayerMeta } from './types.js';")
        );
        assert!(output.contains("import { getNodeTypesByRealmAndLayer } from './layers.js';"));

        // Record type
        assert!(output.contains("Record<Realm, RealmDefinition>"));

        // 2 realms present (v11.2: shared + org)
        assert!(output.contains("shared: {"));
        assert!(output.contains("org: {"));

        // Realm sections
        assert!(output.contains("SHARED (1 layer)"));
        assert!(output.contains("ORG (2 layers)"));

        // Realm properties (v11.4: tenants → orgs terminology)
        assert!(output.contains("realm: 'shared'"));
        assert!(output.contains("label: 'SHARED'"));
        assert!(output.contains("description: 'Shared across ALL orgs.'"));

        // Layer properties (note: keys are quoted in output)
        assert!(output.contains("'config': {"));
        assert!(output.contains("label: 'Configuration'"));
        assert!(output.contains("description: 'Core configuration nodes.'"));
        assert!(output.contains("getNodeTypesByRealmAndLayer('shared', 'config')"));

        assert!(output.contains("'foundation': {"));
        assert!(output.contains("'structure': {"));

        // Cast types
        assert!(output.contains("as Record<Layer, LayerMeta>"));

        // Helper functions
        assert!(
            output.contains("export function getRealmDefinition(realm: Realm): RealmDefinition")
        );
        assert!(output.contains("export function getLayerMeta("));
        assert!(output.contains("export function getLayersForRealm(realm: Realm): Layer[]"));

        // v9 terminology — no v8 terms
        assert!(!output.contains("SCOPE_HIERARCHY"));
        assert!(!output.contains("getNodeTypesBySubcategory"));

        // JSDoc header (v11.2: 2 realms - shared + org)
        assert!(output.contains("2 Realms (3 layers)"));
        assert!(output.contains("Shared: Shared across ALL orgs. (1 layer)"));
        assert!(output.contains("Org: Organization-specific content. (2 layers)"));
    }

    #[test]
    fn generate_hierarchy_integration() {
        let root = std::path::Path::new(env!("CARGO_MANIFEST_DIR"))
            .parent()
            .and_then(|p| p.parent());

        let Some(root) = root else { return };
        if !root.join("pnpm-workspace.yaml").exists() {
            return;
        }

        let generator = HierarchyGenerator;
        let output = generator
            .generate(root)
            .expect("should generate hierarchy.ts");

        // Header (version from taxonomy.yaml)
        assert!(output.contains("AUTO-GENERATED by novanet v0.13.0"));

        // v9 export
        assert!(output.contains("export const REALM_HIERARCHY: Record<Realm, RealmDefinition>"));

        // 2 realms (v11.3: shared + org)
        assert!(output.contains("shared: {"));
        assert!(output.contains("org: {")); // v11.2: org realm

        // v11.3: uses getNodeTypesByRealmAndLayer(realm, layer) calls
        // Check key realm/layer combinations (v11.4: SEO/GEO moved to shared/knowledge)
        assert!(output.contains("getNodeTypesByRealmAndLayer('shared', 'config')")); // v11.4: shared.config
        assert!(output.contains("getNodeTypesByRealmAndLayer('shared', 'locale')"));
        assert!(output.contains("getNodeTypesByRealmAndLayer('shared', 'geography')"));
        assert!(output.contains("getNodeTypesByRealmAndLayer('shared', 'knowledge')"));
        assert!(output.contains("getNodeTypesByRealmAndLayer('org', 'config')"));
        assert!(output.contains("getNodeTypesByRealmAndLayer('org', 'semantic')"));
        assert!(output.contains("getNodeTypesByRealmAndLayer('org', 'foundation')"));
        assert!(output.contains("getNodeTypesByRealmAndLayer('org', 'structure')"));
        assert!(output.contains("getNodeTypesByRealmAndLayer('org', 'instruction')"));
        assert!(output.contains("getNodeTypesByRealmAndLayer('org', 'output')"));
        // v11.4: seo/geo layers removed from org

        // Realm sections (v11.4: 4 shared + 6 org layers)
        assert!(output.contains("SHARED (4 layers)")); // config, locale, geography, knowledge
        assert!(output.contains("ORG (6 layers)")); // config, foundation, structure, semantic, instruction, output

        // Total
        assert!(output.contains("2 Realms (10 layers)")); // v11.4: 10 layers

        // Helper functions
        assert!(output.contains("export function getRealmDefinition"));
        assert!(output.contains("export function getLayerMeta"));
        assert!(output.contains("export function getLayersForRealm"));

        // Spot checks — display_names from YAML
        assert!(output.contains("label: 'Locale'"));
        assert!(output.contains("label: 'Config'")); // v11.4: shared/config layer
        // v11.4: SEO layer removed (nodes moved to shared/knowledge)

        // No v8 terms
        assert!(!output.contains("SCOPE_HIERARCHY"));
        assert!(!output.contains("getNodeTypesBySubcategory"));
    }

    /// Snapshot test for TypeScript hierarchy output.
    /// Run `cargo insta review` to accept changes.
    #[test]
    fn snapshot_hierarchy_typescript() {
        let doc = OrganizingDoc {
            version: "0.12.0".to_string(),
            realms: vec![
                RealmDef {
                    key: "shared".to_string(),
                    display_name: "Shared".to_string(),
                    emoji: "🌍".to_string(),
                    color: "#2aa198".to_string(),
                    llm_context: "Shared across ALL orgs.".to_string(),
                    layers: vec![LayerDef {
                        key: "config".to_string(),
                        display_name: "Configuration".to_string(),
                        emoji: "⚙️".to_string(),
                        color: "#64748b".to_string(),
                        llm_context: "Core configuration nodes.".to_string(),
                    }],
                },
                RealmDef {
                    key: "org".to_string(),
                    display_name: "Org".to_string(),
                    emoji: "🏢".to_string(),
                    color: "#6c71c4".to_string(),
                    llm_context: "Organization-specific content.".to_string(),
                    layers: vec![
                        LayerDef {
                            key: "foundation".to_string(),
                            display_name: "Foundation".to_string(),
                            emoji: "🏛️".to_string(),
                            color: "#b58900".to_string(),
                            llm_context: "Core project identity.".to_string(),
                        },
                        LayerDef {
                            key: "structure".to_string(),
                            display_name: "Structure".to_string(),
                            emoji: "🏗️".to_string(),
                            color: "#268bd2".to_string(),
                            llm_context: "Content structure.".to_string(),
                        },
                    ],
                },
            ],
            traits: vec![TraitDef {
                key: "defined".to_string(),
                display_name: "Defined".to_string(),
                color: "#6366f1".to_string(),
                llm_context: "Does not vary per locale.".to_string(),
            }],
            arc_families: vec![ArcFamilyDef {
                key: "ownership".to_string(),
                display_name: "Ownership".to_string(),
                color: "#22c55e".to_string(),
                arrow_style: "-->".to_string(),
                llm_context: "Containment relationships.".to_string(),
            }],
        };

        let output = render_hierarchy(&doc).unwrap();
        insta::assert_snapshot!(output);
    }
}
