//! Generate `nodeIcons.ts` via MiniJinja template (YAML → TypeScript).
//!
//! Reads all node YAMLs and extracts their dual-format `icon` field.
//! v0.12.5: Updated to support { web: "lucide-name", terminal: "◆" } format.
//!
//! Output target: `apps/studio/src/design/icons/nodeIcons.generated.ts`
//!
//! This is the SINGLE SOURCE OF TRUTH for node icons. Icons are defined
//! in each node's YAML file and generated here for Studio consumption.

use crate::parsers::yaml_node::{self, NodeIcon, ParsedNode};
use minijinja::{Environment, context};
use serde::Serialize;
use std::path::Path;

// ─────────────────────────────────────────────────────────────────────────────
// Template data structures
// ─────────────────────────────────────────────────────────────────────────────

/// Icon entry for template rendering (v0.12.5: dual format).
#[derive(Debug, Serialize)]
struct IconEntry {
    /// NodeType name (PascalCase)
    name: String,
    /// Web icon (Lucide name) for Studio
    web: String,
    /// Terminal icon (Unicode) for TUI
    terminal: String,
}

/// All icon data for the template.
#[derive(Debug, Serialize)]
struct TemplateData {
    version: String,
    node_count: usize,
    icons: Vec<IconEntry>,
}

// ─────────────────────────────────────────────────────────────────────────────
// MiniJinja template
// ─────────────────────────────────────────────────────────────────────────────

const ICONS_TEMPLATE: &str = r##"// apps/studio/src/design/icons/nodeIcons.generated.ts
// Node icons from YAML definitions (SINGLE SOURCE OF TRUTH)
// AUTO-GENERATED by novanet v{{ version }} — DO NOT EDIT
// Run: cargo run -- schema generate

import type { NodeType } from '@novanet/core/types';

// =============================================================================
// NODE ICONS ({{ node_count }} nodes) — DUAL FORMAT
// =============================================================================

/**
 * Icon definition with web (Lucide) and terminal (Unicode) variants.
 */
export interface NodeIcon {
  web: string;      // Lucide icon name for Studio
  terminal: string; // Unicode symbol for TUI
}

/**
 * Dual-format icons for all {{ node_count }} node types.
 *
 * Each icon is defined in the node's YAML file under `node.icon`.
 * Source: packages/core/models/node-classes/<realm>/<layer>/<name>.yaml
 *
 * v0.12.5: Updated to dual format { web, terminal }
 */
export const NODE_ICONS: Record<NodeType, NodeIcon> = {
{%- for entry in icons %}
  {{ entry.name }}: { web: '{{ entry.web }}', terminal: '{{ entry.terminal }}' },
{%- endfor %}
};

/**
 * Get the web (Lucide) icon for a node type.
 *
 * @param type - The NodeType to get icon for
 * @returns The Lucide icon name
 */
export function getNodeWebIcon(type: NodeType): string {
  return NODE_ICONS[type]?.web ?? 'file';
}

/**
 * Get the terminal (Unicode) icon for a node type.
 *
 * @param type - The NodeType to get icon for
 * @returns The Unicode icon string
 */
export function getNodeTerminalIcon(type: NodeType): string {
  return NODE_ICONS[type]?.terminal ?? '◆';
}

/**
 * Default icons for unknown node types.
 */
export const DEFAULT_NODE_ICON: NodeIcon = { web: 'file', terminal: '◆' };
"##;

// ─────────────────────────────────────────────────────────────────────────────
// Generator
// ─────────────────────────────────────────────────────────────────────────────

pub struct IconsGenerator;

impl super::Generator for IconsGenerator {
    fn name(&self) -> &'static str {
        "icons"
    }

    fn generate(&self, root: &Path) -> crate::Result<String> {
        let nodes = yaml_node::load_all_nodes(root)?;
        render_icons(&nodes)
    }
}

/// Build template data from parsed nodes and render.
fn render_icons(nodes: &[ParsedNode]) -> crate::Result<String> {
    let default_icon = NodeIcon::default();

    // Extract icons (use default if missing)
    let icons: Vec<IconEntry> = nodes
        .iter()
        .map(|node| {
            let icon = node.def.icon.as_ref().unwrap_or(&default_icon);
            IconEntry {
                name: node.def.name.clone(),
                web: icon.web().to_string(),
                terminal: icon.terminal().to_string(),
            }
        })
        .collect();

    let data = TemplateData {
        version: "0.13.0".to_string(),
        node_count: icons.len(),
        icons,
    };

    // Render MiniJinja template
    let mut env = Environment::new();
    env.add_template("icons.ts", ICONS_TEMPLATE)
        .map_err(|e| crate::NovaNetError::Generator {
            generator: "icons".to_string(),
            detail: format!("template parse error: {e}"),
        })?;

    let tmpl = env
        .get_template("icons.ts")
        .map_err(|e| crate::NovaNetError::Generator {
            generator: "icons".to_string(),
            detail: format!("template not found: {e}"),
        })?;

    let output = tmpl
        .render(context! {
            version => data.version,
            node_count => data.node_count,
            icons => data.icons,
        })
        .map_err(|e| crate::NovaNetError::Generator {
            generator: "icons".to_string(),
            detail: format!("template render error: {e}"),
        })?;

    Ok(output)
}

// ─────────────────────────────────────────────────────────────────────────────
// Tests
// ─────────────────────────────────────────────────────────────────────────────

#[cfg(test)]
mod tests {
    use super::*;
    use crate::generators::Generator;
    use serial_test::serial;

    #[test]
    #[serial]
    fn generate_icons_integration() {
        let root = std::path::Path::new(env!("CARGO_MANIFEST_DIR"))
            .parent()
            .and_then(|p| p.parent());

        let Some(root) = root else { return };
        if !root.join("pnpm-workspace.yaml").exists() {
            return;
        }

        let generator = IconsGenerator;
        let output = generator.generate(root).expect("should generate icons.ts");

        // Header
        assert!(output.contains("AUTO-GENERATED by novanet v0.13.0"));
        assert!(output.contains("SINGLE SOURCE OF TRUTH"));

        // v0.12.5: 61 nodes with dual format
        assert!(output.contains("NODE ICONS (61 nodes)"));

        // Should have import statement
        assert!(output.contains("import type { NodeType } from '@novanet/core/types'"));

        // v0.12.5: Dual format icons
        assert!(
            output.contains("Project: { web:"),
            "should have Project with dual format"
        );
        assert!(
            output.contains("Locale: { web:"),
            "should have Locale with dual format"
        );
        assert!(
            output.contains("Entity: { web:"),
            "should have Entity with dual format"
        );
        assert!(
            output.contains("PageNative: { web:"),
            "should have PageNative with dual format (v0.13.0 ADR-029)"
        );

        // v0.12.5: Updated helper functions
        assert!(output.contains("export function getNodeWebIcon"));
        assert!(output.contains("export function getNodeTerminalIcon"));
        assert!(output.contains("export const DEFAULT_NODE_ICON: NodeIcon"));
    }

    #[test]
    fn render_icons_basic() {
        use crate::parsers::yaml_node::{NodeDef, NodeTrait, ParsedNode};
        use std::path::PathBuf;

        let nodes = vec![
            ParsedNode {
                def: NodeDef {
                    name: "TestNode".to_string(),
                    realm: "org".to_string(),
                    layer: "foundation".to_string(),
                    node_trait: NodeTrait::Defined,
                    knowledge_tier: None,
                    icon: Some(NodeIcon {
                        web: "rocket".to_string(),
                        terminal: "🚀".to_string(),
                    }),
                    description: "Test".to_string(),
                    standard_properties: None,
                    properties: None,
                    neo4j: None,
                    example: None,
                },
                realm: "org".to_string(),
                layer: "foundation".to_string(),
                source_path: PathBuf::from("test.yaml"),
            },
            ParsedNode {
                def: NodeDef {
                    name: "NoIconNode".to_string(),
                    realm: "shared".to_string(),
                    layer: "config".to_string(),
                    node_trait: NodeTrait::Defined,
                    knowledge_tier: None,
                    icon: None, // No icon - should use default
                    description: "Test".to_string(),
                    standard_properties: None,
                    properties: None,
                    neo4j: None,
                    example: None,
                },
                realm: "shared".to_string(),
                layer: "config".to_string(),
                source_path: PathBuf::from("test2.yaml"),
            },
        ];

        let output = render_icons(&nodes).unwrap();

        // v0.12.5: Dual format icons
        assert!(output.contains("TestNode: { web: 'rocket', terminal: '🚀' }"));
        assert!(output.contains("NoIconNode: { web: 'circle', terminal: '●' }")); // Default icon from NodeIcon::default()

        // Count
        assert!(output.contains("NODE ICONS (2 nodes)"));
    }
}
