//! Generate Kind meta-nodes + schema_hint, context_budget + facet relations.
//!
//! Reads all 44 YAML node definitions and produces idempotent MERGE statements
//! for Kind nodes with auto-computed properties, plus hierarchy and facet rels.
//!
//! Output target: `packages/db/seed/01-kinds.cypher`

use super::cypher_utils::{cypher_list_ref, cypher_str};
use crate::parsers::yaml_node::{self, LocaleBehavior, ParsedNode};
use std::fmt::Write;
use std::path::Path;

// ─────────────────────────────────────────────────────────────────────────────
// Helpers
// ─────────────────────────────────────────────────────────────────────────────

/// Build schema_hint from a ParsedNode's properties.
///
/// Format: `"key, display_name, instructions (req), node_trait"`
/// Required properties get the "(req)" suffix.
fn build_schema_hint(node: &ParsedNode) -> String {
    let mut parts: Vec<String> = Vec::new();

    // Collect standard properties
    if let Some(ref sp) = node.def.standard_properties {
        for (name, def) in sp {
            if def.required == Some(true) {
                parts.push(format!("{name} (req)"));
            } else {
                parts.push(name.clone());
            }
        }
    }

    // Collect business properties
    if let Some(ref p) = node.def.properties {
        for (name, def) in p {
            if def.required == Some(true) {
                parts.push(format!("{name} (req)"));
            } else {
                parts.push(name.clone());
            }
        }
    }

    parts.sort();
    parts.join(", ")
}

/// Determine context_budget based on node_trait trait and layer.
///
/// Rules:
/// - `job` trait → `minimal`
/// - `derived` trait → `low`
/// - `knowledge` trait → `medium`
/// - `instruction` or `config` layer → `medium`
/// - Everything else → `high`
fn context_budget(node: &ParsedNode) -> &'static str {
    match node.def.node_trait {
        LocaleBehavior::Job => "minimal",
        LocaleBehavior::Derived => "low",
        LocaleBehavior::Knowledge => "medium",
        LocaleBehavior::Invariant | LocaleBehavior::Localized => match node.layer.as_str() {
            "instruction" | "config" => "medium",
            _ => "high",
        },
    }
}

/// Compute the YAML path relative to models directory.
fn yaml_path(node: &ParsedNode) -> String {
    let filename = node
        .source_path
        .file_name()
        .map(|f| f.to_string_lossy().to_string())
        .unwrap_or_default();
    format!("node-kinds/{}/{}/{}", node.realm, node.layer, filename)
}

/// Collect all property names (standard + business), sorted.
fn all_properties(node: &ParsedNode) -> Vec<&str> {
    node.all_property_names().to_vec()
}

/// Collect required property names, sorted.
fn required_properties(node: &ParsedNode) -> Vec<&str> {
    let mut names: Vec<&str> = Vec::new();
    if let Some(ref sp) = node.def.standard_properties {
        for (name, def) in sp {
            if def.required == Some(true) {
                names.push(name.as_str());
            }
        }
    }
    if let Some(ref p) = node.def.properties {
        for (name, def) in p {
            if def.required == Some(true) {
                names.push(name.as_str());
            }
        }
    }
    names.sort();
    names
}

// ─────────────────────────────────────────────────────────────────────────────
// Generator
// ─────────────────────────────────────────────────────────────────────────────

pub struct KindGenerator;

impl super::Generator for KindGenerator {
    fn name(&self) -> &'static str {
        "kinds"
    }

    fn generate(&self, root: &Path) -> crate::Result<String> {
        let nodes = yaml_node::load_all_nodes(root)?;
        generate_kind_cypher(&nodes)
    }
}

fn generate_kind_cypher(nodes: &[ParsedNode]) -> crate::Result<String> {
    let mut out = String::with_capacity(32 * 1024);

    // Header
    writeln!(
        out,
        "// ═══════════════════════════════════════════════════════════════════════════════"
    )
    .unwrap();
    writeln!(out, "// Kind Meta-Nodes — v9.0.0").unwrap();
    writeln!(out, "// AUTO-GENERATED by novanet — DO NOT EDIT").unwrap();
    writeln!(
        out,
        "// {count} Kind nodes + hierarchy + facet relations",
        count = nodes.len()
    )
    .unwrap();
    writeln!(
        out,
        "// ═══════════════════════════════════════════════════════════════════════════════"
    )
    .unwrap();
    writeln!(out).unwrap();

    // ── Section 1: Kind nodes ────────────────────────────────────────────────
    write_section_header(&mut out, "Kind Nodes", nodes.len());
    writeln!(out).unwrap();

    for node in nodes {
        let label = &node.def.name;
        let var = format!("k_{label}");
        let display = cypher_str(&node.def.name);
        let llm = cypher_str(&node.def.description);
        let ypath = cypher_str(&yaml_path(node));
        let props = all_properties(node);
        let req_props = required_properties(node);
        let hint = cypher_str(&build_schema_hint(node));
        let budget = context_budget(node);

        writeln!(out, "MERGE ({var}:Meta:Kind {{label: '{label}'}})").unwrap();
        writeln!(out, "ON CREATE SET").unwrap();
        writeln!(out, "  {var}.display_name = '{display}',").unwrap();
        writeln!(out, "  {var}.llm_context = '{llm}',").unwrap();
        writeln!(out, "  {var}.yaml_path = '{ypath}',").unwrap();
        writeln!(
            out,
            "  {var}.properties = {props},",
            props = cypher_list_ref(&props)
        )
        .unwrap();
        writeln!(
            out,
            "  {var}.required_properties = {req_props},",
            req_props = cypher_list_ref(&req_props)
        )
        .unwrap();
        writeln!(out, "  {var}.schema_hint = '{hint}',").unwrap();
        writeln!(out, "  {var}.context_budget = '{budget}',").unwrap();
        writeln!(out, "  {var}.generation_count = 0,").unwrap();
        writeln!(out, "  {var}.created_at = datetime()").unwrap();
        writeln!(out, "ON MATCH SET").unwrap();
        writeln!(out, "  {var}.display_name = '{display}',").unwrap();
        writeln!(out, "  {var}.llm_context = '{llm}',").unwrap();
        writeln!(out, "  {var}.yaml_path = '{ypath}',").unwrap();
        writeln!(
            out,
            "  {var}.properties = {props},",
            props = cypher_list_ref(&props)
        )
        .unwrap();
        writeln!(
            out,
            "  {var}.required_properties = {req_props},",
            req_props = cypher_list_ref(&req_props)
        )
        .unwrap();
        writeln!(out, "  {var}.schema_hint = '{hint}',").unwrap();
        writeln!(out, "  {var}.context_budget = '{budget}',").unwrap();
        writeln!(out, "  {var}.generation_count = 0,").unwrap();
        writeln!(out, "  {var}.updated_at = datetime();").unwrap();
        writeln!(out).unwrap();
    }

    // ── Section 2: HAS_KIND (Layer → Kind) ──────────────────────────────────
    write_section_header(
        &mut out,
        "Hierarchy: Layer -[:HAS_KIND]-> Kind",
        nodes.len(),
    );
    writeln!(out).unwrap();

    for node in nodes {
        writeln!(
            out,
            "MATCH (l:Layer {{key: '{layer}'}}), (k:Kind {{label: '{label}'}})",
            layer = node.layer,
            label = node.def.name
        )
        .unwrap();
        writeln!(out, "MERGE (l)-[:HAS_KIND]->(k);").unwrap();
        writeln!(out).unwrap();
    }

    // ── Section 3: IN_REALM (Kind → Realm) ──────────────────────────────────
    write_section_header(&mut out, "Facet: Kind -[:IN_REALM]-> Realm", nodes.len());
    writeln!(out).unwrap();

    for node in nodes {
        writeln!(
            out,
            "MATCH (k:Kind {{label: '{label}'}}), (r:Realm {{key: '{realm}'}})",
            label = node.def.name,
            realm = node.realm
        )
        .unwrap();
        writeln!(out, "MERGE (k)-[:IN_REALM]->(r);").unwrap();
        writeln!(out).unwrap();
    }

    // ── Section 4: IN_LAYER (Kind → Layer) ──────────────────────────────────
    write_section_header(&mut out, "Facet: Kind -[:IN_LAYER]-> Layer", nodes.len());
    writeln!(out).unwrap();

    for node in nodes {
        writeln!(
            out,
            "MATCH (k:Kind {{label: '{label}'}}), (l:Layer {{key: '{layer}'}})",
            label = node.def.name,
            layer = node.layer
        )
        .unwrap();
        writeln!(out, "MERGE (k)-[:IN_LAYER]->(l);").unwrap();
        writeln!(out).unwrap();
    }

    // ── Section 5: EXHIBITS (Kind → Trait) ──────────────────────────────────
    write_section_header(&mut out, "Facet: Kind -[:EXHIBITS]-> Trait", nodes.len());
    writeln!(out).unwrap();

    for node in nodes {
        writeln!(
            out,
            "MATCH (k:Kind {{label: '{label}'}}), (t:Trait {{key: '{trait_key}'}})",
            label = node.def.name,
            trait_key = node.def.node_trait
        )
        .unwrap();
        writeln!(out, "MERGE (k)-[:EXHIBITS]->(t);").unwrap();
        writeln!(out).unwrap();
    }

    Ok(out)
}

/// Write a visual section header comment.
fn write_section_header(out: &mut String, title: &str, count: usize) {
    let bar = "// ═══════════════════════════════════════════════════════════════════════════════";
    writeln!(out, "{bar}").unwrap();
    writeln!(out, "// {title} ({count})").unwrap();
    writeln!(out, "{bar}").unwrap();
}

// ─────────────────────────────────────────────────────────────────────────────
// Tests
// ─────────────────────────────────────────────────────────────────────────────

#[cfg(test)]
mod tests {
    use super::*;
    use crate::generators::Generator;
    use crate::parsers::yaml_node::{NodeDef, PropertyDef};
    use std::collections::BTreeMap;

    /// Build a minimal ParsedNode for testing.
    fn make_node(name: &str, realm: &str, layer: &str, behavior: LocaleBehavior) -> ParsedNode {
        ParsedNode {
            def: NodeDef {
                name: name.to_string(),
                realm: realm.to_string(),
                layer: layer.to_string(),
                node_trait: behavior,
                icon: None,
                description: format!("{name} description."),
                standard_properties: None,
                properties: None,
                relations: None,
                incoming_relations: None,
                neo4j: None,
                example: None,
            },
            realm: realm.to_string(),
            layer: layer.to_string(),
            source_path: std::path::PathBuf::from(format!(
                "models/node-kinds/{realm}/{layer}/{}.yaml",
                name.to_lowercase()
            )),
        }
    }

    fn make_node_with_props(
        name: &str,
        realm: &str,
        layer: &str,
        behavior: LocaleBehavior,
        props: Vec<(&str, &str, bool)>, // (name, type, required)
    ) -> ParsedNode {
        let mut properties = BTreeMap::new();
        for (pname, ptype, req) in props {
            properties.insert(
                pname.to_string(),
                PropertyDef {
                    prop_type: ptype.to_string(),
                    required: Some(req),
                    description: None,
                    extra: BTreeMap::new(),
                },
            );
        }

        let mut node = make_node(name, realm, layer, behavior);
        node.def.properties = Some(properties);
        node
    }

    #[test]
    fn schema_hint_no_properties() {
        let node = make_node("Test", "project", "foundation", LocaleBehavior::Invariant);
        assert_eq!(build_schema_hint(&node), "");
    }

    #[test]
    fn schema_hint_with_properties() {
        let node = make_node_with_props(
            "Page",
            "project",
            "structure",
            LocaleBehavior::Invariant,
            vec![
                ("key", "string", true),
                ("display_name", "string", true),
                ("instructions", "string", false),
            ],
        );
        let hint = build_schema_hint(&node);
        assert_eq!(hint, "display_name (req), instructions, key (req)");
    }

    #[test]
    fn context_budget_by_trait() {
        assert_eq!(
            context_budget(&make_node("Run", "shared", "seo", LocaleBehavior::Job)),
            "minimal"
        );
        assert_eq!(
            context_budget(&make_node(
                "Metrics",
                "shared",
                "seo",
                LocaleBehavior::Derived
            )),
            "low"
        );
        assert_eq!(
            context_budget(&make_node(
                "Voice",
                "global",
                "knowledge",
                LocaleBehavior::Knowledge
            )),
            "medium"
        );
    }

    #[test]
    fn context_budget_by_layer() {
        // instruction layer → medium (even with invariant trait)
        assert_eq!(
            context_budget(&make_node(
                "PageType",
                "project",
                "instruction",
                LocaleBehavior::Invariant
            )),
            "medium"
        );
        // config layer → medium
        assert_eq!(
            context_budget(&make_node(
                "Locale",
                "global",
                "config",
                LocaleBehavior::Invariant
            )),
            "medium"
        );
        // structure layer + invariant → high
        assert_eq!(
            context_budget(&make_node(
                "Page",
                "project",
                "structure",
                LocaleBehavior::Invariant
            )),
            "high"
        );
        // output layer + localized → high
        assert_eq!(
            context_budget(&make_node(
                "PageL10n",
                "project",
                "output",
                LocaleBehavior::Localized
            )),
            "high"
        );
    }

    #[test]
    fn generate_small_kind_cypher() {
        let nodes = vec![
            make_node_with_props(
                "Page",
                "project",
                "structure",
                LocaleBehavior::Invariant,
                vec![("key", "string", true), ("display_name", "string", true)],
            ),
            make_node("Locale", "global", "config", LocaleBehavior::Invariant),
        ];

        let cypher = generate_kind_cypher(&nodes).unwrap();

        // Header
        assert!(cypher.contains("v9.0.0"));
        assert!(cypher.contains("AUTO-GENERATED"));
        assert!(cypher.contains("2 Kind nodes"));

        // Kind node for Page
        assert!(cypher.contains("MERGE (k_Page:Meta:Kind {label: 'Page'})"));
        assert!(cypher.contains("k_Page.display_name = 'Page'"));
        assert!(cypher.contains("k_Page.context_budget = 'high'"));
        assert!(cypher.contains("k_Page.generation_count = 0"));
        assert!(cypher.contains("k_Page.schema_hint = 'display_name (req), key (req)'"));
        assert!(cypher.contains("k_Page.properties = ['display_name', 'key']"));
        assert!(cypher.contains("k_Page.required_properties = ['display_name', 'key']"));
        assert!(cypher.contains("k_Page.yaml_path = 'node-kinds/project/structure/page.yaml'"));

        // Kind node for Locale
        assert!(cypher.contains("MERGE (k_Locale:Meta:Kind {label: 'Locale'})"));
        assert!(cypher.contains("k_Locale.context_budget = 'medium'"));

        // HAS_KIND hierarchy
        assert!(cypher.contains("(l:Layer {key: 'structure'}), (k:Kind {label: 'Page'})"));
        assert!(cypher.contains("MERGE (l)-[:HAS_KIND]->(k)"));

        // IN_REALM facet
        assert!(cypher.contains("(k:Kind {label: 'Page'}), (r:Realm {key: 'project'})"));
        assert!(cypher.contains("MERGE (k)-[:IN_REALM]->(r)"));

        // IN_LAYER facet
        assert!(cypher.contains("(k:Kind {label: 'Page'}), (l:Layer {key: 'structure'})"));
        assert!(cypher.contains("MERGE (k)-[:IN_LAYER]->(l)"));

        // EXHIBITS facet
        assert!(cypher.contains("(k:Kind {label: 'Page'}), (t:Trait {key: 'invariant'})"));
        assert!(cypher.contains("MERGE (k)-[:EXHIBITS]->(t)"));
        assert!(cypher.contains("(k:Kind {label: 'Locale'}), (t:Trait {key: 'invariant'})"));

        // Section headers
        assert!(cypher.contains("Hierarchy: Layer -[:HAS_KIND]-> Kind"));
        assert!(cypher.contains("Facet: Kind -[:IN_REALM]-> Realm"));
        assert!(cypher.contains("Facet: Kind -[:IN_LAYER]-> Layer"));
        assert!(cypher.contains("Facet: Kind -[:EXHIBITS]-> Trait"));

        // Timestamps
        assert!(cypher.contains("created_at = datetime()"));
        assert!(cypher.contains("updated_at = datetime()"));
    }

    #[test]
    fn generate_kind_integration() {
        let root = std::path::Path::new(env!("CARGO_MANIFEST_DIR"))
            .parent()
            .and_then(|p| p.parent());

        let Some(root) = root else { return };
        if !root.join("pnpm-workspace.yaml").exists() {
            return;
        }

        let generator = KindGenerator;
        let cypher = generator
            .generate(root)
            .expect("should generate kind cypher");

        // 44 Kind MERGE statements
        let kind_merges = cypher
            .lines()
            .filter(|l: &&str| l.contains("MERGE") && l.contains(":Meta:Kind"))
            .count();
        assert_eq!(kind_merges, 44, "expected 44 Kind MERGE statements");

        // 44 HAS_KIND relationships
        let has_kind = cypher
            .lines()
            .filter(|l: &&str| l.contains("MERGE") && l.contains("[:HAS_KIND]"))
            .count();
        assert_eq!(has_kind, 44, "expected 44 HAS_KIND relationships");

        // 44 IN_REALM relationships
        let in_realm = cypher
            .lines()
            .filter(|l: &&str| l.contains("MERGE") && l.contains("[:IN_REALM]"))
            .count();
        assert_eq!(in_realm, 44, "expected 44 IN_REALM relationships");

        // 44 IN_LAYER relationships
        let in_layer = cypher
            .lines()
            .filter(|l: &&str| l.contains("MERGE") && l.contains("[:IN_LAYER]"))
            .count();
        assert_eq!(in_layer, 44, "expected 44 IN_LAYER relationships");

        // 44 EXHIBITS relationships
        let exhibits = cypher
            .lines()
            .filter(|l: &&str| l.contains("MERGE") && l.contains("[:EXHIBITS]"))
            .count();
        assert_eq!(exhibits, 44, "expected 44 EXHIBITS relationships");

        // Spot checks — specific Kinds
        assert!(cypher.contains("k_Project:Meta:Kind {label: 'Project'}"));
        assert!(cypher.contains("k_Page:Meta:Kind {label: 'Page'}"));
        assert!(cypher.contains("k_LocaleVoice:Meta:Kind {label: 'LocaleVoice'}"));
        assert!(cypher.contains("k_SEOKeywordL10n:Meta:Kind {label: 'SEOKeywordL10n'}"));

        // Spot check — context_budget assignments
        assert!(cypher.contains("k_Page.context_budget = 'high'"));
        assert!(cypher.contains("k_BlockType.context_budget = 'medium'"));
        assert!(cypher.contains("k_LocaleVoice.context_budget = 'medium'"));
        assert!(cypher.contains("k_Locale.context_budget = 'medium'"));

        // Spot check — facet wiring
        assert!(cypher.contains("(k:Kind {label: 'Page'}), (r:Realm {key: 'project'})"));
        assert!(cypher.contains("(k:Kind {label: 'LocaleVoice'}), (t:Trait {key: 'knowledge'})"));
        assert!(cypher.contains("(k:Kind {label: 'SEOMiningRun'}), (t:Trait {key: 'job'})"));

        // All context_budget values are valid
        for line in cypher.lines() {
            if line.contains("context_budget") && line.contains('=') {
                assert!(
                    line.contains("'high'")
                        || line.contains("'medium'")
                        || line.contains("'low'")
                        || line.contains("'minimal'"),
                    "invalid context_budget: {line}"
                );
            }
        }

        // Header mentions 44 Kind nodes
        assert!(cypher.contains("44 Kind nodes"));
    }
}
