//! Generate `layers.ts` via MiniJinja template (YAML → TypeScript).
//!
//! Reads all 61 YAML node definitions (v0.12.5 / ADR-028), groups by realm and layer,
//! and produces `packages/core/src/graph/layers.ts`.
//! Replaces `SubcategoryGenerator.ts` from @novanet/schema-tools.
//!
//! Output target: `packages/core/src/graph/layers.ts`

use crate::parsers::yaml_node;
use minijinja::{Environment, context};
use serde::Serialize;
use std::collections::{BTreeMap, HashSet};
use std::path::Path;

// ─────────────────────────────────────────────────────────────────────────────
// Template data structures
// ─────────────────────────────────────────────────────────────────────────────

/// A realm group for the template (project, shared, shared).
#[derive(Debug, Serialize)]
struct TemplateRealm {
    key: String,
    /// Title case for JSDoc comments (e.g. "Project").
    label: String,
    /// Uppercase for section headers (e.g. "PROJECT").
    label_upper: String,
    node_count: usize,
    layers: Vec<TemplateLayer>,
}

/// A layer group within a realm.
#[derive(Debug, Serialize)]
struct TemplateLayer {
    key: String,
    nodes: Vec<String>,
    node_count: usize,
    realm_key: String,
}

// ─────────────────────────────────────────────────────────────────────────────
// Realm ordering
// ─────────────────────────────────────────────────────────────────────────────

/// Fixed realm order matching taxonomy.yaml (v11.2: 2 realms - shared + org).
const REALM_ORDER: &[&str] = &["shared", "org"];

// ─────────────────────────────────────────────────────────────────────────────
// MiniJinja template
// ─────────────────────────────────────────────────────────────────────────────

const LAYERS_TEMPLATE: &str = r##"// packages/core/src/graph/layers.ts
// NODE_LAYERS mapping all {{ total_nodes }} node types to their layers
// AUTO-GENERATED by novanet v{{ version }} — DO NOT EDIT
// Run: novanet schema generate

import type { NodeType, Realm } from '../types/nodes.js';
import type { Layer } from './types.js';
import { CLASS_TAXONOMY } from '../types/nodes.js';

// =============================================================================
// NODE_LAYERS - Maps each NodeType to its layer
// =============================================================================

/**
 * Maps each NodeType to its layer within its realm.
 * AUTO-GENERATED from models/node-classes/ folder structure.
 *
 * Layers by realm:
{%- for realm in realms %}
 * - {{ realm.label }}: {{ realm.layers | map(attribute="key") | join(", ") }}
{%- endfor %}
 */
export const NODE_LAYERS: Record<NodeType, Layer> = {
{%- for realm in realms %}
  // ═══════════════════════════════════════════════════════════════════════════
  // {{ realm.label_upper }} REALM ({{ realm.node_count }} node{{ "s" if realm.node_count != 1 else "" }})
  // ═══════════════════════════════════════════════════════════════════════════
{% for layer in realm.layers %}
  // {{ layer.key }} ({{ layer.node_count }} node{{ "s" if layer.node_count != 1 else "" }}) - matches models/node-classes/{{ layer.realm_key }}/{{ layer.key }}/
{%- for node in layer.nodes %}
  {{ node }}: '{{ layer.key }}',
{%- endfor %}
{% endfor %}
{%- endfor %}
};

// =============================================================================
// HELPER FUNCTIONS
// =============================================================================

/**
 * Get the layer for a node type
 * @param nodeType - The node type to look up
 * @returns The layer for the node type
 */
export function getLayer(nodeType: NodeType): Layer {
  return NODE_LAYERS[nodeType];
}

/**
 * Get all node types in a layer
 * @param layer - The layer to look up
 * @returns Array of node types belonging to the layer
 */
export function getNodeTypesByLayer(layer: Layer): NodeType[] {
  return (Object.entries(NODE_LAYERS) as [NodeType, Layer][])
    .filter(([, l]) => l === layer)
    .map(([nodeType]) => nodeType);
}

/**
 * Get all node types in a specific realm AND layer
 * @param realm - The realm to filter by
 * @param layer - The layer to filter by
 * @returns Array of node types belonging to both the realm and layer
 */
export function getNodeTypesByRealmAndLayer(realm: Realm, layer: Layer): NodeType[] {
  return (Object.entries(CLASS_TAXONOMY) as [NodeType, { realm: Realm; layer: Layer }][])
    .filter(([, meta]) => meta.realm === realm && meta.layer === layer)
    .map(([nodeType]) => nodeType);
}
"##;

// ─────────────────────────────────────────────────────────────────────────────
// Generator
// ─────────────────────────────────────────────────────────────────────────────

pub struct LayerGenerator;

impl super::Generator for LayerGenerator {
    fn name(&self) -> &'static str {
        "layers"
    }

    fn generate(&self, root: &Path) -> crate::Result<String> {
        let nodes = yaml_node::load_all_nodes(root)?;
        render_layers(&nodes)
    }
}

/// Group parsed nodes by realm → layer → sorted node names, then render template.
/// De-duplicates nodes that appear in multiple realms (e.g., Entity in both org and project).
fn render_layers(nodes: &[yaml_node::ParsedNode]) -> crate::Result<String> {
    // Build realm → layer → [node_name] map
    let mut realm_map: BTreeMap<String, BTreeMap<String, Vec<String>>> = BTreeMap::new();

    // Track seen node names to de-duplicate (v10.5: Entity exists in both org and project)
    let mut seen_names: HashSet<String> = HashSet::new();

    // Process in realm order to ensure consistent deduplication (shared first)
    for &realm_key in REALM_ORDER {
        for node in nodes.iter().filter(|n| n.realm == realm_key) {
            // Skip if we've already seen this node name in another realm
            if seen_names.contains(&node.def.name) {
                continue;
            }
            seen_names.insert(node.def.name.clone());

            realm_map
                .entry(node.realm.clone())
                .or_default()
                .entry(node.layer.clone())
                .or_default()
                .push(node.def.name.clone());
        }
    }

    // Sort node names within each layer
    for layers in realm_map.values_mut() {
        for node_names in layers.values_mut() {
            node_names.sort();
        }
    }

    // Build template data in fixed realm order
    let mut realms: Vec<TemplateRealm> = Vec::new();

    for &realm_key in REALM_ORDER {
        let Some(layers_map) = realm_map.get(realm_key) else {
            return Err(crate::NovaNetError::Validation(format!(
                "realm '{realm_key}' has no nodes — expected nodes under models/node-classes/{realm_key}/"
            )));
        };

        let mut layers: Vec<TemplateLayer> = layers_map
            .iter()
            .map(|(layer_key, node_names)| TemplateLayer {
                key: layer_key.clone(),
                nodes: node_names.clone(),
                node_count: node_names.len(),
                realm_key: realm_key.to_string(),
            })
            .collect();

        // Sort layers alphabetically within realm
        layers.sort_by(|a, b| a.key.cmp(&b.key));

        let node_count: usize = layers.iter().map(|l| l.node_count).sum();

        realms.push(TemplateRealm {
            key: realm_key.to_string(),
            label: {
                let mut c = realm_key.chars();
                match c.next() {
                    None => String::new(),
                    Some(f) => f.to_uppercase().to_string() + c.as_str(),
                }
            },
            label_upper: realm_key.to_uppercase(),
            node_count,
            layers,
        });
    }

    let total_nodes: usize = realms.iter().map(|r| r.node_count).sum();

    // Render MiniJinja template
    let mut env = Environment::new();
    env.add_template("layers.ts", LAYERS_TEMPLATE)
        .map_err(|e| crate::NovaNetError::Generator {
            generator: "layers".to_string(),
            detail: format!("template parse error: {e}"),
        })?;

    let tmpl = env
        .get_template("layers.ts")
        .map_err(|e| crate::NovaNetError::Generator {
            generator: "layers".to_string(),
            detail: format!("template not found: {e}"),
        })?;

    let output = tmpl
        .render(context! {
            version => "0.13.0",
            total_nodes => total_nodes,
            realms => realms,
        })
        .map_err(|e| crate::NovaNetError::Generator {
            generator: "layers".to_string(),
            detail: format!("template render error: {e}"),
        })?;

    Ok(output)
}

// ─────────────────────────────────────────────────────────────────────────────
// Tests
// ─────────────────────────────────────────────────────────────────────────────

#[cfg(test)]
mod tests {
    use super::*;
    use crate::generators::Generator;
    use crate::generators::test_utils::make_node_simple as make_node;
    use serial_test::serial;

    #[test]
    fn render_small_layers() {
        // v11.3: Updated test data with new layer structure
        let nodes = vec![
            make_node("Project", "org", "foundation"),
            make_node("Page", "org", "structure"),
            make_node("Block", "org", "structure"),
            make_node("Locale", "shared", "locale"), // v11.3: locale layer
            make_node("Continent", "shared", "geography"), // v11.3: geography layer
            make_node("Term", "shared", "knowledge"), // v11.3: knowledge layer
            make_node("OrgConfig", "org", "config"), // v11.3: OrgConfig (merged)
        ];

        let output = render_layers(&nodes).unwrap();

        // Header
        assert!(output.contains("AUTO-GENERATED by novanet v0.13.0"));
        assert!(output.contains("mapping all 7 node types"));

        // Imports
        assert!(output.contains("import type { NodeType, Realm } from '../types/nodes.js';"));
        assert!(output.contains("import type { Layer } from './types.js';"));
        assert!(output.contains("import { CLASS_TAXONOMY } from '../types/nodes.js';"));

        // NODE_LAYERS declaration
        assert!(output.contains("export const NODE_LAYERS: Record<NodeType, Layer>"));

        // Realm headers (test fixture has 7 nodes: 3 shared + 4 org)
        assert!(output.contains("SHARED REALM (3 nodes)"));
        assert!(output.contains("ORG REALM (4 nodes)"));

        // Layer groups with node counts
        assert!(output.contains("// foundation (1 node)"));
        assert!(output.contains("// structure (2 nodes)"));
        assert!(output.contains("// locale (1 node)")); // v11.3
        assert!(output.contains("// geography (1 node)")); // v11.3
        assert!(output.contains("// knowledge (1 node)")); // v11.3

        // Node mappings
        assert!(output.contains("Project: 'foundation',"));
        assert!(output.contains("Block: 'structure',"));
        assert!(output.contains("Page: 'structure',"));
        assert!(output.contains("Locale: 'locale',")); // v11.3
        assert!(output.contains("Continent: 'geography',")); // v11.3
        assert!(output.contains("Term: 'knowledge',")); // v11.3
        assert!(output.contains("OrgConfig: 'config',")); // v11.3

        // Nodes sorted alphabetically within layers
        let block_pos = output.find("Block: 'structure',").unwrap();
        let page_pos = output.find("Page: 'structure',").unwrap();
        assert!(block_pos < page_pos, "Block should come before Page");

        // Realm order: shared, org (v10.6)
        let shared_pos = output.find("SHARED REALM").unwrap();
        let org_pos = output.find("ORG REALM").unwrap();
        assert!(shared_pos < org_pos);

        // Helper functions
        assert!(output.contains("export function getLayer(nodeType: NodeType): Layer"));
        assert!(output.contains("export function getNodeTypesByLayer(layer: Layer): NodeType[]"));
        assert!(output.contains(
            "export function getNodeTypesByRealmAndLayer(realm: Realm, layer: Layer): NodeType[]"
        ));
    }

    #[test]
    fn render_layers_sorted_within_layer() {
        let nodes = vec![
            make_node("Zebra", "org", "foundation"),
            make_node("Alpha", "org", "foundation"),
            make_node("Middle", "org", "foundation"),
            make_node("Locale", "shared", "config"),
        ];

        let output = render_layers(&nodes).unwrap();

        // Nodes within foundation layer should be sorted
        let alpha_pos = output.find("Alpha: 'foundation',").unwrap();
        let middle_pos = output.find("Middle: 'foundation',").unwrap();
        let zebra_pos = output.find("Zebra: 'foundation',").unwrap();
        assert!(alpha_pos < middle_pos);
        assert!(middle_pos < zebra_pos);
    }

    #[test]
    fn render_layers_missing_realm_fails() {
        // Only shared — missing org (v10.6)
        let nodes = vec![make_node("Locale", "shared", "config")];

        let result = render_layers(&nodes);
        assert!(result.is_err());
        let err = result.unwrap_err().to_string();
        assert!(
            err.contains("org"),
            "error should mention missing realm: {err}"
        );
    }

    #[test]
    fn render_layers_folder_path_in_comment() {
        let nodes = vec![
            make_node("Project", "org", "foundation"),
            make_node("Locale", "shared", "config"),
        ];

        let output = render_layers(&nodes).unwrap();

        // Comments should include the YAML folder path
        assert!(output.contains("models/node-classes/org/foundation/"));
        assert!(output.contains("models/node-classes/shared/config/"));
    }

    #[test]
    fn render_layers_doc_comment_lists_layers_by_realm() {
        let nodes = vec![
            make_node("Project", "org", "foundation"),
            make_node("Page", "org", "structure"),
            make_node("Locale", "shared", "config"),
        ];

        let output = render_layers(&nodes).unwrap();

        // JSDoc comment should list layers per realm (v10.6: 2 realms)
        assert!(output.contains("* - Shared: config"));
        assert!(output.contains("* - Org: foundation, structure"));
    }

    #[test]
    #[serial]
    fn generate_layers_integration() {
        let root = std::path::Path::new(env!("CARGO_MANIFEST_DIR"))
            .parent()
            .and_then(|p| p.parent());

        let Some(root) = root else { return };
        if !root.join("pnpm-workspace.yaml").exists() {
            return;
        }

        let generator = LayerGenerator;
        let output = generator.generate(root).expect("should generate layers.ts");

        // v0.12.5 + Brand Architecture: 61 nodes (40 shared + 21 org)
        assert!(
            output.contains("mapping all 61 node types"),
            "should mention 61 node types"
        );

        // v0.12.5 + Brand Architecture: Realm node counts
        assert!(output.contains("SHARED REALM (40 nodes)")); // config (3) + locale (6) + geography (7) + knowledge (24)
        assert!(output.contains("ORG REALM (21 nodes)")); // Brand Architecture: foundation (6)

        // 9 unique layer names (v11.5: 4 shared + 6 org = 10 total, config in both)
        for layer in [
            "config",
            "locale",
            "geography",
            "knowledge",
            "foundation",
            "structure",
            "semantic",
            "instruction",
            "output",
        ] {
            assert!(
                output.contains(&format!("'{layer}'")),
                "missing layer: {layer}"
            );
        }
        // v11.4: seo/geo layers removed

        // Spot-check specific node → layer mappings (v11.3)
        assert!(output.contains("Project: 'foundation',"));
        assert!(output.contains("Page: 'structure',"));
        assert!(output.contains("Block: 'structure',"));
        assert!(output.contains("Entity: 'semantic',"));
        assert!(output.contains("PageNative: 'output',")); // v0.13.0 ADR-029: renamed from PageGenerated
        assert!(output.contains("Locale: 'config',")); // v11.5: moved to shared/config
        assert!(output.contains("Style: 'locale',")); // v11.3: moved to locale layer
        assert!(output.contains("SEOKeyword: 'knowledge',")); // v11.4: moved to shared/knowledge

        // Helper functions present
        assert!(output.contains("export function getLayer"));
        assert!(output.contains("export function getNodeTypesByLayer"));
        assert!(output.contains("export function getNodeTypesByRealmAndLayer"));

        // Valid TypeScript structure
        assert!(output.contains("export const NODE_LAYERS: Record<NodeType, Layer>"));
        assert!(output.contains("import type { NodeType, Realm }"));
        assert!(output.contains("import type { Layer }"));
        assert!(output.contains("import { CLASS_TAXONOMY }"));
    }

    /// Snapshot test for TypeScript layer mapping output.
    /// Run `cargo insta review` to accept changes.
    #[test]
    fn snapshot_layers_typescript() {
        // v11.3: Updated test data with new layer structure
        let nodes = vec![
            // Shared realm - 3 layers (locale, geography, knowledge)
            make_node("Locale", "shared", "locale"),
            make_node("Style", "shared", "locale"),
            make_node("Continent", "shared", "geography"),
            make_node("Term", "shared", "knowledge"),
            make_node("Expression", "shared", "knowledge"),
            // Org realm (v11.4: 6 layers, no seo/geo)
            make_node("OrgConfig", "org", "config"),
            make_node("Entity", "org", "semantic"),
            make_node("Project", "org", "foundation"),
            make_node("Page", "org", "structure"),
            make_node("Block", "org", "structure"),
            // v0.12.5: PageInstruction deleted, use BlockInstruction instead
            make_node("BlockInstruction", "org", "instruction"),
            make_node("PageNative", "org", "output"),
        ];

        let output = render_layers(&nodes).unwrap();
        insta::assert_snapshot!(output);
    }
}
