//! Generate `layers.ts` via MiniJinja template (YAML → TypeScript).
//!
//! Reads all 35 YAML node definitions, groups by realm and layer,
//! and produces `packages/core/src/graph/layers.ts`.
//! Replaces `SubcategoryGenerator.ts` from @novanet/schema-tools.
//!
//! Output target: `packages/core/src/graph/layers.ts`

use crate::parsers::yaml_node;
use minijinja::{Environment, context};
use serde::Serialize;
use std::collections::BTreeMap;
use std::path::Path;

// ─────────────────────────────────────────────────────────────────────────────
// Template data structures
// ─────────────────────────────────────────────────────────────────────────────

/// A realm group for the template (project, global, shared).
#[derive(Debug, Serialize)]
struct TemplateRealm {
    key: String,
    /// Title case for JSDoc comments (e.g. "Project").
    label: String,
    /// Uppercase for section headers (e.g. "PROJECT").
    label_upper: String,
    node_count: usize,
    layers: Vec<TemplateLayer>,
}

/// A layer group within a realm.
#[derive(Debug, Serialize)]
struct TemplateLayer {
    key: String,
    nodes: Vec<String>,
    node_count: usize,
    realm_key: String,
}

// ─────────────────────────────────────────────────────────────────────────────
// Realm ordering
// ─────────────────────────────────────────────────────────────────────────────

/// Fixed realm order matching the existing subcategories.ts output.
const REALM_ORDER: &[&str] = &["project", "global", "shared"];

// ─────────────────────────────────────────────────────────────────────────────
// MiniJinja template
// ─────────────────────────────────────────────────────────────────────────────

const LAYERS_TEMPLATE: &str = r##"// packages/core/src/graph/layers.ts
// NODE_LAYERS mapping all {{ total_nodes }} node types to their layers
// AUTO-GENERATED by novanet v{{ version }} — DO NOT EDIT
// Run: novanet schema generate

import type { NodeType } from '../types/nodes.js';
import type { Layer } from './types.js';

// =============================================================================
// NODE_LAYERS - Maps each NodeType to its layer
// =============================================================================

/**
 * Maps each NodeType to its layer within its realm.
 * AUTO-GENERATED from models/nodes/ folder structure.
 *
 * Layers by realm:
{%- for realm in realms %}
 * - {{ realm.label }}: {{ realm.layers | map(attribute="key") | join(", ") }}
{%- endfor %}
 */
export const NODE_LAYERS: Record<NodeType, Layer> = {
{%- for realm in realms %}
  // ═══════════════════════════════════════════════════════════════════════════
  // {{ realm.label_upper }} REALM ({{ realm.node_count }} nodes)
  // ═══════════════════════════════════════════════════════════════════════════
{% for layer in realm.layers %}
  // {{ layer.key }} ({{ layer.node_count }} node{{ "s" if layer.node_count != 1 else "" }}) - matches models/nodes/{{ layer.realm_key }}/{{ layer.key }}/
{%- for node in layer.nodes %}
  {{ node }}: '{{ layer.key }}',
{%- endfor %}
{% endfor %}
{%- endfor %}
};

// =============================================================================
// HELPER FUNCTIONS
// =============================================================================

/**
 * Get the layer for a node type
 * @param nodeType - The node type to look up
 * @returns The layer for the node type
 */
export function getLayer(nodeType: NodeType): Layer {
  return NODE_LAYERS[nodeType];
}

/**
 * Get all node types in a layer
 * @param layer - The layer to look up
 * @returns Array of node types belonging to the layer
 */
export function getNodeTypesByLayer(layer: Layer): NodeType[] {
  return (Object.entries(NODE_LAYERS) as [NodeType, Layer][])
    .filter(([, l]) => l === layer)
    .map(([nodeType]) => nodeType);
}
"##;

// ─────────────────────────────────────────────────────────────────────────────
// Generator
// ─────────────────────────────────────────────────────────────────────────────

pub struct LayerGenerator;

impl super::Generator for LayerGenerator {
    fn name(&self) -> &'static str {
        "layers"
    }

    fn generate(&self, root: &Path) -> crate::Result<String> {
        let nodes = yaml_node::load_all_nodes(root)?;
        render_layers(&nodes)
    }
}

/// Group parsed nodes by realm → layer → sorted node names, then render template.
fn render_layers(nodes: &[yaml_node::ParsedNode]) -> crate::Result<String> {
    // Build realm → layer → [node_name] map
    let mut realm_map: BTreeMap<String, BTreeMap<String, Vec<String>>> = BTreeMap::new();

    for node in nodes {
        realm_map
            .entry(node.realm.clone())
            .or_default()
            .entry(node.layer.clone())
            .or_default()
            .push(node.def.name.clone());
    }

    // Sort node names within each layer
    for layers in realm_map.values_mut() {
        for node_names in layers.values_mut() {
            node_names.sort();
        }
    }

    // Build template data in fixed realm order
    let mut realms: Vec<TemplateRealm> = Vec::new();

    for &realm_key in REALM_ORDER {
        let Some(layers_map) = realm_map.get(realm_key) else {
            return Err(crate::NovaNetError::Validation(format!(
                "realm '{realm_key}' has no nodes — expected nodes under models/nodes/{realm_key}/"
            )));
        };

        let mut layers: Vec<TemplateLayer> = layers_map
            .iter()
            .map(|(layer_key, node_names)| TemplateLayer {
                key: layer_key.clone(),
                nodes: node_names.clone(),
                node_count: node_names.len(),
                realm_key: realm_key.to_string(),
            })
            .collect();

        // Sort layers alphabetically within realm
        layers.sort_by(|a, b| a.key.cmp(&b.key));

        let node_count: usize = layers.iter().map(|l| l.node_count).sum();

        realms.push(TemplateRealm {
            key: realm_key.to_string(),
            label: {
                let mut c = realm_key.chars();
                match c.next() {
                    None => String::new(),
                    Some(f) => f.to_uppercase().to_string() + c.as_str(),
                }
            },
            label_upper: realm_key.to_uppercase(),
            node_count,
            layers,
        });
    }

    let total_nodes: usize = realms.iter().map(|r| r.node_count).sum();

    // Render MiniJinja template
    let mut env = Environment::new();
    env.add_template("layers.ts", LAYERS_TEMPLATE)
        .map_err(|e| crate::NovaNetError::Generator {
            generator: "layers".to_string(),
            detail: format!("template parse error: {e}"),
        })?;

    let tmpl = env
        .get_template("layers.ts")
        .map_err(|e| crate::NovaNetError::Generator {
            generator: "layers".to_string(),
            detail: format!("template not found: {e}"),
        })?;

    let output = tmpl
        .render(context! {
            version => "9.0.0",
            total_nodes => total_nodes,
            realms => realms,
        })
        .map_err(|e| crate::NovaNetError::Generator {
            generator: "layers".to_string(),
            detail: format!("template render error: {e}"),
        })?;

    Ok(output)
}

// ─────────────────────────────────────────────────────────────────────────────
// Tests
// ─────────────────────────────────────────────────────────────────────────────

#[cfg(test)]
mod tests {
    use super::*;
    use crate::generators::Generator;
    use crate::parsers::yaml_node::{LocaleBehavior, NodeDef, ParsedNode};

    /// Build a minimal ParsedNode for testing.
    fn make_node(name: &str, realm: &str, layer: &str) -> ParsedNode {
        ParsedNode {
            def: NodeDef {
                name: name.to_string(),
                locale_behavior: LocaleBehavior::Invariant,
                icon: None,
                description: "test".to_string(),
                standard_properties: None,
                properties: None,
                relations: None,
                incoming_relations: None,
                neo4j: None,
                example: None,
            },
            realm: realm.to_string(),
            layer: layer.to_string(),
            source_path: std::path::PathBuf::from(format!(
                "models/nodes/{realm}/{layer}/{name}.yaml"
            )),
        }
    }

    #[test]
    fn render_small_layers() {
        let nodes = vec![
            make_node("Project", "project", "foundation"),
            make_node("Page", "project", "structure"),
            make_node("Block", "project", "structure"),
            make_node("Locale", "global", "config"),
            make_node("LocaleVoice", "global", "knowledge"),
            make_node("SEOKeywordL10n", "shared", "seo"),
        ];

        let output = render_layers(&nodes).unwrap();

        // Header
        assert!(output.contains("AUTO-GENERATED by novanet v9.0.0"));
        assert!(output.contains("mapping all 6 node types"));

        // Imports
        assert!(output.contains("import type { NodeType } from '../types/nodes.js';"));
        assert!(output.contains("import type { Layer } from './types.js';"));

        // NODE_LAYERS declaration
        assert!(output.contains("export const NODE_LAYERS: Record<NodeType, Layer>"));

        // Realm headers
        assert!(output.contains("PROJECT REALM (3 nodes)"));
        assert!(output.contains("GLOBAL REALM (2 nodes)"));
        assert!(output.contains("SHARED REALM (1 nodes)"));

        // Layer groups with node counts
        assert!(output.contains("// foundation (1 node)"));
        assert!(output.contains("// structure (2 nodes)"));
        assert!(output.contains("// config (1 node)"));
        assert!(output.contains("// knowledge (1 node)"));
        assert!(output.contains("// seo (1 node)"));

        // Node mappings
        assert!(output.contains("Project: 'foundation',"));
        assert!(output.contains("Block: 'structure',"));
        assert!(output.contains("Page: 'structure',"));
        assert!(output.contains("Locale: 'config',"));
        assert!(output.contains("LocaleVoice: 'knowledge',"));
        assert!(output.contains("SEOKeywordL10n: 'seo',"));

        // Nodes sorted alphabetically within layers
        let block_pos = output.find("Block: 'structure',").unwrap();
        let page_pos = output.find("Page: 'structure',").unwrap();
        assert!(block_pos < page_pos, "Block should come before Page");

        // Realm order: project, global, shared
        let project_pos = output.find("PROJECT REALM").unwrap();
        let global_pos = output.find("GLOBAL REALM").unwrap();
        let shared_pos = output.find("SHARED REALM").unwrap();
        assert!(project_pos < global_pos);
        assert!(global_pos < shared_pos);

        // Helper functions
        assert!(output.contains("export function getLayer(nodeType: NodeType): Layer"));
        assert!(output.contains("export function getNodeTypesByLayer(layer: Layer): NodeType[]"));
    }

    #[test]
    fn render_layers_sorted_within_layer() {
        let nodes = vec![
            make_node("Zebra", "project", "foundation"),
            make_node("Alpha", "project", "foundation"),
            make_node("Middle", "project", "foundation"),
            make_node("Locale", "global", "config"),
            make_node("Geo", "shared", "geo"),
        ];

        let output = render_layers(&nodes).unwrap();

        // Nodes within foundation layer should be sorted
        let alpha_pos = output.find("Alpha: 'foundation',").unwrap();
        let middle_pos = output.find("Middle: 'foundation',").unwrap();
        let zebra_pos = output.find("Zebra: 'foundation',").unwrap();
        assert!(alpha_pos < middle_pos);
        assert!(middle_pos < zebra_pos);
    }

    #[test]
    fn render_layers_missing_realm_fails() {
        // Only project and global — missing shared
        let nodes = vec![
            make_node("Project", "project", "foundation"),
            make_node("Locale", "global", "config"),
        ];

        let result = render_layers(&nodes);
        assert!(result.is_err());
        let err = result.unwrap_err().to_string();
        assert!(
            err.contains("shared"),
            "error should mention missing realm: {err}"
        );
    }

    #[test]
    fn render_layers_folder_path_in_comment() {
        let nodes = vec![
            make_node("Project", "project", "foundation"),
            make_node("Locale", "global", "config"),
            make_node("Geo", "shared", "geo"),
        ];

        let output = render_layers(&nodes).unwrap();

        // Comments should include the YAML folder path
        assert!(output.contains("models/nodes/project/foundation/"));
        assert!(output.contains("models/nodes/global/config/"));
        assert!(output.contains("models/nodes/shared/geo/"));
    }

    #[test]
    fn render_layers_doc_comment_lists_layers_by_realm() {
        let nodes = vec![
            make_node("Project", "project", "foundation"),
            make_node("Page", "project", "structure"),
            make_node("Locale", "global", "config"),
            make_node("Geo", "shared", "geo"),
        ];

        let output = render_layers(&nodes).unwrap();

        // JSDoc comment should list layers per realm
        assert!(output.contains("* - Project: foundation, structure"));
        assert!(output.contains("* - Global: config"));
        assert!(output.contains("* - Shared: geo"));
    }

    #[test]
    fn generate_layers_integration() {
        let root = std::path::Path::new(env!("CARGO_MANIFEST_DIR"))
            .parent()
            .and_then(|p| p.parent());

        let Some(root) = root else { return };
        if !root.join("pnpm-workspace.yaml").exists() {
            return;
        }

        let generator = LayerGenerator;
        let output = generator.generate(root).expect("should generate layers.ts");

        // Total 35 nodes
        assert!(
            output.contains("mapping all 35 node types"),
            "should mention 35 node types"
        );

        // Realm node counts
        assert!(output.contains("PROJECT REALM (14 nodes)"));
        assert!(output.contains("GLOBAL REALM (15 nodes)"));
        assert!(output.contains("SHARED REALM (6 nodes)"));

        // All 9 layers present
        for layer in [
            "foundation",
            "structure",
            "semantic",
            "instruction",
            "output",
            "config",
            "knowledge",
            "seo",
            "geo",
        ] {
            assert!(
                output.contains(&format!("'{layer}'")),
                "missing layer: {layer}"
            );
        }

        // Spot-check specific node → layer mappings
        assert!(output.contains("Project: 'foundation',"));
        assert!(output.contains("Page: 'structure',"));
        assert!(output.contains("Block: 'structure',"));
        assert!(output.contains("Concept: 'semantic',"));
        assert!(output.contains("PageL10n: 'output',"));
        assert!(output.contains("Locale: 'config',"));
        assert!(output.contains("LocaleVoice: 'knowledge',"));
        assert!(output.contains("SEOKeywordL10n: 'seo',"));
        assert!(output.contains("GEOSeedL10n: 'geo',"));

        // Helper functions present
        assert!(output.contains("export function getLayer"));
        assert!(output.contains("export function getNodeTypesByLayer"));

        // Valid TypeScript structure
        assert!(output.contains("export const NODE_LAYERS: Record<NodeType, Layer>"));
        assert!(output.contains("import type { NodeType }"));
        assert!(output.contains("import type { Layer }"));
    }
}
