//! Generate Cypher for Realm, Layer, ArcFamily meta-nodes.
//!
//! Reads `taxonomy.yaml` and produces idempotent MERGE statements
//! for taxonomy dimensions. All schema-nodes receive `:Schema` double-label.
//!
//!
//! Features: visual encoding properties (border_style, stroke_style),
//! retrieval properties (default_traversal for ArcFamily).
//!
//! Output target: `packages/db/seed/00.5-taxonomy.cypher`

use super::cypher_utils::{
    cypher_list_owned, cypher_str, write_merge_meta, write_section_header_counted,
};
use crate::parsers::taxonomy::TaxonomyDoc;
use std::fmt::Write;
use std::path::Path;

// ─────────────────────────────────────────────────────────────────────────────
// Generator
// ─────────────────────────────────────────────────────────────────────────────

/// Generates Cypher for the 4 taxonomy dimensions from `taxonomy.yaml`.
pub struct OrganizingGenerator;

impl super::Generator for OrganizingGenerator {
    fn name(&self) -> &'static str {
        "taxonomy"
    }

    fn generate(&self, root: &Path) -> crate::Result<String> {
        let doc = crate::parsers::taxonomy::load_taxonomy_from_files(root)?;
        generate_cypher(&doc)
    }
}

/// Build the full Cypher output from a parsed taxonomy document.
fn generate_cypher(doc: &TaxonomyDoc) -> crate::Result<String> {
    let total_layers: usize = doc.node_realms.iter().map(|r| r.layers.len()).sum();
    let mut out = String::with_capacity(8192);

    // ── Header ───────────────────────────────────────────────────────────
    cy!(out, "// Taxonomy Seed v{}", doc.version);
    cy!(out, "// AUTO-GENERATED by novanet — do not edit manually");
    cy!(out, "// Run: novanet schema generate");
    cy!(out, "//");
    cy!(
        out,
        "// Creates: {} Realms, {} Layers, {} ArcFamilies",
        doc.node_realms.len(),
        total_layers,
        doc.arc_families.len()
    );
    cy!(out, "// Includes visual encoding properties");
    cy!(out, "// All schema-nodes have :Schema double-label");
    cy!(out, "// Uses MERGE for idempotent execution");
    cy!(out, "//");
    cy!(out, "// ADR References:");
    cy!(
        out,
        "//   ADR-012: 2-Realm Architecture (SHARED read-only + ORG business)"
    );
    cy!(
        out,
        "//   ADR-024: Trait = Data Origin (defined/authored/imported/generated/retrieved)"
    );

    // ── Realms ───────────────────────────────────────────────────────────
    cy!(out);
    write_section_header_counted(&mut out, "REALMS", doc.node_realms.len());

    for realm in &doc.node_realms {
        cy!(out);
        let var = format!("r_{}", realm.key);
        let content = cypher_str(&realm.content);
        let triggers = cypher_list_owned(&realm.triggers);
        write_merge_meta(
            &mut out,
            &var,
            "Realm",
            &realm.key,
            &[
                ("display_name", &realm.display_name),
                ("content", &content),
            ],
        );
        // triggers is a native Cypher array, written outside write_merge_meta
        cy!(out, "SET {var}.triggers = {triggers};");
    }

    // ── Layers + HAS_LAYER rels ──────────────────────────────────────────
    cy!(out);
    write_section_header_counted(&mut out, "LAYERS", total_layers);

    for realm in &doc.node_realms {
        cy!(out);
        cy!(out, "// {} layers", realm.display_name);

        for layer in &realm.layers {
            // Replace hyphens with underscores for valid Cypher variable names
            let var = format!("l_{}", layer.key.replace('-', "_"));
            let content = cypher_str(&layer.content);
            let triggers = cypher_list_owned(&layer.triggers);
            write_merge_meta(
                &mut out,
                &var,
                "Layer",
                &layer.key,
                &[
                    ("display_name", &layer.display_name),
                    ("content", &content),
                ],
            );
            // triggers is a native Cypher array, written outside write_merge_meta
            cy!(out, "SET {var}.triggers = {triggers};");
            cy!(out);
            cy!(
                out,
                "MATCH (r:Realm {{key: '{}'}}), (l:Layer {{key: '{}'}})",
                realm.key, layer.key
            );
            cy!(out, "MERGE (r)-[:HAS_LAYER]->(l);");
        }
    }


    // ── Arc Families (with visual encoding) ──────────────────────────────
    cy!(out);
    write_section_header_counted(&mut out, "ARC FAMILIES", doc.arc_families.len());

    for af in &doc.arc_families {
        cy!(out);
        let var = format!("af_{}", af.key);
        let triggers = cypher_list_owned(&af.triggers);

        // Start MERGE
        cy!(out, "MERGE ({var}:Schema:ArcFamily {{key: '{}'}})", af.key);
        cy!(out, "ON CREATE SET");
        // node_class discriminator (lowercase = SCHEMA node)
        cy!(out, "  {var}.node_class = 'arc_family',");
        // Provenance as JSON object
        cy!(out, "  {var}.provenance = '{{\"source\": \"seed:schema\", \"version\": \"v0.19.0\"}}',");
        cy!(out, "  {var}.created_at = datetime(),");
        cy!(out, "  {var}.updated_at = datetime()");
        cy!(out, "ON MATCH SET");
        // Always set node_class on match too
        cy!(out, "  {var}.node_class = 'arc_family',");
        cy!(out, "  {var}.updated_at = datetime()");
        cy!(out, "SET");
        cy!(out, "  {var}.display_name = '{}',", af.display_name);
        cy!(out, "  {var}.color = '{}',", af.color);
        cy!(out, "  {var}.arrow_style = '{}',", af.arrow_style);

        // Visual encoding properties
        if let Some(ref style) = af.stroke_style {
            cy!(out, "  {var}.stroke_style = '{style}',");
        }
        if let Some(width) = af.stroke_width {
            cy!(out, "  {var}.stroke_width = {width},");
        }

        // Retrieval default traversal mode
        if let Some(ref traversal) = af.default_traversal {
            cy!(out, "  {var}.default_traversal = '{traversal}',");
        }

        cy!(out, "  {var}.triggers = {triggers};");
    }

    // ── Arc Scopes  ────────────────────────────────────────────────
    if !doc.arc_scopes.is_empty() {
        cy!(out);
        write_section_header_counted(&mut out, "ARC SCOPES", doc.arc_scopes.len());

        for scope in &doc.arc_scopes {
            cy!(out);
            let var = format!("as_{}", scope.key);
            write_merge_meta(
                &mut out,
                &var,
                "ArcScope",
                &scope.key,
                &[
                    ("display_name", &scope.display_name),
                    ("content", &scope.description),
                ],
            );
            // Terminate MERGE statement (write_merge_meta no longer adds trailing semicolon)
            cy!(out, ";");
        }
    }

    // ── Arc Cardinalities  ─────────────────────────────────────────
    if !doc.arc_cardinalities.is_empty() {
        cy!(out);
        write_section_header_counted(&mut out, "ARC CARDINALITIES", doc.arc_cardinalities.len());

        for card in &doc.arc_cardinalities {
            cy!(out);
            let var = format!("ac_{}", card.key);
            write_merge_meta(
                &mut out,
                &var,
                "ArcCardinality",
                &card.key,
                &[
                    ("display_name", &card.display_name),
                    ("content", &card.description),
                ],
            );
            // Terminate MERGE statement (write_merge_meta no longer adds trailing semicolon)
            cy!(out, ";");
        }
    }

    cy!(out);

    Ok(out)
}

// ─────────────────────────────────────────────────────────────────────────────
// Tests
// ─────────────────────────────────────────────────────────────────────────────

#[cfg(test)]
mod tests {
    use super::*;
    use crate::generators::Generator;
    use crate::parsers::taxonomy::{ArcFamilyDef, NodeLayerDef, NodeRealmDef, TaxonomyIcon};
    use serial_test::serial;

    #[test]
    fn generate_small_cypher() {
        let doc = TaxonomyDoc {
            version: "0.13.0".to_string(),
            node_realms: vec![NodeRealmDef {
                key: "test".to_string(),
                display_name: "Test".to_string(),
                content: "A test realm for testing.".to_string(),
                icon: TaxonomyIcon {
                    web: "flask".to_string(),
                    terminal: "🧪".to_string(),
                },
                color: "#000000".to_string(),
                triggers: vec!["test".to_string(), "realm".to_string()],
                layers: vec![NodeLayerDef {
                    key: "base".to_string(),
                    display_name: "Base".to_string(),
                    content: "Base layer for testing.".to_string(),
                    icon: TaxonomyIcon {
                        web: "clipboard".to_string(),
                        terminal: "📋".to_string(),
                    },
                    color: "#111111".to_string(),
                    triggers: vec!["base".to_string()],
                }],
            }],
            layer_retrieval_defaults: None,
            arc_families: vec![ArcFamilyDef {
                key: "owns".to_string(),
                display_name: "Owns".to_string(),
                color: "#333333".to_string(),
                stroke_style: Some("solid".to_string()),
                stroke_width: Some(2),
                arrow_style: "-->".to_string(),
                default_traversal: None,
                triggers: vec!["ownership".to_string()],
            }],
            arc_scopes: vec![],
            arc_cardinalities: vec![],
            terminal: None,
        };

        let cypher = generate_cypher(&doc).unwrap();

        // Realm
        assert!(cypher.contains("MERGE (r_test:Schema:Realm {key: 'test'})"));
        assert!(cypher.contains("r_test.display_name = 'Test'"));
        assert!(cypher.contains("r_test.content = 'A test realm for testing.'"));

        // Layer
        assert!(cypher.contains("MERGE (l_base:Schema:Layer {key: 'base'})"));
        assert!(cypher.contains("l_base.content = 'Base layer for testing.'"));

        // HAS_LAYER
        assert!(cypher.contains("MATCH (r:Realm {key: 'test'}), (l:Layer {key: 'base'})"));
        assert!(cypher.contains("MERGE (r)-[:HAS_LAYER]->(l)"));


        // ArcFamily with visual encoding
        assert!(cypher.contains("MERGE (af_owns:Schema:ArcFamily {key: 'owns'})"));
        assert!(cypher.contains("af_owns.arrow_style = '-->'"));
        assert!(cypher.contains("af_owns.stroke_style = 'solid'"));
        assert!(cypher.contains("af_owns.stroke_width = 2"));

        // :Schema double-label in all MERGE statements
        assert!(cypher.contains(":Schema:Realm"));
        assert!(cypher.contains(":Schema:Layer"));
        assert!(cypher.contains(":Schema:ArcFamily"));

        // Timestamps
        assert!(cypher.contains("created_at = datetime()"));
        assert!(cypher.contains("updated_at = datetime()"));

        // Header
        assert!(cypher.contains("v0.13.0"));
        assert!(cypher.contains("AUTO-GENERATED"));
        assert!(cypher.contains("1 Realms, 1 Layers, 1 ArcFamilies"));
        assert!(cypher.contains("Includes visual encoding properties"));
    }

    #[test]
    fn generate_triggers_as_cypher_array() {
        let doc = TaxonomyDoc {
            version: "10.5.0".to_string(),
            node_realms: vec![NodeRealmDef {
                key: "r".to_string(),
                display_name: "R".to_string(),
                content: "A realm.".to_string(),
                icon: TaxonomyIcon {
                    web: "x".to_string(),
                    terminal: "X".to_string(),
                },
                color: "#fff".to_string(),
                triggers: vec![
                    "keyword1".to_string(),
                    "keyword2".to_string(),
                    "keyword3".to_string(),
                ],
                layers: vec![NodeLayerDef {
                    key: "l".to_string(),
                    display_name: "L".to_string(),
                    content: "A layer.".to_string(),
                    icon: TaxonomyIcon {
                        web: "y".to_string(),
                        terminal: "Y".to_string(),
                    },
                    color: "#000".to_string(),
                    triggers: vec!["layer".to_string()],
                }],
            }],
            layer_retrieval_defaults: None,
            arc_families: vec![ArcFamilyDef {
                key: "e".to_string(),
                display_name: "E".to_string(),
                color: "#bbb".to_string(),
                stroke_style: None,
                stroke_width: None,
                arrow_style: "-->".to_string(),
                default_traversal: None,
                triggers: vec!["arc".to_string()],
            }],
            arc_scopes: vec![],
            arc_cardinalities: vec![],
            terminal: None,
        };

        let cypher = generate_cypher(&doc).unwrap();

        // Realm triggers as Cypher array
        assert!(cypher.contains("r_r.triggers = ['keyword1', 'keyword2', 'keyword3']"));
        // Layer triggers
        assert!(cypher.contains("l_l.triggers = ['layer']"));
        // ArcFamily triggers
        assert!(cypher.contains("af_e.triggers = ['arc']"));
    }

    #[test]
    #[serial]
    fn generate_taxonomy_integration() {
        let root = std::path::Path::new(env!("CARGO_MANIFEST_DIR"))
            .parent()
            .and_then(|p| p.parent());

        let Some(root) = root else { return };
        if !root.join("pnpm-workspace.yaml").exists() {
            return;
        }

        let generator = OrganizingGenerator;
        let cypher = generator.generate(root).expect("should generate cypher");

        // Count MERGE statements per meta-node type
        let count_merges = |label: &str| {
            cypher
                .lines()
                .filter(|l: &&str| l.contains("MERGE") && l.contains(&format!(":Schema:{label}")))
                .count()
        };

        assert_eq!(count_merges("Realm"), 2, "expected 2 Realm nodes");
        assert_eq!(count_merges("Layer"), 10, "expected 10 Layer nodes");
        assert_eq!(count_merges("ArcFamily"), 6, "expected 6 ArcFamily nodes");
        assert_eq!(count_merges("ArcScope"), 2, "expected 2 ArcScope nodes");
        assert_eq!(
            count_merges("ArcCardinality"),
            5,
            "expected 5 ArcCardinality nodes"
        );

        // HAS_LAYER relationships
        let has_layer_count = cypher
            .lines()
            .filter(|l: &&str| l.contains("[:HAS_LAYER]"))
            .count();
        assert_eq!(has_layer_count, 10, "expected 10 HAS_LAYER relationships");

        // Spot checks — specific nodes exist (v11.4: 2 realms, 10 layers)
        assert!(cypher.contains("r_shared:Schema:Realm {key: 'shared'}"));
        assert!(cypher.contains("r_org:Schema:Realm {key: 'org'}"));
        assert!(cypher.contains("l_config:Schema:Layer {key: 'config'}"));
        assert!(cypher.contains("l_locale:Schema:Layer {key: 'locale'}"));
        assert!(cypher.contains("l_geography:Schema:Layer {key: 'geography'}"));
        assert!(cypher.contains("l_knowledge:Schema:Layer {key: 'knowledge'}"));
        assert!(cypher.contains("l_foundation:Schema:Layer {key: 'foundation'}"));
        assert!(cypher.contains("l_semantic:Schema:Layer {key: 'semantic'}"));
        assert!(cypher.contains("af_semantic:Schema:ArcFamily {key: 'semantic'}"));
        assert!(cypher.contains("af_mining:Schema:ArcFamily {key: 'mining'}"));

        // Spot check — arrow_style preserved
        assert!(cypher.contains("af_semantic.arrow_style = '.->'"));
        assert!(cypher.contains("af_generation.arrow_style = '==>'"));
        assert!(cypher.contains("af_mining.arrow_style = '--o'"));


        // Visual encoding — stroke styles on arc families
        assert!(cypher.contains("af_ownership.stroke_style = 'solid'"));
        assert!(cypher.contains("af_localization.stroke_style = 'dashed'"));

        // Arc scopes and cardinalities
        assert!(cypher.contains("as_intra_realm:Schema:ArcScope {key: 'intra_realm'}"));
        assert!(cypher.contains("ac_one_to_many:Schema:ArcCardinality {key: 'one_to_many'}"));

        // Header mentions version
        assert!(cypher.contains("v0.13.0"));

        // HAS_LAYER wiring — specific pairs (v11.4: shared has config, locale, geography, knowledge)
        assert!(cypher.contains("(r:Realm {key: 'shared'}), (l:Layer {key: 'config'})"));
        assert!(cypher.contains("(r:Realm {key: 'shared'}), (l:Layer {key: 'locale'})"));
        assert!(cypher.contains("(r:Realm {key: 'shared'}), (l:Layer {key: 'geography'})"));
        assert!(cypher.contains("(r:Realm {key: 'shared'}), (l:Layer {key: 'knowledge'})"));
        assert!(cypher.contains("(r:Realm {key: 'org'}), (l:Layer {key: 'foundation'})"));
        assert!(cypher.contains("(r:Realm {key: 'org'}), (l:Layer {key: 'output'})"));
    }

    /// Snapshot test for a minimal taxonomy document.
    /// Run `cargo insta review` to accept changes.
    #[test]
    fn snapshot_minimal_taxonomy() {
        let doc = TaxonomyDoc {
            version: "0.13.0".to_string(),
            node_realms: vec![NodeRealmDef {
                key: "test".to_string(),
                display_name: "Test Realm".to_string(),
                content: "A test realm for snapshot testing.".to_string(),
                icon: TaxonomyIcon {
                    web: "flask".to_string(),
                    terminal: "🧪".to_string(),
                },
                color: "#3b82f6".to_string(),
                triggers: vec!["test".to_string(), "realm".to_string()],
                layers: vec![
                    NodeLayerDef {
                        key: "base".to_string(),
                        display_name: "Base Layer".to_string(),
                        content: "The base layer.".to_string(),
                        icon: TaxonomyIcon {
                            web: "clipboard".to_string(),
                            terminal: "📋".to_string(),
                        },
                        color: "#10b981".to_string(),
                        triggers: vec!["base".to_string()],
                    },
                    NodeLayerDef {
                        key: "derived".to_string(),
                        display_name: "Derived Layer".to_string(),
                        content: "A derived layer.".to_string(),
                        icon: TaxonomyIcon {
                            web: "wrench".to_string(),
                            terminal: "🔧".to_string(),
                        },
                        color: "#f59e0b".to_string(),
                        triggers: vec!["derived".to_string()],
                    },
                ],
            }],
            layer_retrieval_defaults: None,
            arc_families: vec![ArcFamilyDef {
                key: "semantic".to_string(),
                display_name: "Semantic".to_string(),
                color: "#8b5cf6".to_string(),
                stroke_style: Some("solid".to_string()),
                stroke_width: Some(2),
                arrow_style: ".->".to_string(),
                default_traversal: None,
                triggers: vec!["semantic".to_string()],
            }],
            arc_scopes: vec![],
            arc_cardinalities: vec![],
            terminal: None,
        };

        let cypher = generate_cypher(&doc).unwrap();
        insta::assert_snapshot!(cypher);
    }
}
