//! Generate v9 Cypher for Realm, Layer, Trait, ArcFamily meta-nodes.
//!
//! Reads `organizing-principles.yaml` and produces idempotent MERGE statements
//! for the 4 taxonomy dimensions. All meta-nodes receive `:Meta` double-label.
//!
//! Output target: `packages/db/seed/00.5-organizing-principles.cypher`

use super::cypher_utils::{cypher_str, write_merge_meta};
use crate::parsers::organizing::OrganizingDoc;
use std::fmt::Write;
use std::path::Path;

// ─────────────────────────────────────────────────────────────────────────────
// Generator
// ─────────────────────────────────────────────────────────────────────────────

/// Generates Cypher for the 4 taxonomy dimensions from `organizing-principles.yaml`.
pub struct OrganizingGenerator;

impl super::Generator for OrganizingGenerator {
    fn name(&self) -> &'static str {
        "organizing-principles"
    }

    fn generate(&self, root: &Path) -> crate::Result<String> {
        let doc = crate::parsers::organizing::load_organizing(root)?;
        generate_cypher(&doc)
    }
}

/// Build the full Cypher output from a parsed organizing document.
fn generate_cypher(doc: &OrganizingDoc) -> crate::Result<String> {
    let total_layers: usize = doc.realms.iter().map(|r| r.layers.len()).sum();
    let mut out = String::with_capacity(8192);

    // ── Header ───────────────────────────────────────────────────────────
    writeln!(out, "// Organizing Principles Seed v{}", doc.version).unwrap();
    writeln!(out, "// AUTO-GENERATED by novanet — do not edit manually").unwrap();
    writeln!(out, "// Run: novanet schema generate").unwrap();
    writeln!(out, "//").unwrap();
    writeln!(
        out,
        "// Creates: {} Realms, {} Layers, {} Traits, {} ArcFamilies",
        doc.realms.len(),
        total_layers,
        doc.traits.len(),
        doc.arc_families.len()
    )
    .unwrap();
    writeln!(out, "// All meta-nodes have :Meta double-label").unwrap();
    writeln!(out, "// Uses MERGE for idempotent execution").unwrap();

    // ── Realms ───────────────────────────────────────────────────────────
    writeln!(out).unwrap();
    write_section_header(&mut out, "REALMS", doc.realms.len());

    for realm in &doc.realms {
        writeln!(out).unwrap();
        let var = format!("r_{}", realm.key);
        let llm = cypher_str(&realm.llm_context);
        write_merge_meta(
            &mut out,
            &var,
            "Realm",
            &realm.key,
            &[
                ("display_name", &realm.display_name),
                ("emoji", &realm.emoji),
                ("color", &realm.color),
                ("llm_context", &llm),
            ],
        );
    }

    // ── Layers + HAS_LAYER rels ──────────────────────────────────────────
    writeln!(out).unwrap();
    write_section_header(&mut out, "LAYERS", total_layers);

    for realm in &doc.realms {
        writeln!(out).unwrap();
        writeln!(out, "// {} layers", realm.display_name).unwrap();

        for layer in &realm.layers {
            let var = format!("l_{}", layer.key);
            let llm = cypher_str(&layer.llm_context);
            write_merge_meta(
                &mut out,
                &var,
                "Layer",
                &layer.key,
                &[
                    ("display_name", &layer.display_name),
                    ("emoji", &layer.emoji),
                    ("color", &layer.color),
                    ("llm_context", &llm),
                ],
            );
            writeln!(out).unwrap();
            writeln!(
                out,
                "MATCH (r:Realm {{key: '{}'}}), (l:Layer {{key: '{}'}})",
                realm.key, layer.key
            )
            .unwrap();
            writeln!(out, "MERGE (r)-[:HAS_LAYER]->(l);").unwrap();
        }
    }

    // ── Traits ───────────────────────────────────────────────────────────
    writeln!(out).unwrap();
    write_section_header(&mut out, "TRAITS", doc.traits.len());

    for trait_def in &doc.traits {
        writeln!(out).unwrap();
        let var = format!("t_{}", trait_def.key);
        let llm = cypher_str(&trait_def.llm_context);
        write_merge_meta(
            &mut out,
            &var,
            "Trait",
            &trait_def.key,
            &[
                ("display_name", &trait_def.display_name),
                ("color", &trait_def.color),
                ("llm_context", &llm),
            ],
        );
    }

    // ── Edge Families ────────────────────────────────────────────────────
    writeln!(out).unwrap();
    write_section_header(&mut out, "ARC FAMILIES", doc.arc_families.len());

    for ef in &doc.arc_families {
        writeln!(out).unwrap();
        let var = format!("ef_{}", ef.key);
        let llm = cypher_str(&ef.llm_context);
        write_merge_meta(
            &mut out,
            &var,
            "ArcFamily",
            &ef.key,
            &[
                ("display_name", &ef.display_name),
                ("color", &ef.color),
                ("arrow_style", &ef.arrow_style),
                ("llm_context", &llm),
            ],
        );
    }

    writeln!(out).unwrap();

    Ok(out)
}

/// Write a visual section header comment.
fn write_section_header(out: &mut String, title: &str, count: usize) {
    let bar = "// ═══════════════════════════════════════════════════════════════════════════════";
    writeln!(out, "{bar}").unwrap();
    writeln!(out, "// {title} ({count})").unwrap();
    writeln!(out, "{bar}").unwrap();
}

// ─────────────────────────────────────────────────────────────────────────────
// Tests
// ─────────────────────────────────────────────────────────────────────────────

#[cfg(test)]
mod tests {
    use super::*;
    use crate::generators::Generator;
    use crate::parsers::organizing::{ArcFamilyDef, LayerDef, RealmDef, TraitDef};

    #[test]
    fn generate_small_cypher() {
        let doc = OrganizingDoc {
            version: "9.0.0".to_string(),
            realms: vec![RealmDef {
                key: "test".to_string(),
                display_name: "Test".to_string(),
                emoji: "🧪".to_string(),
                color: "#000000".to_string(),
                llm_context: "Test realm.".to_string(),
                layers: vec![LayerDef {
                    key: "base".to_string(),
                    display_name: "Base".to_string(),
                    emoji: "📋".to_string(),
                    color: "#111111".to_string(),
                    llm_context: "Base layer.".to_string(),
                }],
            }],
            traits: vec![TraitDef {
                key: "fixed".to_string(),
                display_name: "Fixed".to_string(),
                color: "#222222".to_string(),
                llm_context: "Fixed trait.".to_string(),
            }],
            arc_families: vec![ArcFamilyDef {
                key: "owns".to_string(),
                display_name: "Owns".to_string(),
                color: "#333333".to_string(),
                arrow_style: "-->".to_string(),
                llm_context: "Ownership.".to_string(),
            }],
        };

        let cypher = generate_cypher(&doc).unwrap();

        // Realm
        assert!(cypher.contains("MERGE (r_test:Meta:Realm {key: 'test'})"));
        assert!(cypher.contains("r_test.display_name = 'Test'"));
        assert!(cypher.contains("r_test.color = '#000000'"));

        // Layer
        assert!(cypher.contains("MERGE (l_base:Meta:Layer {key: 'base'})"));
        assert!(cypher.contains("l_base.emoji = '📋'"));

        // HAS_LAYER
        assert!(cypher.contains("MATCH (r:Realm {key: 'test'}), (l:Layer {key: 'base'})"));
        assert!(cypher.contains("MERGE (r)-[:HAS_LAYER]->(l)"));

        // Trait
        assert!(cypher.contains("MERGE (t_fixed:Meta:Trait {key: 'fixed'})"));
        assert!(cypher.contains("t_fixed.color = '#222222'"));

        // ArcFamily
        assert!(cypher.contains("MERGE (ef_owns:Meta:ArcFamily {key: 'owns'})"));
        assert!(cypher.contains("ef_owns.arrow_style = '-->'"));

        // :Meta double-label in all MERGE statements
        assert!(cypher.contains(":Meta:Realm"));
        assert!(cypher.contains(":Meta:Layer"));
        assert!(cypher.contains(":Meta:Trait"));
        assert!(cypher.contains(":Meta:ArcFamily"));

        // Timestamps
        assert!(cypher.contains("created_at = datetime()"));
        assert!(cypher.contains("updated_at = datetime()"));

        // Header
        assert!(cypher.contains("v9.0.0"));
        assert!(cypher.contains("AUTO-GENERATED"));
        assert!(cypher.contains("1 Realms, 1 Layers, 1 Traits, 1 ArcFamilies"));
    }

    #[test]
    fn generate_multiline_llm_context() {
        let doc = OrganizingDoc {
            version: "9.0.0".to_string(),
            realms: vec![RealmDef {
                key: "r".to_string(),
                display_name: "R".to_string(),
                emoji: "X".to_string(),
                color: "#fff".to_string(),
                llm_context: "Line one.\n  Line two.\n  Line three.\n".to_string(),
                layers: vec![LayerDef {
                    key: "l".to_string(),
                    display_name: "L".to_string(),
                    emoji: "Y".to_string(),
                    color: "#000".to_string(),
                    llm_context: "Layer.".to_string(),
                }],
            }],
            traits: vec![TraitDef {
                key: "t".to_string(),
                display_name: "T".to_string(),
                color: "#aaa".to_string(),
                llm_context: "Trait.".to_string(),
            }],
            arc_families: vec![ArcFamilyDef {
                key: "e".to_string(),
                display_name: "E".to_string(),
                color: "#bbb".to_string(),
                arrow_style: "-->".to_string(),
                llm_context: "Edge.".to_string(),
            }],
        };

        let cypher = generate_cypher(&doc).unwrap();

        // Multiline collapsed to single line
        assert!(cypher.contains("r_r.llm_context = 'Line one. Line two. Line three.'"));
    }

    #[test]
    fn generate_organizing_integration() {
        let root = std::path::Path::new(env!("CARGO_MANIFEST_DIR"))
            .parent()
            .and_then(|p| p.parent());

        let Some(root) = root else { return };
        if !root.join("pnpm-workspace.yaml").exists() {
            return;
        }

        let generator = OrganizingGenerator;
        let cypher = generator.generate(root).expect("should generate cypher");

        // Count MERGE statements per meta-node type
        let count_merges = |label: &str| {
            cypher
                .lines()
                .filter(|l: &&str| l.contains("MERGE") && l.contains(&format!(":Meta:{label}")))
                .count()
        };

        assert_eq!(count_merges("Realm"), 3, "expected 3 Realm nodes");
        assert_eq!(count_merges("Layer"), 9, "expected 9 Layer nodes");
        assert_eq!(count_merges("Trait"), 5, "expected 5 Trait nodes");
        assert_eq!(count_merges("ArcFamily"), 5, "expected 5 ArcFamily nodes");

        // HAS_LAYER relationships
        let has_layer_count = cypher
            .lines()
            .filter(|l: &&str| l.contains("[:HAS_LAYER]"))
            .count();
        assert_eq!(has_layer_count, 9, "expected 9 HAS_LAYER relationships");

        // Spot checks — specific nodes exist
        assert!(cypher.contains("r_global:Meta:Realm {key: 'global'}"));
        assert!(cypher.contains("r_project:Meta:Realm {key: 'project'}"));
        assert!(cypher.contains("r_shared:Meta:Realm {key: 'shared'}"));
        assert!(cypher.contains("l_knowledge:Meta:Layer {key: 'knowledge'}"));
        assert!(cypher.contains("l_foundation:Meta:Layer {key: 'foundation'}"));
        assert!(cypher.contains("l_seo:Meta:Layer {key: 'seo'}"));
        assert!(cypher.contains("t_localized:Meta:Trait {key: 'localized'}"));
        assert!(cypher.contains("t_invariant:Meta:Trait {key: 'invariant'}"));
        assert!(cypher.contains("ef_semantic:Meta:ArcFamily {key: 'semantic'}"));
        assert!(cypher.contains("ef_mining:Meta:ArcFamily {key: 'mining'}"));

        // Spot check — arrow_style preserved
        assert!(cypher.contains("ef_semantic.arrow_style = '.->'"));
        assert!(cypher.contains("ef_generation.arrow_style = '==>'"));
        assert!(cypher.contains("ef_mining.arrow_style = '--o'"));

        // Header mentions v9.0.0
        assert!(cypher.contains("v9.0.0"));

        // HAS_LAYER wiring — specific pairs
        assert!(cypher.contains("(r:Realm {key: 'global'}), (l:Layer {key: 'config'})"));
        assert!(cypher.contains("(r:Realm {key: 'project'}), (l:Layer {key: 'output'})"));
        assert!(cypher.contains("(r:Realm {key: 'shared'}), (l:Layer {key: 'geo'})"));
    }
}
