//! Generate Cypher for Realm, Layer, Trait, ArcFamily meta-nodes.
//!
//! Reads `taxonomy.yaml` and produces idempotent MERGE statements
//! for the 4 taxonomy dimensions. All schema-nodes receive `:Schema` double-label.
//!
//! Features: visual encoding properties (border_style, stroke_style),
//! retrieval properties (default_traversal for ArcFamily).
//!
//! Output target: `packages/db/seed/00.5-taxonomy.cypher`

use super::cypher_utils::{cypher_str, write_merge_meta, write_section_header_counted};
use crate::parsers::taxonomy::TaxonomyDoc;
use std::fmt::Write;
use std::path::Path;

// ─────────────────────────────────────────────────────────────────────────────
// Generator
// ─────────────────────────────────────────────────────────────────────────────

/// Generates Cypher for the 4 taxonomy dimensions from `taxonomy.yaml`.
pub struct OrganizingGenerator;

impl super::Generator for OrganizingGenerator {
    fn name(&self) -> &'static str {
        "taxonomy"
    }

    fn generate(&self, root: &Path) -> crate::Result<String> {
        // v0.12.5: Load from individual YAML files instead of taxonomy.yaml
        let doc = crate::parsers::taxonomy::load_taxonomy_from_files(root)?;
        generate_cypher(&doc)
    }
}

/// Build the full Cypher output from a parsed taxonomy document.
fn generate_cypher(doc: &TaxonomyDoc) -> crate::Result<String> {
    let total_layers: usize = doc.node_realms.iter().map(|r| r.layers.len()).sum();
    let mut out = String::with_capacity(8192);

    // ── Header ───────────────────────────────────────────────────────────
    writeln!(out, "// Taxonomy Seed v{}", doc.version).unwrap();
    writeln!(out, "// AUTO-GENERATED by novanet — do not edit manually").unwrap();
    writeln!(out, "// Run: novanet schema generate").unwrap();
    writeln!(out, "//").unwrap();
    writeln!(
        out,
        "// Creates: {} Realms, {} Layers, {} Traits, {} ArcFamilies",
        doc.node_realms.len(),
        total_layers,
        doc.node_traits.len(),
        doc.arc_families.len()
    )
    .unwrap();
    writeln!(out, "// Includes visual encoding properties").unwrap();
    writeln!(out, "// All schema-nodes have :Schema double-label").unwrap();
    writeln!(out, "// Uses MERGE for idempotent execution").unwrap();

    // ── Realms ───────────────────────────────────────────────────────────
    writeln!(out).unwrap();
    write_section_header_counted(&mut out, "REALMS", doc.node_realms.len());

    for realm in &doc.node_realms {
        writeln!(out).unwrap();
        let var = format!("r_{}", realm.key);
        let llm = cypher_str(&realm.llm_context);
        write_merge_meta(
            &mut out,
            &var,
            "Realm",
            &realm.key,
            &[
                ("display_name", &realm.display_name),
                ("emoji", realm.emoji()),
                ("color", &realm.color),
                ("llm_context", &llm),
            ],
        );
    }

    // ── Layers + HAS_LAYER rels ──────────────────────────────────────────
    writeln!(out).unwrap();
    write_section_header_counted(&mut out, "LAYERS", total_layers);

    for realm in &doc.node_realms {
        writeln!(out).unwrap();
        writeln!(out, "// {} layers", realm.display_name).unwrap();

        for layer in &realm.layers {
            // Replace hyphens with underscores for valid Cypher variable names
            let var = format!("l_{}", layer.key.replace('-', "_"));
            let llm = cypher_str(&layer.llm_context);
            write_merge_meta(
                &mut out,
                &var,
                "Layer",
                &layer.key,
                &[
                    ("display_name", &layer.display_name),
                    ("emoji", layer.emoji()),
                    ("color", &layer.color),
                    ("llm_context", &llm),
                ],
            );
            writeln!(out).unwrap();
            writeln!(
                out,
                "MATCH (r:Realm {{key: '{}'}}), (l:Layer {{key: '{}'}})",
                realm.key, layer.key
            )
            .unwrap();
            writeln!(out, "MERGE (r)-[:HAS_LAYER]->(l);").unwrap();
        }
    }

    // ── Traits (with visual encoding) ────────────────────────────────────
    writeln!(out).unwrap();
    write_section_header_counted(&mut out, "TRAITS", doc.node_traits.len());

    for trait_def in &doc.node_traits {
        writeln!(out).unwrap();
        let var = format!("t_{}", trait_def.key);
        let llm = cypher_str(&trait_def.llm_context);

        // Start MERGE
        writeln!(
            out,
            "MERGE ({var}:Schema:Trait {{key: '{}'}})",
            trait_def.key
        )
        .unwrap();
        writeln!(out, "ON CREATE SET").unwrap();
        writeln!(out, "  {var}.created_at = datetime(),").unwrap();
        writeln!(out, "  {var}.updated_at = datetime()").unwrap();
        writeln!(out, "ON MATCH SET").unwrap();
        writeln!(out, "  {var}.updated_at = datetime()").unwrap();
        writeln!(out, "SET").unwrap();
        writeln!(out, "  {var}.display_name = '{}',", trait_def.display_name).unwrap();
        writeln!(out, "  {var}.color = '{}',", trait_def.color).unwrap();

        // Visual encoding properties
        if let Some(ref style) = trait_def.border_style {
            writeln!(out, "  {var}.border_style = '{style}',").unwrap();
        }
        if let Some(width) = trait_def.border_width {
            writeln!(out, "  {var}.border_width = {width},").unwrap();
        }
        if let Some(ref unicode) = trait_def.unicode_border {
            writeln!(out, "  {var}.unicode_border = '{unicode}',").unwrap();
        }

        writeln!(out, "  {var}.llm_context = '{llm}';").unwrap();
    }

    // ── Arc Families (with visual encoding) ──────────────────────────────
    writeln!(out).unwrap();
    write_section_header_counted(&mut out, "ARC FAMILIES", doc.arc_families.len());

    for af in &doc.arc_families {
        writeln!(out).unwrap();
        let var = format!("af_{}", af.key);
        let llm = cypher_str(&af.llm_context);

        // Start MERGE
        writeln!(out, "MERGE ({var}:Schema:ArcFamily {{key: '{}'}})", af.key).unwrap();
        writeln!(out, "ON CREATE SET").unwrap();
        writeln!(out, "  {var}.created_at = datetime(),").unwrap();
        writeln!(out, "  {var}.updated_at = datetime()").unwrap();
        writeln!(out, "ON MATCH SET").unwrap();
        writeln!(out, "  {var}.updated_at = datetime()").unwrap();
        writeln!(out, "SET").unwrap();
        writeln!(out, "  {var}.display_name = '{}',", af.display_name).unwrap();
        writeln!(out, "  {var}.color = '{}',", af.color).unwrap();
        writeln!(out, "  {var}.arrow_style = '{}',", af.arrow_style).unwrap();

        // Visual encoding properties
        if let Some(ref style) = af.stroke_style {
            writeln!(out, "  {var}.stroke_style = '{style}',").unwrap();
        }
        if let Some(width) = af.stroke_width {
            writeln!(out, "  {var}.stroke_width = {width},").unwrap();
        }

        // Retrieval default traversal mode
        if let Some(ref traversal) = af.default_traversal {
            writeln!(out, "  {var}.default_traversal = '{traversal}',").unwrap();
        }

        writeln!(out, "  {var}.llm_context = '{llm}';").unwrap();
    }

    // ── Arc Scopes  ────────────────────────────────────────────────
    if !doc.arc_scopes.is_empty() {
        writeln!(out).unwrap();
        write_section_header_counted(&mut out, "ARC SCOPES", doc.arc_scopes.len());

        for scope in &doc.arc_scopes {
            writeln!(out).unwrap();
            let var = format!("as_{}", scope.key);
            write_merge_meta(
                &mut out,
                &var,
                "ArcScope",
                &scope.key,
                &[
                    ("display_name", &scope.display_name),
                    ("description", &scope.description),
                ],
            );
        }
    }

    // ── Arc Cardinalities  ─────────────────────────────────────────
    if !doc.arc_cardinalities.is_empty() {
        writeln!(out).unwrap();
        write_section_header_counted(&mut out, "ARC CARDINALITIES", doc.arc_cardinalities.len());

        for card in &doc.arc_cardinalities {
            writeln!(out).unwrap();
            let var = format!("ac_{}", card.key);
            write_merge_meta(
                &mut out,
                &var,
                "ArcCardinality",
                &card.key,
                &[
                    ("display_name", &card.display_name),
                    ("description", &card.description),
                ],
            );
        }
    }

    writeln!(out).unwrap();

    Ok(out)
}

// ─────────────────────────────────────────────────────────────────────────────
// Tests
// ─────────────────────────────────────────────────────────────────────────────

#[cfg(test)]
mod tests {
    use super::*;
    use crate::generators::Generator;
    use crate::parsers::taxonomy::{
        ArcFamilyDef, NodeLayerDef, NodeRealmDef, NodeTraitDef, TaxonomyIcon,
    };

    #[test]
    fn generate_small_cypher() {
        let doc = TaxonomyDoc {
            version: "0.13.0".to_string(),
            node_realms: vec![NodeRealmDef {
                key: "test".to_string(),
                display_name: "Test".to_string(),
                icon: TaxonomyIcon {
                    web: "flask".to_string(),
                    terminal: "🧪".to_string(),
                },
                color: "#000000".to_string(),
                llm_context: "Test realm.".to_string(),
                layers: vec![NodeLayerDef {
                    key: "base".to_string(),
                    display_name: "Base".to_string(),
                    icon: TaxonomyIcon {
                        web: "clipboard".to_string(),
                        terminal: "📋".to_string(),
                    },
                    color: "#111111".to_string(),
                    llm_context: "Base layer.".to_string(),
                }],
            }],
            node_traits: vec![NodeTraitDef {
                key: "fixed".to_string(),
                display_name: "Fixed".to_string(),
                color: "#222222".to_string(),
                border_style: Some("solid".to_string()),
                border_width: Some(2),
                unicode_border: Some("─".to_string()),
                llm_context: "Fixed trait.".to_string(),
            }],
            class_retrieval_defaults: None,
            arc_families: vec![ArcFamilyDef {
                key: "owns".to_string(),
                display_name: "Owns".to_string(),
                color: "#333333".to_string(),
                stroke_style: Some("solid".to_string()),
                stroke_width: Some(2),
                arrow_style: "-->".to_string(),
                default_traversal: None,
                llm_context: "Ownership.".to_string(),
            }],
            arc_scopes: vec![],
            arc_cardinalities: vec![],
            terminal: None,
        };

        let cypher = generate_cypher(&doc).unwrap();

        // Realm
        assert!(cypher.contains("MERGE (r_test:Schema:Realm {key: 'test'})"));
        assert!(cypher.contains("r_test.display_name = 'Test'"));
        assert!(cypher.contains("r_test.color = '#000000'"));

        // Layer
        assert!(cypher.contains("MERGE (l_base:Schema:Layer {key: 'base'})"));
        assert!(cypher.contains("l_base.emoji = '📋'"));

        // HAS_LAYER
        assert!(cypher.contains("MATCH (r:Realm {key: 'test'}), (l:Layer {key: 'base'})"));
        assert!(cypher.contains("MERGE (r)-[:HAS_LAYER]->(l)"));

        // Trait with visual encoding
        assert!(cypher.contains("MERGE (t_fixed:Schema:Trait {key: 'fixed'})"));
        assert!(cypher.contains("t_fixed.color = '#222222'"));
        assert!(cypher.contains("t_fixed.border_style = 'solid'"));
        assert!(cypher.contains("t_fixed.border_width = 2"));
        assert!(cypher.contains("t_fixed.unicode_border = '─'"));

        // ArcFamily with visual encoding
        assert!(cypher.contains("MERGE (af_owns:Schema:ArcFamily {key: 'owns'})"));
        assert!(cypher.contains("af_owns.arrow_style = '-->'"));
        assert!(cypher.contains("af_owns.stroke_style = 'solid'"));
        assert!(cypher.contains("af_owns.stroke_width = 2"));

        // :Schema double-label in all MERGE statements
        assert!(cypher.contains(":Schema:Realm"));
        assert!(cypher.contains(":Schema:Layer"));
        assert!(cypher.contains(":Schema:Trait"));
        assert!(cypher.contains(":Schema:ArcFamily"));

        // Timestamps
        assert!(cypher.contains("created_at = datetime()"));
        assert!(cypher.contains("updated_at = datetime()"));

        // Header
        assert!(cypher.contains("v0.13.0"));
        assert!(cypher.contains("AUTO-GENERATED"));
        assert!(cypher.contains("1 Realms, 1 Layers, 1 Traits, 1 ArcFamilies"));
        assert!(cypher.contains("Includes visual encoding properties"));
    }

    #[test]
    fn generate_multiline_llm_context() {
        let doc = TaxonomyDoc {
            version: "10.5.0".to_string(),
            node_realms: vec![NodeRealmDef {
                key: "r".to_string(),
                display_name: "R".to_string(),
                icon: TaxonomyIcon {
                    web: "x".to_string(),
                    terminal: "X".to_string(),
                },
                color: "#fff".to_string(),
                llm_context: "Line one.\n  Line two.\n  Line three.\n".to_string(),
                layers: vec![NodeLayerDef {
                    key: "l".to_string(),
                    display_name: "L".to_string(),
                    icon: TaxonomyIcon {
                        web: "y".to_string(),
                        terminal: "Y".to_string(),
                    },
                    color: "#000".to_string(),
                    llm_context: "Layer.".to_string(),
                }],
            }],
            node_traits: vec![NodeTraitDef {
                key: "t".to_string(),
                display_name: "T".to_string(),
                color: "#aaa".to_string(),
                border_style: None,
                border_width: None,
                unicode_border: None,
                llm_context: "Trait.".to_string(),
            }],
            class_retrieval_defaults: None,
            arc_families: vec![ArcFamilyDef {
                key: "e".to_string(),
                display_name: "E".to_string(),
                color: "#bbb".to_string(),
                stroke_style: None,
                stroke_width: None,
                arrow_style: "-->".to_string(),
                default_traversal: None,
                llm_context: "Arc.".to_string(),
            }],
            arc_scopes: vec![],
            arc_cardinalities: vec![],
            terminal: None,
        };

        let cypher = generate_cypher(&doc).unwrap();

        // Multiline collapsed to single line
        assert!(cypher.contains("r_r.llm_context = 'Line one. Line two. Line three.'"));
    }

    #[test]
    fn generate_taxonomy_integration() {
        let root = std::path::Path::new(env!("CARGO_MANIFEST_DIR"))
            .parent()
            .and_then(|p| p.parent());

        let Some(root) = root else { return };
        if !root.join("pnpm-workspace.yaml").exists() {
            return;
        }

        let generator = OrganizingGenerator;
        let cypher = generator.generate(root).expect("should generate cypher");

        // Count MERGE statements per meta-node type
        let count_merges = |label: &str| {
            cypher
                .lines()
                .filter(|l: &&str| l.contains("MERGE") && l.contains(&format!(":Schema:{label}")))
                .count()
        };

        assert_eq!(count_merges("Realm"), 2, "expected 2 Realm nodes"); // v11.4: shared + org
        assert_eq!(count_merges("Layer"), 10, "expected 10 Layer nodes"); // v11.4: 4 shared + 6 org
        assert_eq!(count_merges("Trait"), 5, "expected 5 Trait nodes"); // v11.2: split derived → generated + aggregated
        assert_eq!(count_merges("ArcFamily"), 6, "expected 6 ArcFamily nodes"); // v0.13.1: added schema family
        assert_eq!(count_merges("ArcScope"), 2, "expected 2 ArcScope nodes");
        assert_eq!(
            count_merges("ArcCardinality"),
            5,
            "expected 5 ArcCardinality nodes"
        );

        // HAS_LAYER relationships
        let has_layer_count = cypher
            .lines()
            .filter(|l: &&str| l.contains("[:HAS_LAYER]"))
            .count();
        assert_eq!(has_layer_count, 10, "expected 10 HAS_LAYER relationships"); // v11.4: 4 shared + 6 org

        // Spot checks — specific nodes exist (v11.4: 2 realms, 10 layers)
        assert!(cypher.contains("r_shared:Schema:Realm {key: 'shared'}"));
        assert!(cypher.contains("r_org:Schema:Realm {key: 'org'}")); // v11.2: org realm
        assert!(cypher.contains("l_config:Schema:Layer {key: 'config'}")); // v11.4: shared.config
        assert!(cypher.contains("l_locale:Schema:Layer {key: 'locale'}")); // v11.3: shared.locale
        assert!(cypher.contains("l_geography:Schema:Layer {key: 'geography'}")); // v11.3: shared.geography
        assert!(cypher.contains("l_knowledge:Schema:Layer {key: 'knowledge'}")); // v11.3: shared.knowledge
        assert!(cypher.contains("l_foundation:Schema:Layer {key: 'foundation'}"));
        assert!(cypher.contains("l_semantic:Schema:Layer {key: 'semantic'}")); // v10.6: tenant.semantic
        // v11.4: seo/geo layers removed (nodes moved to shared/knowledge)
        assert!(cypher.contains("t_authored:Schema:Trait {key: 'authored'}"));
        assert!(cypher.contains("t_defined:Schema:Trait {key: 'defined'}"));
        assert!(cypher.contains("af_semantic:Schema:ArcFamily {key: 'semantic'}"));
        assert!(cypher.contains("af_mining:Schema:ArcFamily {key: 'mining'}"));

        // Spot check — arrow_style preserved
        assert!(cypher.contains("af_semantic.arrow_style = '.->'"));
        assert!(cypher.contains("af_generation.arrow_style = '==>'"));
        assert!(cypher.contains("af_mining.arrow_style = '--o'"));

        // Visual encoding — border styles on traits
        assert!(cypher.contains("t_defined.border_style = 'solid'"));
        assert!(cypher.contains("t_authored.border_style = 'dashed'"));

        // Visual encoding — stroke styles on arc families
        assert!(cypher.contains("af_ownership.stroke_style = 'solid'"));
        assert!(cypher.contains("af_localization.stroke_style = 'dashed'"));

        // Arc scopes and cardinalities
        assert!(cypher.contains("as_intra_realm:Schema:ArcScope {key: 'intra_realm'}"));
        assert!(cypher.contains("ac_one_to_many:Schema:ArcCardinality {key: 'one_to_many'}"));

        // Header mentions version
        assert!(cypher.contains("v0.13.0"));

        // HAS_LAYER wiring — specific pairs (v11.4: shared has config, locale, geography, knowledge)
        assert!(cypher.contains("(r:Realm {key: 'shared'}), (l:Layer {key: 'config'})"));
        assert!(cypher.contains("(r:Realm {key: 'shared'}), (l:Layer {key: 'locale'})"));
        assert!(cypher.contains("(r:Realm {key: 'shared'}), (l:Layer {key: 'geography'})"));
        assert!(cypher.contains("(r:Realm {key: 'shared'}), (l:Layer {key: 'knowledge'})"));
        assert!(cypher.contains("(r:Realm {key: 'org'}), (l:Layer {key: 'foundation'})"));
        assert!(cypher.contains("(r:Realm {key: 'org'}), (l:Layer {key: 'output'})"));
        // v11.4: seo/geo removed from org
    }

    /// Snapshot test for a minimal taxonomy document.
    /// Run `cargo insta review` to accept changes.
    #[test]
    fn snapshot_minimal_taxonomy() {
        let doc = TaxonomyDoc {
            version: "0.13.0".to_string(),
            node_realms: vec![NodeRealmDef {
                key: "test".to_string(),
                display_name: "Test Realm".to_string(),
                icon: TaxonomyIcon {
                    web: "flask".to_string(),
                    terminal: "🧪".to_string(),
                },
                color: "#3b82f6".to_string(),
                llm_context: "A test realm for snapshot testing.".to_string(),
                layers: vec![
                    NodeLayerDef {
                        key: "base".to_string(),
                        display_name: "Base Layer".to_string(),
                        icon: TaxonomyIcon {
                            web: "clipboard".to_string(),
                            terminal: "📋".to_string(),
                        },
                        color: "#10b981".to_string(),
                        llm_context: "The base layer.".to_string(),
                    },
                    NodeLayerDef {
                        key: "derived".to_string(),
                        display_name: "Derived Layer".to_string(),
                        icon: TaxonomyIcon {
                            web: "wrench".to_string(),
                            terminal: "🔧".to_string(),
                        },
                        color: "#f59e0b".to_string(),
                        llm_context: "A derived layer.".to_string(),
                    },
                ],
            }],
            node_traits: vec![
                NodeTraitDef {
                    key: "defined".to_string(),
                    display_name: "Defined".to_string(),
                    color: "#6366f1".to_string(),
                    border_style: Some("solid".to_string()),
                    border_width: Some(2),
                    unicode_border: Some("─".to_string()),
                    llm_context: "Content that does not change per locale.".to_string(),
                },
                NodeTraitDef {
                    key: "authored".to_string(),
                    display_name: "Authored".to_string(),
                    color: "#ec4899".to_string(),
                    border_style: Some("dashed".to_string()),
                    border_width: Some(2),
                    unicode_border: Some("╌".to_string()),
                    llm_context: "Content that varies per locale.".to_string(),
                },
            ],
            class_retrieval_defaults: None,
            arc_families: vec![ArcFamilyDef {
                key: "semantic".to_string(),
                display_name: "Semantic".to_string(),
                color: "#8b5cf6".to_string(),
                stroke_style: Some("solid".to_string()),
                stroke_width: Some(2),
                arrow_style: ".->".to_string(),
                default_traversal: None,
                llm_context: "Semantic relationships.".to_string(),
            }],
            arc_scopes: vec![],
            arc_cardinalities: vec![],
            terminal: None,
        };

        let cypher = generate_cypher(&doc).unwrap();
        insta::assert_snapshot!(cypher);
    }
}
