//! Generate TUI color constants from YAML sources.
//!
//! v0.13.0: Generates `tui/colors.generated.rs` from:
//! - `realms/*.yaml` → Realm colors
//! - `layers/*.yaml` → Layer colors
//! - `traits/*.yaml` → Trait colors + border styles
//! - `arc-families/*.yaml` → Arc family colors
//! - `taxonomy.yaml` → Terminal palette (256/16 color fallbacks)
//!
//! This generator ensures TUI colors are synchronized with the YAML source of truth,
//! eliminating hardcoded color values in `theme.rs`.
//!
//! Output target: `tools/novanet/src/tui/colors.generated.rs`

use crate::parsers::organizing::{self, OrganizingDoc};
use crate::parsers::taxonomy::{self, TerminalPalette};
use minijinja::{Environment, context};
use serde::Serialize;
use std::collections::HashMap;
use std::path::Path;

// ─────────────────────────────────────────────────────────────────────────────
// Template data structures
// ─────────────────────────────────────────────────────────────────────────────

/// Color entry with hex, 256, and 16-color fallbacks.
#[derive(Debug, Serialize)]
struct ColorEntry {
    key: String,
    key_upper: String,
    color_hex: String,
    color_256: u8,
    color_16: String,
}

/// Trait entry with color and border style.
#[derive(Debug, Serialize)]
struct TraitEntry {
    key: String,
    key_upper: String,
    color_hex: String,
    color_256: u8,
    color_16: String,
    border_char: String,
}

/// All color data for the template.
#[derive(Debug, Serialize)]
struct TemplateData {
    version: String,
    realms: Vec<ColorEntry>,
    layers: Vec<ColorEntry>,
    traits: Vec<TraitEntry>,
    arc_families: Vec<ColorEntry>,
}

// ─────────────────────────────────────────────────────────────────────────────
// MiniJinja template
// ─────────────────────────────────────────────────────────────────────────────

const TUI_COLORS_TEMPLATE: &str = r##"//! TUI color constants generated from YAML sources.
//!
//! AUTO-GENERATED by novanet v{{ version }} — DO NOT EDIT
//! Source: realms/*.yaml, layers/*.yaml, traits/*.yaml, arc-families/*.yaml
//! Run: cargo run -- schema generate
//!
//! v0.13.0: Colors synchronized with YAML source of truth.

use ratatui::style::Color;

use super::theme::ColorMode;

// =============================================================================
// REALM COLORS ({{ realms | length }})
// =============================================================================

pub mod realm {
    use super::*;

    // Hex colors
{%- for r in realms %}
    pub const {{ r.key_upper }}_HEX: &str = "{{ r.color_hex }}";
{%- endfor %}

    // 256-color palette indices
{%- for r in realms %}
    pub const {{ r.key_upper }}_256: u8 = {{ r.color_256 }};
{%- endfor %}

    // 16-color palette
{%- for r in realms %}
    pub const {{ r.key_upper }}_16: Color = Color::{{ r.color_16 }};
{%- endfor %}

    /// Get realm color for a given color mode.
    pub fn color(realm: &str, mode: ColorMode) -> Color {
        match mode {
            ColorMode::TrueColor => match realm {
{%- for r in realms %}
                "{{ r.key }}" => super::hex_to_color({{ r.key_upper }}_HEX),
{%- endfor %}
                _ => Color::White,
            },
            ColorMode::Color256 => match realm {
{%- for r in realms %}
                "{{ r.key }}" => Color::Indexed({{ r.key_upper }}_256),
{%- endfor %}
                _ => Color::White,
            },
            ColorMode::Color16 => match realm {
{%- for r in realms %}
                "{{ r.key }}" => {{ r.key_upper }}_16,
{%- endfor %}
                _ => Color::White,
            },
        }
    }
}

// =============================================================================
// LAYER COLORS ({{ layers | length }})
// =============================================================================

pub mod layer {
    use super::*;

    // Hex colors
{%- for l in layers %}
    pub const {{ l.key_upper }}_HEX: &str = "{{ l.color_hex }}";
{%- endfor %}

    // 256-color palette indices
{%- for l in layers %}
    pub const {{ l.key_upper }}_256: u8 = {{ l.color_256 }};
{%- endfor %}

    // 16-color palette
{%- for l in layers %}
    pub const {{ l.key_upper }}_16: Color = Color::{{ l.color_16 }};
{%- endfor %}

    /// Get layer color for a given color mode.
    pub fn color(layer_key: &str, mode: ColorMode) -> Color {
        match mode {
            ColorMode::TrueColor => match layer_key {
{%- for l in layers %}
                "{{ l.key }}" => super::hex_to_color({{ l.key_upper }}_HEX),
{%- endfor %}
                _ => Color::White,
            },
            ColorMode::Color256 => match layer_key {
{%- for l in layers %}
                "{{ l.key }}" => Color::Indexed({{ l.key_upper }}_256),
{%- endfor %}
                _ => Color::White,
            },
            ColorMode::Color16 => match layer_key {
{%- for l in layers %}
                "{{ l.key }}" => {{ l.key_upper }}_16,
{%- endfor %}
                _ => Color::White,
            },
        }
    }
}

// =============================================================================
// TRAIT COLORS + BORDERS ({{ traits | length }})
// =============================================================================

pub mod traits {
    use super::*;
    use ratatui::style::Modifier;

    // Hex colors
{%- for t in traits %}
    pub const {{ t.key_upper }}_HEX: &str = "{{ t.color_hex }}";
{%- endfor %}

    // 256-color palette indices
{%- for t in traits %}
    pub const {{ t.key_upper }}_256: u8 = {{ t.color_256 }};
{%- endfor %}

    // 16-color palette
{%- for t in traits %}
    pub const {{ t.key_upper }}_16: Color = Color::{{ t.color_16 }};
{%- endfor %}

    // Unicode border characters
{%- for t in traits %}
    pub const {{ t.key_upper }}_BORDER: &str = "{{ t.border_char }}";
{%- endfor %}

    /// Get trait border character.
    pub fn border_char(trait_key: &str) -> &'static str {
        match trait_key {
{%- for t in traits %}
            "{{ t.key }}" => {{ t.key_upper }}_BORDER,
{%- endfor %}
            _ => DEFINED_BORDER,
        }
    }

    /// Get trait color for a given color mode.
    pub fn color(trait_key: &str, mode: ColorMode) -> Color {
        match mode {
            ColorMode::TrueColor => match trait_key {
{%- for t in traits %}
                "{{ t.key }}" => super::hex_to_color({{ t.key_upper }}_HEX),
{%- endfor %}
                _ => Color::White,
            },
            ColorMode::Color256 => match trait_key {
{%- for t in traits %}
                "{{ t.key }}" => Color::Indexed({{ t.key_upper }}_256),
{%- endfor %}
                _ => Color::White,
            },
            ColorMode::Color16 => match trait_key {
{%- for t in traits %}
                "{{ t.key }}" => {{ t.key_upper }}_16,
{%- endfor %}
                _ => Color::White,
            },
        }
    }

    /// Get modifier for trait (bold for defined).
    pub fn modifier(trait_key: &str) -> Modifier {
        match trait_key {
            "defined" => Modifier::BOLD,
            _ => Modifier::empty(),
        }
    }
}

// =============================================================================
// ARC FAMILY COLORS ({{ arc_families | length }})
// =============================================================================

pub mod arc_family {
    use super::*;

    // Hex colors
{%- for af in arc_families %}
    pub const {{ af.key_upper }}_HEX: &str = "{{ af.color_hex }}";
{%- endfor %}

    // 256-color palette indices
{%- for af in arc_families %}
    pub const {{ af.key_upper }}_256: u8 = {{ af.color_256 }};
{%- endfor %}

    // 16-color palette
{%- for af in arc_families %}
    pub const {{ af.key_upper }}_16: Color = Color::{{ af.color_16 }};
{%- endfor %}

    /// Get arc family color for a given color mode.
    pub fn color(family: &str, mode: ColorMode) -> Color {
        match mode {
            ColorMode::TrueColor => match family {
{%- for af in arc_families %}
                "{{ af.key }}" => super::hex_to_color({{ af.key_upper }}_HEX),
{%- endfor %}
                _ => Color::White,
            },
            ColorMode::Color256 => match family {
{%- for af in arc_families %}
                "{{ af.key }}" => Color::Indexed({{ af.key_upper }}_256),
{%- endfor %}
                _ => Color::White,
            },
            ColorMode::Color16 => match family {
{%- for af in arc_families %}
                "{{ af.key }}" => {{ af.key_upper }}_16,
{%- endfor %}
                _ => Color::White,
            },
        }
    }
}

// =============================================================================
// HEX COLOR CONVERSION
// =============================================================================

/// Convert hex color string to ratatui Color.
#[inline]
pub fn hex_to_color(hex: &str) -> Color {
    hex_to_rgb(hex).map_or(Color::White, |(r, g, b)| Color::Rgb(r, g, b))
}

/// Convert hex color string to RGB tuple.
#[inline]
pub fn hex_to_rgb(hex: &str) -> Option<(u8, u8, u8)> {
    let hex = hex.trim_start_matches('#');
    if hex.len() != 6 {
        return None;
    }
    let r = u8::from_str_radix(&hex[0..2], 16).ok()?;
    let g = u8::from_str_radix(&hex[2..4], 16).ok()?;
    let b = u8::from_str_radix(&hex[4..6], 16).ok()?;
    Some((r, g, b))
}
"##;

// ─────────────────────────────────────────────────────────────────────────────
// Generator
// ─────────────────────────────────────────────────────────────────────────────

pub struct TuiColorsGenerator;

impl super::Generator for TuiColorsGenerator {
    fn name(&self) -> &'static str {
        "tui_colors"
    }

    fn generate(&self, root: &Path) -> crate::Result<String> {
        // Load colors from individual YAML files
        let doc = organizing::load_organizing(root)?;

        // Load terminal palette for 256/16 color fallbacks
        let taxonomy = taxonomy::load_taxonomy_from_files(root)?;
        let terminal = taxonomy.terminal.unwrap_or_else(default_terminal_palette);

        render_tui_colors(&doc, &terminal)
    }
}

/// Default terminal palette when taxonomy.yaml doesn't have one.
fn default_terminal_palette() -> TerminalPalette {
    let mut palette_256 = HashMap::new();
    let mut palette_16 = HashMap::new();

    // Realms
    palette_256.insert("shared".to_string(), 37);
    palette_256.insert("org".to_string(), 141);
    palette_16.insert("shared".to_string(), 6); // Cyan
    palette_16.insert("org".to_string(), 5); // Magenta

    // Layers
    for (key, idx_256, idx_16) in [
        ("config", 244, 8),
        ("locale", 244, 8),
        ("geography", 43, 2),
        ("knowledge", 141, 5),
        ("foundation", 33, 4),
        ("structure", 45, 6),
        ("semantic", 208, 3),
        ("instruction", 178, 11),
        ("output", 41, 2),
    ] {
        palette_256.insert(key.to_string(), idx_256);
        palette_16.insert(key.to_string(), idx_16);
    }

    // Traits
    for (key, idx_256, idx_16) in [
        ("defined", 33, 4),
        ("authored", 41, 2),
        ("imported", 141, 5),
        ("generated", 136, 3),
        ("retrieved", 141, 5),
    ] {
        palette_256.insert(key.to_string(), idx_256);
        palette_16.insert(key.to_string(), idx_16);
    }

    // Arc families
    for (key, idx_256, idx_16) in [
        ("ownership", 33, 4),
        ("localization", 41, 2),
        ("semantic", 208, 3),
        ("generation", 141, 5),
        ("mining", 205, 13),
    ] {
        palette_256.insert(format!("{}_arc", key), idx_256);
        palette_16.insert(format!("{}_arc", key), idx_16);
    }

    TerminalPalette {
        palette_256,
        palette_16,
    }
}

/// Map 16-color index to Color variant name.
fn color_16_name(idx: u8) -> &'static str {
    match idx {
        0 => "Black",
        1 => "Red",
        2 => "Green",
        3 => "Yellow",
        4 => "Blue",
        5 => "Magenta",
        6 => "Cyan",
        7 => "Gray",
        8 => "DarkGray",
        9 => "LightRed",
        10 => "LightGreen",
        11 => "LightYellow",
        12 => "LightBlue",
        13 => "LightMagenta",
        14 => "LightCyan",
        15 => "White",
        _ => "White",
    }
}

/// Map trait key to Unicode border character.
fn trait_border_char(key: &str) -> &'static str {
    match key {
        "defined" => "─",
        "authored" => "┄",
        "imported" => "┈",
        "generated" => "═",
        "retrieved" => "┅",
        _ => "─",
    }
}

/// Build template data from organizing doc and terminal palette.
fn render_tui_colors(doc: &OrganizingDoc, terminal: &TerminalPalette) -> crate::Result<String> {
    // Extract realms
    let realms: Vec<ColorEntry> = doc
        .realms
        .iter()
        .map(|r| {
            let idx_256 = terminal.palette_256.get(&r.key).copied().unwrap_or(7);
            let idx_16 = terminal.palette_16.get(&r.key).copied().unwrap_or(7);
            ColorEntry {
                key: r.key.clone(),
                key_upper: r.key.to_uppercase(),
                color_hex: r.color.clone(),
                color_256: idx_256,
                color_16: color_16_name(idx_16).to_string(),
            }
        })
        .collect();

    // Extract layers (deduplicated)
    let mut seen_layers = std::collections::HashSet::new();
    let layers: Vec<ColorEntry> = doc
        .realms
        .iter()
        .flat_map(|r| &r.layers)
        .filter(|l| seen_layers.insert(l.key.clone()))
        .map(|l| {
            let idx_256 = terminal.palette_256.get(&l.key).copied().unwrap_or(7);
            let idx_16 = terminal.palette_16.get(&l.key).copied().unwrap_or(7);
            ColorEntry {
                key: l.key.clone(),
                key_upper: l.key.to_uppercase(),
                color_hex: l.color.clone(),
                color_256: idx_256,
                color_16: color_16_name(idx_16).to_string(),
            }
        })
        .collect();

    // Extract traits
    let traits: Vec<TraitEntry> = doc
        .traits
        .iter()
        .map(|t| {
            let idx_256 = terminal.palette_256.get(&t.key).copied().unwrap_or(7);
            let idx_16 = terminal.palette_16.get(&t.key).copied().unwrap_or(7);
            TraitEntry {
                key: t.key.clone(),
                key_upper: t.key.to_uppercase(),
                color_hex: t.color.clone(),
                color_256: idx_256,
                color_16: color_16_name(idx_16).to_string(),
                border_char: trait_border_char(&t.key).to_string(),
            }
        })
        .collect();

    // Extract arc families
    let arc_families: Vec<ColorEntry> = doc
        .arc_families
        .iter()
        .map(|af| {
            // Try with _arc suffix first, then without
            let palette_key = format!("{}_arc", af.key);
            let idx_256 = terminal
                .palette_256
                .get(&palette_key)
                .or_else(|| terminal.palette_256.get(&af.key))
                .copied()
                .unwrap_or(7);
            let idx_16 = terminal
                .palette_16
                .get(&palette_key)
                .or_else(|| terminal.palette_16.get(&af.key))
                .copied()
                .unwrap_or(7);
            ColorEntry {
                key: af.key.clone(),
                key_upper: af.key.to_uppercase(),
                color_hex: af.color.clone(),
                color_256: idx_256,
                color_16: color_16_name(idx_16).to_string(),
            }
        })
        .collect();

    let data = TemplateData {
        version: doc.version.clone(),
        realms,
        layers,
        traits,
        arc_families,
    };

    // Render MiniJinja template
    let mut env = Environment::new();
    env.add_template("tui_colors.rs", TUI_COLORS_TEMPLATE)
        .map_err(|e| crate::NovaNetError::Generator {
            generator: "tui_colors".to_string(),
            detail: format!("template parse error: {e}"),
        })?;

    let tmpl = env
        .get_template("tui_colors.rs")
        .map_err(|e| crate::NovaNetError::Generator {
            generator: "tui_colors".to_string(),
            detail: format!("template not found: {e}"),
        })?;

    let output = tmpl
        .render(context! {
            version => data.version,
            realms => data.realms,
            layers => data.layers,
            traits => data.traits,
            arc_families => data.arc_families,
        })
        .map_err(|e| crate::NovaNetError::Generator {
            generator: "tui_colors".to_string(),
            detail: format!("template render error: {e}"),
        })?;

    Ok(output)
}

// ─────────────────────────────────────────────────────────────────────────────
// Tests
// ─────────────────────────────────────────────────────────────────────────────

#[cfg(test)]
mod tests {
    use super::*;
    use crate::generators::Generator;
    use crate::parsers::organizing::{ArcFamilyDef, LayerDef, OrganizingDoc, RealmDef, TraitDef};
    use serial_test::serial;

    fn make_test_data() -> (OrganizingDoc, TerminalPalette) {
        let doc = OrganizingDoc {
            version: "0.13.0".to_string(),
            realms: vec![
                RealmDef {
                    key: "shared".to_string(),
                    display_name: "Shared".to_string(),
                    emoji: "◉".to_string(),
                    color: "#2aa198".to_string(),
                    llm_context: "test".to_string(),
                    layers: vec![LayerDef {
                        key: "config".to_string(),
                        display_name: "Configuration".to_string(),
                        emoji: "⚙".to_string(),
                        color: "#64748b".to_string(),
                        llm_context: "test".to_string(),
                    }],
                },
                RealmDef {
                    key: "org".to_string(),
                    display_name: "Organization".to_string(),
                    emoji: "◎".to_string(),
                    color: "#6c71c4".to_string(),
                    llm_context: "test".to_string(),
                    layers: vec![LayerDef {
                        key: "semantic".to_string(),
                        display_name: "Semantic".to_string(),
                        emoji: "◆".to_string(),
                        color: "#f97316".to_string(),
                        llm_context: "test".to_string(),
                    }],
                },
            ],
            traits: vec![
                TraitDef {
                    key: "defined".to_string(),
                    display_name: "Defined".to_string(),
                    color: "#3b82f6".to_string(),
                    llm_context: "test".to_string(),
                },
                TraitDef {
                    key: "generated".to_string(),
                    display_name: "Generated".to_string(),
                    color: "#b58900".to_string(),
                    llm_context: "test".to_string(),
                },
            ],
            arc_families: vec![ArcFamilyDef {
                key: "ownership".to_string(),
                display_name: "Ownership".to_string(),
                color: "#3b82f6".to_string(),
                arrow_style: "-->".to_string(),
                llm_context: "test".to_string(),
            }],
        };

        let terminal = default_terminal_palette();

        (doc, terminal)
    }

    #[test]
    fn render_tui_colors_basic() {
        let (doc, terminal) = make_test_data();
        let output = render_tui_colors(&doc, &terminal).unwrap();

        // Header
        assert!(output.contains("AUTO-GENERATED by novanet v0.13.0"));
        assert!(output.contains("DO NOT EDIT"));

        // Realm colors
        assert!(output.contains("pub const SHARED_HEX: &str = \"#2aa198\""));
        assert!(output.contains("pub const ORG_HEX: &str = \"#6c71c4\""));
        assert!(output.contains("pub const SHARED_256: u8 = 37"));
        assert!(output.contains("pub const ORG_256: u8 = 141"));
    }

    #[test]
    fn render_tui_colors_layers() {
        let (doc, terminal) = make_test_data();
        let output = render_tui_colors(&doc, &terminal).unwrap();

        assert!(output.contains("pub const CONFIG_HEX: &str = \"#64748b\""));
        assert!(output.contains("pub const SEMANTIC_HEX: &str = \"#f97316\""));
    }

    #[test]
    fn render_tui_colors_traits() {
        let (doc, terminal) = make_test_data();
        let output = render_tui_colors(&doc, &terminal).unwrap();

        assert!(output.contains("pub const DEFINED_HEX: &str = \"#3b82f6\""));
        assert!(output.contains("pub const GENERATED_HEX: &str = \"#b58900\""));
        assert!(output.contains("pub const DEFINED_BORDER: &str = \"─\""));
        assert!(output.contains("pub const GENERATED_BORDER: &str = \"═\""));
    }

    #[test]
    fn render_tui_colors_arc_families() {
        let (doc, terminal) = make_test_data();
        let output = render_tui_colors(&doc, &terminal).unwrap();

        assert!(output.contains("pub const OWNERSHIP_HEX: &str = \"#3b82f6\""));
    }

    #[test]
    fn render_tui_colors_functions() {
        let (doc, terminal) = make_test_data();
        let output = render_tui_colors(&doc, &terminal).unwrap();

        assert!(output.contains("pub fn color(realm: &str, mode: ColorMode) -> Color"));
        assert!(output.contains("pub fn color(layer_key: &str, mode: ColorMode) -> Color"));
        assert!(output.contains("pub fn color(trait_key: &str, mode: ColorMode) -> Color"));
        assert!(output.contains("pub fn color(family: &str, mode: ColorMode) -> Color"));
        assert!(output.contains("pub fn border_char(trait_key: &str) -> &'static str"));
    }

    #[test]
    fn color_16_name_mapping() {
        assert_eq!(color_16_name(0), "Black");
        assert_eq!(color_16_name(2), "Green");
        assert_eq!(color_16_name(4), "Blue");
        assert_eq!(color_16_name(6), "Cyan");
        assert_eq!(color_16_name(11), "LightYellow");
        assert_eq!(color_16_name(255), "White"); // Fallback
    }

    #[test]
    fn trait_border_char_mapping() {
        assert_eq!(trait_border_char("defined"), "─");
        assert_eq!(trait_border_char("authored"), "┄");
        assert_eq!(trait_border_char("imported"), "┈");
        assert_eq!(trait_border_char("generated"), "═");
        assert_eq!(trait_border_char("retrieved"), "┅");
        assert_eq!(trait_border_char("unknown"), "─"); // Fallback
    }

    #[test]
    #[serial]
    fn generate_tui_colors_integration() {
        let root = std::path::Path::new(env!("CARGO_MANIFEST_DIR"))
            .parent()
            .and_then(|p| p.parent());

        let Some(root) = root else { return };
        if !root.join("pnpm-workspace.yaml").exists() {
            return;
        }

        let generator = TuiColorsGenerator;
        let output = generator
            .generate(root)
            .expect("should generate tui_colors.rs");

        // Should have all realms (v11.2: shared + org)
        assert!(output.contains("SHARED_HEX"));
        assert!(output.contains("ORG_HEX"));

        // Should have all 9 unique layer names
        for layer in [
            "CONFIG",
            "LOCALE",
            "GEOGRAPHY",
            "KNOWLEDGE",
            "SEMANTIC",
            "FOUNDATION",
            "STRUCTURE",
            "INSTRUCTION",
            "OUTPUT",
        ] {
            assert!(
                output.contains(&format!("{layer}_HEX")),
                "missing layer: {layer}"
            );
        }

        // Should have all 5 traits (v0.12.0: ADR-024 Data Origin)
        for tr in ["DEFINED", "AUTHORED", "IMPORTED", "GENERATED", "RETRIEVED"] {
            assert!(output.contains(&format!("{tr}_HEX")), "missing trait: {tr}");
        }

        // Should have all 5 arc families
        for af in [
            "OWNERSHIP",
            "LOCALIZATION",
            "SEMANTIC",
            "GENERATION",
            "MINING",
        ] {
            assert!(
                output.contains(&format!("{af}_HEX")),
                "missing arc family: {af}"
            );
        }
    }
}
