//! Generate `visual-encoding.ts` via MiniJinja template.
//!
//! Reads `visual-encoding.yaml` and produces TypeScript types + helpers for:
//! - Channel mapping (node: fill_color → layer, etc.)
//! - Node/arc states (default, focused, hover, selected, filtered)
//! - Trait border styles (CSS + Unicode for TUI)
//! - Scope stroke styles (intra/cross realm)
//! - Cardinality arrow heads
//! - Class icons (Lucide icon mapping) — v11.8: renamed from Kind icons
//! - Animation presets
//! - Accessibility settings
//!
//! Output target: `packages/core/src/graph/visual-encoding.ts`

use crate::parsers::visual_encoding::{self, VisualEncodingDoc};
use minijinja::{Environment, context};
use serde::Serialize;
use std::path::Path;

// ─────────────────────────────────────────────────────────────────────────────
// Helpers
// ─────────────────────────────────────────────────────────────────────────────

/// Escape single quotes for JavaScript string literals.
fn escape_js_string(s: &str) -> String {
    s.replace('\'', "\\'")
}

// ─────────────────────────────────────────────────────────────────────────────
// Template data structures
// ─────────────────────────────────────────────────────────────────────────────

/// Node state for template.
#[derive(Debug, Serialize)]
struct TemplateNodeState {
    key: String,
    opacity: f32,
    scale: f32,
    shadow: String,
    ring: String,
}

/// Arc state for template.
#[derive(Debug, Serialize)]
struct TemplateArcState {
    key: String,
    opacity: f32,
    stroke_width: f32,
    animated: bool,
    label_visible: bool,
}

/// Trait border for template.
#[derive(Debug, Serialize)]
struct TemplateTraitBorder {
    key: String,
    css_style: String,
    css_width: String,
    css_dash_array: String,
    css_corner_radius: String,
    unicode_char: String,
    unicode_style: String,
    description: String,
}

/// Scope stroke for template.
#[derive(Debug, Serialize)]
struct TemplateScopeStroke {
    key: String,
    stroke_style: String,
    opacity: f32,
    description: String,
}

/// Cardinality arrow for template.
#[derive(Debug, Serialize)]
struct TemplateCardinalityArrow {
    key: String,
    arrow_head: String,
    arrow_end: String,
    description: String,
}

/// Class icon for template (v11.8: renamed from Kind).
#[derive(Debug, Serialize)]
struct TemplateClassIcon {
    /// v11.8: field name preserved as "kind" for backward compatibility in template
    kind: String,
    icon: String,
}

/// Animation for template.
#[derive(Debug, Serialize)]
struct TemplateAnimation {
    key: String,
    duration_ms: u32,
    easing: String,
    stagger_ms: u32,
}

/// Icon entry for template (web + terminal).
#[derive(Debug, Serialize)]
struct TemplateIcon {
    key: String,
    web: String,
    terminal: String,
    description: String,
}

/// Icons category for template.
#[derive(Debug, Serialize)]
struct TemplateIconCategory {
    category: String,
    icons: Vec<TemplateIcon>,
}

/// Channel mapping for template.
#[derive(Debug, Serialize)]
struct TemplateChannelMapping {
    node_fill_color: String,
    node_border_style: String,
    node_border_color: String,
    node_icon: String,
    node_spatial_grouping: String,
    arc_stroke_color: String,
    arc_stroke_style: String,
    arc_arrow_head: String,
    arc_label_position: String,
}

/// Accessibility for template.
#[derive(Debug, Serialize)]
struct TemplateAccessibility {
    min_contrast_ratio: f32,
    use_patterns: bool,
    use_icons: bool,
    use_borders: bool,
    focus_ring_width: String,
    focus_ring_color: String,
    focus_ring_offset: String,
}

// ─────────────────────────────────────────────────────────────────────────────
// MiniJinja template
// ─────────────────────────────────────────────────────────────────────────────

const VISUAL_ENCODING_TEMPLATE: &str = r##"// packages/core/src/graph/visual-encoding.ts
// Visual encoding rules from visual-encoding.yaml
// AUTO-GENERATED by novanet v{{ version }} — DO NOT EDIT
// Run: cargo run -- schema generate

// =============================================================================
// CHANNEL MAPPING — Which visual channel encodes which facet
// =============================================================================

/**
 * Visual channel mapping for nodes.
 *
 * - fill_color: {{ channel_mapping.node_fill_color }} — Uses taxonomy colors
 * - border_style: {{ channel_mapping.node_border_style }} — Uses trait borders
 * - border_color: {{ channel_mapping.node_border_color }} — Uses realm colors
 * - icon: {{ channel_mapping.node_icon }} — Uses kind icons
 * - spatial_grouping: {{ channel_mapping.node_spatial_grouping }} — Layout clustering
 */
export const NODE_CHANNEL_MAPPING = {
  fillColor: '{{ channel_mapping.node_fill_color }}',
  borderStyle: '{{ channel_mapping.node_border_style }}',
  borderColor: '{{ channel_mapping.node_border_color }}',
  icon: '{{ channel_mapping.node_icon }}',
  spatialGrouping: '{{ channel_mapping.node_spatial_grouping }}',
} as const;

/**
 * Visual channel mapping for arcs.
 *
 * - stroke_color: {{ channel_mapping.arc_stroke_color }} — Uses family colors
 * - stroke_style: {{ channel_mapping.arc_stroke_style }} — solid (intra) vs dashed (cross)
 * - arrow_head: {{ channel_mapping.arc_arrow_head }} — Based on relationship cardinality
 * - label_position: {{ channel_mapping.arc_label_position }} — center or offset
 */
export const ARC_CHANNEL_MAPPING = {
  strokeColor: '{{ channel_mapping.arc_stroke_color }}',
  strokeStyle: '{{ channel_mapping.arc_stroke_style }}',
  arrowHead: '{{ channel_mapping.arc_arrow_head }}',
  labelPosition: '{{ channel_mapping.arc_label_position }}',
} as const;

// =============================================================================
// NODE STATES ({{ node_states | length }})
// =============================================================================

export type NodeStateKey = {% for s in node_states %}'{{ s.key }}'{{ " | " if not loop.last else "" }}{% endfor %};

export interface NodeStateStyle {
  opacity: number;
  scale: number;
  shadow: string | null;
  ring: string | null;
}

export const NODE_STATES: Record<NodeStateKey, NodeStateStyle> = {
{%- for s in node_states %}
  {{ s.key }}: {
    opacity: {{ s.opacity }},
    scale: {{ s.scale }},
    shadow: {{ "'" ~ s.shadow ~ "'" if s.shadow else "null" }},
    ring: {{ "'" ~ s.ring ~ "'" if s.ring else "null" }},
  },
{%- endfor %}
};

// =============================================================================
// ARC STATES ({{ arc_states | length }})
// =============================================================================

export type ArcStateKey = {% for s in arc_states %}'{{ s.key }}'{{ " | " if not loop.last else "" }}{% endfor %};

export interface ArcStateStyle {
  opacity: number;
  strokeWidth: number;
  animated: boolean;
  labelVisible: boolean;
}

export const ARC_STATES: Record<ArcStateKey, ArcStateStyle> = {
{%- for s in arc_states %}
  {{ s.key }}: {
    opacity: {{ s.opacity }},
    strokeWidth: {{ s.stroke_width }},
    animated: {{ "true" if s.animated else "false" }},
    labelVisible: {{ "true" if s.label_visible else "false" }},
  },
{%- endfor %}
};

// =============================================================================
// TRAIT BORDERS ({{ trait_borders | length }}) — Studio CSS + TUI Unicode
// =============================================================================

export type TraitKey = {% for b in trait_borders %}'{{ b.key }}'{{ " | " if not loop.last else "" }}{% endfor %};

export interface TraitBorderStyle {
  cssStyle: string;
  cssWidth: string;
  cssDashArray: string | null;
  cssCornerRadius: string | null;
  unicodeChar: string;
  unicodeStyle: string;
  description: string;
}

export const TRAIT_BORDERS: Record<TraitKey, TraitBorderStyle> = {
{%- for b in trait_borders %}
  {{ b.key }}: {
    cssStyle: '{{ b.css_style }}',
    cssWidth: '{{ b.css_width }}',
    cssDashArray: {{ "'" ~ b.css_dash_array ~ "'" if b.css_dash_array else "null" }},
    cssCornerRadius: {{ "'" ~ b.css_corner_radius ~ "'" if b.css_corner_radius else "null" }},
    unicodeChar: '{{ b.unicode_char }}',
    unicodeStyle: '{{ b.unicode_style }}',
    description: '{{ b.description }}',
  },
{%- endfor %}
};

// =============================================================================
// SCOPE STROKES ({{ scope_strokes | length }}) — Intra vs Cross realm arcs
// =============================================================================

export type ScopeKey = {% for s in scope_strokes %}'{{ s.key }}'{{ " | " if not loop.last else "" }}{% endfor %};

export interface ScopeStrokeStyle {
  strokeStyle: string;
  opacity: number;
  description: string;
}

export const SCOPE_STROKES: Record<ScopeKey, ScopeStrokeStyle> = {
{%- for s in scope_strokes %}
  {{ s.key }}: {
    strokeStyle: '{{ s.stroke_style }}',
    opacity: {{ s.opacity }},
    description: '{{ s.description }}',
  },
{%- endfor %}
};

// =============================================================================
// CARDINALITY ARROWS ({{ cardinality_arrows | length }})
// =============================================================================

export type CardinalityKey = {% for a in cardinality_arrows %}'{{ a.key }}'{{ " | " if not loop.last else "" }}{% endfor %};

export interface CardinalityArrowStyle {
  arrowHead: string;
  arrowEnd: string;
  description: string;
}

export const CARDINALITY_ARROWS: Record<CardinalityKey, CardinalityArrowStyle> = {
{%- for a in cardinality_arrows %}
  {{ a.key }}: {
    arrowHead: '{{ a.arrow_head }}',
    arrowEnd: '{{ a.arrow_end }}',
    description: '{{ a.description }}',
  },
{%- endfor %}
};

// =============================================================================
// CLASS ICONS ({{ class_icons | length }}) — Lucide icon names
// =============================================================================

export const CLASS_ICONS: Record<string, string> = {
{%- for i in class_icons %}
  {{ i.kind }}: '{{ i.icon }}',
{%- endfor %}
};

/**
 * Get Lucide icon name for a Class.
 */
export function getClassIcon(className: string): string {
  return CLASS_ICONS[className] ?? 'circle';
}

// =============================================================================
// ANIMATIONS ({{ animations | length }}) — Studio only
// =============================================================================

export type AnimationKey = {% for a in animations %}'{{ a.key }}'{{ " | " if not loop.last else "" }}{% endfor %};

export interface AnimationPreset {
  durationMs: number;
  easing: string;
  staggerMs: number;
}

export const ANIMATIONS: Record<AnimationKey, AnimationPreset> = {
{%- for a in animations %}
  {{ a.key }}: {
    durationMs: {{ a.duration_ms }},
    easing: '{{ a.easing }}',
    staggerMs: {{ a.stagger_ms }},
  },
{%- endfor %}
};

// =============================================================================
// ACCESSIBILITY
// =============================================================================

export const ACCESSIBILITY = {
  minContrastRatio: {{ accessibility.min_contrast_ratio }},
  usePatterns: {{ "true" if accessibility.use_patterns else "false" }},
  useIcons: {{ "true" if accessibility.use_icons else "false" }},
  useBorders: {{ "true" if accessibility.use_borders else "false" }},
  focusRingWidth: '{{ accessibility.focus_ring_width }}',
  focusRingColor: '{{ accessibility.focus_ring_color }}',
  focusRingOffset: '{{ accessibility.focus_ring_offset }}',
} as const;

// =============================================================================
// HELPER FUNCTIONS
// =============================================================================

/**
 * Get node state style by key.
 */
export function getNodeState(key: NodeStateKey): NodeStateStyle {
  return NODE_STATES[key];
}

/**
 * Get arc state style by key.
 */
export function getArcState(key: ArcStateKey): ArcStateStyle {
  return ARC_STATES[key];
}

/**
 * Get trait border style by trait key.
 */
export function getTraitBorder(trait: TraitKey): TraitBorderStyle {
  return TRAIT_BORDERS[trait];
}

/**
 * Get scope stroke style by scope key.
 */
export function getScopeStroke(scope: ScopeKey): ScopeStrokeStyle {
  return SCOPE_STROKES[scope];
}

/**
 * Get animation preset by key.
 */
export function getAnimation(key: AnimationKey): AnimationPreset {
  return ANIMATIONS[key];
}

// =============================================================================
// ICON SYSTEM (v10.6) — Single source of truth for all icons
// =============================================================================
// Each icon has: web (Lucide name) + terminal (Unicode) + description
// Categories: realms, layers, traits, arc_families, states, navigation, quality, modes

export interface IconDefinition {
  web: string;      // Lucide icon name for Studio/web
  terminal: string; // Unicode symbol for TUI
  description: string;
}

{%- for cat in icon_categories %}

// {{ cat.category | upper }} ICONS ({{ cat.icons | length }})
export const {{ cat.category | upper }}_ICONS: Record<string, IconDefinition> = {
{%- for icon in cat.icons %}
  '{{ icon.key }}': { web: '{{ icon.web }}', terminal: '{{ icon.terminal }}', description: '{{ icon.description }}' },
{%- endfor %}
};
{%- endfor %}

/**
 * All icon categories combined.
 */
export const ICONS = {
{%- for cat in icon_categories %}
  {{ cat.category }}: {{ cat.category | upper }}_ICONS,
{%- endfor %}
} as const;

/**
 * Get icon by category and key.
 */
export function getIcon(category: keyof typeof ICONS, key: string): IconDefinition | undefined {
  return ICONS[category]?.[key];
}

/**
 * Get Lucide icon name by category and key.
 */
export function getWebIcon(category: keyof typeof ICONS, key: string): string {
  return ICONS[category]?.[key]?.web ?? 'circle';
}

/**
 * Get terminal Unicode icon by category and key.
 */
export function getTerminalIcon(category: keyof typeof ICONS, key: string): string {
  return ICONS[category]?.[key]?.terminal ?? '·';
}
"##;

// ─────────────────────────────────────────────────────────────────────────────
// Generator
// ─────────────────────────────────────────────────────────────────────────────

pub struct VisualEncodingGenerator;

impl super::Generator for VisualEncodingGenerator {
    fn name(&self) -> &'static str {
        "visual_encoding"
    }

    fn generate(&self, root: &Path) -> crate::Result<String> {
        let doc = visual_encoding::load_visual_encoding(root)?;
        render_visual_encoding(&doc)
    }
}

fn render_visual_encoding(doc: &VisualEncodingDoc) -> crate::Result<String> {
    // Channel mapping
    let channel_mapping = TemplateChannelMapping {
        node_fill_color: doc.channel_mapping.node.fill_color.clone(),
        node_border_style: doc.channel_mapping.node.border_style.clone(),
        node_border_color: doc.channel_mapping.node.border_color.clone(),
        node_icon: doc.channel_mapping.node.icon.clone(),
        node_spatial_grouping: doc.channel_mapping.node.spatial_grouping.clone(),
        arc_stroke_color: doc.channel_mapping.arc.stroke_color.clone(),
        arc_stroke_style: doc.channel_mapping.arc.stroke_style.clone(),
        arc_arrow_head: doc.channel_mapping.arc.arrow_head.clone(),
        arc_label_position: doc.channel_mapping.arc.label_position.clone(),
    };

    // Node states (sorted by key for deterministic output)
    let mut node_states: Vec<TemplateNodeState> = doc
        .node_states
        .iter()
        .map(|(key, state)| TemplateNodeState {
            key: key.clone(),
            opacity: state.opacity,
            scale: state.scale,
            shadow: state.shadow.clone().unwrap_or_default(),
            ring: state.ring.clone().unwrap_or_default(),
        })
        .collect();
    node_states.sort_by(|a, b| a.key.cmp(&b.key));

    // Arc states (sorted)
    let mut arc_states: Vec<TemplateArcState> = doc
        .arc_states
        .iter()
        .map(|(key, state)| TemplateArcState {
            key: key.clone(),
            opacity: state.opacity,
            stroke_width: state.stroke_width,
            animated: state.animated.unwrap_or(false),
            label_visible: state.label_visible.unwrap_or(false),
        })
        .collect();
    arc_states.sort_by(|a, b| a.key.cmp(&b.key));

    // Trait borders (sorted)
    let mut trait_borders: Vec<TemplateTraitBorder> = doc
        .trait_borders
        .iter()
        .map(|(key, border)| TemplateTraitBorder {
            key: key.clone(),
            css_style: border.css_style.clone(),
            css_width: border.css_width.clone(),
            css_dash_array: border.css_dash_array.clone().unwrap_or_default(),
            css_corner_radius: border.css_corner_radius.clone().unwrap_or_default(),
            unicode_char: border.unicode_char.clone(),
            unicode_style: border.unicode_style.clone(),
            description: escape_js_string(&border.description),
        })
        .collect();
    trait_borders.sort_by(|a, b| a.key.cmp(&b.key));

    // Scope strokes (sorted)
    let mut scope_strokes: Vec<TemplateScopeStroke> = doc
        .scope_strokes
        .iter()
        .map(|(key, stroke)| TemplateScopeStroke {
            key: key.clone(),
            stroke_style: stroke.stroke_style.clone(),
            opacity: stroke.opacity,
            description: escape_js_string(&stroke.description),
        })
        .collect();
    scope_strokes.sort_by(|a, b| a.key.cmp(&b.key));

    // Cardinality arrows (sorted)
    let mut cardinality_arrows: Vec<TemplateCardinalityArrow> = doc
        .cardinality_arrows
        .iter()
        .map(|(key, arrow)| TemplateCardinalityArrow {
            key: key.clone(),
            arrow_head: arrow.arrow_head.clone(),
            arrow_end: arrow.arrow_end.clone(),
            description: escape_js_string(&arrow.description),
        })
        .collect();
    cardinality_arrows.sort_by(|a, b| a.key.cmp(&b.key));

    // Class icons (sorted by class name) — v11.8: renamed from Kind icons
    let mut class_icons: Vec<TemplateClassIcon> = doc
        .class_icons
        .iter()
        .map(|(kind, icon)| TemplateClassIcon {
            kind: kind.clone(),
            icon: icon.clone(),
        })
        .collect();
    class_icons.sort_by(|a, b| a.kind.cmp(&b.kind));

    // Animations (sorted)
    let mut animations: Vec<TemplateAnimation> = doc
        .animations
        .iter()
        .map(|(key, anim)| TemplateAnimation {
            key: key.clone(),
            duration_ms: anim.duration_ms,
            easing: anim.easing.clone(),
            stagger_ms: anim.stagger_ms.unwrap_or(0),
        })
        .collect();
    animations.sort_by(|a, b| a.key.cmp(&b.key));

    // Accessibility
    let accessibility = TemplateAccessibility {
        min_contrast_ratio: doc.accessibility.min_contrast_ratio,
        use_patterns: doc.accessibility.use_patterns,
        use_icons: doc.accessibility.use_icons,
        use_borders: doc.accessibility.use_borders,
        focus_ring_width: doc.accessibility.focus_ring_width.clone(),
        focus_ring_color: doc.accessibility.focus_ring_color.clone(),
        focus_ring_offset: doc.accessibility.focus_ring_offset.clone(),
    };

    // Icon categories (v10.6)
    let icon_categories = build_icon_categories(doc);

    // Render template
    let mut env = Environment::new();
    env.add_template("visual-encoding.ts", VISUAL_ENCODING_TEMPLATE)
        .map_err(|e| crate::NovaNetError::Generator {
            generator: "visual_encoding".to_string(),
            detail: format!("template parse error: {e}"),
        })?;

    let tmpl =
        env.get_template("visual-encoding.ts")
            .map_err(|e| crate::NovaNetError::Generator {
                generator: "visual_encoding".to_string(),
                detail: format!("template not found: {e}"),
            })?;

    let output = tmpl
        .render(context! {
            version => doc.version,
            channel_mapping => channel_mapping,
            node_states => node_states,
            arc_states => arc_states,
            trait_borders => trait_borders,
            scope_strokes => scope_strokes,
            cardinality_arrows => cardinality_arrows,
            class_icons => class_icons,
            animations => animations,
            accessibility => accessibility,
            icon_categories => icon_categories,
        })
        .map_err(|e| crate::NovaNetError::Generator {
            generator: "visual_encoding".to_string(),
            detail: format!("template render error: {e}"),
        })?;

    Ok(output)
}

/// Build icon categories from the Icons section of visual-encoding.yaml.
fn build_icon_categories(doc: &VisualEncodingDoc) -> Vec<TemplateIconCategory> {
    let Some(ref icons) = doc.icons else {
        return Vec::new();
    };

    let mut categories = Vec::new();

    // Helper to convert HashMap to sorted Vec of TemplateIcon
    let to_icons =
        |map: &std::collections::HashMap<String, crate::parsers::visual_encoding::Icon>| {
            let mut items: Vec<TemplateIcon> = map
                .iter()
                .map(|(key, icon)| TemplateIcon {
                    key: key.clone(),
                    web: icon.web.clone(),
                    terminal: icon.terminal.clone(),
                    description: escape_js_string(&icon.description),
                })
                .collect();
            items.sort_by(|a, b| a.key.cmp(&b.key));
            items
        };

    // Add each category in a defined order
    if !icons.realms.is_empty() {
        categories.push(TemplateIconCategory {
            category: "realms".to_string(),
            icons: to_icons(&icons.realms),
        });
    }

    if !icons.layers.is_empty() {
        categories.push(TemplateIconCategory {
            category: "layers".to_string(),
            icons: to_icons(&icons.layers),
        });
    }

    if !icons.traits.is_empty() {
        categories.push(TemplateIconCategory {
            category: "traits".to_string(),
            icons: to_icons(&icons.traits),
        });
    }

    if !icons.arc_families.is_empty() {
        categories.push(TemplateIconCategory {
            category: "arc_families".to_string(),
            icons: to_icons(&icons.arc_families),
        });
    }

    if !icons.states.is_empty() {
        categories.push(TemplateIconCategory {
            category: "states".to_string(),
            icons: to_icons(&icons.states),
        });
    }

    if !icons.navigation.is_empty() {
        categories.push(TemplateIconCategory {
            category: "navigation".to_string(),
            icons: to_icons(&icons.navigation),
        });
    }

    if !icons.quality.is_empty() {
        categories.push(TemplateIconCategory {
            category: "quality".to_string(),
            icons: to_icons(&icons.quality),
        });
    }

    if !icons.modes.is_empty() {
        categories.push(TemplateIconCategory {
            category: "modes".to_string(),
            icons: to_icons(&icons.modes),
        });
    }

    categories
}

// ─────────────────────────────────────────────────────────────────────────────
// Tests
// ─────────────────────────────────────────────────────────────────────────────

#[cfg(test)]
mod tests {
    use super::*;
    use crate::generators::Generator;
    use serial_test::serial;

    #[test]
    #[serial]
    fn generate_visual_encoding_integration() {
        let root = std::path::Path::new(env!("CARGO_MANIFEST_DIR"))
            .parent()
            .and_then(|p| p.parent());

        let Some(root) = root else { return };
        if !root.join("pnpm-workspace.yaml").exists() {
            return;
        }

        let generator = VisualEncodingGenerator;
        let output = generator
            .generate(root)
            .expect("should generate visual-encoding.ts");

        // Header
        assert!(output.contains("AUTO-GENERATED by novanet v0.13.0")); // v0.13.0
        assert!(output.contains("visual-encoding.yaml"));

        // Channel mapping
        assert!(output.contains("NODE_CHANNEL_MAPPING"));
        assert!(output.contains("ARC_CHANNEL_MAPPING"));
        assert!(output.contains("fillColor: 'layer'"));
        assert!(output.contains("strokeColor: 'family'"));

        // Node states
        assert!(output.contains("export type NodeStateKey ="));
        assert!(output.contains("'default'"));
        assert!(output.contains("'focused'"));
        assert!(output.contains("NODE_STATES:"));

        // Arc states
        assert!(output.contains("export type ArcStateKey ="));
        assert!(output.contains("ARC_STATES:"));

        // Trait borders
        assert!(output.contains("TRAIT_BORDERS:"));
        assert!(output.contains("cssStyle: 'solid'"));
        assert!(output.contains("unicodeChar:"));

        // Scope strokes
        assert!(output.contains("SCOPE_STROKES:"));
        assert!(output.contains("intra_realm"));
        assert!(output.contains("cross_realm"));

        // Cardinality arrows
        assert!(output.contains("CARDINALITY_ARROWS:"));
        assert!(output.contains("one_to_one"));
        assert!(output.contains("one_to_many"));

        // Class icons
        assert!(output.contains("CLASS_ICONS:"));
        assert!(output.contains("Locale: 'globe'"));
        assert!(output.contains("Page: 'file-text'"));
        assert!(output.contains("export function getClassIcon"));

        // Animations
        assert!(output.contains("ANIMATIONS:"));
        assert!(output.contains("durationMs:"));
        assert!(output.contains("easing:"));

        // Accessibility
        assert!(output.contains("ACCESSIBILITY"));
        assert!(output.contains("minContrastRatio:"));
        assert!(output.contains("focusRingWidth:"));

        // Helper functions
        assert!(output.contains("export function getNodeState"));
        assert!(output.contains("export function getArcState"));
        assert!(output.contains("export function getTraitBorder"));
        assert!(output.contains("export function getScopeStroke"));
        assert!(output.contains("export function getAnimation"));

        // Icon system (v10.6)
        assert!(output.contains("ICON SYSTEM (v10.6)"));
        assert!(output.contains("export interface IconDefinition"));

        // Icon categories
        assert!(output.contains("REALMS_ICONS:"));
        assert!(output.contains("LAYERS_ICONS:"));
        assert!(output.contains("TRAITS_ICONS:"));
        assert!(output.contains("ARC_FAMILIES_ICONS:"));
        assert!(output.contains("STATES_ICONS:"));
        assert!(output.contains("NAVIGATION_ICONS:"));
        assert!(output.contains("QUALITY_ICONS:"));
        assert!(output.contains("MODES_ICONS:"));

        // Icon entries (spot check) - keys are quoted for consistency with hyphenated keys
        assert!(output.contains("'shared': { web: 'globe', terminal: '◉'"));
        assert!(output.contains("'org': { web: 'building-2', terminal: '◎'"));
        assert!(output.contains("'defined': { web: 'lock', terminal: '■'"));
        assert!(output.contains("'authored': { web: 'pen', terminal: '□'")); // v0.12.0: pen icon
        assert!(output.contains("'expanded': { web: 'chevron-down', terminal: '▼'"));
        assert!(output.contains("'collapsed': { web: 'chevron-right', terminal: '▶'"));

        // Combined ICONS object
        assert!(output.contains("export const ICONS = {"));
        assert!(output.contains("realms: REALMS_ICONS"));
        assert!(output.contains("modes: MODES_ICONS"));

        // Helper functions for icons
        assert!(
            output.contains("export function getIcon(category: keyof typeof ICONS, key: string)")
        );
        assert!(
            output
                .contains("export function getWebIcon(category: keyof typeof ICONS, key: string)")
        );
        assert!(output.contains(
            "export function getTerminalIcon(category: keyof typeof ICONS, key: string)"
        ));
    }
}
