//! `novanet doc generate` and `novanet doc list` commands.
//!
//! - generate: Produces Mermaid-in-Markdown docs for individual views
//! - list: Shows available views with categories from the registry

use std::fs;
use std::path::Path;
use std::time::Instant;

// ─────────────────────────────────────────────────────────────────────────────
// Doc Generate
// ─────────────────────────────────────────────────────────────────────────────

/// Result of generating a single view document.
pub struct DocGenerateResult {
    pub view_id: String,
    pub view_name: String,
    pub output_path: String,
    pub bytes: usize,
    pub duration_ms: u128,
}

/// Generate Mermaid documentation for one or all views.
///
/// - If `view_id` is `Some`, generates only that view.
/// - If `view_id` is `None`, generates all views (skips `complete-graph`).
/// - If `dry_run` is `true`, generates output but does not write files.
///
/// Output: `packages/core/models/docs/<view-id>.md`
pub fn doc_generate(
    root: &Path,
    view_id: Option<&str>,
    dry_run: bool,
) -> crate::Result<Vec<DocGenerateResult>> {
    let views = match view_id {
        Some(id) => vec![crate::parsers::views::load_view(root, id)?],
        None => {
            let mut all = crate::parsers::views::load_all_views(root)?;
            // complete-graph is produced by `novanet schema generate`, skip it here
            all.retain(|v| v.id != "complete-graph");
            all
        }
    };

    let docs_dir = crate::config::docs_dir(root);
    let mut results = Vec::with_capacity(views.len());

    for view in &views {
        let start = Instant::now();
        let output = crate::generators::view_mermaid::generate_view(root, view)?;
        let duration_ms = start.elapsed().as_millis();
        let bytes = output.len();

        let rel_path = format!("packages/core/models/docs/{}.md", view.id);

        if !dry_run {
            fs::create_dir_all(&docs_dir).map_err(crate::NovaNetError::Io)?;
            let full_path = docs_dir.join(format!("{}.md", view.id));
            fs::write(&full_path, &output).map_err(crate::NovaNetError::Io)?;
        }

        results.push(DocGenerateResult {
            view_id: view.id.clone(),
            view_name: view.name.clone(),
            output_path: rel_path,
            bytes,
            duration_ms,
        });
    }

    Ok(results)
}

// ─────────────────────────────────────────────────────────────────────────────
// Doc List
// ─────────────────────────────────────────────────────────────────────────────

/// Entry for display in `novanet doc generate --list`.
pub struct DocListEntry {
    pub id: String,
    pub category: String,
    pub description: String,
}

/// List available views from the registry.
pub fn doc_list(root: &Path) -> crate::Result<Vec<DocListEntry>> {
    let registry = crate::parsers::views::load_registry(root)?;
    let entries = registry
        .views
        .into_iter()
        // Skip complete-graph (handled by schema generate)
        .filter(|v| v.id != "complete-graph")
        .map(|v| DocListEntry {
            id: v.id,
            category: v.category,
            description: v.description,
        })
        .collect();
    Ok(entries)
}

// ─────────────────────────────────────────────────────────────────────────────
// Tests
// ─────────────────────────────────────────────────────────────────────────────

#[cfg(test)]
mod tests {
    use super::*;

    fn test_root() -> Option<std::path::PathBuf> {
        let root = std::path::Path::new(env!("CARGO_MANIFEST_DIR"))
            .parent()
            .and_then(|p| p.parent());
        let root = root?;
        if !root.join("pnpm-workspace.yaml").exists() {
            return None;
        }
        Some(root.to_path_buf())
    }

    #[test]
    fn doc_generate_dry_run_all() {
        let Some(root) = test_root() else { return };

        let results = doc_generate(&root, None, true).expect("should generate all view docs");

        // At least 11 views (complete-graph is skipped, geo-pipeline removed in v10.1)
        assert!(
            results.len() >= 11,
            "expected at least 11 view docs, got {}",
            results.len()
        );

        // Verify no complete-graph in results
        assert!(
            !results.iter().any(|r| r.view_id == "complete-graph"),
            "complete-graph should not be generated by doc command"
        );

        for r in &results {
            assert!(
                r.bytes > 100,
                "view '{}': expected >100 bytes, got {}",
                r.view_id,
                r.bytes
            );
            assert!(
                r.output_path.ends_with(".md"),
                "view '{}': output should be .md",
                r.view_id
            );
            assert!(
                r.output_path.contains(&r.view_id),
                "view '{}': output path should contain view id",
                r.view_id
            );
        }
    }

    #[test]
    fn doc_generate_dry_run_single() {
        let Some(root) = test_root() else { return };

        let results = doc_generate(&root, Some("block-generation"), true)
            .expect("should generate single view");

        assert_eq!(results.len(), 1);
        assert_eq!(results[0].view_id, "block-generation");
        assert!(results[0].bytes > 100);
    }

    #[test]
    fn doc_generate_nonexistent_view() {
        let Some(root) = test_root() else { return };

        let result = doc_generate(&root, Some("nonexistent"), true);
        assert!(result.is_err());
    }

    #[test]
    fn doc_list_returns_views() {
        let Some(root) = test_root() else { return };

        let entries = doc_list(&root).expect("should list views");

        // 11 entries (complete-graph skipped, geo-pipeline removed in v10.1)
        assert!(
            entries.len() >= 11,
            "expected at least 11 list entries, got {}",
            entries.len()
        );

        // Verify no complete-graph
        assert!(
            !entries.iter().any(|e| e.id == "complete-graph"),
            "complete-graph should not appear in doc list"
        );

        // Every entry should have non-empty fields
        for e in &entries {
            assert!(!e.id.is_empty(), "empty id");
            assert!(!e.category.is_empty(), "empty category for {}", e.id);
            assert!(!e.description.is_empty(), "empty description for {}", e.id);
        }
    }
}
