// apps/studio/src/design/icons/nodeIcons.generated.ts
// Node icons from YAML definitions (SINGLE SOURCE OF TRUTH)
// AUTO-GENERATED by novanet v10.0.0 — DO NOT EDIT
// Run: cargo run -- schema generate

import type { NodeType } from '@novanet/core/types';

// =============================================================================
// NODE ICONS (44 nodes)
// =============================================================================

/**
 * Emoji icons for all 44 node types.
 *
 * Each icon is defined in the node's YAML file under `node.icon`.
 * Source: packages/core/models/node-kinds/<realm>/<layer>/<name>.yaml
 */
export const NODE_ICONS: Record<NodeType, string> = {
  Block: '🔷',
  BlockL10n: '🟠',
  BlockPrompt: '🔵',
  BlockRules: '🔵',
  BlockType: '🔷',
  BrandIdentity: '🔷',
  Concept: '🔷',
  ConceptL10n: '🟢',
  Constraint: '⚠️',
  ContentSlot: '🔲',
  EvaluationSignal: '📊',
  Expression: '💭',
  GEOMiningRun: '⚙️',
  GEOSeedL10n: '🤖',
  GEOSeedMetrics: '📑',
  GenerationJob: '🚀',
  Locale: '🔷',
  LocaleCulture: '🏛️',
  LocaleCultureReferences: '🎯',
  LocaleIdentity: '🆔',
  LocaleLexicon: '📚',
  LocaleMarket: '📈',
  LocaleRulesAdaptation: '🔄',
  LocaleRulesFormatting: '📐',
  LocaleRulesSlug: '🔗',
  LocaleVoice: '🎭',
  Metaphor: '🎭',
  OutputArtifact: '📦',
  Page: '🔷',
  PageL10n: '🟠',
  PagePrompt: '🔵',
  PageType: '📐',
  Pattern: '📐',
  Project: '🔷',
  ProjectL10n: '🟢',
  PromptArtifact: '📋',
  Reference: '🎯',
  SEOKeywordL10n: '🔍',
  SEOKeywordMetrics: '📸',
  SEOMiningRun: '⚙️',
  SearchIntent: '🎯',
  Thing: '🔮',
  ThingL10n: '🌐',
  TopicCluster: '🎪',
};

/**
 * Get the emoji icon for a node type.
 *
 * @param type - The NodeType to get icon for
 * @returns The emoji icon string
 */
export function getNodeIcon(type: NodeType): string {
  return NODE_ICONS[type] ?? '📄';
}

/**
 * Default icon for unknown node types.
 */
export const DEFAULT_NODE_ICON = '📄';