//! TUI icons from visual-encoding.yaml (SINGLE SOURCE OF TRUTH)
//! AUTO-GENERATED by novanet v11.7.0 — DO NOT EDIT
//! Run: cargo run -- schema generate

use std::collections::HashMap;

/// Icon with web (Lucide) and terminal (Unicode) variants.
#[derive(Debug, Clone)]
pub struct IconDef {
    pub web: &'static str,
    pub terminal: &'static str,
    pub description: &'static str,
}

impl IconDef {
    const fn new(web: &'static str, terminal: &'static str, description: &'static str) -> Self {
        Self { web, terminal, description }
    }
}

// =============================================================================
// REALMS ICONS (2)
// =============================================================================

pub const REALMS_ORG: IconDef = IconDef::new("building-2", "◎", "Organization-specific data");
pub const REALMS_SHARED: IconDef = IconDef::new("globe", "◉", "Universal shared data (read-only)");

// =============================================================================
// LAYERS ICONS (9)
// =============================================================================

pub const LAYERS_CONFIG: IconDef = IconDef::new("settings", "⚙", "Configuration and definitions");
pub const LAYERS_FOUNDATION: IconDef = IconDef::new("landmark", "▣", "Project identity and branding");
pub const LAYERS_GEOGRAPHY: IconDef = IconDef::new("map", "⊙", "Geographic classifications");
pub const LAYERS_INSTRUCTION: IconDef = IconDef::new("file-text", "▧", "Generation directives");
pub const LAYERS_KNOWLEDGE: IconDef = IconDef::new("book-open", "◈", "Locale expertise and knowledge atoms");
pub const LAYERS_LOCALE: IconDef = IconDef::new("globe", "⊕", "Locale settings and formatting");
pub const LAYERS_OUTPUT: IconDef = IconDef::new("check-circle", "●", "Generated content");
pub const LAYERS_SEMANTIC: IconDef = IconDef::new("lightbulb", "◆", "Entities and meaning");
pub const LAYERS_STRUCTURE: IconDef = IconDef::new("layout", "▤", "Information architecture");

// =============================================================================
// TRAITS ICONS (5)
// =============================================================================

pub const TRAITS_AGGREGATED: IconDef = IconDef::new("calculator", "▪", "Computed metrics and analytics");
pub const TRAITS_GENERATED: IconDef = IconDef::new("sparkles", "★", "LLM-generated content output");
pub const TRAITS_INVARIANT: IconDef = IconDef::new("lock", "■", "Stable across all locales");
pub const TRAITS_KNOWLEDGE: IconDef = IconDef::new("brain", "◊", "Locale expertise data");
pub const TRAITS_LOCALIZED: IconDef = IconDef::new("globe", "□", "Generated natively per locale");

// =============================================================================
// ARC_FAMILIES ICONS (5)
// =============================================================================

pub const ARC_FAMILIES_GENERATION: IconDef = IconDef::new("sparkles", "⇒", "LLM pipeline flow");
pub const ARC_FAMILIES_LOCALIZATION: IconDef = IconDef::new("languages", "⇢", "Locale content links");
pub const ARC_FAMILIES_MINING: IconDef = IconDef::new("pickaxe", "⇝", "SEO data extraction");
pub const ARC_FAMILIES_OWNERSHIP: IconDef = IconDef::new("arrow-right", "→", "Parent-child structural");
pub const ARC_FAMILIES_SEMANTIC: IconDef = IconDef::new("link", "~", "Meaning connections");

// =============================================================================
// STATES ICONS (8)
// =============================================================================

pub const STATES_ERROR: IconDef = IconDef::new("x", "✗", "Operation failed");
pub const STATES_LOADING: IconDef = IconDef::new("loader", "◐", "Data loading in progress");
pub const STATES_NO_CONNECTION: IconDef = IconDef::new("wifi-off", "⚠", "Database not connected");
pub const STATES_NO_INSTANCES: IconDef = IconDef::new("file-x", "□", "Kind has no instances");
pub const STATES_NO_KINDS: IconDef = IconDef::new("inbox", "∅", "No node kinds found");
pub const STATES_NO_RESULTS: IconDef = IconDef::new("search-x", "◌", "Query returned nothing");
pub const STATES_SUCCESS: IconDef = IconDef::new("check", "✓", "Operation succeeded");
pub const STATES_WARNING: IconDef = IconDef::new("alert-triangle", "⚠", "Warning condition");

// =============================================================================
// NAVIGATION ICONS (7)
// =============================================================================

pub const NAVIGATION_BACK: IconDef = IconDef::new("arrow-left", "←", "Navigate back");
pub const NAVIGATION_COLLAPSED: IconDef = IconDef::new("chevron-right", "▶", "Node collapsed");
pub const NAVIGATION_COPY: IconDef = IconDef::new("clipboard", "□", "Copy to clipboard");
pub const NAVIGATION_EXPANDED: IconDef = IconDef::new("chevron-down", "▼", "Node expanded");
pub const NAVIGATION_HELP: IconDef = IconDef::new("help-circle", "?", "Help overlay");
pub const NAVIGATION_LEAF: IconDef = IconDef::new("dot", "·", "Leaf node (no children)");
pub const NAVIGATION_SEARCH: IconDef = IconDef::new("search", "/", "Search mode");

// =============================================================================
// QUALITY ICONS (6)
// =============================================================================

pub const QUALITY_CHART: IconDef = IconDef::new("bar-chart-2", "≡", "Statistics/chart header");
pub const QUALITY_COMPLETE: IconDef = IconDef::new("check-circle", "●", "All required fields present");
pub const QUALITY_EMPTY: IconDef = IconDef::new("circle", "○", "No data");
pub const QUALITY_OPTIONAL: IconDef = IconDef::new("minus", " ", "Optional field marker");
pub const QUALITY_PARTIAL: IconDef = IconDef::new("circle-dot", "◐", "Some fields missing");
pub const QUALITY_REQUIRED: IconDef = IconDef::new("asterisk", "*", "Required field marker");

// =============================================================================
// MODES ICONS (v11.7: 2 modes - Graph and Nexus)
// =============================================================================

/// v11.7: Unified tree mode (replaces Data/Meta/Overlay/Query)
pub const MODES_GRAPH: IconDef = IconDef::new("git-branch", "G", "Unified graph tree");
/// v11.7: Hub mode (Quiz, Audit, Stats, Help)
pub const MODES_NEXUS: IconDef = IconDef::new("compass", "N", "Nexus hub");

// Legacy aliases for backwards compatibility (deprecated)
#[deprecated(since = "11.7.0", note = "Use MODES_GRAPH instead")]
pub const MODES_DATA: IconDef = IconDef::new("table", "D", "Data instances view");
#[deprecated(since = "11.7.0", note = "Use MODES_GRAPH instead")]
pub const MODES_META: IconDef = IconDef::new("database", "M", "Meta-graph view");
#[deprecated(since = "11.7.0", note = "Use MODES_GRAPH instead")]
pub const MODES_OVERLAY: IconDef = IconDef::new("layers", "O", "Combined meta+data");
#[deprecated(since = "11.7.0", note = "Use MODES_GRAPH instead")]
pub const MODES_QUERY: IconDef = IconDef::new("filter", "Q", "Faceted query");

// =============================================================================
// LOOKUP FUNCTIONS
// =============================================================================

/// Build a HashMap for a category (called once at startup).
macro_rules! icon_map {
    ($($key:literal => $val:expr),* $(,)?) => {{
        let mut map = HashMap::new();
        $(map.insert($key, $val);)*
        map
    }};
}

/// Get all realm icons.
pub fn realm_icons() -> HashMap<&'static str, IconDef> {
    icon_map! {
        "org" => REALMS_ORG,
        "shared" => REALMS_SHARED,
    }
}

/// Get all layer icons.
pub fn layer_icons() -> HashMap<&'static str, IconDef> {
    icon_map! {
        "config" => LAYERS_CONFIG,
        "foundation" => LAYERS_FOUNDATION,
        "geography" => LAYERS_GEOGRAPHY,
        "instruction" => LAYERS_INSTRUCTION,
        "knowledge" => LAYERS_KNOWLEDGE,
        "locale" => LAYERS_LOCALE,
        "output" => LAYERS_OUTPUT,
        "semantic" => LAYERS_SEMANTIC,
        "structure" => LAYERS_STRUCTURE,
    }
}

/// Get all trait icons.
pub fn trait_icons() -> HashMap<&'static str, IconDef> {
    icon_map! {
        "aggregated" => TRAITS_AGGREGATED,
        "generated" => TRAITS_GENERATED,
        "invariant" => TRAITS_INVARIANT,
        "knowledge" => TRAITS_KNOWLEDGE,
        "localized" => TRAITS_LOCALIZED,
    }
}

/// Get all arc family icons.
pub fn arc_family_icons() -> HashMap<&'static str, IconDef> {
    icon_map! {
        "generation" => ARC_FAMILIES_GENERATION,
        "localization" => ARC_FAMILIES_LOCALIZATION,
        "mining" => ARC_FAMILIES_MINING,
        "ownership" => ARC_FAMILIES_OWNERSHIP,
        "semantic" => ARC_FAMILIES_SEMANTIC,
    }
}

/// Get all state icons.
pub fn state_icons() -> HashMap<&'static str, IconDef> {
    icon_map! {
        "error" => STATES_ERROR,
        "loading" => STATES_LOADING,
        "no_connection" => STATES_NO_CONNECTION,
        "no_instances" => STATES_NO_INSTANCES,
        "no_kinds" => STATES_NO_KINDS,
        "no_results" => STATES_NO_RESULTS,
        "success" => STATES_SUCCESS,
        "warning" => STATES_WARNING,
    }
}

/// Get all navigation icons.
pub fn navigation_icons() -> HashMap<&'static str, IconDef> {
    icon_map! {
        "back" => NAVIGATION_BACK,
        "collapsed" => NAVIGATION_COLLAPSED,
        "copy" => NAVIGATION_COPY,
        "expanded" => NAVIGATION_EXPANDED,
        "help" => NAVIGATION_HELP,
        "leaf" => NAVIGATION_LEAF,
        "search" => NAVIGATION_SEARCH,
    }
}

/// Get all quality icons.
pub fn quality_icons() -> HashMap<&'static str, IconDef> {
    icon_map! {
        "chart" => QUALITY_CHART,
        "complete" => QUALITY_COMPLETE,
        "empty" => QUALITY_EMPTY,
        "optional" => QUALITY_OPTIONAL,
        "partial" => QUALITY_PARTIAL,
        "required" => QUALITY_REQUIRED,
    }
}

/// Get all mode icons (v11.7: Graph + Nexus, legacy modes included for compat).
#[allow(deprecated)]
pub fn mode_icons() -> HashMap<&'static str, IconDef> {
    icon_map! {
        // v11.7 modes
        "graph" => MODES_GRAPH,
        "nexus" => MODES_NEXUS,
        // Legacy modes (deprecated, kept for backwards compatibility)
        "data" => MODES_DATA,
        "meta" => MODES_META,
        "overlay" => MODES_OVERLAY,
        "query" => MODES_QUERY,
    }
}

// =============================================================================
// CONVENIENCE FUNCTIONS
// =============================================================================

/// Get terminal icon for a realm.
pub fn realm_terminal_icon(key: &str) -> &'static str {
    match key {
        "org" => "◎",
        "shared" => "◉",
        _ => "·",
    }
}

/// Get terminal icon for a layer.
pub fn layer_terminal_icon(key: &str) -> &'static str {
    match key {
        "config" => "⚙",
        "foundation" => "▣",
        "geography" => "⊙",
        "instruction" => "▧",
        "knowledge" => "◈",
        "locale" => "⊕",
        "output" => "●",
        "semantic" => "◆",
        "structure" => "▤",
        _ => "·",
    }
}

/// Get terminal icon for a trait.
pub fn trait_terminal_icon(key: &str) -> &'static str {
    match key {
        "aggregated" => "▪",
        "generated" => "★",
        "invariant" => "■",
        "knowledge" => "◊",
        "localized" => "□",
        _ => "·",
    }
}

/// Get terminal icon for a navigation action.
pub fn navigation_terminal_icon(key: &str) -> &'static str {
    match key {
        "back" => "←",
        "collapsed" => "▶",
        "copy" => "□",
        "expanded" => "▼",
        "help" => "?",
        "leaf" => "·",
        "search" => "/",
        _ => "·",
    }
}

/// Get terminal icon for a state.
pub fn state_terminal_icon(key: &str) -> &'static str {
    match key {
        "error" => "✗",
        "loading" => "◐",
        "no_connection" => "⚠",
        "no_instances" => "□",
        "no_kinds" => "∅",
        "no_results" => "◌",
        "success" => "✓",
        "warning" => "⚠",
        _ => "·",
    }
}

/// Get terminal icon for a mode (v11.7: Graph + Nexus primary).
pub fn mode_terminal_icon(key: &str) -> &'static str {
    match key {
        // v11.7 modes
        "graph" => "G",
        "nexus" => "N",
        // Legacy modes (deprecated)
        "data" => "D",
        "meta" => "M",
        "overlay" => "O",
        "query" => "Q",
        _ => "·",
    }
}

// =============================================================================
// TESTS
// =============================================================================

#[cfg(test)]
mod tests {
    use super::*;

    // =========================================================================
    // ICON MAP TESTS
    // =========================================================================

    #[test]
    fn test_realm_icons_count() {
        let icons = realm_icons();
        assert_eq!(icons.len(), 2);
        assert!(icons.contains_key("org"));
        assert!(icons.contains_key("shared"));
    }

    #[test]
    fn test_layer_icons_count() {
        let icons = layer_icons();
        assert_eq!(icons.len(), 9);
        assert!(icons.contains_key("config"));
        assert!(icons.contains_key("semantic"));
        assert!(icons.contains_key("output"));
    }

    #[test]
    fn test_trait_icons_count() {
        let icons = trait_icons();
        assert_eq!(icons.len(), 5);
        assert!(icons.contains_key("invariant"));
        assert!(icons.contains_key("localized"));
        assert!(icons.contains_key("generated"));
    }

    #[test]
    fn test_arc_family_icons_count() {
        let icons = arc_family_icons();
        assert_eq!(icons.len(), 5);
        assert!(icons.contains_key("ownership"));
        assert!(icons.contains_key("semantic"));
    }

    #[test]
    fn test_state_icons_count() {
        let icons = state_icons();
        assert_eq!(icons.len(), 8);
        assert!(icons.contains_key("loading"));
        assert!(icons.contains_key("error"));
        assert!(icons.contains_key("success"));
    }

    #[test]
    fn test_navigation_icons_count() {
        let icons = navigation_icons();
        assert_eq!(icons.len(), 7);
        assert!(icons.contains_key("expanded"));
        assert!(icons.contains_key("collapsed"));
        assert!(icons.contains_key("search"));
    }

    #[test]
    fn test_quality_icons_count() {
        let icons = quality_icons();
        assert_eq!(icons.len(), 6);
        assert!(icons.contains_key("complete"));
        assert!(icons.contains_key("required"));
    }

    #[test]
    #[allow(deprecated)]
    fn test_mode_icons_count() {
        let icons = mode_icons();
        // v11.7: 2 new modes + 4 legacy = 6 total
        assert_eq!(icons.len(), 6);
        assert!(icons.contains_key("graph"));
        assert!(icons.contains_key("nexus"));
        // Legacy modes still present for backwards compat
        assert!(icons.contains_key("data"));
        assert!(icons.contains_key("meta"));
    }

    // =========================================================================
    // TERMINAL ICON TESTS
    // =========================================================================

    #[test]
    fn test_realm_terminal_icon() {
        assert_eq!(realm_terminal_icon("org"), "◎");
        assert_eq!(realm_terminal_icon("shared"), "◉");
        assert_eq!(realm_terminal_icon("unknown"), "·");
    }

    #[test]
    fn test_layer_terminal_icon() {
        assert_eq!(layer_terminal_icon("config"), "⚙");
        assert_eq!(layer_terminal_icon("semantic"), "◆");
        assert_eq!(layer_terminal_icon("output"), "●");
        assert_eq!(layer_terminal_icon("unknown"), "·");
    }

    #[test]
    fn test_trait_terminal_icon() {
        assert_eq!(trait_terminal_icon("invariant"), "■");
        assert_eq!(trait_terminal_icon("localized"), "□");
        assert_eq!(trait_terminal_icon("generated"), "★");
        assert_eq!(trait_terminal_icon("aggregated"), "▪");
        assert_eq!(trait_terminal_icon("unknown"), "·");
    }

    #[test]
    fn test_navigation_terminal_icon() {
        assert_eq!(navigation_terminal_icon("expanded"), "▼");
        assert_eq!(navigation_terminal_icon("collapsed"), "▶");
        assert_eq!(navigation_terminal_icon("search"), "/");
        assert_eq!(navigation_terminal_icon("unknown"), "·");
    }

    #[test]
    fn test_state_terminal_icon() {
        assert_eq!(state_terminal_icon("loading"), "◐");
        assert_eq!(state_terminal_icon("error"), "✗");
        assert_eq!(state_terminal_icon("success"), "✓");
        assert_eq!(state_terminal_icon("unknown"), "·");
    }

    #[test]
    fn test_mode_terminal_icon() {
        // v11.7 modes
        assert_eq!(mode_terminal_icon("graph"), "G");
        assert_eq!(mode_terminal_icon("nexus"), "N");
        // Legacy modes
        assert_eq!(mode_terminal_icon("data"), "D");
        assert_eq!(mode_terminal_icon("meta"), "M");
        assert_eq!(mode_terminal_icon("unknown"), "·");
    }

    // =========================================================================
    // ICON CONTENT TESTS
    // =========================================================================

    #[test]
    fn test_icon_def_fields_not_empty() {
        // Verify all constants have non-empty fields
        assert!(!REALMS_ORG.web.is_empty());
        assert!(!REALMS_ORG.terminal.is_empty());
        assert!(!REALMS_ORG.description.is_empty());

        assert!(!LAYERS_CONFIG.web.is_empty());
        assert!(!TRAITS_INVARIANT.web.is_empty());
        assert!(!ARC_FAMILIES_OWNERSHIP.web.is_empty());
        assert!(!STATES_LOADING.web.is_empty());
        assert!(!NAVIGATION_EXPANDED.web.is_empty());
        assert!(!QUALITY_COMPLETE.web.is_empty());
        assert!(!MODES_GRAPH.web.is_empty());
    }

    #[test]
    fn test_v11_7_modes_constants() {
        // v11.7: Verify new mode constants exist
        assert_eq!(MODES_GRAPH.terminal, "G");
        assert_eq!(MODES_NEXUS.terminal, "N");
        assert!(MODES_GRAPH.description.contains("Unified"));
        assert!(MODES_NEXUS.description.contains("hub"));
    }
}
