// src/__tests__/generators/MarkdownGenerator.test.ts
import { describe, it, expect } from 'vitest';
import { MarkdownGenerator } from '../../generators/MarkdownGenerator.js';
import type { ExtendedViewDefinition } from '../../generators/types.js';
import * as path from 'path';

const RELATIONS_PATH = path.join(process.cwd(), 'models/relations.yaml');
const INDEX_PATH = path.join(process.cwd(), 'models/_index.yaml');

const testView: ExtendedViewDefinition = {
  id: 'test-view',
  name: 'Test View',
  description: 'A test view for documentation',
  version: '1.0',
  root: { type: 'Page' },
  include: [
    { relation: 'HAS_BLOCK', direction: 'outgoing' },
    { relation: 'HAS_PROMPT', direction: 'outgoing' },
  ],
  docs: {
    title: 'Test View Documentation',
    category: 'generation',
    description: 'This is a test view for testing the MarkdownGenerator.',
    layers: [
      { name: 'Page Layer', nodes: ['Page', 'PagePrompt'], color: 'blue' },
      { name: 'Block Layer', nodes: ['Block', 'BlockType'], color: 'green' },
    ],
    examples: [
      {
        name: 'Load a page',
        description: 'Load a page with its blocks',
        query: 'MATCH (p:Page {key: $key})-[:HAS_BLOCK]->(b:Block) RETURN p, b',
        params: { key: 'page-pricing' },
      },
    ],
    notes: ['This is a test note.'],
  },
};

describe('MarkdownGenerator', () => {
  describe('generate', () => {
    it('should generate markdown with header', () => {
      const result = MarkdownGenerator.generate(testView);

      expect(result.content).toContain('# Test View Documentation');
      expect(result.content).toContain('models/views/test-view.yaml');
      expect(result.viewId).toBe('test-view');
    });

    it('should include overview section', () => {
      const result = MarkdownGenerator.generate(testView);

      expect(result.content).toContain('## Overview');
      expect(result.content).toContain('This is a test view for testing');
    });

    it('should generate Mermaid diagram', () => {
      const result = MarkdownGenerator.generate(testView);

      expect(result.content).toContain('```mermaid');
      expect(result.content).toContain('flowchart');
      expect(result.content).toContain('Page Layer');
      expect(result.content).toContain('Block Layer');
    });

    it('should generate nodes table', () => {
      const result = MarkdownGenerator.generate(testView);

      expect(result.content).toContain('## Nodes');
      expect(result.content).toContain('| Node | Layer |');
      expect(result.content).toContain('Page');
      expect(result.content).toContain('PagePrompt');
    });

    it('should generate relations table', () => {
      const result = MarkdownGenerator.generate(testView);

      expect(result.content).toContain('## Relations');
      expect(result.content).toContain('| Relation | Direction |');
      expect(result.content).toContain('HAS_BLOCK');
    });

    it('should generate Cypher examples', () => {
      const result = MarkdownGenerator.generate(testView);

      expect(result.content).toContain('## Cypher Queries');
      expect(result.content).toContain('### Load a page');
      expect(result.content).toContain('```cypher');
      expect(result.content).toContain('MATCH (p:Page');
      expect(result.content).toContain('**Parameters:**');
    });

    it('should include notes if present', () => {
      const result = MarkdownGenerator.generate(testView);

      expect(result.content).toContain('## Notes');
      expect(result.content).toContain('This is a test note.');
    });

    it('should include footer', () => {
      const result = MarkdownGenerator.generate(testView);

      expect(result.content).toContain('*Generated by NovaNet Unified View System');
    });
  });

  describe('generate without docs', () => {
    it('should throw if view has no docs section', () => {
      const viewWithoutDocs: ExtendedViewDefinition = {
        id: 'no-docs',
        name: 'No Docs',
        description: 'A view without docs',
        version: '1.0',
        root: { type: 'Page' },
        include: [],
      };

      expect(() => MarkdownGenerator.generate(viewWithoutDocs)).toThrow(/docs section/);
    });
  });

  describe('options', () => {
    it('should exclude timestamp when includeTimestamp is false', () => {
      const result = MarkdownGenerator.generate(testView, { includeTimestamp: false });

      expect(result.content).not.toContain('Last updated:');
    });

    it('should exclude Mermaid when includeMermaid is false', () => {
      const result = MarkdownGenerator.generate(testView, { includeMermaid: false });

      expect(result.content).not.toContain('```mermaid');
    });

    it('should exclude Cypher when includeCypher is false', () => {
      const result = MarkdownGenerator.generate(testView, { includeCypher: false });

      expect(result.content).not.toContain('## Cypher Queries');
    });
  });

  describe('generateMermaid', () => {
    it('should generate valid Mermaid flowchart', () => {
      const mermaid = MarkdownGenerator.generateMermaid(testView);

      expect(mermaid).toContain('flowchart TB');
      expect(mermaid).toContain('classDef');
      expect(mermaid).toContain('subgraph');
    });

    it('should use Tailwind-Solarized colors', () => {
      const mermaid = MarkdownGenerator.generateMermaid(testView);

      // Check for color definitions
      expect(mermaid).toMatch(/fill:#[0-9a-f]{6}/i);
      expect(mermaid).toMatch(/stroke:#[0-9a-f]{6}/i);
    });
  });

  // ═══════════════════════════════════════════════════════════════════════════
  // MERMAID GENERATOR INTEGRATION
  // ═══════════════════════════════════════════════════════════════════════════

  describe('MermaidGenerator integration', () => {
    describe('generateAsync with useFullGraphMermaid=true', () => {
      it('should use MermaidGenerator output when useFullGraphMermaid is true', async () => {
        const result = await MarkdownGenerator.generateAsync(testView, {
          useFullGraphMermaid: true,
          relationsPath: RELATIONS_PATH,
          indexPath: INDEX_PATH,
        });

        // Should contain MermaidGenerator's output characteristics
        expect(result.content).toContain('```mermaid');
        expect(result.content).toContain('flowchart TB');
        // MermaidGenerator uses locale behavior classes
        expect(result.content).toContain('classDef invariant');
        expect(result.content).toContain('classDef localized');
        // MermaidGenerator uses scope subgraphs with _LAYER suffix
        expect(result.content).toContain('subgraph GLOBAL_LAYER');
        expect(result.content).toContain('subgraph PROJECT_LAYER');
      });

      it('should include all 35 nodes from relations.yaml', async () => {
        const result = await MarkdownGenerator.generateAsync(testView, {
          useFullGraphMermaid: true,
          relationsPath: RELATIONS_PATH,
          indexPath: INDEX_PATH,
        });

        // Check for some key nodes from each scope
        expect(result.content).toContain('Locale');
        expect(result.content).toContain('Project');
        expect(result.content).toContain('Page');
        expect(result.content).toContain('Block');
        expect(result.content).toContain('Concept');
        expect(result.content).toContain('SEOKeywordL10n');
      });

      it('should include relationship edges', async () => {
        const result = await MarkdownGenerator.generateAsync(testView, {
          useFullGraphMermaid: true,
          relationsPath: RELATIONS_PATH,
          indexPath: INDEX_PATH,
        });

        // MermaidGenerator renders edges with labels
        expect(result.content).toContain('-->|HAS_PAGE|');
        expect(result.content).toContain('-->|HAS_BLOCK|');
        expect(result.content).toContain('-->|HAS_CONCEPT|');
      });
    });

    describe('generateAsync with useFullGraphMermaid=false', () => {
      it('should use existing generateMermaid when useFullGraphMermaid is false', async () => {
        const result = await MarkdownGenerator.generateAsync(testView, {
          useFullGraphMermaid: false,
        });

        // Should use the layer-based generateMermaid
        expect(result.content).toContain('```mermaid');
        expect(result.content).toContain('Page Layer');
        expect(result.content).toContain('Block Layer');
        // Should NOT contain MermaidGenerator scope subgraphs
        expect(result.content).not.toContain('subgraph Global');
        expect(result.content).not.toContain('subgraph Shared');
      });

      it('should use generateMermaid by default (without option)', async () => {
        const result = await MarkdownGenerator.generateAsync(testView);

        // Default behavior: use layer-based Mermaid
        expect(result.content).toContain('Page Layer');
        expect(result.content).not.toContain('subgraph Global');
      });
    });

    describe('generateAsync error handling', () => {
      it('should throw if useFullGraphMermaid=true but relationsPath missing', async () => {
        await expect(
          MarkdownGenerator.generateAsync(testView, {
            useFullGraphMermaid: true,
            indexPath: INDEX_PATH,
            // relationsPath missing
          })
        ).rejects.toThrow('relationsPath is required when useFullGraphMermaid is true');
      });

      it('should throw if useFullGraphMermaid=true but indexPath missing', async () => {
        await expect(
          MarkdownGenerator.generateAsync(testView, {
            useFullGraphMermaid: true,
            relationsPath: RELATIONS_PATH,
            // indexPath missing
          })
        ).rejects.toThrow('indexPath is required when useFullGraphMermaid is true');
      });

      it('should propagate MermaidGenerator errors with context', async () => {
        await expect(
          MarkdownGenerator.generateAsync(testView, {
            useFullGraphMermaid: true,
            relationsPath: '/nonexistent/relations.yaml',
            indexPath: INDEX_PATH,
          })
        ).rejects.toThrow(/Failed to generate full graph Mermaid/);
      });
    });

    describe('sync generate() backward compatibility', () => {
      it('should continue working with existing behavior', () => {
        // Sync generate should not be affected by new options
        const result = MarkdownGenerator.generate(testView);

        expect(result.content).toContain('```mermaid');
        expect(result.content).toContain('Page Layer');
        expect(result.viewId).toBe('test-view');
      });

      it('should ignore useFullGraphMermaid in sync mode', () => {
        // Sync generate cannot use MermaidGenerator (it's async)
        // It should fall back to existing behavior
        const result = MarkdownGenerator.generate(testView, {
          useFullGraphMermaid: true,  // ignored in sync mode
          relationsPath: RELATIONS_PATH,
          indexPath: INDEX_PATH,
        });

        // Should still use layer-based Mermaid (not MermaidGenerator)
        expect(result.content).toContain('Page Layer');
      });
    });
  });
});
