// src/__tests__/generators/MarkdownGenerator.test.ts
import { describe, it, expect } from 'vitest';
import { MarkdownGenerator } from '../../generators/MarkdownGenerator.js';
import type { ExtendedViewDefinition } from '../../generators/types.js';

const testView: ExtendedViewDefinition = {
  id: 'test-view',
  name: 'Test View',
  description: 'A test view for documentation',
  version: '1.0',
  root: { type: 'Page' },
  include: [
    { relation: 'HAS_BLOCK', direction: 'outgoing' },
    { relation: 'HAS_PROMPT', direction: 'outgoing' },
  ],
  docs: {
    title: 'Test View Documentation',
    category: 'generation',
    description: 'This is a test view for testing the MarkdownGenerator.',
    layers: [
      { name: 'Page Layer', nodes: ['Page', 'PagePrompt'], color: 'blue' },
      { name: 'Block Layer', nodes: ['Block', 'BlockType'], color: 'green' },
    ],
    examples: [
      {
        name: 'Load a page',
        description: 'Load a page with its blocks',
        query: 'MATCH (p:Page {key: $key})-[:HAS_BLOCK]->(b:Block) RETURN p, b',
        params: { key: 'page-pricing' },
      },
    ],
    notes: ['This is a test note.'],
  },
};

describe('MarkdownGenerator', () => {
  describe('generate', () => {
    it('should generate markdown with header', () => {
      const result = MarkdownGenerator.generate(testView);

      expect(result.content).toContain('# Test View Documentation');
      expect(result.content).toContain('models/views/test-view.yaml');
      expect(result.viewId).toBe('test-view');
    });

    it('should include overview section', () => {
      const result = MarkdownGenerator.generate(testView);

      expect(result.content).toContain('## Overview');
      expect(result.content).toContain('This is a test view for testing');
    });

    it('should generate Mermaid diagram', () => {
      const result = MarkdownGenerator.generate(testView);

      expect(result.content).toContain('```mermaid');
      expect(result.content).toContain('flowchart');
      expect(result.content).toContain('Page Layer');
      expect(result.content).toContain('Block Layer');
    });

    it('should generate nodes table', () => {
      const result = MarkdownGenerator.generate(testView);

      expect(result.content).toContain('## Nodes');
      expect(result.content).toContain('| Node | Layer |');
      expect(result.content).toContain('Page');
      expect(result.content).toContain('PagePrompt');
    });

    it('should generate relations table', () => {
      const result = MarkdownGenerator.generate(testView);

      expect(result.content).toContain('## Relations');
      expect(result.content).toContain('| Relation | Direction |');
      expect(result.content).toContain('HAS_BLOCK');
    });

    it('should generate Cypher examples', () => {
      const result = MarkdownGenerator.generate(testView);

      expect(result.content).toContain('## Cypher Queries');
      expect(result.content).toContain('### Load a page');
      expect(result.content).toContain('```cypher');
      expect(result.content).toContain('MATCH (p:Page');
      expect(result.content).toContain('**Parameters:**');
    });

    it('should include notes if present', () => {
      const result = MarkdownGenerator.generate(testView);

      expect(result.content).toContain('## Notes');
      expect(result.content).toContain('This is a test note.');
    });

    it('should include footer', () => {
      const result = MarkdownGenerator.generate(testView);

      expect(result.content).toContain('*Generated by NovaNet Unified View System');
    });
  });

  describe('generate without docs', () => {
    it('should throw if view has no docs section', () => {
      const viewWithoutDocs: ExtendedViewDefinition = {
        id: 'no-docs',
        name: 'No Docs',
        description: 'A view without docs',
        version: '1.0',
        root: { type: 'Page' },
        include: [],
      };

      expect(() => MarkdownGenerator.generate(viewWithoutDocs)).toThrow(/docs section/);
    });
  });

  describe('options', () => {
    it('should exclude timestamp when includeTimestamp is false', () => {
      const result = MarkdownGenerator.generate(testView, { includeTimestamp: false });

      expect(result.content).not.toContain('Last updated:');
    });

    it('should exclude Mermaid when includeMermaid is false', () => {
      const result = MarkdownGenerator.generate(testView, { includeMermaid: false });

      expect(result.content).not.toContain('```mermaid');
    });

    it('should exclude Cypher when includeCypher is false', () => {
      const result = MarkdownGenerator.generate(testView, { includeCypher: false });

      expect(result.content).not.toContain('## Cypher Queries');
    });
  });

  describe('generateMermaid', () => {
    it('should generate valid Mermaid flowchart', () => {
      const mermaid = MarkdownGenerator.generateMermaid(testView);

      expect(mermaid).toContain('flowchart TB');
      expect(mermaid).toContain('classDef');
      expect(mermaid).toContain('subgraph');
    });

    it('should use Tailwind-Solarized colors', () => {
      const mermaid = MarkdownGenerator.generateMermaid(testView);

      // Check for color definitions
      expect(mermaid).toMatch(/fill:#[0-9a-f]{6}/i);
      expect(mermaid).toMatch(/stroke:#[0-9a-f]{6}/i);
    });
  });

  // ═══════════════════════════════════════════════════════════════════════════
  // GENERATE ASYNC (v8.2.0 - MermaidGenerator moved to @novanet/schema-tools)
  // ═══════════════════════════════════════════════════════════════════════════

  describe('generateAsync', () => {
    it('should use layer-based Mermaid by default', async () => {
      const result = await MarkdownGenerator.generateAsync(testView);

      expect(result.content).toContain('```mermaid');
      expect(result.content).toContain('Page Layer');
      expect(result.viewId).toBe('test-view');
    });

    it('should be equivalent to sync generate()', async () => {
      const syncResult = MarkdownGenerator.generate(testView);
      const asyncResult = await MarkdownGenerator.generateAsync(testView);

      // Content should match (ignoring timestamp)
      expect(asyncResult.viewId).toBe(syncResult.viewId);
      // Both should have the same structure
      expect(asyncResult.content).toContain('Page Layer');
      expect(syncResult.content).toContain('Page Layer');
    });

    it('should continue working with existing behavior', () => {
      const result = MarkdownGenerator.generate(testView);

      expect(result.content).toContain('```mermaid');
      expect(result.content).toContain('Page Layer');
      expect(result.viewId).toBe('test-view');
    });
  });
});
